### DISCUSSION TITLE
Eventbus installation Error : failed to get nats streaming version

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-helm#1441] [Q&A] [answered]
Hi Team,

I was installing argo events as argocd application. I was able to sync the argo events.

I created a separate repo added eventbus, sensor, eventsource file. and created application CRD to apply those into argo-events namespace and now argocd is taking care of this to install in destination namespace. When I tried to install eventbus in argo-events namespace it says error like this:
Can anyone guide me with the same?

```
{"level":"error","ts":1662616061.2807608,"logger":"argo-events.eventbus-controller.nats","caller":"installer/nats.go:374","msg":"error building statefulset spec","namespace":"argo-events","eventbus":"default","error":"failed to get nats streaming version, err: \"eventBus.nats\" not found in the configuration","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus/installer.(*natsInstaller).
```

Thanks in advance!

**Comment by pdrastil** [comment, marked as answer]
Hi @sharadhirao,
the EventBus version should be matching the provided configuration when installing argo-events. Please provide images you want to use in following config [NATs](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-events/values.yaml#L66) or [JetStream](https://github.com/argoproj/argo-helm/blob/db0957d3cbae617b72995ee3db8790081f2095ef/charts/argo-events/values.yaml#L93) sections in values.yaml.

**Reply by sharadhirao** [reply]
Hi @pdrastil,

Thanks a lot for answer, Its running now after passing nat and jetstream version in the values.yaml
```
configs:
  jetstream:
    versions:
    - version: "2.8.1"
      natsImage: nats:2.8.1
      metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
      configReloaderImage: natsio/nats-server-config-reloader:0.6.3
      startCommand: /nats-server
  nats:
    versions: 
    - version: 0.22.1
      natsStreamingImage: nats-streaming:0.22.1
      metricsExporterImage: natsio/prometheus-nats-exporter:0.9.3
```
This solved the problem. Thanks again.
