### DISCUSSION TITLE
Argo CD creating duplicate components for every pod

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-helm#1538] [Q&A] [answered]
Hi team,
I was following the approach given in this video : https://www.youtube.com/watch?v=XNXJtxkUKeY&ab_channel=DevOpsToolkit 
where argocd manages itself. 

First I installed argocd through helm and then made argo cd look after itself. When I do this I am seeing every element of argocd two times. every pod, service, deployment, replicas if getting duplicated. But when I login to argo-server both are showing same application with same configuration.

<img width="660" alt="Screenshot 2022-10-10 at 3 49 46 PM" src="https://user-images.githubusercontent.com/60086120/194844932-7852b84f-8dfa-4b52-99bd-439ef7967f08.png">

How can I remove the duplicate pods, services and deployments? Can anyone help? its urgent.
Thanks in advance.

**Comment by pdrastil** [comment, marked as answer]
Hi - you installed 2 different releases via Helm and Argo CD. One is called `argocd` and second one `argo-cd` that's why your components are doubled.

**Reply by sharadhirao** [reply]
Hi @pdrastil ,

In my minikube, i am trying now. i deleted everything and clone argo helm repository: https://github.com/argoproj/argo-helm.git
Ran these commands

```
cd argo-helm/charts
helm lint ./argo-cd/ 
helm dependency update ./argo-cd  
helm install --dry-run --debug ./argo-cd/ --generate-name 
helm install argocd ./argo-cd/ -n argocd
```

Which installed the pods like this:
<img width="573" alt="Screenshot 2022-10-11 at 9 29 19 AM" src="https://user-images.githubusercontent.com/60086120/194994095-37521dfa-16ea-48fe-9efb-d08e8e0e2934.png">

After that I created a application.yaml like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
```

After I applied this file. Again I am getting duplicate pods.
<img width="668" alt="Screenshot 2022-10-11 at 9 31 00 AM" src="https://user-images.githubusercontent.com/60086120/194994278-4629b43c-57fb-4f9f-995c-e3ef012131da.png">

But as you suggested I did same with quickstart install. 

```
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```
I installed from this commands and stored same install.yaml file in my repository and created application CRD.
Now when I use this there is no duplicate pods coming

**Only through the helm installation, I am getting this error. Can you please help me with this? **
