### DISCUSSION TITLE
Argo Workflows Adding signed certificate

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-helm#1551] [Q&A] [answered]
Hi Team,

For now argo workflows is creating self signed certificate when I made secure: true in values.yaml. **I have my own cert to add**. How to add it? I tried reading through this article:https://argoproj.github.io/argo-workflows/tls/ this seems only for CLI and I did not understand clealy from it. I did my installation through helm.

I have added cert to argocd, but argocd provided me to add certificate value as secret in secretName: argocd-server-tls in server. I can't seem to get same thing in argo-workflows.
Can anyone give the steps or process to add cert to argo-workflows?

Thanks in advance.

**Comment by sharadhirao** [comment]
Hi team,

I have this dependency to add my own cert to the argo-workflow. I have created ingress controller and created ingress. As i am using helm installation of argo-workflows my ingress looks like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-workflows-server
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # networking.gke.io/managed-certificates: managed-cert
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "argo-workflow.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-workflows-server
                port:
                  number: 443
  tls:
    - hosts:
      - argo-workflow.com
      secretName: argoworkflows-example-tls
```
In deployment file i added basehref as /.
Even now I am not able to remove the self-signed certificate. Can anyone suggest me where i am going wrong? @alexec @pdrastil 

Thanks in advance.

**Reply by sharadhirao** [reply]
Hi Team,

Can anyone help in this?
@alexec  @pdrastil 
Thanks in advance

**Comment by vitalyrychkov** [comment, marked as answer]
Hi @sharadhirao , the only way of providing your trusted certificates to Argo Workflows I know is to save it in a secret and mount it as a volume. Save the certificate or certificate chain in a secret in the namespace where Argo Workflows has been deployed:  

    kubectl create secret generic ca --from-file=ca.crt=ca.crt -n <argo namespace>
 
Add the following section to the `controller:` and `server:` container specs of your manifest or Helm values file, for example:

    volumeMounts: 
    - name: ca
      mountPath: /etc/ssl/certs/ca.crt
      subPath: ca.crt 
    volumes: 
    - name: ca
      secret:
        secretName: ca

**Reply by sharadhirao** [reply]
hi @vitalyrychkov, Thanks a lot for the reply. Yes, we started using the same approach and it removed the self-signed certificate and Its working fine.

**Reply by bd-bord1** [reply]
Hi, 

"Add the following section to the controller: and server: container specs of your manifest or Helm values file, for example."

The volume and volume mounts must be added to server deployment of Argocd - to the 2 containers of the argocd server deployment?

Could someone please clarify? Grateful for any help you can provide.

**Reply by vitalyrychkov** [reply]
Hi @bd-bord1,

My original comment was related to Argo Workflows server and controller deployments (we do not use Argo CD), but you may try the same for the Argo CD deployments, there is a good chance this will do the job.  The point is that this way you provide your trusted certificate(s) to the default location inside the pod.

**Reply by bd-bord1** [reply]
Hi vitalyrychkov, 
I tried it however all the changes I do are being overwritten by the operator. 
I tried many solutions provided on the internet and all my changes are being overwritten.

Feeling quite pessimistic

**Reply by sharadhirao** [reply]
@bd-bord1 have you tried this approach: https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#tls-certificates-used-by-argocd-server
I have done like this for argocd and it worked. I created the secret like this with same name. https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L2093 and here enable it.

**Reply by bd-bord1** [reply]
Hi, Thank you. 
Our ArgoCD has been already created.
Once it has been created, I think it is not possible to use the values.yaml because values.yaml is usually used at the initial deployment. 
Please correct me if I am wrong...

**Reply by vitalyrychkov** [reply]
Hi, that depends on you situation, but one of the main purposes of Helm to easily upgrade a release (deployment etc) with an updated values.yaml file as many times as necessary. If you are allowed to change the values file update the deployment, this is the best way to consistently upgrade Helm releases. Hope I understood your last question correctly.

**Reply by sharadhirao** [reply]
@bd-bord1 , yeah vitalyrychkov is correct helm will allow you to update the releases even after deploying things by helm upgrade commands. So you will be able to change the values.yml refer this once if you are new to helm: https://helm.sh/docs/helm/helm_upgrade/

**Comment by bd-bord1** [comment]
Thanks a lot @sharadhirao  for your help! 
In my case the deployment of argocd crds was triggered from a pipeline and I needed to add a new cm argocd-cm in the pipeline with these configurations: 

  ```
oidc.config: |
    ...
    rootCA: |
      -----BEGIN CERTIFICATE-----
      ... encoded certificate data here ...
      -----END CERTIFICATE-----
```


++ these 2 labels:

```
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
```

Everything works now. Thank you for your help once again. 
This case can be closed now.

https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#configuring-a-custom-root-ca-certificate-for-communicating-with-the-oidc-provider
