### DISCUSSION TITLE
Secure Connection to External Redis

### DISCUSSION THREAD

**Discussion by krcy** [argoproj/argo-helm#1655] [Q&A] [answered]
Hi Team,

We need argocd to connect to the managed Redis with in-transit encryption enabled. So we need to provide Redis' ca-cert to Argocd. I guess we need --redis-use-tls and --redis-ca-certificate options for this. 
See [documentation.](https://argo-cd.readthedocs.io/en/release-2.3/operator-manual/server-commands/argocd-server/)

Because we are using argo-helm charts in our setup, I want to ask if argo-helm charts support to provide redis certificates to securely connect to external managed Redis?

Thanks in advance.

**Comment by ChristopherLenz** [comment, marked as answer]
Hello, actually you said everything correctly. Unfortunately, the parameters you mentioned are not available as prepared parameters. But you can use the `extraArgs` without any problems. Here is an example for a Tls connection without specific certificates.

```
  controller:
    extraArgs:
      - --redis-use-tls
      - --redis-insecure-skip-tls-verify
  repoServer:
    extraArgs:
      - --redis-use-tls
      - --redis-insecure-skip-tls-verify
  server:
    extraArgs:
      - --redis-use-tls 
      - --redis-insecure-skip-tls-verify
```

See the appropriate PR for more examples: https://github.com/argoproj/argo-cd/pull/6742
