### DISCUSSION TITLE
Disabling kustomize or Jsonnet isn't restarting argocd

### DISCUSSION THREAD

**Discussion by adrianmoisey** [argoproj/argo-helm#1664] [Q&A]
I've done the following in my Values file:
```
configs:
  cm:
    jsonnet.enable: false
    kustomize.enable: false
```

But after applying it, it seems like argocd isn't restarted, making me assume that the config wasn't loaded.

Am I incorrect in this assumption?
