### DISCUSSION TITLE
(Gitops Argocd Notification) I want to receive an alarm by detecting only the changes in github What should I do?

### DISCUSSION THREAD

**Discussion by oliverpark999** [argoproj/argo-helm#1670] [Q&A]
I use argocd notification

I'm getting an alarm on Slack.

By the way, the problem is as follows.

New Deploy alarm occurs when github build & manifest update occurs

Alarm occurs when pod change occurs due to scale-in/out

Alarm occurs when pod is regenerated for some reason

I want to receive an alarm by detecting only the changes in github

What should I do?

**-- Trigger in use --**
```
triggers:
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.syncResult.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
```
