### DISCUSSION TITLE
How to upgrade from v2.2.5 to v2.3.1 (Helm, ApplicationSet)

### DISCUSSION THREAD

**Discussion by gajus** [argoproj/argo-helm#1684] [Q&A] [answered]
Previously, we created ApplicationSet using

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contra-application-sets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:contra/contra-cluster.git
    targetRevision: main
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
```

Now that we attempted to upgrade to v2.3, which [adds native support for ApplicationSet](https://github.com/argoproj/argo-cd/blob/master/CHANGELOG.md#v230-2022-03-05), the upgrade is just stuck in a downgraded state. It is not clear how to proceed further and changelog does not include documentation.

It seems like I should just attempt to delete `contra-application-sets` application, but not clear if this may cause an outage to our services, e.g. worried it can delete existing applications associated with the application set.
