### DISCUSSION TITLE
SSO Login returns 401

### DISCUSSION THREAD

**Discussion by JunaidChaudry** [argoproj/argo-helm#1748] [Q&A]
I am trying to set up argo workflow first time, and trying to use sso login using AzureAD. But the redirect after login keeps giving me a 401. 

 I have enabled sso with `server.extraArgs: ["--auth-mode=sso"]`, created my secret with the `client-id` and `client-secret`, and passed those under `server.sso.clientId`, and `server.sso.clientSecret`.  The redirect URL is registered in my Azure AppRegistration as well. 

Upon trying to log in, the application does redirect for login, but then returns the following error while trying the /oauth2/callback link. 
"This page isn’t working right nowIf the problem continues, contact the site owner. HTTP ERROR 401" 

All that I see in the server logs is the following: 

```
time="2023-01-03T17:40:06.925Z" level=info duration="46.802µs" method=GET path=/oauth2/redirect size=298 status=302
time="2023-01-03T17:40:08.301Z" level=info duration=845.230728ms method=GET path=/oauth2/callback size=0 status=401
```

Argo Workflow Helm Chart Version: 0.22.4
APP Version: v3.4.4

Attached are my values 
```

extraObjects: {}
fullnameOverride: argo-workflows
server:
  extraArgs:
  - --auth-mode=sso
  extraEnv: []
  logging:
    level: debug
  replicas: 1
  sso:
    clientId:
      key: client-id
      name: argo-server-sso
    clientSecret:
      key: client-secret
      name: argo-server-sso
    issuer: https://sts.windows.net/{tenant-id}/
    rbac:
      enabled: false
    redirectUrl: https://{my-hostname}/oauth2/callback
  volumeMounts: []
  volumes: []
useDefaultArtifactRepo: true
useStaticCredentials: false
```
