### DISCUSSION TITLE
helm values file configManagementPlugins

### DISCUSSION THREAD

**Discussion by ValdasDienas** [argoproj/argo-helm#1766] [Q&A]
Hi guys when you are planing to add this parameter into helm values file ?

**Comment by pdrastil** [comment]
Hi - this parameter is deprecated and option should be removed from upstream soon. Check new CMP architecture via sidecars + changes for upcoming 2.6 release here https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/

If you mean new structure for sidecars without creating custom container you can also add this into `configs.cm` section that will render such config into argocd-cm ConfigMap.

**Reply by ValdasDienas** [reply]
Sorry maybe i wrote not full info what i mean but to update argocd-cm configMap there is no parameter as configManagementPlugins
so using helm there is no way to do that

**Reply by pdrastil** [reply]
Yes there is - you just need to supply it with your value overrides. We do not copy & paste full configs, the section contains only commonly used options and link to upstream with all options.

```yaml
configs:
  cm:
    configManagementPlugins: |
      - name: pluginName
        init:
          command: ["sample command"]
          args: ["sample args"]
        generate:
          command: ["sample command"]
          args: ["sample args"]
        lockRepo: true
```
