### DISCUSSION TITLE
Argo workflow sso integration giving error code 12

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-helm#1840] [Q&A]
Hi team,
I have integrated okta with argo workflow. If I click login in workflow UI, I am able to get the okta login page and once logged in I am getting the error as "Code 12 not implemented" 
```
  sso: 
    issuer: https://company.okta.com
    # Name of a secret and a key in it to retrieve the app OIDC client ID from.
    clientId:
      name: argo-server-sso
      key: client-id
    # Name of a secret and a key in it to retrieve the app OIDC client secret from.
    clientSecret:
      name: argo-server-sso
      key: client-secret
    
    redirectUrl: https://argourl/api/oauth2/callback
    rbac:
      enabled: true
      secretWhitelist: []
    scopes:
    - groups
```
this is my sso and I have given auth mode as sso. the group I have is argo-admins , I have specified in the service account as given here. https://argoproj.github.io/argo-workflows/argo-server-sso/ Could anyone please help me with this? It's urgent. @alexec @pdrastil
