### DISCUSSION TITLE
AgroCD Notifications doesn't work

### DISCUSSION THREAD

**Discussion by GoSiddhartha** [argoproj/argo-helm#1858] [Q&A] [answered]
Hello team,
I have been trying to implement ArgoCd notifications into our clusters. First let me explain my use case and scenario.
We have k8s clusters running and they are provisioned and maintained my a centralised team. They have installed ArgoCd and also notification in their foundation namespace which we use with our applications and configs. We do not have control on their namespaces so I installed ArgoCD notification controller separately in a different namespace.
Will all configured I can see the notification pod logs as below -
`time="2023-02-23T16:02:47Z" level=info msg="ArgoCD Notifications Controller is starting" built="2023-02-16T15:05:14Z" commit=6e02f8b23201b0620a4ff1bce5d38229ba1eb02e namespace=infra version=v2.6.2+6e02f8b
3
{"level":"info","msg":"serving metrics on port 9001","time":"2023-02-23T16:02:47Z"}
2
{"level":"info","msg":"loading configuration 9001","time":"2023-02-23T16:02:47Z"}
1
{"level":"warning","msg":"Controller is running.","time":"2023-02-23T16:02:47Z"}
`

When I try to delete a deployment I get no teams message and no logs to troubleshoot. Am I doing something wrong?

This is the deployment image I use "**_quay.io/argoproj/argocd:v2.6.2_**"

The cm is configured as below and the templates and triggers are copied from the latest documentation

```
apiVersion: v1
  data:
    context: |
      argocdUrl: $argourl
      environmentName: dev
      region: west-europe
    service.teams: |
      recipientUrls:
        channelName: $msteams
    service.webhook.msteams: |
      url: $msteams
    subscriptions: |
      - recipients:
        - msteams
        triggers:
        - on-sync-succeeded
        - on-created
        - on-deleted
        - on-deployed
        - on-health-degraded
        - on-sync-failed
        - on-sync-running
        - on-sync-status-unknown
```
