### DISCUSSION TITLE
Installing ArgoCD on a K8s Cluster using helm_release resource on Terraform.

### DISCUSSION THREAD

**Discussion by mateokurti** [argoproj/argo-helm#1886] [Q&A]
I'm not sure if this is a bug as I assume this is a common thing and would probably have other issues opened if a bug, so I'm starting a discussion instead.

I am trying to install ArgoCD using `helm_release` resource on Terraform. It works fine, but I am facing an issue when it comes to TLS, which I don't know why is happening as I'm doing everything as described in the README.

So I have the following code in Terraform:

```tf
resource "helm_release" "argocd" {
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = "5.24.1"

  name      = "argocd"
  namespace = var.namespace

  values = [
    file("${path.module}/configs/helm-values.yaml")
  ]
}
```
And the `helm-values.yaml` file as following:

```yaml
crds:
  keep: false

configs:
  secret:
    argocdServerAdminPassword: "abcdef" # real password is here
  repositories:
    - url: git@github.com:myorganization/myrepo.git
      name: myrepo
      type: git
      sshPrivateKey: abcdef # real private key is here

server:
  certificate:
    enabled: true
    secretName: argocd-server-tls
    domain: argocd.mydomain.com
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.mydomain.com
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.mydomain.com

```

The ArgoCD is being installed and everything is configured correctly, apart from the `argocd-server-tls` Secret. It won't be created and I have no idea why.

`cert-manager` is being installed separately using the following terraform code:

```tf
resource "helm_release" "cert_manager" {
  name       = "cert-manager"
  namespace  = kubernetes_namespace.cert_manager.metadata.0.name
  chart      = "cert-manager"
  repository = "https://charts.jetstack.io"
  version    = "v1.11"

  set {
    name  = "installCRDs"
    value = "true"
  }
}

resource "kubectl_manifest" "clusterissuer_letsencrypt_prod" {
  yaml_body          = file("${path.module}/cert-manager/clusterissuer-letsencrypt-prod.yaml")
  override_namespace = kubernetes_namespace.cert_manager.metadata.0.name
  depends_on = [
    helm_release.ingress_nginx,
    helm_release.cert_manager,
  ]
}
```

What might the issue be?
