### DISCUSSION TITLE
What resources requirements do you have set in your argoCD chart?

### DISCUSSION THREAD

**Discussion by Almenon** [argoproj/argo-helm#1929] [General]
I'm curious what resource requirements you use, and whether you've ever seen argoCD hit your CPU or memory limit.

**Comment by Almenon** [comment]
My resource usage for the past week is _extremely_ low, as it has very little usage. I set it to the following:
```yaml
server:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
applicationSet:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
notifications:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
controller:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi
```
