### DISCUSSION TITLE
Are repoServer ENVs usable for Sidecar Plugins?

### DISCUSSION THREAD

**Discussion by Moep90** [argoproj/argo-helm#1968] [Q&A]
Good Morning from Germany,
I'm currently migrating from argocd 2.4 to 2.6.
I'm using a sidecar plugin and would like to pass an existing env variable from the repoServer into the sidecar plugin execution.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
[....]
    plugin:
      name: kapitan-v1.0
      parameters:
[....]
        - name: VAULT_TOKEN
          string: ${my_VAULT_TOKEN}
```
When passing the VAULT_TOKEN as string here, this works. referencing an ENV seams to not work.
Does anyone has a tipp on how I can achieve that?
Another option I see is to pass the envs directly into the plugin extraContainer, but it does not seem to have this option atm.

Cheers guys!

https://cloud-native.slack.com/archives/C01TSERG0KZ/p1681455422193329
