### DISCUSSION TITLE
ARGOCD helm chart with default value doesn't work

### DISCUSSION THREAD

**Discussion by Kilz78** [argoproj/argo-helm#2106] [Q&A]
Hello, 

I'm trying to install for the first time argoCD, with default value, the helm chart doesn't work. 
can someone help please ? 

$ helm install arhocd -n argotst1 ./argoCD/

```
Error: INSTALLATION FAILED: template: argo-cd/templates/dex/deployment.yaml:16:11: 
executing "argo-cd/templates/dex/deployment.yaml" at <include "argo-cd.strategy" (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.dex.deploymentStrategy)>: error calling include: template: argo-cd/templates/_common.tpl:130:8: executing "argo-cd.strategy" at <eq $preset.type "Recreate">: 

error calling eq: incompatible types for comparison
```

**Comment by yu-croco** [comment]
Hi @Kilz78 ,
I think this is because your Helm version is old. Please update it and try again.

Ref: https://github.com/argoproj/argo-helm/issues/1984#issuecomment-1525367453
Ref: https://github.com/argoproj/argo-helm/discussions/1973#discussioncomment-5709498

**Reply by Kilz78** [reply]
@yu-croco Yep I saw this discussion, so I upgraded my helm with the last one ? 
`version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}`

It doesn't solve my issue.

**Reply by yu-croco** [reply]
I prepared Helm Chart on my local with default values.yaml.

- Chart.yaml
```yaml
apiVersion: v2
name: argocd-samples
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 5.36.1
    repository: https://argoproj.github.io/argo-helm
```

I installed the chart and it worked well. 🤔 
```
$ helm version
version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

$ helm install argo-cd .
NAME: argo-cd
LAST DEPLOYED: Thu Jun 15 19:54:21 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

```
