### DISCUSSION TITLE
How to define the AWS ALB Helm Chart tag (like Redis Helm Chart) to use in the ArgoCD values.yaml?

### DISCUSSION THREAD

**Discussion by good92** [argoproj/argo-helm#2110] [General]
Is it possible to set the particular tag of the ALB Helm chart in the ArgoCD values.yaml file?

I tried to find the dependencies version used with no success.

- Redis tag
```
redis:
  image:
    # -- Redis repository https://gallery.ecr.aws/docker/library/redis
    repository: public.ecr.aws/docker/library/redis
    # -- Redis tag
    tag: 7.0.11-alpine3.18`
```

- Commands to look for the dependencies on a specific Helm Chart - limited to one depth:

```
wget https://github.com/argoproj/argo-helm/releases/tag/argo-cd-5.29.1
helm dependency list ./argo-cd-5.29.1.tgz
```
```
NAME VERSION REPOSITORY STATUS
redis-ha 4.22.5 https://dandydeveloper.github.io/charts/ unpacked
```

ALB: https://github.com/kubernetes-sigs/aws-load-balancer-controller

Thank you in advance.
