### DISCUSSION TITLE
ARGOCD HelmChart install OCI repos

### DISCUSSION THREAD

**Discussion by tribu** [argoproj/argo-helm#2168] [Q&A] [answered]
Hi,
I am using helmcharts to install and manage argocd. I wanted to know if there is a way to configure OCI repos via helmchart? or any other way to automate configuring  OCI repos in argocd helmchart

**Comment by pdrastil** [comment, marked as answer]
Hi,
yes there are two possible ways. Either you use OCI image directly in Application resource like this:

```yaml
kind: Application
spec:
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.29.0
```

OR you can config repository in Argo CD helm chart like this:

```yaml
configs:
  repositories:
    aws:
      type: helm
      name: aws
      url: public.ecr.aws
      enableOCI: true
```

NOTE: I haven't seen any drop down menus in UI for charts / versions even when you enter the values correctly. You will have to elaborate a little bit what are correct values to fetch the chart in OCI format.
