### DISCUSSION TITLE
how to use rollouts with multiple containers in one pod?

### DISCUSSION THREAD

**Discussion by arturmon** [argoproj/argo-helm#2185] [Q&A]
how to use rollouts with multiple containers in one pod?
example:
```
...
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/instance: release-name
        app.kuberntes.io/service: app-backend
    spec:
      strategy:
        canary:
          canaryService: release-name-service-review
          stableService: release-name-service-stable
          trafficRouting:
            smi: {}
          steps:
          - setWeight: 5
          - pause: {}
...
      containers:
        - name: service
          ports:
            - name: http-service
              containerPort: 3333
        - name: service-2
          ports:
            - name: http-service-2
              containerPort: 3332
...
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-service-stable
...
  ports:
    - port: 3333
      targetPort: http-service
      protocol: TCP
      name: http-service
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: release-name
    app.kuberntes.io/service: app-backend
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-service-2-stable
...
  ports:
    - port: 3332
      targetPort: http-service-2
      protocol: TCP
      name: http-service-2
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: release-name
    app.kuberntes.io/service: app-backend

...
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-service-review
...
  ports:
    - port: 3333
      targetPort: http-service
      protocol: TCP
      name: http-service
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: release-name
    app.kuberntes.io/service: app-backend-review
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-service-2-review
...
  ports:
    - port: 3332
      targetPort: http-service-2
      protocol: TCP
      name: http-service-2
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: release-name
    app.kuberntes.io/service: app-backend-review
```
how to make canary release-name-service-2-stable and release-name-service-2-review ?
