### DISCUSSION TITLE
ArgoCD apps helm chart projects don't show on the UI.

### DISCUSSION THREAD

**Discussion by madelaney** [argoproj/argo-helm#2188] [General]
Using terraform and helm charts, I'm attempting to create a project and app. The app shows up on the UI and shows an associated project. When I attempt to view the project(s), either from global projects URL (https://argocd/settings/projects) nothing is displayed. When I attempt to use project URL (i.e https://argocd/settings/projects/prometheus), I see the error message: `Failed to load data, please try again.`

The terraform code is:
```terraform
resource "helm_release" "argocd-projects" {
  name       = "argocd-apps"
  chart      = "argocd-apps"
  repository = "https://argoproj.github.io/argo-helm"
  version    = "1.3.0"
  namespace  = "argo-cd"
  values = [
    file("${path.module}/../config/argocd-projects/values.yaml"),
  ]
}
```

The `values.yaml` looks like:
```yaml
---
projects:
  - name: prometheus
    namespace: argo-cd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    description: Prometheus Engine
    sourceRepos:
      - "*"
    destinations:
      - namespace: prometheus
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    orphanedResources:
      warn: false
```

From the examples I've been able to find, this seems accurate but something must be wrong here.

- Mike D.
