### DISCUSSION TITLE
I use traefik but I can't access my domain

### DISCUSSION THREAD

**Discussion by Re3v3s** [argoproj/argo-helm#2272] [Q&A]
First I apologize with my bad English , So my yml is like this
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: my-argocd
spec:
  entryPoints:
    - websecure
  tls:
    secretName: my-secret
  routes:
    - kind: Rule
      match: Host(`my.domain.com`)
      priority: 10
      middlewares:
        - name: traefik-redirect-scheme
          namespace: default
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`my.domain.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
```

But I still can't reach my domain , someone advice please
