### DISCUSSION TITLE
[Question] Application Controller ha replica count

### DISCUSSION THREAD

**Discussion by emirot** [argoproj/argo-helm#2368] [General]
I would like to enable ha.
However in the example, I would like to know more about the application controller.
This one is a statefulset and I would like to understand if putting 2 replicas will do something?
Especially if I have only one cluster, it is not clear to me.

From the example Readme: https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
```
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
```

Not found in [previous discussions](https://github.com/argoproj/argo-helm/discussions?discussions_q=%5BQuestion%5D+Application+Controller+ha+replica+count+)
