### DISCUSSION TITLE
Why does argocd-repo-server need admin permission

### DISCUSSION THREAD

**Discussion by ytizhang** [argoproj/argo-helm#2420] [Q&A] [answered]
We are using argo-cd chart version 5.43.4, and noticed the service account used by argocd-repo-server has admin permission. Based on my understanding, argocd-repo-server is responsible for holding the application manifests and generating kubernetes manifests. Why does it need admin permission?

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cd-argocd-repo-server
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-cd-argocd-repo-server
subjects:
  - kind: ServiceAccount
    name: argo-cd-argocd-repo-server
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cd-argocd-repo-server
```
