### DISCUSSION TITLE
Where do I put resource.links configuration in argocd helm chart 6.x.x?

### DISCUSSION THREAD

**Discussion by boniek83** [argoproj/argo-helm#2487] [General]
In older versions of the helm chart I've put it under server.config but now it is not getting picked up.

**Comment by pdrastil** [comment]
Hi `server.config` was replaced with `configs.cm` roughly year ago. You can provide any arbitrary keys that are currently supported by upstream https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml

```yaml
configs:
  cm:
    resource.links: |
    - url: https://mycompany.splunk.com?search={{.metadata.namespace}}
      title: Splunk
      if: kind == "Pod" || kind == "Deployment"
```
