### DISCUSSION TITLE
How to disable argo-cd server when using helm chart to deploy argo-cd core mode?

### DISCUSSION THREAD

**Discussion by zyy17** [argoproj/argo-helm#2529] [Q&A]
When I use the argo-cd helm chart to deploy the argo-cd core, which only contains application-controller,applicationset-controller, and repo-server, I can't disable argo-cd server deployment. The following are my values:

```yaml
argo-cd:
  redis-ha:
    enabled: false

  controller:
    replicas: 1

  server:
    replicas: 1

  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1

  dex:
    enabled: false

  redis:
    enabled: false

  notifications:
    enabled: false
```
