### DISCUSSION TITLE
Can Argo Manage its own Helm Release? Should it?

### DISCUSSION THREAD

**Discussion by charles-horel-rogers** [argoproj/argo-helm#2661] [Ideas]
It would be nice if I could bootstrap ArgoCD on a kubernetes cluster, and then define an application that manages the ArgoCD helm release.

Currently if I want to make changes to RBAC or the ArgoCD config maps declaratively using Argo, I have a couple of options. I can just patch the CM manually using argo (snippet below). I also have the option of re-running my helm bootstrap process manually with modified values.

I am wondering if managing this by having Argo manage its own helm release after bootstrapping is a better idea, or a much worse idea. That way I can push a change to version control and update TLS trust on the argocd-cm, or add policy mappings to policy.csv. I noticed that argo deployed helm releases don't show up when you run helm list, it looks like it's managing releases internally to argo and deploying manifests to the cluster only.

Has anyone tried this? My gut tells me it's not a great idea, but I figured I'd ask about my current approach and see if there are any other alternatives that are preferable.

```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, ADMIN_GROUP, role:admin
  policy.default: "role:readonly"
  # essential to get argo to use groups for RBAC:
  scopes: '[groups,email]'
```
