### DISCUSSION TITLE
Setting custom Interval check for Argo CD Image Updater via CLI

### DISCUSSION THREAD

**Discussion by soakes** [argoproj/argo-helm#2755] [Q&A]
Hi everyone,

I'm trying to configure Argo CD Image Updater to check for new image updates every 6 hours instead of the default 2 minutes. Ideally, I'd prefer to achieve this using the command-line interface (CLI) rather than modifying the values.yaml file.

I've attempted various approaches to set the interval flag via helm install, but haven't been successful. Could someone provide guidance on how to handle this through the CLI?

What you see from the values.yaml file below, is what I am trying to do via CLI
https://github.com/argoproj/argo-helm/blob/main/charts/argocd-image-updater/values.yaml#L30-L31

Here are some of the options I've tried:

```
❯ helm upgrade -n argocd argocd-image-updater --set extraArgs:"--interval=6h" argo/argocd-image-updater
```

```
❯ helm upgrade -n argocd argocd-image-updater --set extraArgs.interval=6h argo/argocd-image-updater
```
.. and many others.

The top one does seem to accept but checking the logs, I dont see the time being updated, its still every 2 mins.

Does anyone know how this should be done?

**Comment by soakes** [comment]
### Update
I have created a work around, but I would still love to know why I can't do it directly via `--set` options.  Any thoughts?

```
helm repo add argo https://argoproj.github.io/argo-helm
helm upgrade -n argocd argocd-image-updater argo/argocd-image-updater -f - <<EOF
# -- Extra arguments for argocd-image-updater not defined in config.argocd.
# If a flag contains both key and value, they need to be split to a new entry
extraArgs: 
  - --interval
  - 360m
config:
  # -- Username to use for Git commits
  gitCommitUser: ""

  # -- E-Mail address to use for Git commits
  gitCommitMail: ""

  # -- Changing the Git commit message
  gitCommitTemplate: ""

  # -- Argo CD Image Updater registries list configuration. More information [here](https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/)
  registries: 
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      ping: yes
      credentials: secret:argocd/dockerhub
      defaultns: library
EOF
```
