### DISCUSSION TITLE
Should Redis haproxy be enabled by default?

### DISCUSSION THREAD

**Discussion by hongbo-miao** [argoproj/argo-helm#2785] [General]
I tried to enable high avaiablity for Argo CD. However, I got error

> Back-off restarting failed container haproxy

withtout any useful logs

```sh
➜ kubectl logs hm-argo-cd-redis-ha-haproxy-66f76857db-5hz4r -n production-hm-argo-cd -c haproxy
(empty)

➜ kubectl logs hm-argo-cd-redis-ha-haproxy-66f76857db-5hz4r -n production-hm-argo-cd -c config-init
10.100.105.117    hm-argo-cd-redis-ha-announce-0.production-hm-argo-cd.svc.cluster.local  hm-argo-cd-redis-ha-announce-0.production-hm-argo-cd.svc.cluster.local hm-argo-cd-redis-ha-announce-0
10.100.87.44      hm-argo-cd-redis-ha-announce-1.production-hm-argo-cd.svc.cluster.local  hm-argo-cd-redis-ha-announce-1.production-hm-argo-cd.svc.cluster.local hm-argo-cd-redis-ha-announce-1
10.100.60.14      hm-argo-cd-redis-ha-announce-2.production-hm-argo-cd.svc.cluster.local  hm-argo-cd-redis-ha-announce-2.production-hm-argo-cd.svc.cluster.local hm-argo-cd-redis-ha-announce-2
```

So I am currently disabled Redis's `haproxy`

```yaml
redis-ha:
  enabled: true
  haproxy:
    enabled: false
controller:
  replicas: 1
server:
  autoscaling:
    enabled: true
    minReplicas: 2
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
applicationSet:
  replicas: 2
```

Based on

https://github.com/argoproj/argo-helm/blob/b0d4648471aef30a1a849a82c84dcb37ed7b504d/charts/argo-cd/values.yaml#L1534-L1536

Redis haproxy is enabled by default.

However, based on https://github.com/DandyDeveloper/charts/blob/61dbe860a2519e70033de651a59593ba2de8e8ac/charts/redis-ha/values.yaml#L69-L73

haproxy is recommended for Redis clusters exposed externally.

Should Redis haproxy be enabled by default? Thanks!
