### DISCUSSION TITLE
SSO in values wont repercut into configmap

### DISCUSSION THREAD

**Discussion by JDHawken** [argoproj/argo-helm#2859] [Q&A] [answered]
Hello guys!
I'm on big upgrade of my ArgoWorkFlows Chart (3.4.8 to 3.5.8), everything looking good or almost, my pods **argo-server** are on **CrashLoopBackOff**, when I get the logs, I got the following message : 
`argo-server-677bb5fb98-ls9rt issuer empty`

After long time of check, I notice my ConfigMaps **argo-workflow-controller-configmap** aren't complety set...

In Production (3.4.8), I got theses seetings :

```
sso:
  issuer: [my-server]/realms/master
  clientId:
    name: [my-id]
    key: [my-key]
  clientSecret:
    name: [my-secret]
    key: [my-key]
  redirectUrl: [my-server]/oauth2/callback
  rbac:
    enabled: true
  scopes:
    - [my-roles]
nodeEvents:
  enabled: true
```
But I didn't have theses lines on my test servers...
No problem with my sso, I've even rollback test servers on 3.4.8 and it's worked again!

Here a part on my Helm Charts :
**values.yaml**

```yaml
server:
  extraArgs: ["--auth-mode", "sso"]
  sso:
    issuer: ""
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    redirectUrl: ""
    rbac:
      enabled: true
  ssoAccounts:
    enabled: true
    prefix: argo
    userRule: "'ARGO_USER' in groups"
    adminRule: "'ARGO_ADMIN' in groups"
  # OJX
```
**values-staging.yaml**
```yaml
server:
  sso:
    issuer: [my-server]/realms/master
    redirectUrl: [my-server]/oauth2/callback
```

I already checked if my predecessor didn't put any values in /templates/controller but I couldn't find anything.
**values.yaml** and **values-staging.yaml** on prod (3.4.8) and staging (3.5.8) are same files, I only updated folders ci and templates and the image.
Any ideas about why Helm just ignore sso part from my values.yaml when I deploy ArgoWorkFlow ? 

Many thanks in advance!
