### DISCUSSION TITLE
SSO issue on ArgoWorkFlow after HelmChart Upgrade

### DISCUSSION THREAD

**Discussion by JDHawken** [argoproj/argo-helm#2865] [Q&A] [answered]
Hello everyone,
I'm trying to update my ArgoWorkFlow from 3.4.8 to 3.5.8.
Everything look good but I meet issue when users (administrators included) try to loggin into ArgoWorkFlow, we got the following error :
`Failed to load version/info Error: Forbidden`
![Capture](https://github.com/user-attachments/assets/2ddd4ad9-a58a-4455-9461-6bd01f808bf6)
I looked into logs and I can find theses following messages :

```
time="2024-08-06T09:37:08.059Z" level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
time="2024-08-06T09:37:08.059Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed"
time="2024-08-06T09:37:08.059Z" level=error msg="failed to perform RBAC authorization" error="no service account rule matches"                                  
time="2024-08-06T09:37:08.059Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed"
```

Here my values.yaml on this part :

```yaml
  sso:
    enabled: true
    issuer: [my-domain]/auth/realms/master
    redirectUrl: [my-domain]/argo/oauth2/callback
    clientId:
      name: [my-id]
      key: [my-key]
    clientSecret:
      name: [my-secret]
      key: [my-key]
    redirectUrl: ""
    insecureSkipVerify: true
    rbac:
      enabled: true
    scopes:
      - ArgoRoles
  ssoCAcrt: [my-crt]
  ssoSecret:
    enabled: true
    name: [my-secret]
    clientId: argo
    clientSecret: [secret-in-keycloak]
  ssoAccounts:
    enabled: true
    prefix: argo
    userRule: "'ARGO_USER' in groups"
    adminRule: "'ARGO_ADMIN' in groups"
```
Authentication is provided by Keycloak, I'm not sure where to look...
I checked Keycloak and communication in logs and everything looking good on my part :

When I put wrong password :
`13:28:21,098 WARN  [org.keycloak.events] (default task-57) type=LOGIN_ERROR, realmId=master, clientId=argo, userId=9cf3f2cb-e74d-47cd-a4b0-23da81cc172b, ipAddress=, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=[my-domain]/argo/oauth2/callback, code_id=e3c5e019-64fd-420c-9e8a-5c4fa57508ed, username=[my-username], authSessionParentId=e3c5e019-64fd-420c-9e8a-5c4fa57508ed, authSessionTabId=KrTMZNxNpT0`

When password is correct : No log.

I checked existence of **ArgoRoles** in Keycloak (Realms>Master>Configure>Client Scopes) and I can found it !
I try to back on 3.4.8 and it's worked again, I think I got problem in my values.yaml.
Any idea ?

Many thanks in advance !
