### DISCUSSION TITLE
How to enable ingress with Istio?

### DISCUSSION THREAD

**Discussion by davidshen84** [argoproj/argo-helm#2901] [Q&A]
Hi,

I found an [ingress](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L2155) value for the argocd-server deployment in the helm chart. If I want to enable ingress control to the argocd server, is it the right place to start with?

I have a k3s running in my WSL 2 on my Windows. I have Istio installed. I also manually configured istio gateway and virtual-service to provide ingress gateway to my argocd server. But I want to use one chart to install all the configuration, so I wonder if the `ingress` section is the right place.

I update that section to this:

```yaml
    ingress:
        enabled: true
        controller: generic
        labels: {}
        annotations: {}
        ingressClassName: istio
        hostname: wsl.local
        path: /argo
        pathType: Prefix
        tls: false
        extraHosts: []
        extraPaths: []
        extraRules: []
        extraTls: []
```

After applied the updates, I found an `Ingress` resource is created in my `argocd` namespace. But I cannot connect to my argocd server using `http://wsl.local/argo`. The connection is simply refused.

Also, based on my understanding, we also need a `gateway` and a `httproute` resource for the k8s gateway API to work, but I could not find them. I wonder if I have missed some configurations. I also cannot find any guideline or documentation about this `ingress` section.

Thanks
