### DISCUSSION TITLE
e-mail notification: gomail: could not send e-mail 1: gomail: invalid address \"\": mail

### DISCUSSION THREAD

**Discussion by volker-raschek** [argoproj/argo-helm#2963] [Q&A]
I have deployed ArgoCD on my cluster and am about to complete the setup. I want to activate the e-mail notification service right away. I have rolled out a test deployment for this. In the logs of ArgoCD I can see that the appplication is trying to send the e-mail, but ArgoCD runs into an error:

```text
time="2024-10-03T17:22:45Z" level=info msg="Trigger on-sync-succeeded result: [{[0].zxM90Et6k4Elb1-fHdjtDJq0xR0  [app-sync-succeeded] true}]" resource=default/test
time="2024-10-03T17:22:45Z" level=info msg="Sending notification about condition 'on-sync-succeeded.[0].zxM90Et6k4Elb1-fHdjtDJq0xR0' to '{myEmail volker-raschek@my-company.local using the configuration in namespace default" resource=default/test
time="2024-10-03T17:22:45Z" level=error msg="Failed to notify recipient {myEmail volker-raschek@my-company.local} defined in resource default/test: gomail: could not send email 1: gomail: invalid address \"\": mail: no address using the configuration in namespace default" resource=default/test
```

I cannot explain why the e-mail address should be invalid, because I have configured the helm chart accordingly. Does anyone have any idea what I might have done wrong here? Here is an excerpt of my configuration:

```yaml
notifications:
  secret:
    items:
      email-username: noreply@my-company.local 
      email-password: my-secret-password


  notifiers:
    service.email.myEmail: |
      username: $email-username
      password: $email-password
      host: smtp1.my-company.local
      port: 587
      form: $email-username
 
  templates:
    template.app-sync-status-unknown: |
      email:
        subject: Application {{.app.metadata.name}} sync status is 'Unknown'
      message: |
        {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} sync is 'Unknown'.
        Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
        {{if ne .serviceType "slack"}}
        {{range $c := .app.status.conditions}}
            * {{$c.message}}
        {{end}}
        {{end}}
    template.app-sync-succeeded: |
      email:
        subject: Application {{.app.metadata.name}} has been successfully synced.
      message: |
        {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
        Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .

  triggers:
    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'
    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        send:
        - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']
```
