### DISCUSSION TITLE
can `.Values.controller.extraContainers` use subtemplates?

### DISCUSSION THREAD

**Discussion by tianhui-fu** [argoproj/argo-helm#3133] [Q&A]
we have defined sidecar template. we want to include it to values.yaml directly. for example:
```
argocd:
  controller:
    extraContainers: 
    - |
      {{- include "xxx" .Values.xxx }}
    - |
      {{- include "yyyy" .Values.yyy}}
```

is it possible to do that?

in my test, if we update the [lines](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-application-L350) to something like
```
{{- range .Values.argocd.controller.extraContainers }}
  {{- tpl . $ | nindent 6 }}
{{- end }}
```

it can work.
