### DISCUSSION TITLE
service.beta.kubernetes.io/aws-load-balancer-name doesn't set the load balancer name on new deployment.

### DISCUSSION THREAD

**Discussion by jamrobi2** [argoproj/argo-helm#3337] [General]
Apologies if this is a basic question, but i'm currently stumped, I do have a work around by using tags and they work, but for my own piece of mind...

The following config is used for deploying an nlb.
```
server:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

  ingress:
    enabled: false

  service:
    type: LoadBalancer

    annotations:
      # Make the Load Balancer internal
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-name: "argocd-nlb"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=argocd-nlb,Environment=dev"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-subnets: "${subnets_string}"
    loadBalancerSourceRanges:
      - 10.0.0.0/8
```

Everything is working except the name is ALWAYS a generated string, not the name passed in by the `service.beta.kubernetes.io/aws-load-balancer-name` annotation.

Is this supported, if so how should I be using it?
