### ISSUE TITLE
missing mount  commit.template for argocd-image-updater

### ISSUE THREAD

**Issue by jenningsloy318** [argoproj/argo-helm#1004]
### Describe the bug

when installed it, we will configure the commit.template in the configmap, but here in the deployment.yaml. it doesn't mount it here, now only registries.conf mounted
```
...
      volumes:
      - configMap:
          items:
          - key: registries.conf
            path: registries.conf
          name: argocd-image-updater-config
        name: registries-conf
...
```

### Related helm chart

argocd-image-updater

### To Reproduce

any deployment will have same result

### Expected behavior

```
      volumes:
      - configMap:
          items:
          - key: registries.conf
            path: registries.conf
          - key: commit.template
            path: commit.template
          name: argocd-image-updater-config

```
