### ISSUE TITLE
[argo-workflows] Unable to submit CronWorkflow from Argo Server UI 

### ISSUE THREAD

**Issue by am-sebastiankunze** [argoproj/argo-helm#1009]
### Describe the bug

When submitting a CronWorkflow from the Argo Server UI, I receive the following error message:

```
Forbidden: workflows.argoproj.io "aweseom-octopus-cron-g7vng" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

### Related helm chart

argo-workflows

### To Reproduce

1. Go to `Cron Workflow`
2. Create the following CronWorkflow
```
metadata:
  name: awesome-octopus-cron
  namespace: default
  labels:
    example: 'true'
spec:
  workflowMetadata:
    creationTimestamp: null
    labels:
      example: 'true'
  schedule: '*/5 * * * *'
  workflowSpec:
    entrypoint: argosay
    arguments:
      parameters:
        - name: message
          value: hello argo
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: '{{workflow.parameters.message}}'
        outputs: {}
        metadata: {}
        container:
          name: main
          image: 'argoproj/argosay:v2'
          command:
            - /argosay
          args:
            - echo
            - '{{inputs.parameters.message}}'
          resources: {}
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
```
4. Open CronWorkflow and submit it

### Expected behavior

Workflow is submitted and executed immediately

### Additional context

I have added the following rule to the Role used by the ServiceAccount of the Argo Server. That seems to fix things.
```
- apiGroups:
  - argoproj.io
  resources:
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
```
