### ISSUE TITLE
Argo-Rollouts helm chart misses leader clusterroles

### ISSUE THREAD

**Issue by derjust** [argoproj/argo-helm#1012]
### Describe the bug

With Argo 1.1, there was a HA leader-election implement based on K8s primitives: https://github.com/argoproj/argo-rollouts/pull/1519

### Related helm chart

argo-rollouts

### To Reproduce

1. Deploy the Argo-rollouts  helm chart `2.3.0`
2. See logs of the  Argo-rollouts controller 

### Expected behavior

The Helm chart creates the required cluster roles and the Argo rollout deployment would just work.

### Additional context

Judging by other helm charts the, the additional cluster roles to `charts/argo-rollouts/templates/controller/clusterrole.yaml`
```yml
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - argo-rollouts-controller-lock
  verbs:
  - get
  - watch
  - update
  - patch
  - delete
```
resolved the issue

**Comment by sergeyshaykhullin** [comment]
+1 Getting the same error

```
E1113 13:45:08.492572       1 leaderelection.go:325] error retrieving resource lock kube-system/argo-rollouts-controller-lock: leases.coordination.k8s.io "argo-rollouts-controller-lock" is forbidden: User "system:serviceaccount:argo:rollouts" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

Fixed with

```
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - create
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
```
