### ISSUE TITLE
Dex metrics are still not reachable.

### ISSUE THREAD

**Issue by hughhm** [argoproj/argo-helm#1013]
This issue should be reopened. Dex metrics are still not reachable.

_Originally posted by @aslafy-z in https://github.com/argoproj/argo-helm/issues/615#issuecomment-841643114_

Port forward on the pod to default port 5558 shows that the metrics are not being posted by the Dex server. Otherwise the configuration is in place for metrics but the core piece of the puzzle is missing.

I am using the latest chart version: 3.25.2. With the following configuration:

```
  metrics:
    enabled: true
    service:
      labels:
        app: argocd-dex
    serviceMonitor:
      enabled: true
      interval: 30s
      selector:
        app: argocd-dex
        prometheus: serviceMonitor
      namespace: monitoring
```

With the `kube-prometheus-stack` chart option `serviceMonitorSelector` set to pick up the label `prometheus: serviceMonitor` on the service monitor and i have confirmed it is doing so with the target showing in prometheus.
