### ISSUE TITLE
ArgoCD AKS credentials in values.yml

### ISSUE THREAD

**Issue by JimFran** [argoproj/argo-helm#1026]
Hello,

I need to connect via ArgoCD Helm values.yml a couple of AKS clusters when deploying ArgoCD.

https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml

**From the values.yml files I saw that it's possible to pass the AKS clusters credentials into the values:**

```
clusterCredentials: []
    # - name: mycluster
    #   server: https://mycluster.com
    #   labels: {}
    #   annotations: {}
    #   config:
    #     bearerToken: "<authentication token>"
    #     tlsClientConfig:
    #       insecure: false
    #       caData: "<base64 encoded certificate>"
    # - name: mycluster2
    #   server: https://mycluster2.com
    #   labels: {}
    #   annotations: {}
    #   namespaces: namespace1,namespace2
    #   config:
    #     bearerToken: "<authentication token>"
    #     tlsClientConfig:
    #       insecure: false
    #       caData: "<base64 encoded certificate>"
```
**and also when setting up the applications pass the cluster URL**

```
 additionalApplications: []
  # - name: guestbook
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations: {}
  #   finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  #   project: guestbook
  #   source:
  #     repoURL: https://github.com/argoproj/argocd-example-apps.git
  #     targetRevision: HEAD
  #     path: guestbook
  #     directory:
  #       recurse: true
  #   destination:
  #     server: https://kubernetes.default.svc
  #     namespace: guestbook
  #   syncPolicy:
  #     automated:
  #       prune: false
  #       selfHeal: false
  #   ignoreDifferences:
  #   - group: apps
  #     kind: Deployment
  #     jsonPointers:
  #     - /spec/replicas
  #   info:
  #   - name: url
  #     value: https://argoproj.github.io/
```

My questions are:

**1. When setting up "additional applications" in order to deploy the application in the target AKS cluster do I need just to include the URL that I used when setting up "cluster credentials"?**

**2. When I check my ".kube" file where I have stored my AKS credentials in Azure I see 3 different data:**

```
    client-certificate-data: XXX
    client-key-data: ZZZ
    token: YYY
```

For "bearerToken" i guess I have to use "token" data. However, for "caData" what do I have to use? Also do I need to encode into Base64 this info in values.yml files?

I followed the official info from ArgoCD but it is not straightforward to me.

https://argo-cd.readthedocs.io/en/stable/getting_started/#5-register-a-cluster-to-deploy-apps-to-optional
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters

Thanks in advance.

**Comment by mkilchhofer** [comment]
To answer your questions:
1. Lets say you register an external cluster to your ArgoCD instance like this:
   ```yaml
   clusterCredentials:
     - name: mycluster
       server: https://mycluster.com
       config:
         bearerToken: "<authentication token>"
         tlsClientConfig:
           insecure: false
           caData: "<base64 encoded certificate>"
   ```
   You can then deploy apps to this cluster by using `mycluster` or `https://mycluster.com` in the destination. Eg:
   ```yaml
       destination:
         server: https://mycluster.com
   ```
   And here a full example:
   ```yaml
   additionalApplications:
     - name: guestbook
       namespace: argocd
       additionalLabels: {}
       additionalAnnotations: {}
       finalizers:
       - resources-finalizer.argocd.argoproj.io
       project: guestbook
       source:
         repoURL: https://github.com/argoproj/argocd-example-apps.git
         targetRevision: HEAD
         path: guestbook
         directory:
           recurse: true
       destination:
         server: https://mycluster.com # <------------ see here!
         namespace: guestbook
       syncPolicy:
         automated:
           prune: false
           selfHeal: false
   ```
2. I'd recommend not using a personal user to deploy to an external cluster. You should create a ServiceAccount/ClusterRole/ClusterRoleBinding in the external cluster and use this. Eg.

   - create ServiceAccount and read the ServiceAccount token
     ```console
     $ cat foo.yaml
     apiVersion: v1
     kind: ServiceAccount
     metadata:
       name: argo-cd
       namespace: kube-system
     ---
     apiVersion: rbac.authorization.k8s.io/v1
     kind: ClusterRoleBinding
     metadata:
       name: read-secrets-global
     subjects:
     - kind: ServiceAccount
       name: argo-cd
       namespace: kube-system
     roleRef:
       kind: ClusterRole
       name: admin
       apiGroup: rbac.authorization.k8s.io


     $ kubectl apply -f foo.yaml
     serviceaccount/argo-cd created
     clusterrolebinding.rbac.authorization.k8s.io/read-secrets-global created
     kubectl get secret argo-cd-token-dmjvx -o yaml
     apiVersion: v1
     data:
       ca.crt: LS0tLS1CRU...QVRFLS0tLS0K # <--- this is your caData
       namespace: a3ViZS1zeXN0ZW0=
       token: ZXlKa...wRVlOdw==          # <--- this is your bearerToken (you need to decode it first via `base64 -d`)
     kind: Secret
     metadata:
       (..)
     ```
   - Use this config
     ```yaml
     clusterCredentials:
       - name: mycluster
         server: https://mycluster.com
         config:
           bearerToken: "eyJhbG...LFOUgYnLxLlRpEYNw"
           tlsClientConfig:
             insecure: false
             caData: "LS0tLS1CRU...QVRFLS0tLS0K"
     ```
