### ISSUE TITLE
ApplicationSet not found in values.yml

### ISSUE THREAD

**Issue by JimFran** [argoproj/argo-helm#1027]
Hello,

I was thiking that "Additional applications" is similar to ApplicationSet so i can deploy different applications in different clusters. However I need to use just a single file ApplicationSet.yml

How can I use ApplicationSet in Values.yml files? I cannot see the option to add the application set file.

In case that I need to pass this file, how can I do that?

Thank you in advance.

**Comment by JimFran** [comment]
> Hi @JimFran,
> 
> I don't understand your request. Is it about Argo CD installation via Helm chart? If yes, please open an issue in the `argo-helm` repository.

Am I not in argo-helm repository?

![image](https://user-images.githubusercontent.com/65667266/142724484-03d5433c-3757-4081-bb34-18b7bbe38ab5.png)

My question is about ApplicationSet in ArgoCD Helm.

In a regular ArgoCD deployment in order to use applicationset we use this kind of deployment:

** I want to use ApplicationSet to deploy applications to more than one AKS server **

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://1.2.3.4
      - cluster: engineering-prod
        url: https://2.4.6.8
      - cluster: finance-preprod
        url: https://9.8.7.6
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```
In Values.yml chart I can see this section to add applications but not to use applicationset:

```
dditionalApplications: []
  # - name: guestbook
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations: {}
  #   finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  #   project: guestbook
  #   source:
  #     repoURL: https://github.com/argoproj/argocd-example-apps.git
  #     targetRevision: HEAD
  #     path: guestbook
  #     directory:
  #       recurse: true
  #   destination:
  #     server: https://kubernetes.default.svc
  #     namespace: guestbook
  #   syncPolicy:
  #     automated:
  #       prune: false
  #       selfHeal: false
  #   ignoreDifferences:
  #   - group: apps
  #     kind: Deployment
  #     jsonPointers:
  #     - /spec/replicas
  #   info:
  #   - name: url
  #     value: https://argoproj.github.io/
```

My question then:

Can I use ApplicationSet in ArgoCD Helm values.yml file? Instead of deploy an applicationset.yml I want to ddo this using argocd helm values.yml file.

Hope this clarifies my question.

**Comment by mkilchhofer** [comment]
Hi @JimFran the charts `argo-cd` and `argocd-applicationset` are two separate charts. The argo-cd chart does not include functionality from `argocd-applicationset`.

The key `additionalApplications` of the `argo-cd` chart just deploys resources of Kind `Application`.
If you need to deploy the resource `ApplicationSet` when using the applicationset app, you have to create this resource outside of helm as the chart `argocd-applicationset` does not yet provide this functionality.

**Comment by JimFran** [comment]
> Hi @JimFran the charts `argo-cd` and `argocd-applicationset` are two separate charts. The argo-cd chart does not include functionality from `argocd-applicationset`.
> 
> The key `additionalApplications` of the `argo-cd` chart just deploys resources of Kind `Application`. If you need to deploy the resource `ApplicationSet` when using the applicationset app, you have to create this resource outside of helm as the chart `argocd-applicationset` does not yet provide this functionality.

Thanks for your message @mkilchhofer 

I'm doing something that's not working... not sure if I'm following the correct approarch to deploy applicationset.

This is my override_values.yml file that I use to deploy argocd helm chart:

**In "additional applications", in override_values.yml file, I specified the path to my ApplicationSet.yml file** So basically inside _additional application_ i will deploy an **applicationset file** which is located in another folder inside the same repo.

I'm deploying two applications (argocd for self managed and sonarqube). ArgoCD is located at "argocd/argocd-install/argocd" and SonarQube applicationset in "app/applicationset" path

```
## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
server:

  extraArgs:
    - --rootpath=/argocd

  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true
  config:
    repositories: |
      - type: git
        url: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
  configs:
    credentialTemplates:
      https-creds:
        url: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        username: ***
        password: ***
  additionalApplications: 

    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ../values-override.yaml
        path: argocd/argocd-install/argocd
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

    - name: sonarqube
      namespace: argocd 
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: app/applicationfiles
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

    - name: argocd-appprojects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-appprojects
        repoURL: xxx
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

  additionalProjects: 
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false

  config:
    url: https://xxx/argocd
    application.instanceLabelKey: argocd.argoproj.io/instance

    oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/yyy/v2.0
      clientID: zzz
      clientSecret: $oidc.azuread.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

  rbacConfig:
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, get, *, allow
      p, role:admin, repositories, get, *, allow
      p, role:admin, repositories, create, *, allow
      p, role:admin, repositories, update, *, allow
      p, role:admin, repositories, delete, *, allow
      g, xxx, role:admin
    policy.default: role:readonly
```

This is the applicationset.yml file that I'm using to deploy the SonarQube app in my AKS cluster (located at _app/applicationfiles_ inside the repo). SonarQube app files are located at "sonarqube" folder inside the repo.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sonarqube
spec:
  generators:
  - list: 
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
      elements: 
      - cluster: SonarQubeHelm
        url: https://kubernetes.default.svc
  template: 
    # An Argo CD Application template, with support for parameter substitution 
    # with values from parameters generated above.
    metadata:
      name: '{{cluster}}-sonarqube'
    spec:
      project: default
      source:
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
        path: sonarqube
      destination:
        server: '{{url}}'
        namespace: argocd
```

When deploying argocd helm it is not working.... I mean, I cannot even access the URL of argoCD and nothing is being deploied in AKS.

**Paths** are OK and **Files of ArgoCD and SonarQube** are fine because when I use this override_values.yml file specifying the exact path of SonarQube application (not using an applicationset.yml file it is working fine).

Any idea why is not working?

**Comment by mkilchhofer** [comment]
When I see
```yaml
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      #(..)
```

in your `additionalApplications` list, I dont feel confident. ArgoCD cannot self-manage itself IMHO.

**Comment by JimFran** [comment]
> When I see
> 
> ```yaml
>     - name: argocd
>       namespace: argocd
>       destination:
>         namespace: argocd
>         server: https://kubernetes.default.svc
>       #(..)
> ```
> 
> in your `additionalApplications` list, I dont feel confident. ArgoCD cannot self-manage itself IMHO.

Hi @mkilchhofer,

as I mentioned that is working fine for me.

I use the "app of apps" approach in order to self managed ArgoCD. That's working fine.

When I deploy my ArgoCD override_values.yml file and I specify the exat path to the SonarQube files it is working perfect. ArgoCD can manage itself and also I can SYNC SonarQube to be deployed in "argoc" namespace which is the one I am using for the tests for now.

```
- name: sonarqube
      namespace: argocd 
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: sonarqube
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
```

The problem comes when I use "additional applications" to deploy an applicationset.yml file:
**inside app/applicationfiles there is an ApplicationSet.yml file** the one I attached in the previous message.

```
- name: sonarqube
      namespace: argocd 
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: app/applicationfiles
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
```

Just mention that inside the folder where I have SonarQube application files (sonarqube folder) there is also a couple of ingress rules, one for SonarQube app and the second one for ArgoCD. 

When I deploy the override_value.yml file specifying the applicationset.yml file path, I can see all the argocd pods and so one but nothing from the ingress rules and nothing from sonarqube...

**Comment by mkilchhofer** [comment]
Okay, have you checked, that the apps gets visible in argo?

In my eyes your values aren't correct:
- `server.config` defined twice
- Settings related `configs` (see the leading 's') are located toplevel.
  So move `server. configs.credentialTemplates` -> `configs.credentialTemplates`

**Comment by JimFran** [comment]
Thanks @mkilchhofer 

Just in case i re-written the override_values.yml file:

```
## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##
## Server
server:

  extraArgs:
    - --rootpath=/argocd

  ## ArgoCD config
  ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
  configEnabled: true
  
  config:
    url: https://xxx/argocd
    application.instanceLabelKey: argocd.argoproj.io/instance

    repositories: |
      - type: git
        url: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
    
    oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/yyy/v2.0
      clientID: zzz
      clientSecret: $oidc.azuread.clientSecret
      requestedIDTokenClaims:
        groups:
          essential: true
      requestedScopes:
        - openid
        - profile
        - email

  additionalApplications: 

    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        helm:
          version: v3
          valueFiles:
          - values.yaml
          - ../values-override.yaml
        path: argocd/argocd-install/argocd
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

    - name: sonarqube
      namespace: argocd 
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: app/applicationfiles
        repoURL: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

    - name: argocd-appprojects
      namespace: argocd
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: argocd
      source:
        path: argocd-appprojects
        repoURL: xxx
        targetRevision: HEAD
        directory:
          recurse: true
          jsonnet: {}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true

  additionalProjects: 
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false

  rbacConfig:
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, get, *, allow
      p, role:admin, repositories, get, *, allow
      p, role:admin, repositories, create, *, allow
      p, role:admin, repositories, update, *, allow
      p, role:admin, repositories, delete, *, allow
      g, xxx, role:admin
    policy.default: role:readonly
    
configs:
  credentialTemplates:
    https-creds:
      url: https://xxx@dev.azure.com/xxx/est/_git/sonarqube
      username: xxx
      password: xxx
```

Hope this looks better now. 

From "config" should I delete anything? I did not follow what you meant with defined "twice" sorry.

```
config:
    url: https://xxx/argocd
    application.instanceLabelKey: argocd.argoproj.io/instance

    repositories: |
      - type: git
        url: https://xxx@dev.azure.com/xxx/Test/_git/sonarqube
      - name: argo-helm
        type: helm
        url: https://argoproj.github.io/argo-helm
```

Howerver when deploying this override_values.yml. I can see the applicationset deployed:

```
kubectl get applicationset -n argocd
NAME        AGE
sonarqube   2m31s
```

I can see a message reated to the "name" that I used:

```
8c56f-h57fx                      1/1     Running   0          4h38m
francisco@Azure:~$ kubectl describe applicationset sonarqube -n argocd
Name:         sonarqube
Namespace:    argocd
Labels:       argocd.argoproj.io/instance=sonarqube
Annotations:  <none>
API Version:  argoproj.io/v1alpha1
Kind:         ApplicationSet
.
.
.

Status:
  Conditions:
    Last Transition Time:  2021-11-22T13:04:54Z
    Message:               Application.argoproj.io "SonarQubeHelm-sonarqube" is invalid: metadata.name: Invalid value: "SonarQubeHelm-sonarqube": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    Reason:                UpdateApplicationError
    Status:                True
    Type:                  ErrorOccurred
    Last Transition Time:  2021-11-22T13:04:54Z
    Message:               Successfully generated parameters for all Applications
    Reason:                ParametersGenerated
    Status:                True
    Type:                  ParametersGenerated
    Last Transition Time:  2021-11-22T13:04:54Z
    Message:               Application.argoproj.io "SonarQubeHelm-sonarqube" is invalid: metadata.name: Invalid value: "SonarQubeHelm-sonarqube": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
    Reason:                UpdateApplicationError
    Status:                False
    Type:                  ResourcesUpToDate
Events:                    <none>
```

I will change the name and come back with the results.
