### ISSUE TITLE
Helm list - does not list current helm installations

### ISSUE THREAD

**Issue by tyriis** [argoproj/argo-helm#1028]
### Describe the bug

When i install a Helm Chart with Argo like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.8.1
    helm:
      valueFiles:
        - values.yaml
      # Values file as block file
      values: |
        persistence:
          enabled: true
    chart: loki
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
when i call 
```bash
helm list -n monitoring
```
The installed Chart is not listed, did i miss something?

comparing applied manifests with helm native installed ones are pointing to missing `meta.helm.sh/release-name` and `meta.helm.sh/release-namespace` annotations.

Also secret used by helm is missing.

### Related helm chart

argo-cd

### To Reproduce

1. apply given application definition in yaml
2. check with helm for chart

### Expected behavior

Would be great to have a native helm compatible solution.
