### ISSUE TITLE
repoServer ServiceaccountName always to "default"

### ISSUE THREAD

**Issue by stephaneetje** [argoproj/argo-helm#1035]
### Describe the bug

I installed argocd with helm at first, i had no problem.
Then, i  used argocd to manage itself. With the same values file (encrypted or unencrypted), it always want to replace in reposerver deployment :
`serviceAccountName: argocd-repo-server`
by
`serviceAccountName: default`

My reposerver values is as follow:

```
repoServer:
  serviceAccount:
    create: true
    annotations:
      iam.gke.io/gcp-service-account: sa-argocd-ciam-qa@cc-clm.iam.gserviceaccount.com
    automountServiceAccountToken: true
    name: argocd-repo-server
```

So it has the reposerver.serviceAccount.name/create enabled, but keeps wanting to change it for `default` in argocd.

I don't understand why as i saw in the helper that it uses this variable :
```
Create the name of the repo-server service account to use
*/}}
{{- define "argo-cd.repoServerServiceAccountName" -}}
{{- if .Values.repoServer.serviceAccount.create -}}
    {{ default (include "argo-cd.repoServer.fullname" .) .Values.repoServer.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.repoServer.serviceAccount.name }}
{{- end -}}
{{- end -}}
```

### Related helm chart

argo-cd

### To Reproduce

Install argocd with helm with repoServer.serviceAccount.create = true and with a custom name
Then use argo cd to let it manage itself with the same value file

### Expected behavior

It should not replace the serviceAccountName from the custom name to `default` in repoServer's deployment

### Screenshots

<img width="623" alt="Capture d’écran 2021-11-23 à 09 58 50" src="https://user-images.githubusercontent.com/73826402/142995772-b15fe4b2-8066-4003-a370-f5ae8cae2d48.png">

### Additional context

I used the same chart version for both helm install and argocd managed upgrade (tried with `3.26.10` and `3.26.9`, both make the same mistake with argocd).
I also tried passing the values in the GUI instead of valuesFile, result is the same.
