### ISSUE TITLE
Use existing (managed) Redis for Argo CD

### ISSUE THREAD

**Issue by illagrenan** [argoproj/argo-helm#1045]
### Is your feature request related to a problem?

When I deploy the Argo CD HELM chart, I have the option to turn Redis off or on. I would like to be able to use existing Redis - my application already uses managed Redis (AWS ElastiCache) and it seems unnecessary to run more than one Redis in that case.

### Related helm chart

argo-cd

### Describe the solution you'd like

It would be great if I could disable Redis deployment in `values.yaml` and configure host/port/... to an existing running Redis.

```yaml

redis:
  enabled: false

  host: foo-redis.bar.0001.euw1.cache.amazonaws.com
  port: 6379
  ...
  ...

redis-ha:
  enabled: false

```

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by bat79a** [comment]
Nice feature, I have the same use case ;p

up !

**Comment by psanzm** [comment]
Totally agree, it will be a nice feature!

+1!

**Comment by yq314** [comment]
I think this can be done through `.Values.server.extraArgs`

**Comment by yq314** [comment]
when you enable redis in the helm chart values.yaml, it's basically adding `--redis <host>:<port>` 
to the container's command: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/deployment.yaml#L61

so you should be able to do the same with `.Values.server.extraArgs` by specifying your host and port directly.

**Comment by illagrenan** [comment]
Update: I had to add redis to other components. Hopefully this is now complete.

```yaml
controller:
  extraArgs:
    - --redis=hostname:6379
    - --redisdb=1

server:
  extraArgs:
    - --redis=hostname:6379
    - --redisdb=1

repoServer:
  extraArgs:
    - --redis=hostname:6379
    - --redisdb=1

redis:
  enabled: false
```

**Comment by mkilchhofer** [comment]
We also think about using an AWS managed service for redis.
Would it make sense to follow the pattern of the bitnami charts and use something like?

```yaml
externalRedis:
  host: ""
  port: 6379
  # password: ""
  # existingSecret: ""
```

Ref: https://github.com/bitnami/charts/search?q=externalRedis
