### ISSUE TITLE
[argo-cd]: Inconsistent between grafana dashboard query expression and helm chart template.

### ISSUE THREAD

**Issue by FuyuanChu** [argoproj/argo-helm#1047]
### Describe the bug

There are some queries in the [dashboard](https://github.com/argoproj/argo-cd/blob/master/examples/dashboard.json
) provided in `argo-cd` repo contain a label filter `job="argocd-repo-server"` to query some metrics of argocd-repo-server. 

According to the [doc](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/metrics.md#prometheus-operator), It uses the service's label `app.kubernetes.io/name` as job names.

And as in the helm chart [template](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-repo-server/metrics-service.yaml#L12), the label `app.kubernetes.io/name` was set to the name `argocd-repo-server-metrics`. For that reason when we use the dashboard, there will be in some panels with no data as they use the wrong filter expr.

I think we should keep them aligned. I'd like to help on this if you guys have solutions.

### Related helm chart

argo-cd

### To Reproduce

1. helm install ArgoCD with metrics enabled
2. Import this dashboard to grafana : https://grafana.com/grafana/dashboards/14584
3. You will see some panel in the row `Repo Server Stats` has no data.

### Expected behavior

panels in the row `Repo Server Stats` should have data.

**Comment by Vladyslav-Miletskyi** [comment]
Bump

**Comment by Vladyslav-Miletskyi** [comment]
Setting next helm values actually is helping to actually use the given dashboard.

```yaml
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      relabelings:
        - replacement: argocd-metrics
          targetLabel: job

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    relabelings:
      - replacement: argocd-repo-server
        targetLabel: job

server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      relabelings:
        - replacement: argocd-server-metrics
          targetLabel: job
```

maybe we can add those as defaults in helm chart / serviceMonitors?
