### ISSUE TITLE
Event source (webhook) and Event bus services not available when singleNamespace to true

### ISSUE THREAD

**Issue by iamdinesh** [argoproj/argo-helm#1049]
### Describe the bug

When I set `singleNamespace: true` in values.yaml in argo-events, specified event bus and event source is not generated. But If I set it to false, everything is generated as expected.

Using argo-events version - 1.6.2

Event Bus:

```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      serviceAccountName: argo-events-sa
      replicas: 3
```

Event Source:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  service:
    ports:
      - port: 12001
        targetPort: 12001
  webhook:
    githubPrHook:
      port: "12001"
      endpoint: /github-webhook
      method: POST
```

Values:

```
argo-events:
  singleNamespace: true
  namespace: argo-events
```

### Related helm chart

argo-events

### To Reproduce

Set singleNamespace to true in values.yaml

values.yaml
```
argo-events:
  singleNamespace: true
  namespace: argo-events
```

### Expected behavior

When we set to true, it must create specified eventsource and eventbus resources.

### Screenshots

Curernt Behaviour: 

kubectl get po -n argo-events

<img width="631" alt="Screen Shot 2021-12-02 at 1 52 57 PM" src="https://user-images.githubusercontent.com/9393883/144509231-fee885be-ad34-4036-8be4-25682078984e.png">

kubectl get svc -n argo-events

No resources found in tc-argo-events namespace.

Expected:

kubectl get po -n argo-events

<img width="622" alt="Screen Shot 2021-12-02 at 1 54 44 PM" src="https://user-images.githubusercontent.com/9393883/144509363-5fa3b007-8915-425d-9dd9-0e13593301c0.png">

kubectl get svc -n argo-events

<img width="807" alt="Screen Shot 2021-12-02 at 1 56 19 PM" src="https://user-images.githubusercontent.com/9393883/144509555-456a0b79-4ac2-4dd6-b148-5e7d5ad4ca7c.png">
