### ISSUE TITLE
Add defaultBackend configuration to the ingress.yaml

### ISSUE THREAD

**Issue by lachezar** [argoproj/argo-helm#1051]
### Is your feature request related to a problem?

Currently I have to do extra steps to make the default backend for a load balancer in GCP work (open up nodeport range in the firewall config). I would like instead to be able to define my own `defaultBackend` that is exposed as a `ClusterIP` with a predetermined port number using NEG.

Here is an example how `defaultBackend` can be configured: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#default_backend

### Related helm chart

argo-cd

### Describe the solution you'd like

I would like to be able to specify the default backend service name and port
```
spec:
  defaultBackend:
    service:
      name: {{ $defaultBackendServiceName }}
      port:
        number: {{ $defaultBackendServicePort }}
```

If no `defaultBackendServiceName` and `defaultBackendServicePort` are explicitly defined, then we should exclude the `defaultBackend` part of the configuration and let the gke/k8s control plane set its default value (the config with the nodeport).
