### ISSUE TITLE
After a while the argocd-repo-server is broken ("cannot fork")

### ISSUE THREAD

**Issue by nmasse-itix** [argoproj/argo-helm#1052]
### Describe the bug

Hello,

I'm deploying ArgoCD on my Kubernetes 1.21 server using this Helm chart. 
After a while (several days), the ArgoCD repo-server stops from working and is returning the following error: "cannot fork". 

I investigated and found that this was a known bug (argoproj/argo-cd#3611), fixed in the current installation manifest. 
However, it seems the fix has not been backported to the Helm chart. 

**https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml** :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
    spec:
      containers:
      - command:
        - entrypoint.sh
        - argocd-repo-server
        - --redis
        - argocd-redis:6379
```

**charts/argo-cd/templates/argocd-repo-server/deployment.yaml** :

https://github.com/argoproj/argo-helm/blob/7033883914e07f9248eba1cf5a208084394318bc/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L41-L53

The entrypoint.sh (that runs `tini`, in charge of reaping zombie processes) is missing !

### Related helm chart

argo-cd

### To Reproduce

- deploy ArgoCD
- configure some applications as explained in argoproj/argo-cd#3611
- wait a week or two

### Expected behavior

The ArgoCD repo-server continues to work after severa weeks without restart

### Additional context

See argoproj/argo-cd#3611
