### ISSUE TITLE
[argo-rollouts] Missing secret: argo-rollouts-notification-secret

### ISSUE THREAD

**Issue by mubarak-j** [argoproj/argo-helm#1056]
### Describe the bug

Argo-rollouts [install manifest](https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml) creates a secret named: `argo-rollouts-notification-secret`

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-rollouts-notification-secret
---
```
By default argo-rollouts looks for this secret and throws an error if not found:
```
Failed to process: secret \"argo-rollouts-notification-secret\" not found
```

It would be nice if argo-rollouts helm-chart installs this secret by default. 

### Related helm chart

argo-rollouts

### To Reproduce

install argo-rollouts v1.1.1 with helm chart v2.6.0

### Expected behavior

helm-chart to match install manifest in k8s components installed, at least a secret is missing here.
