### ISSUE TITLE
Duplicated initContainers in chart

### ISSUE THREAD

**Issue by patoarvizu** [argoproj/argo-helm#1060]
### Describe the bug

The argo-cd chart renders the `argocd-repo-server` with duplicate `initContainers` fields, if the `repoServer.initContainers` field is set. It looks like this was introduced in [this](https://github.com/argoproj/argo-helm/commit/6d872cb02fff53644546f0dfe3197bbad2fa2f88) commit.

### Related helm chart

argo-cd

### To Reproduce

- Create Helm values with `repoServer.initContainers` set to something, e.g.:
```
repoServer:
  initContainers:
  - name: init
    image: alpine:3.8
    command: [sh, -c]
    args:
    - echo "init"
```
- Set chart to version 3.29.0.
- Run `helm template` and inspect the generated yaml
- The resulting `Deployment` object for `argocd-repo-server` will have the `initContainers` field duplicated, once with the hard-coded `copyutil` at the top, and another with the custom `init` at the bottom.

### Expected behavior

The additional init containers provided as chart values are appended to the required `copyutil` one.
