### ISSUE TITLE
Using Vault Sidecar for populating argocd-cm content. 

### ISSUE THREAD

**Issue by sjqnn** [argoproj/argo-helm#1062]
### Is your feature request related to a problem?

There are potentially sensitive values that are expected to be loaded into the `argocd-cm` configmap, for instance AzureAD App ClientIDs and ClientSecrets passed in through the `dex-config` key. Is there any way that we can use a hashicorp vault sidecar to inject these secret from vault to be used by this configmap/ argo itself? 

### Related helm chart

argo-cd

### Describe the solution you'd like

A way to pass in secrets from vault to the `argocd-cm` / guidance on how to do so with the current chart. 

### Describe alternatives you've considered

I've looked at some alternate approaches such as:

- https://github.com/jkroepke/helm-secrets
- https://github.com/external-secrets/external-secrets

We'd like to avoid storing even encrypted secrets in source code, not have to install additional k8s plugins on the cluster to make this work. 

### Additional context

I've resorted to just installing the chart, adding notation to grab the value from the argocd-secret like this:
```yaml
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: microsoft
      id: microsoft
      name: Azure AD
      config:
        clientID: $microsoft.azureAD.clientID
        clientSecret: $microsoft.azureAD.clientSecret
 ```
 then i just manually patch the secret with the desired values.
