### ISSUE TITLE
[argo-cd]: redis-ha assumes DockerHub images but should be more flexible

### ISSUE THREAD

**Issue by inductor** [argoproj/argo-helm#1069]
### Is your feature request related to a problem?

So far you can configure Redis HA with the following params

```yaml
  haproxy:
    # -- Enabled HAProxy LoadBalancing/Proxy
    enabled: true
    metrics:
      # -- HAProxy enable prometheus metric scraping
      enabled: true
  image:
    # -- Redis tag
    tag: 6.2.4-alpine
```

But I am facing problems where you cannot set the default container registry. In our environment we are using different registries for DevOps and App dev so specifying the default container registry for the cluster wouldn't suit this case.

### Related helm chart

argo-cd

### Describe the solution you'd like

```yaml
redis-ha:
  enabled: true
  haproxy:
    # -- Enabled HAProxy LoadBalancing/Proxy
    enabled: true
    metrics:
      # -- HAProxy enable prometheus metric scraping
      enabled: true
    # -- HAProxy image repository
    repository: haproxy
    # -- HAProxy tag
    tag: 2.0.4
  image:
    # -- Redis image repository
    repository: redis
    # -- Redis tag
    tag: 6.2.4-alpine
```
