### ISSUE TITLE
Error: found in Chart.yaml, but missing in charts/ directory: redis-ha

### ISSUE THREAD

**Issue by Jessev6** [argoproj/argo-helm#1073]
### Describe the bug

/*.tgz in .helmignore at charts/argocd causes issues with redis-ha configuration.

### Related helm chart

argo-cd

### To Reproduce

From a clean install

Configure redis-ha:

```
# values.yaml
redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
```

1. `helm dependency update ./charts/argo-cd`
2. `helm template ./charts/argo-cd`

Result:

```
Error: found in Chart.yaml, but missing in charts/ directory: redis-ha
```

### Expected behavior

Output of kubernetes resource files.

### Additional context

A fix that worked for me is to just remove the /*.tgz from the .helmignore.
