### ISSUE TITLE
Applicationset does not deploy applications

### ISSUE THREAD

**Issue by JimFran** [argoproj/argo-helm#1077]
### Describe the bug

Hello team,

Not sure if this is a bug related issue or just a misconfiguration on my applicationset.yaml file.

I have created a repo git structure to self-managed argocd and also deploy cluster-addons and a sonarqube application through an applicationset.yaml file.

Basically the override_values.yaml file during argocd helm installation, deploy the self-managed argocd and also the applicationset:

```
argo-cd:
  ## ArgoCD configuration
  ## Ref: https://github.com/argoproj/argo-cd
  ##
  ## Server
  server:

  ##  extraArgs:
  ##    - --rootpath=/argocd

    ## ArgoCD config
    ## reference https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    configEnabled: true

    config:
      url: https://argocd.k8s.loandepotdev.io
      application.instanceLabelKey: argocd.argoproj.io/instance

      repositories: |
        - type: git
          url: https://XXX/_git/argocd-bootstrapping
        - name: argo-helm
          type: helm
          url: https://argoproj.github.io/argo-helm
    
      oidc.config: |
        name: Azure
        issuer: https://login.microsoftonline.com/XXX/v2.0
        clientID: XXX
        clientSecret: $oidc.azuread.clientSecret
        requestedIDTokenClaims:
          groups:
            essential: true
        requestedScopes:
          - openid
          - profile
          - email
    additionalApplications: 

      - name: argocd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: default
        source:
          helm:
            version: v3
            valueFiles:
            - override_values.yaml
          path: argo-cd
          repoURL: https://XXX/_git/argocd-bootstrapping
          targetRevision: HEAD
        syncPolicy:
          syncOptions:
          - CreateNamespace=true       

      - name: ld-apps
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: default
        source:
          path: apps/applicationset
          repoURL: https://XXX/_git/argocd-bootstrapping
          targetRevision: HEAD
          directory:
            recurse: true
            jsonnet: {}
        syncPolicy:
          automated:
            selfHeal: true
            prune: true

    additionalProjects:  

    rbacConfig:
      policy.csv: |
        g, "XXX-72a0918cb3ed", role:admin
        g, "34cb7011-XXX", role:admin
        g, "a5af9fa6-XXX", role:admin
        g, "c346ff11-XXX", role:admin
      policy.default: role:readonly
    
  configs:
    credentialTemplates:
      https-creds:
        url: https://XXX/_git/argocd-bootstrapping
        username: argocd
        password: XXX
```
However, instead of deploy the cluster-addons and sonarqube I can see only this:

![image](https://user-images.githubusercontent.com/65667266/148191687-f87f3d1e-f6aa-4f81-880f-5941fe7429f6.png)

This is the git repo structure:

![image](https://user-images.githubusercontent.com/65667266/148190170-0bf10660-a823-4462-b3c7-f0cbc375b9b2.png)

There are two main folders: apps and argo-cd. apps is the folder where I setup the cluster-addons and sonarqube application and also the applicationset file which is used to deploy those files. argo-cd folder is used to deploy argocd itself. 

This is the link to my git repo:

https://github.com/JimFran/argocd.git

some of the cluster-addons like akv2k8s, nginx-ingress (with ingress-rules) and cert-manager are deployed in different namespaces than argocd.

Anyone can have a look at the folder structure and files just to check if the deployment is setup correctly?

Thank you!

### Related helm chart

argocd-applicationset

### To Reproduce

0. First change the XXX values in the files for your own data.
1. git clone https://github.com/JimFran/argocd.git
2. cd argocd/argo-cd/
3. helm dep update
4. helm install argocd . --namespace=argocd --create-namespace -f override_values.yaml
5. kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}"
6. decode password to base 64
7. login to argocd instance 

### Expected behavior

I was expecting to have cluster-addons and sonarqube as applications in argocd dashboard. But I can only see argocd (for self-managed) and applicationset. 

### Screenshots

![image](https://user-images.githubusercontent.com/65667266/148192491-1a803200-c8d7-469e-99b0-18cc007ca490.png)
