### ISSUE TITLE
serviceAccount annotations not appear after installing

### ISSUE THREAD

**Issue by mrrusik** [argoproj/argo-helm#1079]
### Describe the bug

sa annotations not appear in sa after installing

chart version: v2.2.2
I use helmfile. Tested with controller and server

```
    values:
      - controller:
          serviceAccount:
            annotations: 
              a: b
            name: "argocd-application-controller-custom"
            automountServiceAccountToken: true
            create: true
        server:
          image:
            tag: v2.2.2
          serviceAccount:
            annotations: 
              eks.amazonaws.com/role-arn: "arn:aws:iam::id:role/rolename"
            name: "argocd-server"
            automountServiceAccountToken: true
            create: true
```

after helm install, argocd-server and argocd-application-controller-custom serviceaccount has similar view without my annotations:

```
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
```

### Related helm chart

argo-cd

### To Reproduce

helmfile -f filename.yaml apply or helmfile -f filename.yaml sync

### Expected behavior

annotations must appear in serviceaccount
