### ISSUE TITLE
Ingress and HA conflict?

### ISSUE THREAD

**Issue by sunshine69** [argoproj/argo-helm#1086]
### Describe the bug

If I enable HA mode using the doc in readme file, the ingress is not deployed.

I am not sure if it is really a bug a what I miss. Basically when I enable HA so my values.yaml looks like this

```
clusterCredentials: []
argocdServerAdminPassword: ""
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - "argocd.go1.cloud"
    https: true
    ingressClassName: "nginx"
    tls:
      - hosts:
          - "argocd.go1.cloud"
        secretName: "argocd.go1.cloud-tls"
  extraArgs:
    - "--insecure"

# HA config section. Select the HA mode with autoscaling
redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

```

The helm deploy fine however I don't know how to access the cluster!

Previously when the whole HA section does not exists, the deployment create an ingress and I can access the argocd server fine using the hostname in the ingress. HOwever since I added the HA section, the ingress manifest wont be generated anymore. I verify it by run helm template command and examine the output.

It might be intentional however now I do not know how to access the server anymore.

Question is: 
- Why disable ingress when HA is enabled?
- What is the correct way to access the server ? If there is, where is the doc? If not yet available, could we add it?
- Or we need to create and route ingress manually - that is in a separate tasks, however why?

### Related helm chart

argo-cd

### To Reproduce

just normal helm install cmd

### Expected behavior

system is up, ingress created so user can access the argocd frontend
