### ISSUE TITLE
Repo-servers copyutil initContainer does not set resources

### ISSUE THREAD

**Issue by romanwoessner** [argoproj/argo-helm#1087]
### Describe the bug

The repo server has an InitContainer called "copyutil". This container does not set its resources.

### Related helm chart

argo-cd

### To Reproduce

Just render a template of the chart. There are no ressources set for the copyutil initContainer.

### Expected behavior

The container makes use of resources predefinded in in the repo-server values.
The same initContainer as part of the dex deployment is equipped with resources defined in `.Values.dex.resources`

**Comment by jwitko** [comment]
To work around this for now I downgraded the chart to 3.25.2, set:

```
global:
  image:
    # This should get removed once https://github.com/argoproj/argo-helm/issues/1087 is resolved
    tag: "v2.2.2"

repoServer:
  enableCopyutilInitContainer: false
  initContainers:
    - command:
      - cp
      - -n
      - /usr/local/bin/argocd
      - /var/run/argocd/argocd-cmp-server
      image: argoproj/argocd:v2.2.2
      name: copyutil
      volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi
```
