### ISSUE TITLE
Cannot use argo-cd as a sub-chart (dependency)

### ISSUE THREAD

**Issue by mosheavni** [argoproj/argo-helm#1095]
### Describe the bug

I'm trying to install the chart when it's a dependency of a parent chart.
Without messing with the values, the error is:
```
→ helm template argo-cd --include-crds --namespace argocd --debug .
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /Users/mavni/Repos/k8s-conf/charts/argo-cd


Error: template: argo-cd/charts/argo-cd/templates/redis/service.yaml:8:8: executing "argo-cd/charts/argo-cd/templates/redis/service.yaml" at <include "argo-cd.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name)>: error calling include: template: argo-cd/templates/_helpers.tpl:37:18: executing "argo-cd.labels" at <include "argo-cd.chart" .>: error calling include: template: argo-cd/templates/_helpers.tpl:30:25: executing "argo-cd.chart" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm.go:88: [debug] template: argo-cd/charts/argo-cd/templates/redis/service.yaml:8:8: executing "argo-cd/charts/argo-cd/templates/redis/service.yaml" at <include "argo-cd.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name)>: error calling include: template: argo-cd/templates/_helpers.tpl:37:18: executing "argo-cd.labels" at <include "argo-cd.chart" .>: error calling include: template: argo-cd/templates/_helpers.tpl:30:25: executing "argo-cd.chart" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

Here's the `Chart.yaml`:
```
apiVersion: v2
name: argo-cd
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: argo-cd
  version: 3.30.0
  repository: https://argoproj.github.io/argo-helm
```

### Related helm chart

argo-cd

### To Reproduce

```
helm create argo-cd && cd argo-cd

cat <<EOF >> Chart.yaml
dependencies:
- name: argo-cd
  version: 3.30.0
  repository: https://argoproj.github.io/argo-helm
EOF

helm dependency build

helm template argocd --include-crds --namespace argocd --debug .
```

### Expected behavior

chart is installed
