### ISSUE TITLE
Add certificate renwal duration in certificate templarte

### ISSUE THREAD

**Issue by AnshumanTripathi** [argoproj/argo-helm#1096]
### Is your feature request related to a problem?

We want to renew our certificates at different duration than a default 90 days defined by cert-manager.

### Related helm chart

argo-cd

### Describe the solution you'd like

Adding support for [duration](https://cert-manager.io/docs/reference/api-docs/)  in the certificate template should help us.

### Describe alternatives you've considered

For now we are updating the certificate manually to autorotate.

**Comment by charlrvd** [comment]
Hi @AnshumanTripathi,
Isn't it possible for you to just add the annotation to the values file?
I'd expect something like this would work, for the cluster-issuer annotation It does at least. And the other annotation is supported as seen [here](https://cert-manager.io/docs/usage/ingress/#supported-annotations)

```yaml
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/duration: 42
```

**Comment by AnshumanTripathi** [comment]
Thanks @charlrvd. We were using a L7 load balancer instead of an ingress. I wonder if we can add this annotations in service itself. https://github.com/argoproj/argo-helm/blob/bee32880a88d3b56a702e73e8f8e9e25c9e56fca/charts/argo-cd/values.yaml#L201

**Comment by tonypowell1809** [comment]
@charlrvd I am helping Anshuman with this ticket do you know the answer to his question above

**Comment by mkilchhofer** [comment]
No that will not work. Cert-Manager only watches the Ingress resource (or Istio/Gateway resource).

What L7 loadbalancer do you use?

**Comment by AnshumanTripathi** [comment]
Hi @mkilchhofer,
That is correct we are using a L4 Loadbalancer with `server.service.type: LoadBalancer`. These is how it is added in the values file

```yaml
server:
  service:
    type: LoadBalancer
    loadBalancerIP: ${argo_load_balancer_ip}
    annotations:
      networking.gke.io/load-balancer-type: Internal
```
