### ISSUE TITLE
Allow dex config to reference an existing secret

### ISSUE THREAD

**Issue by gajus** [argoproj/argo-helm#1113]
### Is your feature request related to a problem?

I am managing my entire cluster using ArgoCD and sealed secrets.

The current way that the Helm chart is setup requires to provide values roughly equivalent to:

```yaml
dex.config: |
  connectors:
    - type: saml
      id: saml
      name: saml
      config:
        ssoURL: https://accounts.google.com/o/saml2/idp?idpid=C025oghrr
        entityIssuer: https://argocd.contra.dev/api/dex/callback
        caData: <replace>
        redirectURI: https://argocd.contra.dev/api/dex/callback
        usernameAttr: name
        emailAttr: email
        ssoIssuer: https://accounts.google.com/o/saml2?idpid=C025oghrr
```

As far as I understand, the `caData` is supposed to be a secret. There is no way to provide a reference to existing secret.

### Related helm chart

argo-cd

### Describe the solution you'd like

Perhaps allow to point the entire `dex.config` to an existing secret.
