### ISSUE TITLE
extraArgs breaks my argocd-server 

### ISSUE THREAD

**Issue by gimpiron** [argoproj/argo-helm#1123]
### Describe the bug

Hey,
Before im starting to talk about the ingress,  i found out that the extraArgs values breaks my chart;
Im trying to add:
```
server:
  extraArgs: 
    - --insecure
```
to my values.yaml, ending up with this file:
```
---
redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

server:
  extraArgs: 
    - --insecure

  autoscaling:
    enabled: true
    minReplicas: 2

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

    ingressClassName: "nginx-internal"
    pathType: Prefix
    
    paths:
      - /argocd(/|$)(.*)

    https: false
```

I manage to get all argocd's resources, but when i port-forward my argocd-server service i cant get into the UI-

![image](https://user-images.githubusercontent.com/60313280/152383814-d7739f9c-c465-44cf-87da-79d30a50382b.png)

**with curl command:**
```
curl -X GET http://localhost:8080 -kv
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 843
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: sameorigin
< X-Xss-Protection: 1
< Date: Thu, 03 Feb 2022 16:02:37 GMT
<
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Argo CD</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='icon' type='image/png' href='assets/favicon/favicon-32x32.png' sizes='32x32'/>
    <link rel='icon' type='image/png' href='assets/favicon/favicon-16x16.png' sizes='16x16'/>
    <link href="assets/fonts.css" rel="stylesheet">
</head>

<body>
    <noscript>
        <p>
        Your browser does not support JavaScript. Please enable JavaScript to view the site.
        Alternatively, Argo CD can be used with the <a href="https://argoproj.github.io/argo-cd/cli_installation/">Argo CD CLI</a>.
        </p>
    </noscript>
    <div id="app"></div>
<script type="text/javascript" src="main.623766253c82eb2ff4e6.js"></script></body>

</html>
* Connection #0 to host localhost left intact
```

after removing the extraArgs, i manage to access the service via the UI.

Any ideas? 

### Related helm chart

argo-cd

### To Reproduce

Add / remove the 
```
server:
  extraArgs: 
    - --insecure
```
values.

### Expected behavior

Full UI access, then move on to debug the ingress :) 
(this insecure flag should help me debug why i cant access the UI via nginx ingress)
