### ISSUE TITLE
getting archive workflows not working

### ISSUE THREAD

**Issue by TimSchSkaylink** [argoproj/argo-helm#1134]
### Describe the bug

After adding needed values like explained in the [docu](https://argoproj.github.io/argo-workflows/workflow-archive/) for "Workflow Archive"
workflows getting archived into the database is working, but they dont show up in the UI.
From api perspective i'm geeting different responds.
If i call `/api/v1/archived-workflows` i get `{"metadata":{},"items":null}`
If i call `/api/v1/archived-workflows/<uid>` i get `{"code":2,"message":"getting archived workflows not supported"}`

I saw [issue 323 ](https://github.com/argoproj/argo-helm/issues/323) and it seems like i have the same issues like explained there but i have persistence.archive true in my configmap

### Related helm chart

argo-workflows

### To Reproduce

1. Running argo-workflows inside aks
2. Create postgres pod in same namespace
3. Create aks secret in same namespace with values  `password:<postgrespassword>` and  `username: <postgresusername>`
4. Add persistence under data in workflow configmap
```
persistence: |
    archive: true
    postgresql:
      host: postgres.argo.svc.cluster.local
      port: 5432
      database: postgresdb
      tableName: argo_workflows
      userNameSecret:
        name: <SecretNameFromStep3>
        key: username
      passwordSecret:
        name: <SecretNameFromStep3>
        key: password
```

### Expected behavior

I would expect the UI and API is now showing the archived workflows.
And that the api endpoints are giving back the same error codes if not configured correctly.

### Additional context

argo workflow version: v3.2.4
