### ISSUE TITLE
Is resource customization supported?

### ISSUE THREAD

**Issue by prein** [argoproj/argo-helm#1155]
Does current chart version support resource customization? It seems that it has been removed in #129
What's the suggested way to implement custom health checks using the chart?

**Comment by mkilchhofer** [comment]
Can you elaborate what exactly you want to customize?

All probes are customizable in their timing parameters.

**Comment by mubarak-j** [comment]
Yes it is supported, it needs to be defined under `server.config` to be included in `argocd-cm`, e.g:
```yaml
server:
  config:
    resource.customizations.knownTypeFields.argoproj.io_Rollout: |
      - field: spec.template.spec
        type: core/v1/PodSpec
```
