### ISSUE TITLE
support timeout.reconciliation setting

### ISSUE THREAD

**Issue by RafalSkolasinski** [argoproj/argo-helm#1174]
### Is your feature request related to a problem?

ArgoCD v2.1 deprecated `--app-resync` feature, see [upgrade notes](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.0-2.1.md#replacing---app-resync-flag-with-timeoutreconciliation-setting). 

Main documentation indicates that now it should be set via [argo-cm](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml#L272) configmap field `timeout.reconciliation`. 

It does seem not possible to set it via argo-cd helm char from this repository. 

### Related helm chart

argo-cd

### Describe the solution you'd like

Single helm value to control current correct setting for `--app-resync`.

### Describe alternatives you've considered

By looking at related [PR](https://github.com/argoproj/argo-cd/pull/6102/files) it does seem this can also be controlled via `ARGOCD_RECONCILIATION_TIMEOUT` env variable. So it could be set via helm values as
```
controller:
  env:
  - name: ARGOCD_RECONCILIATION_TIMEOUT
    value: "10s"
repoServer:
  env:
  - name: ARGOCD_RECONCILIATION_TIMEOUT
    value: "10s"
```
but this does not seem elegant and I am not sure it is fully correct. 

### Additional context

The only way I actually got it working was to set it almost everywhere

```
server:
  extraArgs:
  - --insecure
  - --rootpath
  - /argocd
  env:
  - name: ARGOCD_RECONCILIATION_TIMEOUT
    value: "10s"
repoServer:
  env:
  - name: ARGOCD_RECONCILIATION_TIMEOUT
    value: "10s"
configs:
  secret:
    argocdServerAdminPassword: "{{ gitops_password | password_hash('bcrypt') }}"
    argocdServerAdminPasswordMtime: "2021-01-01T10:11:12Z"
controller:
  args:
    appResyncPeriod: 10
  env:
  - name: ARGOCD_RECONCILIATION_TIMEOUT
    value: "10s"
```

But the sync was still happening a bit more than after 10 seconds.
