### ISSUE TITLE
ArgoCD Controller NetworkPolicy does not allow access to metrics service

### ISSUE THREAD

**Issue by ErikLundJensen** [argoproj/argo-helm#1182]
### Describe the bug

The NetworkPolicy does not include access to the metric port:

https://github.com/argoproj/argo-helm/blob/48bf6d4a3808636b76ff793a68b50e613e6f009f/charts/argo-cd/templates/argocd-application-controller/networkpolicy.yaml#L13

If "metrics" is added to the NetworkPolicy then the metrics can be scraped by Prometheus (or similar product).

I suggest that the "metrics" port is added.

### Related helm chart

argo-cd

### To Reproduce

render the chart with
```
global:
  networkPolicy:
    create: true
```

The NetworkPolicy does not allow ingress access to 'metrics' service.
```
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: controller
      protocol: TCP
```

### Expected behavior

Prometheus can scrape metrics from argocd-application-controller when NetworkPolicies are enforced.

```
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: controller
      protocol: TCP
    - port: metrics
      protocol: TCP

```
