### ISSUE TITLE
Sync status Unknown when adding a new application

### ISSUE THREAD

**Issue by xamroc** [argoproj/argo-helm#1183]
### Describe the bug

Hi All,

I am trying to install applications (such as `cert-manager`, `prometheus`, etc.) immediately after a cluster is provisioned in an automated way. I used `terraform` to provision an EKS cluster and installed this helm chart like below:

```
resource "helm_release" "argo_cd" {
  name       = "argo-cd"
  namespace  = "argocd"

  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
}
```
This was installed successfully.

However, I tried to install an `Application` using the `kubernetes` provider.  The application is a sample from here: https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#helm-example

```
# ./apps/application.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

```
resource "kubernetes_manifest" "apps" {
  manifest = yamldecode(file("./apps/application.yml"))
}
```

The Application show that the Sync Status is `Unknown`. There are no resources to synchronize and the application status also shows the following error:
```
ComparisonError rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
I have provided screenshots from the ArgoCD UI below.

I have tested this application before with a `kind` cluster and it installs and syncs properly. I'm not sure whether running this in an EKS cluster makes a difference.

Looking at some logs from the `argocd-server` pod, I see this as interesting but I'm not sure who it's referring to:
```
time="2022-03-18T07:39:56Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = no session information" grpc.code=Unauthenticated grpc.method=List grpc.service=cluster.ClusterService grpc.start_time="2022-03-18T07:39:56Z" grpc.time_ms=4.628 span.kind=server system=grpc
```

Appreciate any advice. Thanks!

### Related helm chart

argo-cd

### To Reproduce

These steps happen within one `terraform apply` command:
1. Provision EKS using open source modules(terraform-aws-modules/eks/aws and terraform-aws-modules/vpc/aws).
2. Use `helm` provider to install `argo-cd`:
```
resource "helm_release" "argo_cd" {
  name       = "argo-cd"
  namespace  = "argocd"

  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
}
```
3. Use `kubernetes` provider to install an application.
```
# ./apps/application.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
```

```
resource "kubernetes_manifest" "apps" {
  manifest = yamldecode(file("./apps/application.yml"))
}
```

Terraform providers for reference:
```
terraform {
  required_version = "~> 1.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.73"
    }

    helm = {
      version = "~> 2.4"
    }

    kubernetes = {
      version = "~> 2.8"
    }
  }
}
```

### Expected behavior

ArgoCD installs the applications.

### Screenshots

![Screenshot 2022-03-18 at 8 41 02 PM](https://user-images.githubusercontent.com/3961452/159005143-aebc38ac-7fd5-4546-8b1f-9ae21dc3b4a6.png)
![Screenshot 2022-03-18 at 8 43 41 PM](https://user-images.githubusercontent.com/3961452/159005152-fe1d683b-96e2-43d6-9a76-3687b95eb5e2.png)

**Comment by qasmi** [comment]
Hello, any news in this issue ?

**Comment by alkdese** [comment]
I also have same problem it stays in Unknown argocd 2.3.4 and I also have in the app these lines

```yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
