### ISSUE TITLE
[argo-cd] - bot container cannot find secret in default helm chart values. 

### ISSUE THREAD

**Issue by haghabozorgi** [argoproj/argo-helm#1187]
### Describe the bug

default helm values for notifications controller, when the bot is enabled leads to the bot throwing error.
`notifications.name` is defaulted to `name: notifications-controller`
but the bot throws an error since it is seems to be looking for  `argocd-notifications-secret`

`time="2022-03-21T21:49:41Z" level=error msg="Failed to process: secret \"argocd-notifications-secret\" not found" resource=argocd/prometheus-operator`

### Related helm chart

argo-cd

### To Reproduce

using chart  4.2.1

```
notifications:
  bots:
     slack:
       enabled: true
```

### Expected behavior

expect the bot to lookup the secret relative to the name specified in notifications.name given that is the name the secret is created under? Not sure where it is set exactly though as I dont see any env var/command in deployment spec of bot in chart that could be responsible?

### Screenshots

![Screenshot_20220321_145157](https://user-images.githubusercontent.com/1186748/159369599-babf9e69-d16e-4620-9c5c-f69c166b1e0f.png)

### Additional context

Note: Workaround it seems is removing -controller from name like this...This seems to cause the bot pod to not log these errors.

```
notifications:
  name: notifications
  bots:
     slack:
       enabled: true
```
