### ISSUE TITLE
argo-workflow 3.3.x workflows not running when installed using helm

### ISSUE THREAD

**Issue by agustinvinao** [argoproj/argo-helm#1188]
### Describe the bug

After installing argo-workflow from scratch, version 3.3.0 or 3.3.1, using a hello-world workflow is not working:

workflow test:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: vnovoselskiy/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

the workflow appears in the UI but when I try to access the logs it shows:

```
Cannot read property 'undefined' of undefined

Stack Trace
TypeError: Cannot read property 'undefined' of undefined
    at t.WorkflowLogsViewer (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:225:76593)
    at $i (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:52993)
    at Io (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:65197)
    at qa (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:90552)
    at Ga (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:90936)
    at Os (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:97823)
    at ks (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:97203)
    at Rs (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:98578)
    at Tn (http://10.0.0.203/main.50457fd4714d6e3e36c4.js:516:30569)
Component Stack

    in Unknown
    in div
    in div
    in div
    in Unknown
    in div
    in div
    in Unknown
    in Unknown
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in t
    in Unknown
    in t
```

from command line it shows:
```
Name:                dag-henet-updater
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Tue Mar 22 14:25:30 +0000 (1 minute ago)
Progress:            
Parameters:          
  update_force:      0

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```

hanging forever and not running.

Same helm install values with v3.2.9 works ok.

### Related helm chart

argo-workflows

### To Reproduce

1. install argo-workflows using helm v3.3.x
2. submit hello-world example `argo submit -n argo workflow-test.yaml --watch`

### Expected behavior

run the worflow
