### ISSUE TITLE
Controller cluster role lacks get permissions on persistentvolumeclaims

### ISSUE THREAD

**Issue by alefray** [argoproj/argo-helm#1189]
### Describe the bug

After restarting (for example, after a crash), the `workflow-controller` fails to resume an **existing** workflow which uses **a PVC** with the following error:

```
pvc create error: persistentvolumeclaims "my-enacted-workflow" is forbidden: User "system:serviceaccount:argo:argo-workflows-workflow-controller" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "my-enacted-namespace"
```

Moreover, the workflow is in state `Error` while the pod is in state `Pending`.

### Related helm chart

argo-workflows

### To Reproduce

1. Launch a workflow with a PVC as documented here: https://argoproj.github.io/argo-workflows/fields/#persistentvolumeclaim
2. Restart workflow-controller pod

### Expected behavior

The workflow-controller is able to resume and terminate with success the workflow.

### Additional context

We believe this error is raised when the `workflow-controller` tries to **get** the pvc status when discovering on-going workflows.

Currently, the service account `system:serviceaccount:argo:argo-workflows-workflow-controller` is bound to the ClusterRole `argo-workflows-workflow-controller`with the following permissions: (cf https://github.com/argoproj/argo-helm/blob/argo-workflows-0.13.0/charts/argo-workflows/templates/controller/workflow-controller-cluster-roles.yaml#L34-L40) :

```yaml
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
```

The `get` permissions is missing, it should be:

```yaml
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
```
