### ISSUE TITLE
[argo-cd] pathType: Prefix should not be hardcoded for AWS ALB gRPC Ingress 

### ISSUE THREAD

**Issue by martinlindner** [argoproj/argo-helm#1193]
### Describe the bug

When installing the argo-cd chart with `server.ingressGrpc.isAWSALB: true` and `server.ingressGrpc.enabled: true`, the `pathType` for the gRPC service is hardcoded to `Prefix` instead of using the value from `server.ingress.pathType` or `server.ingressGrpc.pathType`:

https://github.com/argoproj/argo-helm/blob/b9193965741061c2d3c32a164555cfd73d2fcf36/charts/argo-cd/templates/argocd-server/ingress.yaml#L42-L45

If that makes sense to you, I'm happy to submit a PR to use the value from `{{ .Values.server.ingressGrpc.pathType }}` instead.

### Related helm chart

argo-cd

### To Reproduce

`helm install argo/argo-cd ..` with values resembling:

```yaml
server:
  ingress:
    enabled: true
    pathType: ImplementationSpecific
..
  ingressGrpc:
    enabled: true
    isAWSALB: true
    pathType: ImplementationSpecific
..
```

-> Ingress is created with `pathType: Prefix` for the gRPC path.

### Expected behavior

Ingress is created with `pathType: ImplementationSpecific` for the gRPC path.
