### ISSUE TITLE
Helm chart not providing default value for applicationset service targetport

### ISSUE THREAD

**Issue by visheyra** [argoproj/argo-helm#1199]
### Describe the bug

At this [location](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-applicationset/service.yaml) the service port is defined as follow:

```
# ommited for clarity
spec:
  ports:
  - name: {{ .Values.applicationSet.service.portName }}
    port: {{ .Values.applicationSet.service.port }}
    targetPort: {{ .Values.applicationSet.containerPort }}
```

However `Values.applicationSet.containerPort` has no value set in the [default values.yaml file](https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml) meaning that the chart will not be rendered properly using default values only.

### Related helm chart

argo-cd

### To Reproduce

clone the repo as is:
```
git clone https://github.com/argoproj/argo-helm
cd argo-helm/charts/
helm template argo-cd argo-cd -f argo-cd/values.yaml
```

see output below
```
# ommited for clarity
---
# Source: argo-cd/templates/argocd-applicationset/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-cd-argocd-applicationset-controller
  labels:
    helm.sh/chart: argo-cd-4.2.3
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  ports:
  - name: webhook
    port: 7000
    targetPort:
  selector:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/instance: argo-cd
 ---
 # ommited for clarity
```

### Expected behavior

for the containerPort to be populated and the chart to build without additional configuration
