### ISSUE TITLE
Do not create slack service account argocd-notifications-bot when Values.notifications.enable=false

### ISSUE THREAD

**Issue by MalibuKoKo** [argoproj/argo-helm#1207]
### Describe the bug

Just like this other service account: https://github.com/argoproj/argo-helm/blob/argo-cd-4.4.0/charts/argo-cd/templates/argocd-notifications/serviceaccount.yaml

Could you restrict creation of the service account when Values.notifications.enable=true ?

### Related helm chart

argo-cd

### To Reproduce

`helm template --version 4.4.0 argo/argo-cd --set notifications.enabled=false | yq -j | jq -s . | jq '[.[] | select( .kind == "ServiceAccount" ) | select( .metadata.name | match("^argocd-notifications-") ) ]' | yq e -P`

```
- apiVersion: v1
  kind: ServiceAccount
  automountServiceAccountToken: null
  metadata:
    name: argocd-notifications-bot
    labels:
      helm.sh/chart: argo-cd-4.4.0
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: argocd
```

### Expected behavior

`helm template --version 4.4.0 argo/argo-cd --set notifications.enabled=false | yq -j | jq -s . | jq '[.[] | select( .kind == "ServiceAccount" ) | select( .metadata.name | match("^argocd-notifications-") ) ]' | yq e -P`

```
[]
```
