### ISSUE TITLE
applicationSet.image.pullPolicy by applicationSet.image.imagePullPolicy in values.yaml

### ISSUE THREAD

**Issue by MalibuKoKo** [argoproj/argo-helm#1225]
### Describe the bug

See: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L1894

change **pullPolicy** => **imagePullPolicy** in file: values.yaml
```
applicationSet:
  image:
    # -- Repository to use for the application set controller
    repository: quay.io/argoproj/argocd-applicationset
    # -- Image pull policy for the application set controller
    pullPolicy: IfNotPresent
    # -- Tag to use for the application set controller
    tag: "v0.4.1"
```
see: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-applicationset/deployment.yaml#L54

### Related helm chart

argocd-applicationset

### To Reproduce

applicationSet.image.pullPolicy=Always not work

### Expected behavior

applicationSet.image.imagePullPolicy=Always work
