### ISSUE TITLE
add missing imagePullPolicy on argocd-repo-server/deployment (initContainers)

### ISSUE THREAD

**Issue by MalibuKoKo** [argoproj/argo-helm#1227]
### Is your feature request related to a problem?

See: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L199-L213

imagePullPolicy in initContainer is missing :
```
      initContainers:
      - command:
        - cp
        - -n
        - /usr/local/bin/argocd
        - /var/run/argocd/argocd-cmp-server
        image: {{ default .Values.global.image.repository .Values.repoServer.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.repoServer.image.tag }}
        name: copyutil
        resources:
          {{- toYaml .Values.repoServer.copyutil.resources | nindent 10 }}
        {{- if .Values.repoServer.containerSecurityContext }}
        securityContext: {{- toYaml .Values.repoServer.containerSecurityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
```

### Related helm chart

other

### Describe the solution you'd like

add imagePullPolicy
```
      initContainers:
      - command:
        - cp
        - -n
        - /usr/local/bin/argocd
        - /var/run/argocd/argocd-cmp-server
        image: {{ default .Values.global.image.repository .Values.repoServer.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.repoServer.image.tag }}
        imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.repoServer.image.imagePullPolicy }}
        name: copyutil
        resources:
          {{- toYaml .Values.repoServer.copyutil.resources | nindent 10 }}
        {{- if .Values.repoServer.containerSecurityContext }}
        securityContext: {{- toYaml .Values.repoServer.containerSecurityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
```
