### ISSUE TITLE
[charts/argo-cd] Adding namespacing

### ISSUE THREAD

**Issue by jl431** [argoproj/argo-helm#124]
**Is your feature request related to a problem? Please describe.**
It is frustrating that helm deployments of Argo can't target a different namespace.

**Describe the solution you'd like**
Can we add namespace to the definition of each component?
E.g.
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller
  namespace: {{ .Release.Namespace }}
```
