### ISSUE TITLE
Workflow stuck after finish

### ISSUE THREAD

**Issue by tgruenert** [argoproj/argo-helm#1241]
### Describe the bug

After create a demo worflow this stucks as running. 

### Related helm chart

argo-workflows

### To Reproduce

1. Submit new workflow
2. Klick "Edit using full workflow options"
3. Click "+Create"
4. the workflow starts and print the message out

### Expected behavior

workflows should stop by itself after successful finish

### Additional context

helm chart 0.14 with values.yaml 
```
controller: 
  workflowNamespaces:
  - default 
  - geomap-workflows
server: 
  ingress:
    enabled: true 
    ingressClassName: "nginx"
 
[...]

  extraArgs:
  - --auth-mode=sso
  sso:
    # All the values are required. SSO is activated by adding --auth-mode=sso
    # to the server command line.
    
    # The root URL of the OIDC identity provider.
    issuer: https://dex.domain.com:5556/dex
    # Name of a secret and a key in it to retrieve the app OIDC client ID from.
    clientId:
      name: argo-server-sso
      key: client-id
    # Name of a secret and a key in it to retrieve the app OIDC client secret from.
    clientSecret:
      name: argo-server-sso
      key: client-secret
    # The OIDC redirect URL. Should be in the form <argo-root-url>/oauth2/callback.
    redirectUrl: https://argowf.domain.com/oauth2/callback
    rbac:
      enabled: false
    # When present, restricts secrets the server can read to a given list.
    # You can use it to restrict the server to only be able to access the
    # service account token secrets that are associated with service accounts
    # used for authorization.
      secretWhitelist: []
    # Scopes requested from the SSO ID provider.  The 'groups' scope requests
    # group membership information, which is usually used for authorization
    # decisions.
    scopes:
    - groups    

```

wait-container:
```
time="2022-04-22T16:53:32.612Z" level=info msg="Starting Workflow Executor" executorType=docker version=v3.3.2
time="2022-04-22T16:53:32.615Z" level=info msg="Creating a docker executor"
time="2022-04-22T16:53:32.616Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2022-04-22T16:53:32.616Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=default podName=sparkly-rhino template="{\"name\":\"argosay\",\"inputs\":{\"parameters\":[{\"name\":\"message\",\"value\":\"hello argo\"}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"main\",\"image\":\"argoproj/argosay:v2\",\"command\":[\"/argosay\"],\"args\":[\"echo\",\"hello argo\"],\"resources\":{}}}" version="&Version{Version:v3.3.2,BuildDate:2022-04-20T21:37:39Z,GitCommit:35492a1700a0f279694cac874b6d9c07a08265d1,GitTag:v3.3.2,GitTreeState:clean,GoVersion:go1.17.9,Compiler:gc,Platform:linux/amd64,}"
time="2022-04-22T16:53:32.616Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=default --filter=label=io.kubernetes.pod.name=sparkly-rhino"
time="2022-04-22T16:53:32.616Z" level=info msg="Starting deadline monitor"
time="2022-04-22T16:53:32.641Z" level=info msg="listed containers" containers="map[]"
time="2022-04-22T16:53:33.642Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=default --filter=label=io.kubernetes.pod.name=sparkly-rhino"
time="2022-04-22T16:53:33.672Z" level=info msg="listed containers" containers="map[]"
time="2022-04-22T16:53:34.672Z" level=info msg="docker ps --all --no-trunc --format={{.Status}}|{{.Label \"io.kubernetes.container.name\"}}|{{.ID}}|{{.CreatedAt}} --filter=label=io.kubernetes.pod.namespace=default --filter=label=io.kubernetes.pod.name=sparkly-rhino"
time="2022-04-22T16:53:34.696Z" level=info msg="listed containers" containers="map[]"
```
the last lines repeats endless

---
server log shows repeating 
```
422 16:59:46.009056       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
E0422 17:00:20.041070       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.Secret: unknown (get secrets)
E0422 17:00:27.424840       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: unknown (get serviceaccounts)
```
