### ISSUE TITLE
update-password failed    unable to extract token claims

### ISSUE THREAD

**Issue by pikomen** [argoproj/argo-helm#1256]
### Describe the bug

error on update-password with argocd cli tool

```console
argocd account get --account qa
Name:               qa
Enabled:            true
Capabilities:       apiKey, login

Tokens:
NONE
```

```console
argocd account update-password --account qa --current-password ADMIN_PASS --new-password NEW_PASS
ERRO[0000] finished unary call with code Unknown         error="unable to extract token claims" grpc.code=Unknown grpc.method=UpdatePassword grpc.service=account.AccountService grpc.start_time="2022-05-03T17:07:55+03:00" grpc.time_ms=0.069 span.kind=server system=grpc
FATA[0000] rpc error: code = Unknown desc = unable to extract token claims
```

### Related helm chart

argo-cd

### To Reproduce

argo-cd-4.5.8
k8s v1.21.3

```yaml
  config:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
    accounts.qa: apiKey, login
    accounts.dev: apiKey, login
    accounts.qa.enabled: "true"
    accounts.dev.enabled: "false"
```

### Expected behavior

change password for new user created by config
