### ISSUE TITLE
Strange behaviour on Argo workflow helm install

### ISSUE THREAD

**Issue by Ragatzino** [argoproj/argo-helm#1265]
### Describe the bug

I am using helm chart 0.14.0

and values
```yaml
controller:
  containerRuntimeExecutor: emissary
  podSecurityContext:
    runAsNonRoot: false
    runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
server:
   ingress:
     enabled: true
     hosts: 
      - example.org
   extraArgs: 
   - --auth-mode=server
```

And i get this error on pods:
```console
pods "delightful-poochenheimer" is forbidden: PodSecurityPolicy:
unable to admit pod: [spec.volumes[1].hostPath.pathPrefix: 
Invalid value: "/var/run/docker.sock": is not allowed to be used spec.volumes[1]: 
Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

Which i seemingly associated with docker executor though helm templating shows a emissary executor inside the config map according to plan.

Is it a typo in chart definition or a miscomprehension on my side of things ?

### Related helm chart

argo-workflows

### To Reproduce

Install chart 0.14.0 with my values in a run as non root PSP environnement through 
```
helm template -f values.yaml argo/argo-workflows --version 0.14.1 > template.yaml
kubectl apply -f template.yaml
```

### Expected behavior

Have pods run unpriviledged and not trigger PSP.

### Additional context

I actually installed it with helm template using Argo cd.
