### ISSUE TITLE
Unable to connect to MASTER: Address family not supported by protocol

### ISSUE THREAD

**Issue by thangamani-arun** [argoproj/argo-helm#1268]
### Describe the bug

We have deployed argocd using helm charts. Running latest chart version 4.10.5 and enabled with `redis-ha`. All the pods are up and running, when we delete apps in argocd, it says `NOREPLICAS Not enough good replicas to write.`

**values.yaml**
```
global:
  image:
    repository: quay.io/argoproj/argocd
    tag: "v2.3.3"

controller:
  enableStatefulSet: true
  image:
    repository: quay.io/argoproj/argocd
    tag: "v2.3.3"
  volumeMounts:
    - name: custom-ca-certificates
      mountPath: /etc/ssl/certs/custom-ca-certificates.crt
      subPath: custom-ca-certificates.crt
  volumes:
    - name: custom-ca-certificates
      secret:
        defaultMode: 420
        secretName: custom-ca-certificates
  metrics:
    enabled: false
    service:
      servicePort: 8082

dex:
  enabled: true
  image:
    repository: ghcr.io/dexidp/dex
    tag: "v2.30.2"
  metrics:
    enabled: false

redis-ha:
  enabled: true
  image:
    repository: redis
    tag: "6.2.6-alpine"
  exporter:
    enabled: true
    image: oliver006/redis_exporter
    tag: "v1.3.2"
  redis:
    config:
      save: "\"\""
      bind: "0.0.0.0"
  sentinel:
    bind: 0.0.0.0
  haproxy:
    enabled: true
    metrics:
      enabled: true
    image:
      repository: chaproxy
      tag: "2.4.9"

server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    # -- Average CPU utilization percentage for the Argo CD server [HPA]
    targetCPUUtilizationPercentage: 50
    # -- Average memory utilization percentage for the Argo CD server [HPA]
    targetMemoryUtilizationPercentage: 50
  extraArgs:
    - --insecure
  logFormat: text
  logLevel: info
  volumeMounts:
    - name: custom-ca-certificates
      mountPath: /etc/ssl/certs/custom-ca-certificates.crt
      subPath: custom-ca-certificates.crt
  volumes:
    - name: custom-ca-certificates
      secret:
        defaultMode: 420
        secretName: custom-ca-certificates
  metrics:
    enabled: false
    servicePort: 8083

  ingress:
    enabled: true
    annotations:
      - nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      - nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      - nginx.ingress.kubernetes.io/proxy-body-size: 100m
      - nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
      - nginx.ingress.kubernetes.io/proxy-buffering: 'on'
      - nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
      - nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
    ingressClassName: "nginx-default"
    hosts:
      - argocd.mysite.com
    tls:
      - secretName: tls-cert-secret
        hosts:
          - argocd.mysite.com
    https: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    # -- Average CPU utilization percentage for the Argo CD server [HPA]
    targetCPUUtilizationPercentage: 50
    # -- Average memory utilization percentage for the Argo CD server [HPA]
    targetMemoryUtilizationPercentage: 50
  logFormat: text
  logLevel: info
  metrics:
    enabled: false
    servicePort: 8084
  volumeMounts:
    - name: custom-ca-certificates
      mountPath: /etc/ssl/certs/custom-ca-certificates.crt
      subPath: custom-ca-certificates.crt
  volumes:
    - name: custom-ca-certificates
      secret:
        defaultMode: 420
        secretName: custom-ca-certificates

applicationSet:
  enabled: false
  replicaCount: 1
  image:
    repository: quay.io/argoproj/argocd-applicationset
    tag: "v0.4.1"
  metrics:
    enabled: false
    servicePort: 8085
````

### Related helm chart

argo-cd

### To Reproduce

1. Setup your K8s cluster with IPv4 and disable IPv6 support
2. Deploy argocd using helm

### Expected behavior

Redis-Ha cluster is up (master and replicas are able to connect each other

### Screenshots

**Logs of redis-slave pod**

```
kubectl logs -f --tail=10 -n argocd argo-cd-redis-ha-server-1 redis
1:S 07 May 2022 21:33:22.653 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:22.659 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:23.663 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:23.670 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:24.673 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:24.680 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:25.684 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:25.690 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:26.694 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:26.701 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:27.704 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:27.710 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:28.713 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:28.720 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:29.723 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:29.730 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:30.733 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:30.739 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:31.742 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:31.749 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:32.753 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:32.759 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:33.763 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:33.769 # Unable to connect to MASTER: Address family not supported by protocol
1:S 07 May 2022 21:33:34.773 * Connecting to MASTER a98:b077:::6379
1:S 07 May 2022 21:33:34.779 # Unable to connect to MASTER: Address family not supported by protocol
```

**argocd controller logs**
```
time="2022-05-07T20:32:06Z" level=error msg="Failed to cache app resources: error setting app resource tree: NOREPLICAS Not enough good replicas to write." application=test-vault dedup_ms=0 diff_ms=79 git_ms=191 health_ms=1 live_ms=2 settings_ms=0 sync_ms=0
time="2022-05-07T20:32:06Z" level=error msg="Failed to cache app resources: error setting app resource tree: NOREPLICAS Not enough good replicas to write." application=gitlab-0 dedup_ms=0 diff_ms=312 git_ms=5273 health_ms=11 live_ms=2 settings_ms=0 sync_ms=0
```

### Additional context

running pod status

```
kubectl get pods -n argocd
NAME                                                      READY   STATUS    RESTARTS   AGE
argo-cd-argocd-application-controller-0                   1/1     Running   0          112m
argo-cd-argocd-dex-server-b496c7bc6-5wrc2                 1/1     Running   0          124m
argo-cd-argocd-notifications-controller-6bbcdff98-xmx5q   1/1     Running   0          126m
argo-cd-argocd-repo-server-74c7cfcd9-rmrsp                1/1     Running   0          126m
argo-cd-argocd-repo-server-74c7cfcd9-xfss4                1/1     Running   0          127m
argo-cd-argocd-server-85b9b4d799-c66td                    1/1     Running   0          126m
argo-cd-argocd-server-85b9b4d799-hw6z8                    1/1     Running   0          127m
argo-cd-redis-ha-haproxy-57cff8bb98-cv9bd                 1/1     Running   0          64m
argo-cd-redis-ha-haproxy-57cff8bb98-jjpmd                 1/1     Running   0          64m
argo-cd-redis-ha-haproxy-57cff8bb98-lb75j                 1/1     Running   0          64m
argo-cd-redis-ha-server-0                                 3/3     Running   0          15m
argo-cd-redis-ha-server-1                                 3/3     Running   0          13m
```
