### ISSUE TITLE
workflow-role needs list, watch on workflowtasksets and patch on workflowtasksets/status

### ISSUE THREAD

**Issue by ntdt** [argoproj/argo-helm#1273]
### Describe the bug

With the helm chart argo-workflows v1.5, the service account created by value `workflow.serviceAccount.create` needs more permissions to be able to run http template. Following this manifest https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start/base/agent-role.yaml, the workflow-role need list, watch the workflowtasksets and patch on the workflowtasksets/status.

### Related helm chart

argo-workflows

### To Reproduce

Deploy the argo-workflows with values.

```
workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"
  rbac:
    create: true
```

Then try to run the http template, there are errors on missing permissions

### Expected behavior

http template must run.
