### ISSUE TITLE
Chart version in Helm repository is not up to date

### ISSUE THREAD

**Issue by jaysiee** [argoproj/argo-helm#128]
**Describe the bug**

The chart version in the Helm repository is 0.5.4 and not 0.6.x as expected. 
Possibly similar to: https://github.com/argoproj/argo-helm/issues/86
Is there a CI job or a pipeline that can be triggered automatically for each new chart version?

**To Reproduce**

```
❯ helm repo list  
NAME    URL
argo    https://argoproj.github.io/argo-helm
❯ helm repo update
❯ helm fetch argo/argo-cd 
❯ ls   
argo-cd-0.5.4.tgz
```

**Expected behavior**
I exptect the downloaded version to be 0.6.x.

**Comment by Snapple49** [comment]
I'd like to chime in and point out the same for argo-events. It would be much appreciated if the chart versions could be bumped!

**Comment by l15k4** [comment]
Guys pretty pls, with sugar on top, I'm trying to work around it by : 
```
dependencies:
- name: argo
  version: "0.6.1"
  repository: "file:///home/ubuntu/src/argo-helm/charts/argo-events"
- name: argo-events
  version: "0.5.0"
  repository: "file:///home/ubuntu/src/argo-helm/charts/argo"
```
but this for some reason ends with : 
```
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Save error occurred:  can't get a valid version for dependency argo
Deleting newly downloaded charts, restoring pre-update state
Error: can't get a valid version for dependency argo
```
