### ISSUE TITLE
Prometheus metrics failing for Workflow

### ISSUE THREAD

**Issue by andrew-pickin-epi** [argoproj/argo-helm#1301]
### Describe the bug

Latest version (main) of reports argo-workflows-workflow-controller down (connection refused).

Reviewing previous versions:
Working 0.13.1 [workflow (3.2.9)]
Not Working 0.14.1 [workflow (3.3.2)] 

Note using help 0.13.1 workflow tag 3.3.0 doesn't work. 
Incompatibility between helm and workflow?

### Related helm chart

argo-workflows

### To Reproduce

```
  values:
    server:
      extraArgs: [ "--secure=false", "--auth-mode=server", "--log-format=json" ]
    workflow:
      serviceAccount:
        create: true
        name: "argo-workflow"
    controller:
      extraArgs: [ "--log-format=json" ]
      metricsConfig:
        enabled: true
      serviceMonitor:
        enabled: true
```

### Expected behavior

Work as previously.
