### ISSUE TITLE
Unable to render argocd helm chart when redis-ha enabled in versions > 4.7.0

### ISSUE THREAD

**Issue by eknudtson** [argoproj/argo-helm#1309]
### Describe the bug

When I attempt to build the Argo-CD Helm chart (> v4.7.0) with a kustomize helm chart inflator generator and the `redis-ha.enabled` key set to `true`, I get the following output:

```Error: Error: YAML parse error on argo-cd/charts/redis-ha/templates/redis-haproxy-deployment.yaml: error converting YAML to JSON: yaml: line 51: mapping values are not allowed in this context```

Looking into this, I noticed `redis-ha.haproxy.image` `repository` and `tag` keys are set to null.  Setting these values to non-null in my helm generator values allows the chart to render properly.

`https://github.com/argoproj/argo-helm/blob/argo-cd-4.8.0/charts/argo-cd/values.yaml#L797-L803`

### Related helm chart

argo-cd

### To Reproduce

Attempt to build Argo-CD helm chart using a kustomize helm chart inflator generator:

kustomize.yaml
```
helmCharts:
- name: argo-cd
  namespace: argocd
  includeCRDs: true
  version: 4.8.0
  releaseName: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
     redis-ha:
       enabled: true
```

`kustomize build --enable-helm .`

```
Error: Error: YAML parse error on argo-cd/charts/redis-ha/templates/redis-haproxy-deployment.yaml: error converting YAML to JSON: yaml: line 51: mapping values are not allowed in this context
```

Now set `redis-ha.haproxy.image.repository` and `redis-ha.haproxy.image.tag` keys explicitly:

kustomize.yaml
```
helmCharts:
- name: argo-cd
  namespace: argocd
  includeCRDs: true
  version: 4.8.0
  releaseName: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    redis-ha:
      enabled: true
      haproxy:
        image:
          repository: haproxy
          tag: 2.4.9
```

`kustomize build --enable-helm .`

Manifests rendered as expected.

### Expected behavior

Manifests should be rendered as expected when `redis-ha.enabled` is set to `true`.

**Comment by yu-croco** [comment]
I suck at English, so I could not get the exact meaning of `follows subchart default`. I am wondering if `~` is a function to fulfill subchart's value or users need to set value explicitly... (I searched but could not get any information so far...) 🤔 

As far as I checked, we need to set value explicitly, otherwise it returns nil and failed `kustomize build --enable-helm .` as you reported.

https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L806-L812

```yaml
redis-ha:
  # ...
  haproxy:
    image:
      # -- HAProxy Image Repository
      # @default -- `nil` (follows subchart default)
      repository: ~
      # -- HAProxy Image Tag
      # @default -- `nil` (follows subchart default)
      tag: ~
```

**Comment by yu-croco** [comment]
Hi @mkilchhofer ,
could you please tell me the meaning of `~` above, whether users need to set value explicitly or it is supposed to be fulfilled automatically ? 🙇 

ref: https://github.com/argoproj/argo-helm/pull/1296

**Comment by sabrisay** [comment]
I am running into the same issue. Although I disabled redis-ha, I am getting the same error.

**Comment by mkilchhofer** [comment]
> Hi @mkilchhofer , could you please tell me the meaning of `~` above, whether users need to set value explicitly or it is supposed to be fulfilled automatically ? 🙇
> 
> ref: #1296

> The tilde is one of the ways the null value can be written. Most parsers also accept an empty value for null, and of course null, Null and NULL.

I tested the behavior inside helm only. There was an issue that we do not document how image repository can be overwritten when installing the argo-cd chart.

As we use helm-docs we cannot document parameters in the README without having the key inside values.yaml. But I tested what happens if the parent/umbrella chart "overrides" a parameter with `null`/`nil`/`~`. It outcome was that the subchart (redis-ha) then will use its default values.

Maybe this is different when using helm together with kustomize?

**Comment by yu-croco** [comment]
Thank you for explaining!

> Maybe this is different when using helm together with kustomize?

It seems...😇 

As a workaround on kustomize, set the values explicitly like below. 🤔 
```yaml
helmCharts:
- name: argo-cd
  namespace: argocd
  includeCRDs: true
  version: 4.8.0
  releaseName: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesInline:
    redis-ha:
      enabled: true
      haproxy:
        image:
          repository: haproxy
          tag: 2.4.9
```

**Comment by eknudtson** [comment]
It looks like there are a few other omissions in redis-ha when using kustomize.  I'm having to set the following values myself, or they're empty in the rendered manifests:

```
      exporter:
        image: oliver006/redis_exporter
        tag: v1.27.0
      image:
        repository: redis
```
