### ISSUE TITLE
sso and rbac enabled : cannot list resource "secrets" in API group "" at the cluster scope. 

### ISSUE THREAD

**Issue by tiwarisanjay** [argoproj/argo-helm#1316]
### Describe the bug

I have enabled sso, which throws error for serviceAccount. So I eneabled rbac and now seeing following issue: 

pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:argo:demo-argo-workflows-server" cannot list resource "secrets" in API group "" at the cluster scope. 

### Related helm chart

argo-workflows

### To Reproduce

Updating following values for Values.yaml 
```yaml  
  controller:
    image:
      registry: quay.io
      repository: argoproj/workflow-controller
      tag: v3.3.6
  server:
    secure: true
    image:
      registry: quay.io
      repository: argoproj/argocli
      tag: v3.3.6
    serviceType: LoadBalancer
    loadBalancerIP: 11.111.11.111
    volumeMounts:
    - name: ca-pemstore
      mountPath: /etc/ssl/certs/ca.crt
      subPath: ca.crt
      readOnly: false
    volumes:
    - name: ca-pemstore
      configMap:
        name: dex-ca    
    extraArgs:
      - --auth-mode=sso
    sso:
      issuer: https://22.222.222.222:5556/dex
      clientId:
        name: argo-workflows-sso
        key: client-id
      clientSecret:
        name: argo-workflows-sso
        key: client-secret
      redirectUrl: https://11.111.11.111:2746/oauth2/callback
      rbac:
        secretWhitelist: 
        - argo-workflows-sso
        - tls-secret
```

### Expected behavior

Deployment should work for argo server.  as it woks if I add ClusterRole and Rolebinding by adding verbs get, list and watch. 
Check Additional context. 

### Additional context

It works if I add following ClusterRole and Rolebinding 
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-server-secret
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  argo-workflows-server-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-server-secret
subjects:
- kind: ServiceAccount
  name: dexdemo-argo-workflows-server
  namespace:  {{ .Release.Namespace }}
```
