### ISSUE TITLE
Some argo-workflows Resources Are Installed in default Namespace

### ISSUE THREAD

**Issue by qgervacio** [argoproj/argo-helm#1321]
### Describe the bug

Hi Argo Team,

Perhaps my understanding is wrong, `argo-workflows` chart should install all resources in namespace specified. However some resources like below are installed in `default` namespace causing failure unless a project is given permission to deploy in `default` namespace. Is this an expected behaviour?

Sample result:

```
helm template test . | grep -B 5 'namespace: default'
  kind: ClusterRole
  name: test-argo-workflows-workflow-controller
subjects:
  - kind: ServiceAccount
    name: test-argo-workflows-workflow-controller
    namespace: default
--
  kind: ClusterRole
  name: test-argo-workflows-workflow-controller-cluster-template
subjects:
  - kind: ServiceAccount
    name: test-argo-workflows-workflow-controller
    namespace: default
--
  kind: ClusterRole
  name: test-argo-workflows-server
subjects:
- kind: ServiceAccount
  name: test-argo-workflows-server
  namespace: default
--
  kind: ClusterRole
  name: test-argo-workflows-server-cluster-template
subjects:
- kind: ServiceAccount
  name: test-argo-workflows-server
  namespace: default
--
# Source: argo-workflows/templates/controller/workflow-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-argo-workflows-workflow
  namespace: default
--
# Source: argo-workflows/templates/controller/workflow-rb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-argo-workflows-workflow
  namespace: default
--
  kind: Role
  name: test-argo-workflows-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: default
```

### Related helm chart

argo-workflows

### To Reproduce

```
git clone https://github.com/argoproj/argo-helm.git
cd argo-helm/charts/argo-workflows
helm template test . | grep -B 5 'namespace: default'
```

### Expected behavior

All resources should be installed in namespace specified.

### Additional context

Using chart `argo-workflows:0.16.2`. Temporary workaround is to allow a project to install in `default` namespace.

**Comment by vladlosev** [comment]
The resources are installed into the namespace specified by the `--namespace` option in the `helm install` or `helm upgrade` commands. If you don's specify anything, it will be `default`. But it will be the same namespace regardless of whether it's implied or specified with `.Release.Namespace`.

**Comment by qgervacio** [comment]
> The resources are installed into the namespace specified by the `--namespace` option in the `helm install` or `helm upgrade` commands. If you don's specify anything, it will be `default`. But it will be the same namespace regardless of whether it's implied or specified with `.Release.Namespace`.

My apologies i forgot to add `-n` in the sample up top. But even so, there are still some resources that are _fixed_ to `default` namespace.

```
helm template test . -n argo-workflows | grep default
  namespace: default
  namespace: default
    namespace: default
```

This becomes a problem when the chart is created via `Application` object. Below will fail unless the project where the application resides have a permission to create stuff in `default` namespace.

```
...
spec:
  project: platform
  source:
    helm:
      releaseName: argo-workflows
      valueFiles:
      - values.yaml
    path: .
    repoURL: http://192.168.57.20:7990/scm/plathc/argo-workflows.git
    targetRevision: HEAD
  destination:
    namespace: argo-workflows # like "helm ... -n  argo-workflows"
    server: https://kubernetes.default.svc
...
```
