### ISSUE TITLE
Support clusterResourceBlacklist in server.additionalProjects for argo-cd

### ISSUE THREAD

**Issue by adrienzieba** [argoproj/argo-helm#1332]
### Is your feature request related to a problem?

I don't know if it is intended but I notice that in `server.additionalProjects`, `clusterResourceWhitelist` is supported but not `clusterResourceBlacklist`.
Is it possible to add it?

### Related helm chart

argo-cd

### Describe the solution you'd like

I would like being able to configure the clusterResourceBlacklist using the values file.

```
additionalProjects:
  - name: guestbook
     namespace: argocd
     description: Example Project
     sourceRepos:
       - '*'
     destinations:
       - namespace: guestbook
          server: https://kubernetes.default.svc
     clusterResourceWhitelist: 
       - group: '*'
          kind: '*'
     clusterResourceBlacklist:
     - group: agroup
       kind: aKind
```

### Describe alternatives you've considered

The only alternative I have right now is to modified the project manually once synced in argo-cd.
