### ISSUE TITLE
add-crds-in-to-argocd-templates-with-condition-enabled-true-false

### ISSUE THREAD

**Issue by MohamedKhelifi** [argoproj/argo-helm#1336]
### Is your feature request related to a problem?

Hello,

When I'm trying to deploy Argocd with terraform, I can't add the option --install-crd on terraform code (helm_release resource)
So it will be good if we can enable CRD installation on values.yaml like on argo-events.

Thanks

### Related helm chart

argo-cd

### Describe the solution you'd like

Like [argo-events](https://github.com/argoproj/argo-helm/tree/main/charts/argo-events) move crds directory on argocd/templates/

Add this condition on CRD files: 
```YAML
{{- if .Values.crds.install }}

#code

{{- end }}
```

On values.yaml:
```YAML
## Custom resource configuration
crds:
  # -- Install and upgrade CRDs
  install: true
```
