### ISSUE TITLE
Argo events controller config template renders version list incorrectly

### ISSUE THREAD

**Issue by jfklingler** [argoproj/argo-helm#1343]
### Describe the bug

The current event bus versions config for [nats](https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/templates/argo-events-controller/config.yaml#L12-L17) and [jetstream](https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/templates/argo-events-controller/config.yaml#L33-L40) incorrectly renders `versions:` for each list element supplied in the values. This results in a configmap like 

```yaml
apiVersion: v1
data:
  controller-config.yaml: |
    eventBus:
...
        versions:
        - version: latest
          natsImage: nats:2.8.1
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: /nats-server
        versions:
        - version: 2.8.1
          natsImage: nats:2.8.1
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: /nats-server
        versions:
        - version: 2.8.1-alpine
          natsImage: nats:2.8.1-alpine
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: nats-server
        versions:
        - version: 2.8.2
          natsImage: nats:2.8.2
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: /nats-server
        versions:
        - version: 2.8.2-alpine
          natsImage: nats:2.8.2-alpine
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: nats-server
...
```
Only the last version in the list is ultimately recognized as a valid event bus version.

### Related helm chart

argo-events

### Helm chart version

2.0.0

### To Reproduce

Create a helm release that specifies multiple event bus versions.

### Expected behavior

ConfigMap is rendered correctly without `versions:` being repeated as, for example
```yaml
apiVersion: v1
data:
  controller-config.yaml: |
    eventBus:
...
        versions:
        - version: latest
          natsImage: nats:2.8.1
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: /nats-server
        - version: 2.8.1
          natsImage: nats:2.8.1
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: /nats-server
        - version: 2.8.1-alpine
          natsImage: nats:2.8.1-alpine
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: nats-server
        - version: 2.8.2
          natsImage: nats:2.8.2
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: /nats-server
        - version: 2.8.2-alpine
          natsImage: nats:2.8.2-alpine
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
          configReloaderImage: natsio/nats-server-config-reloader:0.7.0
          startCommand: nats-server
...
```
