### ISSUE TITLE
Unable to use proxy for outgoing connections

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-helm#1367]
### Describe the bug

Error: looks like "https://helm.traefik.io/traefik" is not a valid chart repository or cannot be reached: Get "https://helm.traefik.io/traefik/index.yaml": dial tcp: lookup helm.traefik.io on 192.168.64.10:53: no such host

### Related helm chart

argo-cd

### Helm chart version

4.9.12

### To Reproduce

```yaml
  # -- Environment variables to pass to Argo CD server
  env:
  - name: http_proxy
    value: http://security-proxy.emea.svc.corpintra.net:3128/
  - name: https_proxy
    value: http://security-proxy.emea.svc.corpintra.net:3128/
  - name: no_proxy
    value: argocd-repo-server,argocd-application-controller,argocd-metrics,argocd-server,argocd-server-metrics,argocd-redis,192.168.0.0/8
```

### Expected behavior

The corporate proxy should be able to resolve the DNS name helm.traefik.io correctly but it does not seem to work.
