### ISSUE TITLE
[argo-cd] environment variable not rendered with 4.9.x

### ISSUE THREAD

**Issue by headyj** [argoproj/argo-helm#1382]
### Describe the bug

I tried updating from 4.8.3 to 4.9.14, but it seems that the helm args are no more rendered:

`Error: Error: YAML parse error on composer/templates/nginx-persistent-volume.yml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context`

I tried locally and I have this exact issue if I don't pass any value to `$helm_args` variable. The plugin command is the following:
`helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --api-versions apiregistration.k8s.io/v1 --include-crds $helm_args . | argocd-vault-plugin generate -s vault-configuration -`

this variable is passed using ENV variable of argocd application, and it's working on 4.8.3 version

I tried with multiple verison of 4.9 without any success. I updated both the charts and the CRD

Could be related to https://github.com/argoproj/argo-helm/issues/1309, but it's not the same version and the proposed fix doesn't seems to work for me

### Related helm chart

argo-cd

### Helm chart version

4.9.x

### To Reproduce

1. Configure a custom plugin with the following command:
```
generate:
  command: ["/bin/sh", "-c"]
  args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --api-versions apiregistration.k8s.io/v1 --include-crds $helm_args . | argocd-vault-plugin generate -s vault-configuration -"]
```
2. create an application with environment variables:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/myapp.git
    targetRevision: HEAD
    path: myapp
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: "--namespace myapp --values values.yaml --set [...] --set [...]"
```

### Expected behavior

helm_args should be rendered correctly

**Comment by headyj** [comment]
I just wanted to add that even if https://github.com/argoproj/argo-helm/issues/1309 has been closed that I still have the issue with latest 4.5.10 version:

```
rpc error: code = Unknown desc = `/bin/sh -c helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --api-versions apiregistration.k8s.io/v1 --include-crds $helm_args . | argocd-vault-plugin generate -s vault-configuration -` failed exit status 1: Error: YAML parse error on chart/templates/nginx-persistent-volume.yml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context Use --debug flag to render out invalid YAML Error: No manifests Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret in the argocd namespace containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD). The namespace can be overridden by using the format <namespace>:<name> --verbose-sensitive-output enable verbose mode for detailed info to help with debugging. Includes sensitive data (credentials), logged to stderr
```
This is exactly the same error message I would have if I do helm template without passing any variable, which confirm that the environment variable helm_args is not read at all.

**Comment by headyj** [comment]
Any news on that issue? It's quite an annoying job as we are still blocked with 4.3 version

**Comment by headyj** [comment]
For those who have the same problem, I finally found what was the problem. v2.4 introduced a new behaviour concerning variables in application specs, which is documented here: https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#environment, which is mentions:

_v2.4_

_Before reaching the init.command, generate.command, and discover.command commands, Argo CD prefixes all user-supplied environment variables (#3 above) with ARGOCD_ENV_. This prevents users from directly setting potentially-sensitive environment variables._

_If your plugin was written before 2.4 and depends on user-supplied environment variables, then you will need to update your plugin's behavior to work with 2.4. If you use a third-party plugin, make sure they explicitly advertise support for 2.4._

**Comment by tiwarisanjay** [comment]
@headyj Hows your Yaml looks like now for vault plug-in?

**Comment by headyj** [comment]
Basically I just added `ARGOCD_ENV_` in front of my existing variables. Example bellow for my `helm_args` variable:
Before my plugin looked like that:
```
configManagementPlugins: |
  - name: my-plugin
    init:
      command: ["/bin/sh", "-c"]
      args: ["helm repo add **** && helm repo update && helm dependency build ."]
    generate:
      command: ["/bin/sh", "-c"]
      args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --api-versions apiregistration.k8s.io/v1 $helm_args . | argocd-vault-plugin generate -s vault-configuration -"]
```
and now:
```
configManagementPlugins: |
  - name: my-plugin
    init:
      command: ["/bin/sh", "-c"]
      args: ["helm repo add **** && helm repo update && helm dependency build ."]
    generate:
      command: ["/bin/sh", "-c"]
      args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE --api-versions apiregistration.k8s.io/v1 $ARGOCD_ENV_helm_args . | argocd-vault-plugin generate -s vault-configuration -"]
```

**Comment by mehdibenfeguir** [comment]
I'm having the same issue even after adding the prefix 

these are details about the version used
argocd version  --grpc-web
argocd: v2.4.11+3d9e9f2
  BuildDate: 2022-08-22T09:35:38Z
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64


`apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build || true"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helm template ../../helm_base --name-template $ARGOCD_APP_NAME --include-crds > ../../helm_base/all.yml && kustomize build"]
    - name: helm-test--p14
      generate: 
           command: ["sh", "-c"]
           args: ["helm template  test test  --repo $ARGOCD_ENV_HELM_REPO_URL  --values $(pwd)/values-test.yaml --namespace test-eta`
           
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-eta
  namespace: argocd
  
spec:
  project: default
  source:
    repoURL: 'myurl.git'
    path: helm-charts/test
    targetRevision: master
    plugin:
     name: helm-test--p14
     env:

       - name: ARGOCD_ENV_HELM_REPO_URL
         value: "myotherurl"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true`

**Comment by gabrielfsousa** [comment]
stil wont work for me... how can i fix ?

```
        plugin:
          name: awesome-plugin
          env:
            - name: ARGOCD_ENV_HELM_RELEASE_NAME
              value: "weave-scope"
            - name: ARGOCD_ENV_HELM_CHART_VERSION
              value: "1.0.1"
            - name: ARGOCD_ENV_NAMESPACE
              value: "observability"
            - name: ARGOCD_ENV_HELM_REPO_URL
```
```
rpc error: code = Unknown desc = `sh -c helm template --version ${ARGOCD_ENV_HELM_CHART_VERSION} --repo ${ARGOCD_ENV_HELM_REPO_URL} --namespace ${ARGOCD_ENV_NAMESPACE} ${ARGOCD_ENV_HELM_CHART_NAME} --name-template=${ARGOCD_ENV_HELM_RELEASE_NAME} -f $(pwd)/${ARGOCD_ENV_HELM_VALUES_FILE}` failed exit status 1: Error: "helm template" requires at least 1 argument Usage: helm template [NAME] [CHART] [flags]

```
