### ISSUE TITLE
ArgoWorkflows Image Repository Issues

### ISSUE THREAD

**Issue by a3yko** [argoproj/argo-helm#1415]
### Describe the bug

I am deploying Argo Workflows using terraform via their helm provider, and it times out with an error, when I check the pods. I get an InvalidImageName error on the `argo-workflows-argo-events-controller-manager` pod. When I describe the pods I  get the following in the events section

`Failed to apply default image tag "quay.io/:v3.3.9": couldn't parse image reference "quay.io/:v3.3.9": invalid reference format`

I am using the default values.yaml file with just some ingress settings

```
controller:
  image:
    # -- Registry to use for the controller
    registry: quay.io
    # -- Registry to use for the controller
    repository: argoproj/workflow-controller
    # -- Image tag for the workflow controller. Defaults to `.Values.images.tag`.
    tag: ""
```
I also tried modifying to the following and got the same error on the pod

```
controller:
  image:
    # -- Registry to use for the controller
    registry: quay.io/argoproj/workflow-controller
    # -- Registry to use for the controller
    repository: argoproj/workflow-controller
    # -- Image tag for the workflow controller. Defaults to `.Values.images.tag`.
    tag: ""
```

### Related helm chart

argo-workflows

### Helm chart version

0.17.0

### To Reproduce

1. install helm chart 0.17.0 with default yaml file

### Expected behavior

Installs without issue
