### ISSUE TITLE
redis_exporter 1.27.0 does not support arm64

### ISSUE THREAD

**Issue by headless-kjh** [argoproj/argo-helm#1437]
### Describe the bug

I am using aws amd64 instance
maybe can't use ha-proxy because redis-exporter doesn't support amd64

command: 
kubectl logs argocd-redis-ha-server-0 -c redis-exporter
-------------
exec /redis_exporter: exec format error

### Related helm chart

argo-cd

### Helm chart version

5.4.0

### To Reproduce

helm config redis ha-proxy: enable

### Expected behavior

install helm config

**Comment by pdrastil** [comment]
Hi @headless-kjh,
did you look at [DockerHub](https://hub.docker.com/r/oliver006/redis_exporter/tags?page=1&name=v1.27.1) for image tag that supports ARM 64? I see [v1.27.1-arm64](https://hub.docker.com/layers/oliver006/redis_exporter/v1.27.1-arm64/images/sha256-388a4bef6466c9b89dddc0f97d2f5888d286f68350e4c5996f6ac73e4a7ac79a?context=explore) tag for this specific version. 

Latest default configuration for Argo CD 5.4.6 with ha-proxy 4.22.2 is following and tag v1.43.0 supports arm64.

```yaml
redis-ha:
  # Prometheus exporter specific configuration options
  exporter:
    enabled: false
    image: oliver006/redis_exporter
    tag: v1.43.0
    pullPolicy: IfNotPresent
```
