### ISSUE TITLE
argocd-repo-server fails to start

### ISSUE THREAD

**Issue by lsoica** [argoproj/argo-helm#1471]
### Describe the bug

```
argocd-repo-server-c784cd67c-qkv5x                  0/1     CrashLoopBackOff
```
```
$ kubectl logs -n argocd argocd-repo-server-c784cd67c-qkv5x 
time="2022-09-21T07:44:34Z" level=info msg="Generating self-signed gRPC TLS certificate for this session"
time="2022-09-21T07:44:34Z" level=info msg="Initializing GnuPG keyring at /app/config/gpg/keys"
time="2022-09-21T07:44:34Z" level=info msg="gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe2245652282" dir= execID=acdc9
time="2022-09-21T07:44:40Z" level=error msg="`gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe2245652282` failed exit status 2" execID=acdc9
time="2022-09-21T07:44:40Z" level=info msg=Trace args="[gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe2245652282]" dir= operation_name="exec gpg" time_ms=6006.143275
time="2022-09-21T07:44:40Z" level=fatal msg="`gpg --no-permission-warning --logger-fd 1 --batch --gen-key /tmp/gpg-key-recipe2245652282` failed exit status 2"

```

### Related helm chart

argo-cd

### Helm chart version

5.4.8

### To Reproduce

```
helm install argocd --create-namespace --namespace argocd argo/argo-cd --version 5.4.8 -f values.yaml
```
where values yaml is:
```
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      kubernetes.io/ingress.class: nginx
    hosts:
      - "..."
    https: true
    tls:
      - hosts:
          - "..."
        secretName: "kubessl"
  extraArgs:
    - "--insecure"
```

### Expected behavior

argocd-repo-server Running.

**Comment by pdrastil** [comment]
Hi @lsoica,
thanks for submitting the bug, however I'm not able to reproduce CrashLoop with provided values.yaml. Is this only configuration that is supplied?

**Comment by lsoica** [comment]
@pdrastil yes, config only. however , found this thread on the issue https://github.com/argoproj/argo-cd/issues/9809

managed to move past that by updating config with:
```
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      kubernetes.io/ingress.class: nginx-nci-service-ingress-default
    hosts:
      - "argocd.prod.ui.nci.buc.ds.jdsu.net"
    https: true
    tls:
      - hosts:
          - "argocd.prod.ui.nci.buc.ds.jdsu.net"
        secretName: "kubessl"
  extraArgs:
    - "--insecure"
  env:
    - name: "ARGOCD_GPG_ENABLED"
      value: "false"
repoServer:
  env:
    - name: "ARGOCD_GPG_ENABLED"
      value: "false"
controller:
  env:
    - name: "ARGOCD_GPG_ENABLED"
      value: "false"

```
