### ISSUE TITLE
Configure CMP containers as maps instead of an array

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-helm#1490]
### Is your feature request related to a problem?

It is not possible to override a single array element in Helm values. I have a custom CMP sidecar container configured using `repoServer.extraContainers`. I want to be able to override specific values from my CMP container but as its an array that isn't possible, if I want to override one value I need to copy and paste the whole `extraContainers` block just to override one value from one `extraContainers` entry.

### Related helm chart

argo-cd

### Describe the solution you'd like

I would like to be able to configure a CMP sidecar container as a map so that I can easily override individual values in that container. For example: `cmp.image.tag=v1`

### Additional context

https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#option-2-configure-plugin-via-sidecar

**Comment by pdrastil** [comment]
Hi @lacarvalho91, have you considered doing something like this if you need to override just a single value?

```
helm install argocd argo/argo-cd -f my-values.yaml --set server.extraContainers[0].image.tag=v1
```

Your request sounds sane, however every single community chart I've seen is defining containers, volumes etc. as arrays because if you do some change inside you can break other things around so it's safer to force user to redefine these blocks. What do you think @mkilchhofer @jmeridth @yu-croco

**Comment by lacarvalho91** [comment]
@pdrastil we're using values files so i'm not sure that would work? 

what you're saying makes sense, but it does seem to be done for other things in this chart like [copyutil](https://github.com/argoproj/argo-helm/blob/332173bd77f47220f19b96d6f41f83ccd15a729f/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L308)

**Comment by pdrastil** [comment]
@lacarvalho91 - not really - copyutil init container is actually same argocd image set in `global.image`.

**Comment by lacarvalho91** [comment]
OK, i don't mean specifically the image. I just mean in general `copyutil` is an array element in `initContainers` that you can configure separately as a map. For example I could do:
```yaml
repoServer:
  copyutil:
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
```

**Comment by pdrastil** [comment]
This is kinda bad example, `repoServer.copyutil` is removed in current PR with refactoring. Reason is that total pod requests / limits are function of MAX(MAX(init_containers), SUM(containers)) and both containers are the same.

I might have different option that might not be breaking for everyone else - how about adding support for templates in init / extra containers like this?
```
extraStuff:
  image: extra-image
  tag: v1.0.0

repoServer:
  extraContainers
   - name: extra-stuff
      image: {{ .Values.extraStuff.image }}:{{ .Values.extraStuff.tag }} 
```

At that point you can override your custom section without touching the list for containers / volumes.
