### ISSUE TITLE
Argo Workflows chart >= 0.19.2 breaks SSO configuration

### ISSUE THREAD

**Issue by aaaaahaaaaa** [argoproj/argo-helm#1491]
### Describe the bug

Since `0.19.2`, the Helm chart of Argo Workflows seems broken when `sso` is enabled. The following error is raised:
```
[...]
Error: template: argo-workflows/templates/controller/workflow-controller-config-map.yaml:141:49: executing "argo-workflows/templates/controller/workflow-controller-config-map.yaml" at <.sessionExpiry.duration>: nil pointer evaluating interface {}.duration Use --debug flag to render out invalid YAML
```

It seems that the parsing of the `sessionExpiry` config has changed and it's now expecting a `duration` attribute, even though I'm not overriding the default value, and the documentation doesn't reflect that. Furthermore, AFAICT, I didn't see breaking changes announced there (I might have missed that).

Whether the value is missing or matching the previous format (`sessionExpiry: <value>`), the rendering error above is thrown. But if I specify a value trying to match this new format:
```
sessionExpiry:
  duration: 24h
```
Then the following error is thrown in the logs at runtime:
```
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field SSOConfig.sso.sessionExpiry of type string
```

### Related helm chart

argo-workflows

### Helm chart version

0.19.2

### To Reproduce

Argo Workflows is installed on the cluster with the following config:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.19.2
    helm:
      releaseName: argo-workflows
      values: |
        server:
          extraArgs:
            - --auth-mode=sso
          sso:
            issuer: https://accounts.google.com
            redirectUrl: https://example.com/oauth2/callback
            scopes:
              - openid
            clientId:
              name: oauth2-client-secret
              key: clientId
            clientSecret:
              name: oauth2-client-secret
              key: clientSecret
            rbac:
              enabled: true
[...]
```

### Expected behavior

SSO config should not break the chart

**Comment by aaaaahaaaaa** [comment]
@yu-croco I believe [this](https://github.com/argoproj/argo-helm/commit/fd0f2c92e18742e59f85cd51e7c5972a2448a063#diff-cec457098d9d42755fa547ad6016ce4901bc41f31553e4a1caf9526dbc577961R122-R153) might have introduced the regression.

**Comment by yu-croco** [comment]
Thank you for reporting!
It looks that the behavior is different, it works if Helm version is v3.10.0 or higher because Helm v3.10.0 uses go v1.18.

ref: https://tip.golang.org/doc/go1.18
> The and function no longer always evaluates all arguments; it stops evaluating arguments after the first argument that evaluates to false. Similarly, the or function now stops evaluating arguments after the first argument that evaluates to true. This makes a difference if any of the arguments is a function call.

I fix this for backward compatibility. 🙏

**Comment by rdavyd** [comment]
Just a quick workaround if anyone requires in values
```yaml
server:
 sso:
   sessionExpiry:
     duration: ""
```
