### ISSUE TITLE
Allow for securityContext to be configured on argocd-extensions container in server Pod

### ISSUE THREAD

**Issue by congiv-VG** [argoproj/argo-helm#1494]
### Related helm chart

argo-cd

### Describe the solution you'd like

It would be great if the container level securityContext could be configured in the same way as the other workloads in the chart. Something like:

```yaml
server:
  extensions:
    securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ "ALL" ]
```
