### ISSUE TITLE
Cannot delete argo workflows due to ArtifactGC

### ISSUE THREAD

**Issue by allemp** [argoproj/argo-helm#1498]
### Describe the bug

When ArtifactGC is set for as workflow defaults, you cannot delete workflows if they do not have any artifacts. This does not occur if you actually do have artifacts to GC.

### Related helm chart

argo-workflows

### Helm chart version

0.20.0

### To Reproduce

Submit the following workflow with ArtifactGC enabled as workflow default:

```yaml
# The following workflow executes a fan-in workflow
# 
# A   B
#  \ /
#   C
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-fanin-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        depends: "A && B"
        template: echo
        arguments:
          parameters: [{name: message, value: C}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
```

Then click delete workflow in the UI

### Expected behavior

I expect the workflow to be deleted within a minute or so after clicking delete in the UI.

### Additional context

I tested this on a cluster with argo workflows created from a helm chart using argocd and a cluter with argo workflows created directly from manifests in the argo workflows repo using argocd. This problem does not occur on the cluster created from manifests.

Deleting the artifactgc finalizer manually with kubectl helps with deleting the workflows.
