### ISSUE TITLE
Setting reconciliation timeout in configs.params does not work

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-helm#1503]
### Describe the bug

I upgraded the version of the Argo CD chart we are using to `5.5.6` and noticed in the README that it says to configure `configs.params."timeout.reconciliation"` for reconciliation timeout. This gets templated onto the [cmd params config map](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-configs/argocd-cmd-params-cm.yaml).

When deploying this version I noticed in the logs of the application controller that it was still using the default:
```json
{"level":"info","msg":"appResyncPeriod=3m0s, appHardResyncPeriod=0s","time":"2022-09-30T13:08:59Z"}
```
After looking at the pod I can see:
```yaml
    - name: ARGOCD_RECONCILIATION_TIMEOUT
      valueFrom:
        configMapKeyRef:
          key: timeout.reconciliation
          name: argocd-cm
          optional: true
```

So it seems that using `configs.params` to configure that is wrong.

### Related helm chart

argo-cd

### Helm chart version

5.5.6

### To Reproduce

- Configure `configs.params."timeout.reconciliation"` and install the chart.
- Check the first couple of log lines of the application controller
- You should it has not picked up that configuration and is using the default `appResyncPeriod=3m0s`

### Expected behavior

I expected `appResyncPeriod` to be set to what I configured in `configs.params."timeout.reconciliation"`
