### ISSUE TITLE
ArgoCD webhook ingress might be pointing to the wrong service

### ISSUE THREAD

**Issue by omerlh** [argoproj/argo-helm#1510]
### Describe the bug

I wanted to move Argo to run behind corporate VPN and not accessible to the internet, and keep only the webhook endpoint open so Github could reach it. 
The chart has 2 ingress sections - one under `server` and one under `applicationSet.webhook`. So I tried to enable both - the one under server to be internal and the one under applicationSet to be public, and I changed Github to send events to the new ingress - the one on applicationSet.
I can see that events are getting and has a valid response from Github UI, but that's all. The application is not automatically refreshed like it was before when I pointed Github to the regular ingress.
Is this expected? Am I missing something here? Or maybe misconfiguration?

### Related helm chart

argo-cd

### Helm chart version

4.10.0

### To Reproduce

The relevant part of my values file:

```
webhook:
      ingress:
        # -- Enable an ingress resource for Webhooks
        enabled: true
        # -- Additional ingress annotations
        annotations: 
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/group.name: shared
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/ssl-redirect: '443'
        # -- Additional ingress labels
        labels: {}
        # -- Defines which ingress controller will implement the resource
        ## Hostnames must be provided if Ingress is enabled.
        ## Secrets must be manually created in the namespace
        hosts:
          - <redacted>
          # - argocd-applicationset.example.com

        # -- List of ingress paths
        paths:
          - /api/webhook
        # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
        pathType: Prefix
```

Most of it come with the chart...

### Expected behavior

Application is automatically refreshed when a user is push to Github

**Comment by mubarak-j** [comment]
@yu-croco @pdrastil are you able to look into this issue? I'm using ngnix-ingress and when I enable applicationset webhook, github shows 502 bad gateway error

**Comment by pdrastil** [comment]
I will have to verify how this works after 2.5.0 release that is very close right now.

**Comment by pdrastil** [comment]
Have you seen this documentation? Webhook seems to work only with Git generator + you have to restart controller if you have some private secret.

Ref: https://argocd-applicationset.readthedocs.io/en/stable/Generators-Git/#webhook-configuration 

I've verified that path is correct:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-applicationset-controller
spec:
  rules:
    - http:
        paths:
          - path: /api/webhook
            pathType: Prefix
            backend:
              service:
                name: argocd-applicationset-controller
                port:
                  name: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller
spec:
  ports:
  - name: webhook
    port: 7000
    targetPort: webhook
  selector:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/instance: argocd
---
# Simplified content for readability
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
      app.kubernetes.io/instance: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-applicationset-controller
        app.kubernetes.io/instance: argocd
    spec:
      containers:
        - name: applicationset-controller
          image: quay.io/argoproj/argocd:v2.4.15
          imagePullPolicy: IfNotPresent
          command: [entrypoint.sh, argocd-applicationset-controller]
          ports:
            - name: webhook
              containerPort: 7000
              protocol: TCP
```
