### ISSUE TITLE
Add application resourceTrackingMethod

### ISSUE THREAD

**Issue by clementblaise** [argoproj/argo-helm#1519]
### Is your feature request related to a problem?

In order for Crossplane to sync correctly composed resource the tracking method needs to be set to annotation as outline [here](https://github.com/crossplane/crossplane/blob/master/docs/guides/argo-cd-crossplane.md)

This required that the Chart expose a parameter to template the following resource accordingly :
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
kind: ConfigMap
```

### Related helm chart

argo-cd

### Describe the solution you'd like

Add `application.resourceTrackingMethod` to `configs`
