### ISSUE TITLE
Add as a Secret the OIDC clientSecret

### ISSUE THREAD

**Issue by JJotah** [argoproj/argo-helm#1541]
### Is your feature request related to a problem?

I want to add the feature to use secret for clientSecret in oidc.config instead hardcoding the secret in the values.yaml

### Related helm chart

argo-cd

### Describe the solution you'd like

Create Secret to use that instead to pass the secret in values yaml file

### Describe alternatives you've considered

N/A

**Comment by pdrastil** [comment]
Update - after poking in the operator manual I've found this which is exactly what you wanted:

https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative

**Comment by JJotah** [comment]
Yeah but with that solution is without helm chart. I meant with helm chart

**Comment by pdrastil** [comment]
I'm not exactly sure what you mean by this. You either hardcore the secret in values or you provide it by different means. If you don't want to use plaintext in values for security, you might need another solution that injects the secret by other means like [external-secrets](https://external-secrets.io/v0.6.0/) operator or you have extra value file just for the secrets.

**Comment by toyamagu-2021** [comment]
I have been in a similar use case and completely agree with @pdrastil .
Is following procedure not enough for your use case?

1. In your `values.yaml`

	```yaml
	server:
	  config:
  	    url: "http://your_fqdn_for_argocd/"
  	 	oidc.config: |
          name: Auth0
          clientID: aabbccddeeff00112233
          # Reference key in argocd-secret
          clientSecret: $your-secret.auth0.clientSecret
	```

2. Deploy `your-secret`. 
	- Adding to @pdrastil `suggestion`, I used [SecretProviderClass](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html). And mount it on `argocd-server`.

**Comment by JJotah** [comment]
Hi @toyamagu-2021 
When you meant $your-secret.auth0.clientSecret is a secret under kubernetes named your-secret with key auth0? and the clientSecret field for what? 
Sorry if I missunderstood something
thanks in advance

**Comment by pdrastil** [comment]
@JJotah  From the link I've posted `Syntax: $<k8s_secret_name>:<a_key_in_that_k8s_secret>` so:

```yaml
server:
  config:
    url: "http://your_fqdn_for_argocd/"
    oidc.config: |
      name: Auth0
      clientID: aabbccddeeff00112233
      # Reference key in argocd-secret
      clientSecret: $another-secret:oidc.auth0.clientSecret
```

coresponds to:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: another-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  ...
  # Store client secret like below.
  # Ensure the secret is base64 encoded
  oidc.auth0.clientSecret: <client-secret-base64-encoded>
```
