### ISSUE TITLE
[argo-workflows] Missing RBAC to list *v1.ServiceAccount

### ISSUE THREAD

**Issue by clementlecorre** [argoproj/argo-helm#1572]
### Describe the bug

With a clean install I have RBAC error on my argo src

```
E1024 12:14:44.339841       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.ServiceAccount: failed to list *v1.ServiceAccount: serviceaccounts is forbidden: User "system:serviceaccount:my-namespace:argo-server" cannot list resource "serviceaccounts" in API group "" at the cluster scope
```

### Related helm chart

argo-workflows

### Helm chart version

0.20.3

### To Reproduce

install argo-workflows chart

### Expected behavior

n/a

**Comment by yu-croco** [comment]
Hi @clementlecorre , will you please tell me the values.yaml  that you encountered this issue? 🙋

**Comment by clementlecorre** [comment]
hi @yu-croco 
It's work with this fix : https://github.com/argoproj/argo-helm/pull/1586

```
  sso:
    rbac:
      enabled: true
    issuer: https://accounts.google.com
    clientId:
      name: argo-sso-config
      key: client-id
    clientSecret:
      name: argo-sso-config
      key: client-secret
```

**Comment by yu-croco** [comment]
Thank you for your reply, @clementlecorre .
We encountered another error by https://github.com/argoproj/argo-helm/issues/1638, so we revert it on https://github.com/argoproj/argo-helm/pull/1641.
Then, let us discuss how to fix the original issue. 🙋 

ref: https://github.com/argoproj/argo-helm/issues/1638#issuecomment-1313444123

cc: @vladlosev

**Comment by yu-croco** [comment]
Hi @clementlecorre ,
it's just a confirmation, did you also set `server.extraArgs: ["--auth-mode=sso"]` ([here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L421-L427)) as well ?

**Comment by clementlecorre** [comment]
@yu-croco Yes

**Comment by vladlosev** [comment]
The error message aside, does the authentication work?

**Comment by yu-croco** [comment]
I checked with argo-chart version `0.20.8` .
I couldn't get error, so I am wondering what I missed... 😇 

values.yaml

```yaml
server:
  extraArgs:
    - --auth-mode=sso
  sso:
    rbac:
      enabled: true
    issuer: https://accounts.google.com
    clientId:
      name: argo-sso-config
      key: client-id
    clientSecret:
      name: argo-sso-config
      key: client-secret
```

log of argo-workflows-server
```
time="2022-11-14T12:01:20.883Z" level=info msg="not enabling pprof debug endpoints"
time="2022-11-14T12:01:20.884Z" level=info authModes="[sso]" baseHRef=/ managedNamespace= namespace=default secure=false ssoNamespace=default
time="2022-11-14T12:01:20.884Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo-workflows/tls/"
time="2022-11-14T12:01:21.470Z" level=info msg="SSO configuration" clientId="{{argo-sso-config} client-id <nil>}" insecureSkipVerify=false issuer="https://accounts.google.com" issuerAlias=DISABLED redirectUrl= scopes="[openid]"
time="2022-11-14T12:01:21.570Z" level=info msg="SSO enabled"
time="2022-11-14T12:01:21.572Z" level=info msg="Starting Argo Server" instanceID= version=v3.4.3
time="2022-11-14T12:01:21.572Z" level=info msg="Creating event controller" asyncDispatch=false operationQueueSize=16 workerCount=4
time="2022-11-14T12:01:21.574Z" level=info msg="GRPC Server Max Message Size, MaxGRPCMessageSize, is set" GRPC_MESSAGE_SIZE=104857600
time="2022-11-14T12:01:21.574Z" level=info msg="Argo Server started successfully on http://localhost:2746" url="http://localhost:2746"
time="2022-11-14T12:01:38.121Z" level=info duration="133.375µs" method=GET path=index.html size=473 status=0
time="2022-11-14T12:01:58.120Z" level=info duration="121.958µs" method=GET path=index.html size=473 status=0
time="2022-11-14T12:02:18.119Z" level=info duration="106.834µs" method=GET path=index.html size=473 status=0
time="2022-11-14T12:02:38.118Z" level=info duration="73.583µs" method=GET path=index.html size=473 status=0
time="2022-11-14T12:02:58.117Z" level=info duration="139.875µs" method=GET path=index.html size=473 status=0
time="2022-11-14T12:03:18.117Z" level=info duration="202.125µs" method=GET path=index.html size=473 status=0
```
