### ISSUE TITLE
Unable to load data: strconv.ParseInt: parsing "2.636044e+07": invalid syntax

### ISSUE THREAD

**Issue by gabriel-brotas** [argoproj/argo-helm#1576]
### Describe the bug

trying to create repo credentials with github app
```
configs:
  credentialTemplates:
    github-enterprise-creds:
      url: https://github.com/xxx
      githubAppID: xxx
      githubAppInstallationID: xxx
      githubAppPrivateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        .....
        -----END RSA PRIVATE KEY-----
```

Error:
```
{"error":"strconv.ParseInt: parsing \"...\": invalid syntax","code":2,"message":"strconv.ParseInt: parsing \"...\": invalid
```

Note: if I add this creds using the UI it works,  but from this helm chart it throws me this error

### Related helm chart

argo-cd

### Helm chart version

latest

### To Reproduce

add credentials template with github app method

### Expected behavior

Create repository template creds
