### ISSUE TITLE
ArgoCD upgrade fails

### ISSUE THREAD

**Issue by powellchristoph** [argoproj/argo-helm#1587]
### Describe the bug

Upgrade to latest release fails.
```
helm upgrade argocd argo/argo-cd -n argocd -f secrets://values.yaml --version 5.8.2

Error: UPGRADE FAILED: template: argo-cd/templates/argocd-server/clusterrole.yaml:30:9: executing "argo-cd/templates/argocd-server/clusterrole.yaml" at <eq (index (coalesce .Values.server.config .Values.configs.cm) "exec.enabled") "true">: error calling eq: incompatible types for comparison
```

It appears to not be properly referencing older values. https://github.com/argoproj/argo-helm/pull/1528

I fixed it by moving the relevant `Values.server.config` sections to `Values.configs`
```yaml
server:
  config:
    url: https://argocd.example.net
    oidc.config: <insert config>
  rbacConfig:
    policy.default: role:''
    scopes: "[email,groups]"
    policy.csv: |
      g, example-admin, role:admin
```
to
```yaml
configs:
  cm:
    url: https://argocd.example.net
    oidc.config: <insert config>
  rbac:
    policy.default: role:''
    scopes: "[email,groups]"
    policy.csv: |
      g, example-admin, role:admin 
```

### Related helm chart

argo-cd

### Helm chart version

5.8.2

### To Reproduce

1. Have existing helm install prior to 5.7.0 with the relevant `server.config` values set.
2. Execute a helm upgrade

### Expected behavior

Upgraded Argocd.

**Comment by pdrastil** [comment]
Hi @powellchristoph, I've tested with this values on 5.8.2 but I was able to reproduce only with `exec.enabled: true` that is not present in your sample. Notice that `true` is boolean and ConfigMap is using strings.

```
configs:
  cm:
    url: https://argocd.example.net
    oidc.config: ""
    exec.enabled: true
  rbac:
    policy.default: role:''
    scopes: "[email,groups]"
    policy.csv: |
      g, example-admin, role:admin
```
