### ISSUE TITLE
Error on Okta SSO OIDC Authentication, Invalid Redirect URL with Ingress enabled

### ISSUE THREAD

**Issue by gabriel-brotas** [argoproj/argo-helm#1593]
### Describe the bug

when I try to authenticate using Okta SSO OIDC I get this error:
```
Invalid redirect URL: the protocol and host (including port) must match and the path must be within allowed URLs if provided
````

### Related helm chart

argo-cd

### Helm chart version

5.8.2

### To Reproduce

values.yaml
```
server:
  extraArgs:
    - --insecure

  ingress:
    enabled: true
    hosts:
      - argocd.<domain>.com
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/subnets: "subnet-xxx,subnet-xxx,subnet-xxx"
      alb.ingress.kubernetes.io/scheme: "internal"
      alb.ingress.kubernetes.io/target-type: "ip"
      alb.ingress.kubernetes.io/certificate-arn: "xxx"
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
  config:
    url: https://argocd.<domain>.com
    oidc.config: |
      name: SSO
      issuer: "https://xxx.okta.com/oauth2/xxx"
      clientID: "xxx"
      clientSecret: xxx
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
    admin.enabled: "false"
```

### Expected behavior

authenticate successfully
