### ISSUE TITLE
clusterCredentials not creating the secrets properly

### ISSUE THREAD

**Issue by runderwoodcr14** [argoproj/argo-helm#1633]
### Describe the bug

Hello,

I've been trying to configure our clusters using declarative setup, unfortunately I've hit a snag, I've tried to search to see if someone else is having the same problem but unfortunately no much information, to be honest I'm not 100% sure this is a bug, however it does look like, basically I have argocd self managed and using argocd-vault plugin integrated with Google Cloud Secret Manager, so far all that works perfectly until the point when I try to configure my additional k8s clusters, I have baremetal and GKE clusters, argocd is running on a GKE cluster, its safe to say that adding the clusters using the argocd cli works fine, but my intention is to have everything in code to avoid any manual actions, that being said here is what I've done:
argocd installed using helm with chart version 5.13.5 and argocd v2.5.1

according to the helm chart values file:

```yaml
clusterCredentials:
 - name: mycluster
       server: https://mycluster.com
       labels: {}
       annotations: {}
       config:
         bearerToken: "<authentication token>"
         tlsClientConfig:
           insecure: false
           caData: "<base64 encoded certificate>"
```

Now if I use argocd-vault-plugin

```yaml
clusterCredentials:
 - name: mycluster
       server: <path:projects/4343434645e/secre/tservert#server>
       labels: {}
       annotations: {}
       config:
         bearerToken: "<path:projects/4343434645e/secret/bearertoken#bearertoken>"
         tlsClientConfig:
           insecure: false
           caData: "<paht/to/secret/caData#caData>"
```
When the configuration is applied the `server` secret gets rendered correctly when it creates the cluster secret, however the `bearerToken` and `caData` are not rendered, instead they get displayed as strings and the `<,>` escaped.

Then I tried then to add directly the values bypassing the usage of argocd-vault-plugin:

```yaml
clusterCredentials:
 - name: mycluster
       server: https://mycluster.com
       labels: {}
       annotations: {}
       config:
         bearerToken: "fskfdfjskdfsor549s85s89s854jk"
         tlsClientConfig:
           insecure: false
           caData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRRzN2eTFxWnNTSTVhRGcybjlPNy9sREFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNE9HVmhOMk01TlMwNFlXWmlMVFJpTm1FdE9XTXdaQzFsTURkaFpqSmpNMkV6T1dNdwpJQmNOTWpJd09ERXlNVEF5T0RVeVdoZ1BNakEx"
```
Now all the fields are rendered correctly, by this I mean when I describe the cluster secret I can see the same values I added in the declarative setup, however there is a problem, the caData which I input as base64 encoded as the helm chart recommends, is still in base64 and of course the cluster authentication fails with an error saying that it can't unmarshall the json data.

My other attempt is very similar to the previous one, just that this time I will pase the caData in clear text

```yaml
clusterCredentials:
 - name: mycluster
       server: https://mycluster.com
       labels: {}
       annotations: {}
       config:
         bearerToken: "fskfdfjskdfsor549s85s89s854jk"
         tlsClientConfig:
           insecure: false
           caData: | 
        -----BEGIN CERTIFICATE-----
        BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAFE4SdKsX9UsLy+Z0xuHSxhTd0jfn
        Iih5mtzb8CDNO5oTw4z0aMeAvpsUvjJ/XjgxnkiRACXh7K9hsG2r+ageRWGevyvx
        CaRXFbherV1kTnZw4Y9/pgZTYVWs9jlqFOppz5sStkfjsDQ5lmPJGDii/StENAz2
        XmtiPOgfG9Upb0GAJBCuKnrU9bIcT4L20gd2F4Y14ccyjlf8UiUi192IX6yM9OjT
        +TuXwZgqnTOq6piVgr+FTSa24qSvaXb5z/mJDLlk23npecTouLg83TNSn3R6fYQr
        d/Y9eXuUJ8U7/qTh2Ulz071AO9KzPOmleYPTx4Xty4xAtWi1QE5NHW9/Ajlv5OtO
        OnMNWIs7ssDJBsB7VFC8hcwf79jz7kC0xmQqDfw51Xhhk04kla+v+HZcFW2AO9so
        6ZdVHHQnIbJa7yQJKZ+hK49IOoBR6JgdB5kymoplLLiuqZSYTcwSBZ72FYTm3iAr
        jzvt1hxpxVDmXvRnkhRrIRhK4QgJL0jRmirBjDY+PYYd7bdRIjN7WNZLFsgplnS8
        9w6CwG32pRlm0c8kkiQ7FXA6BYCqOsDI8f1VGQv331OpR2Ck+FTv+L7DAmg6l37W
        +LB9LGh4OAp68ImTjqf6ioGKG0RBSznwME+r4nXtT1S/qLR6ASWUS4ViWRhbRlNK
        XWyb96wrUlv+E8I=
        -----BEGIN CERTIFICATE-----
```
Yet again, the secret is created with right values, by this I mean when I describe the cluster secret I can see the same values I added in the declarative setup, however yet again I get the error that it can't be unmarshalled.

I even tried to add the different values into the additional secrets for argocd-secret and then use them like this:
```yaml
clusterCredentials:
 - name: mycluster
       server: $server
       labels: {}
       annotations: {}
       config:
         bearerToken: $token
         tlsClientConfig:
           insecure: false
           caData: $caData
```

This also applies when trying to add GKE cluster:

```yaml
- name: playground
      server: <path:projects/4343434645e/secrets/server#server>
      labels: {}
      annotations: {}
      clusterResources: true
      config:
        execProviderConfig:
          command: "argocd-k8s-auth"
          args: "gcp"
          apiVersion: "client.authentication.k8s.io/v1beta1"
        tlsClientConfig:
          insecure: false
          caData: <path:projects/4343434645e/secrets/caData#caData>
```
The resulting cluster secret is not usable.

I've looked into the template `cluster-secrets.yaml` and I see that `stringData` is used instead of `Data` which allow to pass the values in plain text, yet still nothing seems to work

### Related helm chart

argo-cd

### Helm chart version

5.13.5

### To Reproduce

Using argocd-vault-plugin

```yaml
clusterCredentials:
 - name: mycluster
       server: <paht/to/secre/servert#server>
       labels: {}
       annotations: {}
       config:
         bearerToken: "<paht/to/secret/bearertoken#bearertoken>"
         tlsClientConfig:
           insecure: false
           caData: "<paht/to/secret/caData#caData>"
```
When the configuration is applied the `server` secret gets rendered correctly when it creates the cluster secret, however the `bearerToken` and `caData` are not rendered, instead they get displayed as strings and the `<,>` escaped.

Then I tried then to add directly the values bypassing the usage of argocd-vault-plugin:

```yaml
clusterCredentials:
 - name: mycluster
       server: https://mycluster.com
       labels: {}
       annotations: {}
       config:
         bearerToken: "fskfdfjskdfsor549s85s89s854jk"
         tlsClientConfig:
           insecure: false
           caData: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRRzN2eTFxWnNTSTVhRGcybjlPNy9sREFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNE9HVmhOMk01TlMwNFlXWmlMVFJpTm1FdE9XTXdaQzFsTURkaFpqSmpNMkV6T1dNdwpJQmNOTWpJd09ERXlNVEF5T0RVeVdoZ1BNakEx"
```
Now all the fields are rendered correctly, by this I mean when I describe the cluster secret I can see the same values I added in the declarative setup, however there is a problem, the caData which I input as base64 encoded as the helm chart recommends, is still in base64 and of course the cluster authentication fails with an error saying that it can't unmarshall the json data.

My other attempt is very similar to the previous one, just that this time I will pase the caData in clear text

```yaml
clusterCredentials:
 - name: mycluster
       server: https://mycluster.com
       labels: {}
       annotations: {}
       config:
         bearerToken: "fskfdfjskdfsor549s85s89s854jk"
         tlsClientConfig:
           insecure: false
           caData: | 
        -----BEGIN CERTIFICATE-----
        BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAFE4SdKsX9UsLy+Z0xuHSxhTd0jfn
        Iih5mtzb8CDNO5oTw4z0aMeAvpsUvjJ/XjgxnkiRACXh7K9hsG2r+ageRWGevyvx
        CaRXFbherV1kTnZw4Y9/pgZTYVWs9jlqFOppz5sStkfjsDQ5lmPJGDii/StENAz2
        XmtiPOgfG9Upb0GAJBCuKnrU9bIcT4L20gd2F4Y14ccyjlf8UiUi192IX6yM9OjT
        +TuXwZgqnTOq6piVgr+FTSa24qSvaXb5z/mJDLlk23npecTouLg83TNSn3R6fYQr
        d/Y9eXuUJ8U7/qTh2Ulz071AO9KzPOmleYPTx4Xty4xAtWi1QE5NHW9/Ajlv5OtO
        OnMNWIs7ssDJBsB7VFC8hcwf79jz7kC0xmQqDfw51Xhhk04kla+v+HZcFW2AO9so
        6ZdVHHQnIbJa7yQJKZ+hK49IOoBR6JgdB5kymoplLLiuqZSYTcwSBZ72FYTm3iAr
        jzvt1hxpxVDmXvRnkhRrIRhK4QgJL0jRmirBjDY+PYYd7bdRIjN7WNZLFsgplnS8
        9w6CwG32pRlm0c8kkiQ7FXA6BYCqOsDI8f1VGQv331OpR2Ck+FTv+L7DAmg6l37W
        +LB9LGh4OAp68ImTjqf6ioGKG0RBSznwME+r4nXtT1S/qLR6ASWUS4ViWRhbRlNK
        XWyb96wrUlv+E8I=
        -----BEGIN CERTIFICATE-----
```
Yet again, the secret is created with right values, by this I mean when I describe the cluster secret I can see the same values I added in the declarative setup, however yet again I get the error that it can't be unmarshalled.

I even tried to add the different values into the additional secrets for argocd-secret and then use them like this:
```yaml
clusterCredentials:
 - name: mycluster
       server: $server
       labels: {}
       annotations: {}
       config:
         bearerToken: $token
         tlsClientConfig:
           insecure: false
           caData: $caData
```
This also applies when trying to add GKE cluster:

```yaml
- name: playground
      server: <path:projects/4343434645e/secrets/server#server>
      labels: {}
      annotations: {}
      clusterResources: true
      config:
        execProviderConfig:
          command: "argocd-k8s-auth"
          args: "gcp"
          apiVersion: "client.authentication.k8s.io/v1beta1"
        tlsClientConfig:
          insecure: false
          caData: <path:projects/4343434645e/secrets/caData#caData>
```

### Expected behavior

The cluster secret that is rendered has the correct values to be able to add a cluster
