### ISSUE TITLE
clusterCredentials throws got "map", expected "string"

### ISSUE THREAD

**Issue by flickers** [argoproj/argo-helm#1635]
### Describe the bug

In version 5.13.7 the following values
```yaml
configs:
  clusterCredentials:
    - name: shared
      server: https://kubernetes.default.svc/
      labels: {}
      annotations: {}
      config:
        tlsClientConfig:
          insecure: false
```
gives this error
`error validating data: ValidationError(Secret.stringData.config): invalid type for io.k8s.api.core.v1.Secret.stringData: got "map", expected "string"`

helm template 5.13.6
```yaml
---
# Source: argocd/charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-shared
  labels:
    helm.sh/chart: argo-cd-5.13.6
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: shared
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
```

helm template for 5.13.7
```yaml
---
# Source: argocd/charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-shared
  labels:
    helm.sh/chart: argo-cd-5.13.7
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: shared
  server: https://kubernetes.default.svc
  config: {"tlsClientConfig":{"insecure":false}}
```

### Related helm chart

argo-cd

### Helm chart version

5.13.7

### To Reproduce

Use the values in the description and try to deploy. I would expect that not to work in 5.13.7 but should work in 5.13.6

### Expected behavior

Should not throw an error
