### ISSUE TITLE
argocd not decode base64 env

### ISSUE THREAD

**Issue by Iceforestik** [argoproj/argo-helm#1637]
### Describe the bug

I make an application in argon , synchronize it with gitlab , there is a help chart in the repository for deployment deployment
in the env deployment section
```yaml
env:
  - name: myenv
     value: {{ .Values.myenv |base64|quote}}
```

in values:
```yaml
myenv: ZWFzeQ==
```
when syncing in argocd, everything goes well, but in the deployment and pod in values illegal base64 data at input byte 0

if I do it through helm to the cluster, then the value is substituted with the correct one
```yaml
- name: myenv
  value: "easy"
```

why does this happen via argocd?

### Related helm chart

argo-cd

### Helm chart version

v2

### To Reproduce

deployment
```yaml
env:
  - name: myenv
     value: {{ .Values.myenv |base64|quote}}
```
in values:
```yaml
myenv: ZWFzeQ==
```

### Expected behavior

in deployment
```yaml
- name: myenv
  value: "easy"
```

in pod 
```yaml
- name: myenv
  value: "easy"
```

### Screenshots

![изображение](https://user-images.githubusercontent.com/47591939/201348288-0c8c9426-cf07-454c-ae3a-c02c86964332.png)

**Comment by pdrastil** [comment]
Hi, based on the snippet you've sent this cannot work as there is no base64 method defined in Helm. Try to render your chart locally with `b64enc` instead and verify the result via `helm template` as Argo CD is using exactly same approach to render the applied manifests.

**Comment by Iceforestik** [comment]
> Hi, based on the snippet you've sent this cannot work as there is no base64 method defined in Helm. Try to render your chart locally with `b64enc` instead and verify the result via `helm template` as Argo CD is using exactly same approach to render the applied manifests.

@pdrastil hello, if I install helm, there is no problem
here is the output of the deployment
```
# Source: chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dialogmanager
  labels:
    helm.sh/chart: chart-0.1.0
    app.kubernetes.io/name: chart
    app.kubernetes.io/instance: ch
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: chart
      app.kubernetes.io/instance: ch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chart
        app.kubernetes.io/instance: ch
    spec:
      imagePullSecrets:
        - name: regsecret
      securityContext:
        {}
      containers:
        - name: chart
          securityContext:
            {}
          image: "dialog:v2"
          imagePullPolicy: Always
          ports:
            - containerPort: 10500
              protocol: TCP
          env:
            - name: TtsText
              value: "easy\n"
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 250Mi
```
I run this command 
`helm install ch --dry-run --debug . -f values-sandbox5.yaml -n test`
