### ISSUE TITLE
Ingress is not working on eks cluster

### ISSUE THREAD

**Issue by s9r-5** [argoproj/argo-helm#1639]
### Describe the bug

I am using this value.yaml file for ingress and there is no error but still not working.

```
  redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
    servicePortHttp: 80
    servicePortHttps: 443
    servicePortHttpName: http
    servicePortHttpsName: https

  autoscaling:
    enabled: true
    minReplicas: 2

  ingress:
    enabled: ture
    annotations:
       kubernetes.io/ingress.class: alb
       alb.ingress.kubernetes.io/scheme: internet-facing
       alb.ingress.kubernetes.io/target-type: instance
       external-dns.alpha.kubernetes.io/hostname: "a.com"
       alb.ingress.kubernetes.io/backend-protocol: HTTPS
       alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    labels: {}
    ingressClassName: ""
    hosts:
      - a.com
    paths:
      - /
    pathType: Prefix
    extraPaths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 443
    tls:
      []
    https: false

  ingressGrpc:
    enabled: true
    isAWSALB: true
    annotations:
      alb.ingress.kubernetes.io/backend-protocol-version: GRPC
      alb.ingress.kubernetes.io/conditions.argogrpc: |
        [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
    labels: {}
    ingressClassName: ""

    awsALB:
      serviceType: NodePort
      backendProtocolVersion: HTTP2
    hosts:
       - a.com
    paths:
      - /
    pathType: Prefix
    extraPaths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo.cd-argocd-server-grpc
            port:
              number: 443
    tls:
      []
    https: false
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
```

### Related helm chart

argo-cd

### Helm chart version

4.9.14

### To Reproduce

1. Use this value.yaml 

### Expected behavior

Ingress should work.

### Screenshots

NA

### Additional context

NA
