### ISSUE TITLE
Invalid server role permissions

### ISSUE THREAD

**Issue by andrewm-aero** [argoproj/argo-helm#1650]
### Describe the bug

[The Argo Workflows server role](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/server/server-cluster-roles.yaml#L27 ) contains permissions to delete pods/log. As far as I can tell (from doing this via `kubectl delete --raw`), this isn't a valid action, and as such, isn't likely to be granted to non-admin users, making the chart undeployable in restricted environments. As well, the pods/exec needs to have create permissions to perform correctly (which can be seen by doing `kubectl exec -v10` to view the raw URIs), as seen [in the workflow role](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-role.yaml#L32).

### Related helm chart

argo-workflows

### Helm chart version

0.20.8

### To Reproduce

Install the chart as a non-priviliged user. For reference, my team discovered the issue when deploying into a Rancher v2.6.8 managed server using the built-in "Project Member" role. This produces the following error:

```
roles.rbac.authorization.k8s.io "argo-workflows-server" is forbidden: user "<REDACTED>" (groups=["<REDACTED>"]) is attempting to grant RBAC permissions not currently held: {APIGroups:[""], Resources:["pods/log"], Verbs:["delete"]}
```

### Expected behavior

The chart to install without permission errors

**Comment by yu-croco** [comment]
Upstream has the same permission, so I am not so sure which is correct... 🤔 

ref: https://github.com/argoproj/argo-workflows/blob/master/manifests/cluster-install/argo-server-rbac/argo-server-clusterole.yaml#L21-L31

```yaml
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - watch
      - delete
```

**Comment by vladlosev** [comment]
Yes, the chart has originally copied the permissions from the upstream, but those may have been written up without the consideration of permission validity. As far as I understand, the following combinations actually make sense and thus are likely to be granted to a user to further delegate:
```yaml
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
```
Having said that, does the server even use `pods/exec`? If not, we should not grant it.

**Comment by sdelrio** [comment]
> Yes, the chart has originally copied the permissions from the upstream, but those may have been written up without the consideration of permission validity. As far as I understand, the following combinations actually make sense and thus are likely to be granted to a user to further delegate:
> 
> ```yaml
> - apiGroups:
>   - ""
>   resources:
>   - pods
>   verbs:
>   - get
>   - list
>   - watch
>   - delete
> - apiGroups:
>   - ""
>   resources:
>   - pods/log
>   verbs:
>   - get
>   - list
>   - watch
> - apiGroups:
>   - ""
>   resources:
>   - pods/exec
>   verbs:
>   - create
> ```
> 
> Having said that, does the server even use `pods/exec`? If not, we should not grant it.

It uses the pod/exec it for the exec resource
https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#the-exec-resource

But it just need the 
```
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  ```
https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/#enabling-the-terminal

Maybe can add something like `{{ if configs.cm.exec.enabled }}` to add that `apiGroups` in the roles part of the argo-cd helm chat.
