### ISSUE TITLE
No Pods shown in UI

### ISSUE THREAD

**Issue by christianknell** [argoproj/argo-helm#1651]
### Describe the bug

After Upgrading from Chart version v3.35.4 (= ArgoCD v2.2.5) to v5.13.8 (= ArgoCD v2.5.2) no Pods are displayed in the UI anymore.

Pods also aren't listed in the "Kind" filter anymore.

I also can't find any relevant error or warning in the logs of any of the ArgoCD-Pods.

### Related helm chart

argo-cd

### Helm chart version

5.13.8

### To Reproduce

1. Install Helm Chart in v3.35.4
2. Upgrade installation using Helm Chart v5.13.8
3. Log into UI
4. Inspect any deployed Application

### Expected behavior

Pods are shown as usual in the UI.

### Screenshots

![grafik](https://user-images.githubusercontent.com/12433010/202407813-b3dc96a5-bd46-4900-9f32-46190a1a35e9.png)

### Values
```yaml
---
argo-cd:
  global:
    image:
      imagePullPolicy: Always
    logging:
      level: warn
    revisionHistoryLimit: 0
  server:
    config:
      admin.enabled: "true"
      exec.enabled: "true"
      oidc.config: |
        name: <OMITTED>
        issuer: <OMITTED>
        clientID: <OMITTED>
        clientSecret: <OMITTED>
        requestedIDTokenClaims: {"groups": {"essential": true}}
        requestedScopes: ["openid", "profile", "email"]
      server.rbac.log.enforce.enable: "true"
      url: https://<OMITTED>
    extensions:
      contents:
        - name: argo-rollouts
          url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.0/extension.tar
      enabled: true
    extraArgs:
      - "--insecure"
    rbacConfig:
      policy.csv: |
        g, admin, role:admin
      policy.default: role:readonly
      scopes: "[groups]"
```

The behaviour is the same using the admin Account or using a Admin-user of the OIDC-Provider.

### ClusterRoles
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd
    helm.sh/chart: argo-cd-5.13.8
  name: argocd-application-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd
    helm.sh/chart: argo-cd-5.13.8
  name: argocd-server
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - update
  - watch
```

**Comment by pdrastil** [comment]
Hi @christianknell, unfortunately I wasn't able to reproduce with your values (minus OIDC).

![upgrade](https://user-images.githubusercontent.com/19188617/202519918-50c0f3e9-c45c-456a-a3f5-a53cfc05a9de.png)

Any idea @crenshaw-dev why Server UI might not display pods?

**Comment by christianknell** [comment]
I just checked and initially i started with v3.26.3 of the Helm Chart. Maybe that helps.

**Comment by pdrastil** [comment]
Again same result where pods are visible in the UI

```sh
❯ helm install argocd argo/argo-cd --version 3.26.3 -f charts/argo-cd/test.yaml
❯ export YOUR_ARGOCD_RELEASENAME=argocd
❯ export YOUR_ARGOCD_NAMESPACE=argocd
❯ for crd in "applications.argoproj.io" "applicationsets.argoproj.io" "argocdextensions.argoproj.io" "appprojects.argoproj.io"; do
  kubectl label --overwrite crd $crd app.kubernetes.io/managed-by=Helm
  kubectl annotate --overwrite crd $crd meta.helm.sh/release-namespace="$YOUR_ARGOCD_NAMESPACE"
  kubectl annotate --overwrite crd $crd meta.helm.sh/release-name="$YOUR_ARGOCD_RELEASENAME"
done
❯ helm upgrade --install argocd argo/argo-cd --version 5.13.8 -f charts/argo-cd/test.yaml
❯ cat charts/argo-cd/test.yaml
   1   │ global:
   2   │   image:
   3   │     imagePullPolicy: Always
   4   │   logging:
   5   │     level: warn
   6   │   revisionHistoryLimit: 0
   7   │ server:
   8   │   config:
   9   │     admin.enabled: "true"
  10   │     exec.enabled: "true"
  11   │     server.rbac.log.enforce.enable: "true"
  12   │   extensions:
  13   │     contents:
  14   │       - name: argo-rollouts
  15   │         url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.0/extension.tar
  16   │     enabled: true
  17   │   extraArgs:
  18   │     - "--insecure"
  19   │   rbacConfig:
  20   │     policy.csv: |
  21   │       g, admin, role:admin
  22   │     policy.default: role:readonly
  23   │     scopes: "[groups]"
```

Only difference from your setup is omitted OIDC config + not using umbrella chart with `argo-cd` section.

**Comment by mikutas** [comment]
It's possibly intended behavior.
See https://github.com/argoproj/argo-cd/releases/tag/v2.3.2 and confirm your AppProject.

**Comment by christianknell** [comment]
Thanks @mikutas that solved the problem.

For future reference, add the following to the definition of your AppProject:

```yaml
---
spec:
  namespaceResourceWhitelist:
    - group: ""
      kind: Pod
    - group: apps
      kind: ReplicaSet
```
