### ISSUE TITLE
certificateSecret not being created

### ISSUE THREAD

**Issue by Whisper40** [argoproj/argo-helm#1660]
### Describe the bug

```
  certificateSecret:
    # -- Create argocd-server-tls secret
    enabled: true
    # -- Annotations to be added to argocd-server-tls secret
    annotations: {}
    # -- Labels to be added to argocd-server-tls secret
    labels: {}
    # -- Private Key of the certificate
    key: 'AAAAAAAAAAAAA'
    # -- Certificate data
    crt: 'BBBBBBBBBBBBBBB'
```

While using this : `helm template argo-cd --output-dir './yamls' --values ../inventories/os/dev/values.yaml`

The manifest is being generated : 
```
---
# Source: argo-cd/templates/argocd-configs/argocd-server-tls.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-tls
  labels:
    helm.sh/chart: argo-cd-5.13.6
    app.kubernetes.io/name: argocd-server-tls
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiB...."
  tls.key: "LS0tLS1CRUdJTiBQUnJsQ1JLekZrS2UgS2xpenJoMVNZWTljL2xHbHZsY3NDdzhHbHovT3V3MkVVVGh3ekRRdXJ6YjJCOUQwcC9Va1Fm..."

```

But while deploying with fluxcd 2, the secret is not being created ! 
All is created but not this secret, i don't understand why...

```
argo-cd-argocd-applicationset-controller-token-wxzbg   kubernetes.io/service-account-token   3      30h
argo-cd-argocd-repo-server-token-2g2fq                 kubernetes.io/service-account-token   3      30h
argo-cd-redis-ha-haproxy-token-4gdzh                   kubernetes.io/service-account-token   3      30h
argo-cd-redis-ha-token-ztcwg                           kubernetes.io/service-account-token   3      30h
argocd-application-controller-token-8klsv              kubernetes.io/service-account-token   3      30h
argocd-carioca-certs                                   Opaque                                2      29h
argocd-dex-server-token-clg2n                          kubernetes.io/service-account-token   3      30h
argocd-notifications-controller-token-88d85            kubernetes.io/service-account-token   3      30h
argocd-notifications-secret                            Opaque                                2      30h
argocd-secret                                          Opaque                                1      30h
argocd-server-token-vzsxz                              kubernetes.io/service-account-token   3      30h
ca-microsoft                                           Opaque                                1      30h
default-token-g8srt                                    kubernetes.io/service-account-token   3      32h
sh.helm.release.v1.argo-cd.v27                         helm.sh/release.v1                    1      4h31m
sh.helm.release.v1.argo-cd.v28                         helm.sh/release.v1                    1      4h29m
sh.helm.release.v1.argo-cd.v29                         helm.sh/release.v1                    1      4h27m
sh.helm.release.v1.argo-cd.v30                         helm.sh/release.v1                    1      4h26m
sh.helm.release.v1.argo-cd.v31                         helm.sh/release.v1                    1      4h20m
sh.helm.release.v1.argo-cd.v32                         helm.sh/release.v1                    1      4h15m
sh.helm.release.v1.argo-cd.v33                         helm.sh/release.v1                    1      4h12m
sh.helm.release.v1.argo-cd.v34                         helm.sh/release.v1                    1      4h5m
sh.helm.release.v1.argo-cd.v35                         helm.sh/release.v1                    1      31m
sh.helm.release.v1.argo-cd.v36                         helm.sh/release.v1                    1      21m
```

### Related helm chart

argo-cd

### Helm chart version

5.13.6

### To Reproduce

Use FluxCD 2 with certificateSecret enabled

### Expected behavior

It should create the secret

### Additional context

If i create the secret manually it works.. But i don't understand what's wrong to create the manifest with fluxcd.
