### ISSUE TITLE
Duplicate mount path /shared

### ISSUE THREAD

**Issue by gajus** [argoproj/argo-helm#1686]
### Describe the bug

Deploying `contra-argo-cd-argocd-dex-server` is failing with an error:

```
one or more objects failed to apply, reason: Deployment.apps "contra-argo-cd-argocd-dex-server" is invalid: [spec.template.spec.volumes[3].name: Duplicate value: "static-files", spec.template.spec.volumes[4].name: Duplicate value: "dexconfig", spec.template.spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/shared": must be unique, spec.template.spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/tmp": must be unique]. Retrying attempt #5 at 6:30PM.
```

Looking at the generated files, the generated yaml looks like so:

```yaml
volumeMounts:
  - mountPath: /shared
    name: static-files
  - mountPath: /tmp
    name: dexconfig
  - mountPath: /tmp/oidc
    name: google-json
    readOnly: true
  - mountPath: /shared
    name: static-files
  - mountPath: /tmp
    name: dexconfig
  - mountPath: /tls
    name: argocd-dex-server-tls
```

### Related helm chart

argo-cd

### Helm chart version

5.16.1

### To Reproduce

Appears to be triggered by our DEX configuration, which is:

```yaml
dex.config: |
  connectors:
  - config:
      redirectURI: https://argo.contra.dev/api/dex/callback
      clientID: $contra-argo-cd:GOOGLE_CLIENT_ID
      clientSecret: $contra-argo-cd:GOOGLE_CLIENT_SECRET
      serviceAccountFilePath: /tmp/oidc/googleAuth.json
      adminEmail: gajus@contra.com
    type: google
    id: google
    name: Google
```

This happened after I updated `dex.config` and deleted `contra-argo-cd-argocd-dex-server` container (the intent was to force consume the new configuration, since it was not updating).

### Expected behavior

Expecting `contra-argo-cd-argocd-dex-server` to start without an error.

**Comment by gajus** [comment]
We also have this config:

```yaml
  dex:
    volumeMounts:
      - mountPath: /shared
        name: static-files
      - mountPath: /tmp
        name: dexconfig
      - mountPath: /tmp/oidc
        name: google-json
        readOnly: true
    volumes:
      - emptyDir: {}
        name: static-files
      - emptyDir: {}
        name: dexconfig
      - name: google-json
        secret:
          defaultMode: 420
          secretName: contra-argo-cd
```

which is taken from https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#openid-connect-using-dex

**Comment by gajus** [comment]
Removing `dex:` and `dex.config` from Helm entirely, and re-adding, fixed the problem.

Still feels like a bug, but there is a workaround.

**Comment by pdrastil** [comment]
@gajus Hi, it seems that you have redefinition in values.yaml as following mounts / volumes are defined inside Argo CD template for Dex:

```yml
volumeMounts:
  {{- with .Values.dex.volumeMounts }}
    {{- toYaml . | nindent 8 }}
  {{- end }}
  - name: static-files
    mountPath: /shared
  - name: dexconfig
    mountPath: /tmp
  - name: argocd-dex-server-tls
    mountPath: /tls

volumes:
- name: static-files
  emptyDir: {}
- name: dexconfig
  emptyDir: {}
- name: argocd-dex-server-tls
  secret:
    secretName: argocd-dex-server-tls
    optional: true
    items:
    - key: tls.crt
      path: tls.crt
    - key: tls.key
      path: tls.key
    - key: ca.crt
      path: ca.crt
{{- with .Values.dex.volumes }}
  {{- toYaml . | nindent 6 }}
{{- end }}
```
