### ISSUE TITLE
HA mode does not support private image registry

### ISSUE THREAD

**Issue by mpodolsk** [argoproj/argo-helm#1688]
### Describe the bug

I have requirement to use internal approved container registries for security reasons.
The helm chart has already "global.image.repository" etc 
however in the ha mode there are couple images that slip and there are no helm values that allow me to override them.

```yaml
      - name: redis-exporter
        image: "oliver006/redis_exporter:v1.43.0"
```
i think its coming from

```
dependencies:
  - name: redis-ha
    version: 4.22.3
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
```

### Related helm chart

other

### Helm chart version

5.13.9

### To Reproduce

try to use a private container registry with redis-ha enabled 

### Expected behavior

if i specify 
```
global:
  image:
    repository: xxx
```

in the values i would expect it to be used for all of the images
