### ISSUE TITLE
Helm chart creates Role and RoleBinding for workflows when workflow.serviceAccount.create is false

### ISSUE THREAD

**Issue by JoostDuisters** [argoproj/argo-helm#1689]
### Describe the bug

Hi Apologies if I'm missing something, it seems on the surface that the Argo-Workflows chart is doing something slightly un-intuitive wrt a ServiceAccount and corresponding Role/RoleBinding. More specifically the chart with default values creates a Role and a RoleBinding without the corresponding ServiceAccount that is mentioned in the RoleBinding.

It's due to the default values [here](https://github.com/argoproj/argo-helm/blob/34a33c967f83622b086de824b0e67c83360de791/charts/argo-workflows/values.yaml#L38-L53):
```
workflow:
  # -- Deprecated; use controller.workflowNamespaces instead.
  namespace:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Labels applied to created service account
    labels: {}
    # -- Annotations applied to created service account
    annotations: {}
    # -- Service account which is used to run workflows
    name: "argo-workflow"
  rbac:
    # -- Adds Role and RoleBinding for the above specified service account to be able to run workflows.
    # A Role and Rolebinding pair is also created for each namespace in controller.workflowNamespaces (see below)
    create: true
```

Running the template just like that creates a Role and a RoleBinding that looks as follows:
```
# Source: argo-workflows/templates/controller/workflow-rb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-workflow
  labels:
    helm.sh/chart: argo-workflows-0.22.0
    app.kubernetes.io/name: argo-workflows-workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-workflow
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: default
```
However the ServiceAccount named `argo-workflow` is never created.

I would say the sensible default for `workflow.rbac.create` here should be false as well. 

I suppose two further questions about the interplay between the two: is there ever a use case where you would only want to create the ServiceAccount or where you would only want to create the Role and RoleBinding (i.e. leave it to the user to create the rest manually)? 

If the answer to both questions is no I would remove the field `workflow.rbac.create` all together and just use `workflow.serviceAccount.create` as the switch for the creation of all three resources. 

If there is a use case for both scenarios, I would leave the values file as-is and just change the default value of `workflow.rbac.create`.

If there is a use case for only wanting the ServiceAccount but not the Role and RoleBinding I would nest the rbac settings under serviceAccount like this: `workflow.serviceAccount.rbac.create`

If there is a genuine usecase for having only the Role and RoleBinding then I would still make the default for `workflow.rbac.create` false. But also then the UX is a bit unintuitive because you would have to manually create a serviceAccount with the name specified in 'workflow.serviceAccount.name`.

### Related helm chart

argo-workflows

### Helm chart version

As far as I can tell it goes as far back as 0.17.0 but haven't done elaborate testing.

### To Reproduce

1. `helm repo add `
2. `helm template argo-workflows argo/argo-workflows`
3. Look for RoleBinding called `argo-workflows-workflow`
4. Look for ServiceAccount specified under subjects (called `argo-workflow`) by default
5. Look for corresponding resource spec for said ServiceAccount -> not there.

### Expected behavior

First: for the helm-chart to not create that Role and RoleBinding by default. It leads to weird/unexpected behavior especially because the Roles and RoleBindings are namespaced to the default namespace by default so installing it in any other namespace than default throws an error.

Second: Depending on the intended user-experience/interplay between the ServiceAccount and Role, I would change the way `workflow.rbac.create` and `workflow.serviceAccount.create` operate.

### Additional context

It refers to these three manifests:
https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-rb.yaml
https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-role.yaml
https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-sa.yaml
effectively the first if statement in each of those files.
