### ISSUE TITLE
[argocd-notifications] Add service manifest for argocd-notifications-controller deployment in the argocd helm charts

### ISSUE THREAD

**Issue by ChauhanKrunal** [argoproj/argo-helm#1723]
### Is your feature request related to a problem?

Include argocd-notifications-controller service manifest in the argocd helm charts.

I'm setting up Slack to send me notifications whenever my applications are synced and healthy. For that I installed the argocd with `helm chart v5.16.9` and that is when I ran into trouble when I used argocd-notifications for sending the slack notifications. My apps cannot communicate with the argocd-notifications-controller deployment even though it is installed with a helm chart. I require the service in order to communicate with the deployment of the argocd-notifications-controller. As far as I'm aware, service manifest for communicating with the argocd-notifications-controller deployment is not currently included in argocd helm charts. I need to manually construct an argocd-notifications-controller service manifest using the `selector: app.kubernetes.io/name: argocd-notifications-controller` with `port: 9001` and apply it to the argocd-notifications-controller deployment namespace in order to communicate with the argocd-notifications-controller deployment resource. Even in the values.yaml file for the argocd helm charts, this service is not there.

For Reference:
![argocd-helm-chart-v5 16 9](https://user-images.githubusercontent.com/86162969/208972959-76d265e5-1c06-4a3c-ac1d-0f5c76b7b116.png)

### Related helm chart

argo-cd

### Describe the solution you'd like

In argocd helm charts, add the argocd-notifications-controller-metrics service manifest in the chart templates. in order to communicate with the deployment of the argocd-notification-controller.

For Reference :
```
apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-controller-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-controller-metrics
spec:
  selector:
    app.kubernetes.io/name: argocd-notifications-controller
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
    targetPort: 9001
```
