### ISSUE TITLE
Cannot set server.service.loadBalancerIP

### ISSUE THREAD

**Issue by fmunteanu** [argoproj/argo-helm#1746]
### Describe the bug

I have a simple custom chart, where I'm trying to set few custom values. Everything works as expected, except `server.service.loadBalancerIP`.

### Related helm chart

argo-cd

### Helm chart version

5.16.13

### To Reproduce

./charts/argocd/Chart.yaml:

```yaml
apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 5.16.13
    repository: https://argoproj.github.io/argo-helm
```

./charts/argocd/values.yaml:

```yaml
nameOverride: ""
fullnameOverride: ""

argo-cd:
  applicationSet:
    replicaCount: 2
  dex:
    enabled: false
  fullnameOverride: argocd
  repoServer:
    replicas: 2
  server:
    replicas: 2
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    service:
      loadBalancerIP: 192.168.4.11
```

Running:

```shell
kubectl create namespace argocd
helm install argo-cd ./charts/argocd/ --namespace argocd
```

will produce:

```shell
# kubectl get svc -n argocd
NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
argocd-applicationset-controller   ClusterIP   10.43.132.234   <none>        7000/TCP         28s
argocd-repo-server                 ClusterIP   10.43.85.195    <none>        8081/TCP         28s
argocd-server                      ClusterIP   10.43.85.56     <none>        80/TCP,443/TCP   27s
argocd-redis                       ClusterIP   10.43.123.227   <none>        6379/TCP         27s
```

### Expected behavior

I have to manually patch the `spec`:

```shell
# kubectl patch service argocd-server -n argocd --patch \
    '{ "spec": { "type": "LoadBalancer", "loadBalancerIP": "192.168.4.11" } }'
```

Which produces the expected result:

```shell
# kubectl get svc -n argocd
NAME                               TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
argocd-applicationset-controller   ClusterIP      10.43.132.234   <none>         7000/TCP                     42m
argocd-repo-server                 ClusterIP      10.43.85.195    <none>         8081/TCP                     42m
argocd-redis                       ClusterIP      10.43.123.227   <none>         6379/TCP                     42m
argocd-server                      LoadBalancer   10.43.85.56     192.168.4.11   80:30579/TCP,443:32286/TCP   42m
```
