### ISSUE TITLE
Argo-CD: unable to specify project-scoped cluster project

### ISSUE THREAD

**Issue by lgiedrius** [argoproj/argo-helm#1753]
### Describe the bug

cluster-secret generated from configs.clusterCredentials does not include needed project key
This key is added by argocd CLI when created --project scoped cluster

Need to add to [templates/argocd-configs/cluster-secrets.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-configs/cluster-secrets.yaml#L23), below stringData:
```yaml
  {{- if .project }}
  project: {{ .project | quote }}
  {{- end }}
```

### Related helm chart

argo-cd

### Helm chart version

5.16.14

### To Reproduce

1. Install ArgoCD with project-scoped cluster via HELM:
```yaml
configs:
  clusterCredentials:
    - clusterResources: true
      project: test-project
      config:
        bearerToken: "token"
        tlsClientConfig:
          insecure: true
      name: test-cluster
      server: https://cluster.url.svc
```
2. Check secret for "project" key or via UI `Settings -> Projects -> test-project -> scoped-clusters`
3.  No project-scoped clusters seen

The missing part is project key in the secret

### Expected behavior

Project-scoped cluster correctly marked

### Additional context

`argocd cluster add --project` adds `project:` key to the secret
