### ISSUE TITLE
Argo-CD: `configs.params.server.insecure` not populating `argocd-cmd-params-cm` correctly

### ISSUE THREAD

**Issue by rhyswilliamsza** [argoproj/argo-helm#1780]
### Describe the bug

Setting:

```
configs:
    params:
        server:
            insecure: true
```

Results in the following `argocd-cmd-params-cm` data entry:

```
server: 'map[insecure:true]'
```

instead of

```
server.insecure: 'true'
```

### Related helm chart

argo-cd

### Helm chart version

5.17.4

### To Reproduce

1. Set `configs.params.server.insecure` to true.
2. Observe that `argocd-cmd-params-cm` has `server: <map>` set.

### Expected behavior

The resultant `argocd-cmd-params-cm` map should have `server.insecure: true` set, instead of a serialised sub-map under `server`.

**Comment by rhyswilliamsza** [comment]
> I think we should update our documentation and maybe add some more failure catching. The section config.params is a flat dictionary of `key: value`, while a key is eg `server.insecure`.
> 
> If you want to set this on CLI level, you need to escape the dot: `--set configs.params."server\.insecure"=true`
> 
> If you want to achieve the same behavior in a YAML-style values, then you need to use:
> 
> ```yaml
> configs:
>   params:
>     server.insecure: true
> ```

Ah, right! That makes sense. 

We rolled this chart out using a separate instance of `argo-cd`. We needed to escape the param key to get it to pick up correctly. Thanks for the help!

```
configs:
  params:
    "server.insecure": true
```

**Comment by pdrastil** [comment]
@mkilchhofer I've tried to improve this but I don't believe this has a simple solution as we are trying to bypass Helm strong typing. When user provides values as `--set configs.params.server.insecure=true` the .Values will contain following structure:

```yml
config:
  params:
     # default value
     server.insecure: false
     # user provided
     server:
       insecure: true
```

If you flatten such structure you get 2 duplicate keys with different values:
```yml
config:
  params:
     server.insecure: false
     server.insecure: true
```

So most reasonable would be to just update our documentation.
