### ISSUE TITLE
 kustomize.buildOptions 

### ISSUE THREAD

**Issue by Joishy** [argoproj/argo-helm#1817]
### Is your feature request related to a problem?

There is noway to set  kustomize.buildOptions when installing argocd through helm.

### Related helm chart

argo-cd

### Describe the solution you'd like

By default the argocd helm doesn't include  kustomize.buildOptions: --enable-helm which is needed when any helm related resources are to be be deployed through argocd.

**Comment by pdrastil** [comment]
Hi @Joishy these options are part of argocd-cm and can be configured via `configs.cm` section.

**Comment by nicl-dev** [comment]
Could you provide an example for this? I can't seem to find the correct field to enable helm in the `configs.cm` section.

**Comment by pdrastil** [comment]
Sure just provide the options described in upstream CM into `configs.cm` section

```yaml
configs:
  cm:
    # Build options/parameters to use with `kustomize build` (optional)
    kustomize.buildOptions: --load_restrictor none

    # Per-version build options and binary paths
    kustomize.path.v3.9.1: /custom-tools/kustomize_3_9
    kustomize.buildOptions.v3.9.1: --enable_kyaml true
```
