### ISSUE TITLE
[Suggestion] Cluster Declaration using pre-defined Sealed Secrets

### ISSUE THREAD

**Issue by kworkbee** [argoproj/argo-helm#1875]
### Is your feature request related to a problem?

To add cluster information into ArgoCD, we need to use CLI commands to add them.

```
argocd cluster add [cluster]
```

I suggest adding a feature so that predefined cluster information can be reflected at the time of installation through values.yaml.

### Related helm chart

argo-cd

### Describe the solution you'd like

Declarative clusters in values.yaml may look like below:

```yaml
clusters:
  secretName: "" # If uses Sealed Secrets, or etc,.
  [clusterName]:
    server: [serverAddress]
```
