### ISSUE TITLE
extraObjects does work with ApplicationSet in ArgoCd

### ISSUE THREAD

**Issue by oisin88** [argoproj/argo-helm#1882]
### Describe the bug

The value "extraObjects" does not work when the type is Argo "ApplicationSet".

If you you add the sample ApplicationSet from Argo Docs to values.yaml under extraObjects.

https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/

and run 

`helm template .`

it fails with:

`Error: template: argo-cd/templates/extra-manifests.yaml:3:3: executing "argo-cd/templates/extra-manifests.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "apiVersion: argoproj.io/v1alpha1\nkind: ApplicationSet\nmetadata:\n  name: guestbook\nspec:\n  generators:\n  - list:\n      elements:\n      - cluster: engineering-dev\n        url: https://1.2.3.4\n      - cluster: engineering-prod\n        url: https://2.4.6.8\n      - cluster: finance-preprod\n        url: https://9.8.7.6\n  template:\n    metadata:\n      name: '{{cluster}}-guestbook'\n    spec:\n      destination:\n        namespace: guestbook\n        server: '{{url}}'\n      project: default\n      source:\n        path: applicationset/examples/list-generator/guestbook/{{cluster}}\n        repoURL: https://github.com/argoproj/argo-cd.git\n        targetRevision: HEAD": parse error at (argo-cd/templates/extra-manifests.yaml:17): function "cluster" not defined
helm.go:84: [debug] template: argo-cd/templates/extra-manifests.yaml:3:3: executing "argo-cd/templates/extra-manifests.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "apiVersion: argoproj.io/v1alpha1\nkind: ApplicationSet\nmetadata:\n  name: guestbook\nspec:\n  generators:\n  - list:\n      elements:\n      - cluster: engineering-dev\n        url: https://1.2.3.4\n      - cluster: engineering-prod\n        url: https://2.4.6.8\n      - cluster: finance-preprod\n        url: https://9.8.7.6\n  template:\n    metadata:\n      name: '{{cluster}}-guestbook'\n    spec:\n      destination:\n        namespace: guestbook\n        server: '{{url}}'\n      project: default\n      source:\n        path: applicationset/examples/list-generator/guestbook/{{cluster}}\n        repoURL: https://github.com/argoproj/argo-cd.git\n        targetRevision: HEAD": parse error at (argo-cd/templates/extra-manifests.yaml:17): function "cluster" not defined
coder@oisin-devspace:~/mycode/argo-helm/charts/argo-cd$ helm template .
Error: template: argo-cd/templates/extra-manifests.yaml:3:3: executing "argo-cd/templates/extra-manifests.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "apiVersion: argoproj.io/v1alpha1\nkind: ApplicationSet\nmetadata:\n  name: guestbook\nspec:\n  generators:\n  - list:\n      elements:\n      - cluster: engineering-dev\n        url: https://1.2.3.4\n      - cluster: engineering-prod\n        url: https://2.4.6.8\n      - cluster: finance-preprod\n        url: https://9.8.7.6\n  template:\n    metadata:\n      name: '{{cluster}}-guestbook'\n    spec:\n      destination:\n        namespace: guestbook\n        server: '{{url}}'\n      project: default\n      source:\n        path: applicationset/examples/list-generator/guestbook/{{cluster}}\n        repoURL: https://github.com/argoproj/argo-cd.git\n        targetRevision: HEAD": parse error at (argo-cd/templates/extra-manifests.yaml:17): function "cluster" not defined`

It will render if you remove the curly bracers, but these will alomst always be in ApplicationSet.

### Related helm chart

argo-cd

### Helm chart version

5.24.0

### To Reproduce

add to values.yaml

```
extraObjects: 
- apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: guestbook
  spec:
    generators:
    - list:
        elements:
        - cluster: engineering-dev
          url: https://1.2.3.4
        - cluster: engineering-prod
          url: https://2.4.6.8
        - cluster: finance-preprod
          url: https://9.8.7.6
    template:
      metadata:
        name: '{{cluster}}-guestbook'
      spec:
        project: default
        source:
          repoURL: https://github.com/argoproj/argo-cd.git
          targetRevision: HEAD
          path: applicationset/examples/list-generator/guestbook/{{cluster}}
        destination:
          server: '{{url}}'
          namespace: guestbook
```
          
          
  run
  
  
  helm template. 

### Expected behavior

This field should support all helm and kubernetes manifests.   It should work with all Argo CRDs including application sets. 

### Additional context

I am trying to create a multi instance argo setup using your chart. thanks  it is great !

I want to use your chart for "master" and "worker" Argos. I would like the master Argo to create worker Argos using ApplicationSet. 

The only real difference between the Worker and master apps will be the apps they sync. So extraObjects would be ideal if it supported extraObjects. 

Thanks,
Oisin
