### ISSUE TITLE
emptyDir hardcoded

### ISSUE THREAD

**Issue by krikunovk** [argoproj/argo-helm#1885]
### Describe the bug

Hello!
I have nodes of a middle size in k8s and sometimes I’m out of disk space for the argo repo-server we have. I’ve tried to use pvc for ‘helm-working-dir’, but I found out that ‘helm-working-dir’, ‘tmp’, ‘plugins’ and ‘var-files’ are hardcoded with ‘emptyDir’ parameter into the Argo chart’s deployment template, so I haven’t found out the way to mount volume for the above-mentioned folders. 
**Expected behaviour:** after 'helm template' command I want to have in _deployment.yaml_:
```
    spec:
      volumes:
      - name: helm-working-dir
        persistentVolumeClaim:
          claimName: helm-working-dir
```
**Real behaviour:** in _deployment.yaml_ I've got both pvc and emptyDir parameters like this:
```
    spec:
      volumes:
      - name: helm-working-dir
        persistentVolumeClaim:
          claimName: helm-working-dir
      - name: helm-working-dir
        emptyDir: {}
```

### Related helm chart

argo-cd

### Helm chart version

5.16.9-5.24.0

### To Reproduce

- Add pvc parameters in _values.yaml_:
```
  repoServer:
    volumes:
      - name: helm-working-dir
        persistentVolumeClaim:
          claimName: helm-working-dir
```
- Run `'helm template .'` command
- Discover in _deployment.yaml_ file this:
```
    spec:
      volumes:
      - name: helm-working-dir
        persistentVolumeClaim:
          claimName: helm-working-dir
      - name: helm-working-dir
        emptyDir: {}
```

### Expected behavior

```
    spec:
      volumes:
      - name: helm-working-dir
        persistentVolumeClaim:
          claimName: helm-working-dir
```
