### ISSUE TITLE
Add support for using existing secrets as credential templates

### ISSUE THREAD

**Issue by barucoh** [argoproj/argo-helm#1895]
### Is your feature request related to a problem?

I'm deploying ArgoCD helm chart as part of a Terraform manifest and I want to declare my repository connections as part of it.
Thing is, to connect I need to configure the `configs.credentialTemplates.ssh-creds` object with the proper credentials.
According to the docs the secrets are being created for every credential template - https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L415

This means that in order to create the repo connection, I have to supply the secret itself as part of the chart's values, which if done through Terraform, may end up saved in the environment's state file.

In many cases, such secrets are created externally through a tool like ESO and are referenced where needed.

So is it possible to add support for reading from an existing secret instead of creating a secret based on actual credentials?

Same flow as in here - https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L181

### Related helm chart

argo-cd

### Describe the solution you'd like

Add support to receive existing secret names for credential templates instead of the secret credentials.

Like here - https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L181

**Comment by mkilchhofer** [comment]
The credentialTemplates can absolutely be created via an arbitrary solution. You only need to create a Secret with the label `argocd.argoproj.io/secret-type: repo-creds`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/argoproj
  password: my-password
  username: my-username
```

Ref:
- https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
