### ISSUE TITLE
Dex redirect to auth/callback not working

### ISSUE THREAD

**Issue by ausias-armesto** [argoproj/argo-helm#1897]
### Describe the bug

ArgoCD server does not redirect requests coming to the path `/auth/callback` with successful authentication and authorization to the home page of ArgoCD. After a successful login, I am redirected to the page `/auth/callback` where it shows my correct token and claim information but I'm not redirected to the home page.

<img width="570" alt="auth-callback" src="https://user-images.githubusercontent.com/29434949/224990291-d31a5458-b336-43b3-a150-6a768f0ab90c.png">

### Related helm chart

argo-cd

### Helm chart version

5.26.0

### To Reproduce

1. Access the login page
2. Login with the Github credentials
3. Wait until the `/auth/callback` page appears and then rewrite the browser url to `https://argocd.example.com`

### Expected behavior

I expect the argocd server to redirect from `/auth/callback` to the home page.

### Additional context

I'm using these values.yaml at the Helm chart:

````yaml
global:
  logging:
    level: debug
    format: json
configs:
  cm:
    create: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    admin.enabled: false
    url: "https://argocd.example.com"
    dex.config: |
      logger:
        level: debug
        format: json
      connectors:
      - id: github
        type: github
        name: GitHub
        redirectURI: "https://argocd.example.com/api/dex/callback"
        config:
          clientID: XXXXX
          clientSecret: XXXXXX
          orgs:
          - name: my-org-name
  cmp:
    create: true
  params:
    server.insecure: false
    server.dex.server: "https://argocd-dex-server.argocd.svc.cluster.cluster.local:5556"
    # server.dex.server.strict.tls: false
    dexserver.disable.tls: false
    redis.server: "argocd-redis.argocd.svc.cluster.cluster.local:6379"
  rbac:
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      p, role:org-admin, logs, get, *, allow
      p, role:org-admin, exec, create, */*, allow
      g, my-org-name:my-group-name, role:org-admin
    policy.default: "role:readonly"
  secret:
    argocdServerAdminPassword: "{{ argocd_admin_password }}"
server:
  ingress:
    enabled: true
    hosts: [ "argocd.example.com" ]
    ingressClassName: nginx
    https: true
    annotations:
      cert-manager.io/cluster-issuer: linode-issuer
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      # If you encounter a redirect loop or are getting a 307 response code
      # then you need to force the nginx ingress to connect to the backend using HTTPS.
      #
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls: 
      - hosts: 
          - "argocd.example.com"
        secretName: "argocd.example.com-tls"
  env:
    - name: ARGOCD_SSO_DEBUG
      value: "1"
dex:
  enabled: true
redis:
  enabled: true
````

On the other hand, I've created the corresponding Github OAuth App with this configuration:
- Homepage URL: https://argocd.example.com/
- Authorization callback URL: https://argocd.example.com/api/dex/callback

### Nginx Ingress controller logs
````
2157.90.129.92 - - [14/Mar/2023:11:50:30 +0000] "GET /auth/login?return_url=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fapplications HTTP/2.0" 303 262 "https://argocd.stage.hoprtech.net/login?return_url=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fapplications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 73 0.000 [argocd-argocd-server-443] [] 10.2.173.234:8080 262 0.000 303 2a94a92b7166bee51f4fae1b7735c3fb
157.90.129.92 - - [14/Mar/2023:11:50:30 +0000] "GET /api/dex/auth?client_id=argo-cd&redirect_uri=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=ZoMlvXMAKaYKotWmDaPAfdvv HTTP/2.0" 302 1504 "https://argocd.stage.hoprtech.net/login?return_url=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fapplications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 154 0.000 [argocd-argocd-server-443] [] 10.2.173.234:8080 1504 0.000 302 8709d641fb15516ab552c1e46375bd51
157.90.129.92 - - [14/Mar/2023:11:50:30 +0000] "GET /api/dex/auth/github?client_id=argo-cd&redirect_uri=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fauth%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=ZoMlvXMAKaYKotWmDaPAfdvv HTTP/2.0" 302 267 "https://argocd.stage.hoprtech.net/login?return_url=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fapplications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 159 0.000 [argocd-argocd-server-443] [] 10.2.173.234:8080 267 0.000 302 bdb99800e5c72ad0ba9e80d945e40236
157.90.129.92 - - [14/Mar/2023:11:50:31 +0000] "GET /api/dex/callback?code=ff49b75164fd80164584&state=hnuzirckpv37kkboucvzfscg6 HTTP/2.0" 303 127 "https://argocd.stage.hoprtech.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 82 0.876 [argocd-argocd-server-443] [] 10.2.173.234:8080 127 0.876 303 8639b19b083e31c2a14070f2f76b4615
157.90.129.92 - - [14/Mar/2023:11:50:31 +0000] "GET /api/dex/approval?req=hnuzirckpv37kkboucvzfscg6&hmac=8fd0flnUt8nSV8kN9QZ8ICg4tIKjVS9wPPCvjF4tftE HTTP/2.0" 303 140 "https://argocd.stage.hoprtech.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 92 0.000 [argocd-argocd-server-443] [] 10.2.173.234:8080 140 0.000 303 411b8e210dedfe4657705266b182c464
157.90.129.92 - - [14/Mar/2023:11:50:31 +0000] "GET /auth/callback?code=s7fr27af3oabszqk7gb77w6gb&state=ZoMlvXMAKaYKotWmDaPAfdvv HTTP/2.0" 200 1991 "https://argocd.stage.hoprtech.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 231 0.006 [argocd-argocd-server-443] [] 10.2.173.234:8080 1991 0.006 200 f1c27bacb9ab28112295b6c2e9880748
````

### ArgoCD server logs
````
{"level":"info","msg":"Performing authorization_code flow login: https://argocd.stage.hoprtech.net/api/dex/auth?client_id=argo-cd\u0026redirect_uri=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fauth%2Fcallback\u0026response_type=code\u0026scope=openid+profile+email+groups\u0026state=ZoMlvXMAKaYKotWmDaPAfdvv","time":"2023-03-14T11:50:30Z"}
{"level":"info","msg":"Callback: /auth/callback?code=s7fr27af3oabszqk7gb77w6gb\u0026state=ZoMlvXMAKaYKotWmDaPAfdvv","time":"2023-03-14T11:50:31Z"}
{"level":"info","msg":"POST /api/dex/token HTTP/1.1\r\nHost: argocd.stage.hoprtech.net\r\nAuthorization: Basic YXJnby1jZDp1M0VmamlZaG9leERVdlhZdHFxUzVvY1d3STR4cEJEeVpUeTJuTDdW\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\ncode=s7fr27af3oabszqk7gb77w6gb\u0026grant_type=authorization_code\u0026redirect_uri=https%3A%2F%2Fargocd.stage.hoprtech.net%2Fauth%2Fcallback","time":"2023-03-14T11:50:31Z"}
{"level":"info","msg":"HTTP/1.1 200 OK\r\nContent-Length: 1999\r\nCache-Control: no-store\r\nContent-Type: application/json\r\nDate: Tue, 14 Mar 2023 11:50:31 GMT\r\nPragma: no-cache\r\n\r\n{\"access_token\":\".......\"}","time":"2023-03-14T11:50:31Z"}
{"level":"info","msg":"Web login successful. Claims: {\"at_hash\":\"30KAjiyP1jcOAasIcHiETA\",\"aud\":\"argo-cd\",\"c_hash\":\"LI5D0quJi3wv7lYDagCl-Q\",\"email\":\"ausiasarmesto@gmail.com\",\"email_verified\":true,\"exp\":1678881031,\"groups\":[\".........\"],\"iat\":1678794631,\"iss\":\"https://argocd.stage.hoprtech.net/api/dex\",\"name\":\"ausias-armesto\",\"preferred_username\":\"ausias-armesto\",\"sub\":\"......\"}","time":"2023-03-14T11:50:31Z"}
````

### Dex server logs
````
{"level":"info","msg":"login successful: connector \"github\", username=\"ausias-armesto\", preferred_username=\"ausias-armesto\", email=\"ausiasarmesto@gmail.com\", groups=[\"....."]","time":"2023-03-14T11:50:31Z"}
````
