### ISSUE TITLE
argo-cd: server.service.annotations seems to be broken

### ISSUE THREAD

**Issue by 0Bu** [argoproj/argo-helm#1914]
### Describe the bug

By the values defined `server.service.annotations` are not present in the created server service.

### Related helm chart

argo-cd

### Helm chart version

5.27.0

### To Reproduce

`values.yaml`
```
server:
    service:
      annotations:
       metallb.universe.tf/address-pool: default
       metallb.universe.tf/loadBalancerIPs: 10.x.x.x
```

### Expected behavior

annotations are adopted
