### ISSUE TITLE
server.sso.rbac is applied regardless of enabled=true or enabled=false

### ISSUE THREAD

**Issue by gberche-orange** [argoproj/argo-helm#1916]
### Describe the bug

As a user
In order to install argo workflow
I need to trust the documentation and values.yaml documented fields

The values.yaml suggests the server.sso.rbac.enabled default value is true
https://github.com/argoproj/argo-helm/blob/2563d1e6f94e7102fb403bfa1ca6ece9ca39e3c3/charts/argo-workflows/values.yaml#L539-L556

The readme does not document the server.sso value
https://github.com/argoproj/argo-helm/blob/2563d1e6f94e7102fb403bfa1ca6ece9ca39e3c3/charts/argo-workflows/README.md?plain=1#L256-L256

But the template seems to instead only check on sso.server.rbac:

https://github.com/argoproj/argo-helm/blob/2563d1e6f94e7102fb403bfa1ca6ece9ca39e3c3/charts/argo-workflows/templates/server/server-cluster-roles.yaml#L54-L63

See related issue at https://github.com/argoproj/argo-helm/issues/1624#issuecomment-1311612643

### Related helm chart

argo-workflows

### Helm chart version

 0.22.14

### To Reproduce

Install the helm chart with 
* server.sso.rbac.enabled=true

### Expected behavior

values.yaml should reflect the code behavior

**Comment by yu-croco** [comment]
Hi @gberche-orange, thank you for raising issue.

I agree with it. 
In addition to fixing flags like adding `server.sso.enabled`, 
it would be better to remove comment out and declare the values so that attributes can be searched/edited easily by IDE. 🤔 

Here is an example.
```yaml
server:
  sso:
    # -- Create SSO configuration.
    ## SSO is activated by adding --auth-mode=sso to the server command line.
    enabled: false
    # The root URL of the OIDC identity provider.
    issuer: ""
    # Name of a secret and a key in it to retrieve the app OIDC client ID from.
    clientId:
      name: ""
      key: ""
    # Name of a secret and a key in it to retrieve the app OIDC client secret from.
    clientSecret:
      name: ""
      key: ""
    # The OIDC redirect URL. Should be in the form <argo-root-url>/oauth2/callback.
    redirectUrl: ""
    rbac:
      enabled: true
```

@stefansedich @paguos @vladlosev @yann-soubeyrand @jmeridth 
WDYT? 🤔
