### ISSUE TITLE
Add additional labels to all the crds?

### ISSUE THREAD

**Issue by trv-bmpage** [argoproj/argo-helm#1919]
### Is your feature request related to a problem?

In the current helm chart there is no way to add labels to the crds, can you provide a way to add labels?

### Related helm chart

argo-cd

### Describe the solution you'd like

```yaml
{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    {{- with .Values.crds.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
```
