### ISSUE TITLE
Argo-workflow should not install clusterworkflowtemplates when disabled

### ISSUE THREAD

**Issue by warren-dalmeida-ext** [argoproj/argo-helm#1925]
### Describe the bug

In order to install argo workflow in a single namespace with clusterworkflowtemplates disabled.
The customResourceDefinition _clusterworkflowtemplates.argoproj.io_ in that case should not be install as done for ClusterRole and ClusterRoleBinding.

> message: 'Helm install failed: rendered manifests contain a resource that already
      exists. Unable to continue with install: could not get information about the
      resource CustomResourceDefinition "clusterworkflowtemplates.argoproj.io" in
      namespace "": customresourcedefinitions.apiextensions.k8s.io "clusterworkflowtemplates.argoproj.io"
      is forbidden: User "system:serviceaccount" cannot get resource
      "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scop

### Related helm chart

argo-workflows

### Helm chart version

0.22.15

### To Reproduce

1.  With a namespace restricted user

  - Use default Helm installation procedure with the following values.
  ```yaml
  singleNamespace: true
  controller:
    clusterWorkflowTemplates:
      enabled: false
  server:
    clusterWorkflowTemplates:
      enabled: false
  ```
  - When trying to install you will see the mention message

2. With a cluster user
  - Use default Helm installation procedure with the following values.
  ```yaml
  singleNamespace: true
  controller:
    clusterWorkflowTemplates:
      enabled: false
  server:
    clusterWorkflowTemplates:
      enabled: false
  ```
  - You should see the CRD install (but we don't want that to happen)

### Expected behavior

The customResourceDefinition clusterworkflowtemplates.argoproj.io should not be install.
