### ISSUE TITLE
Argo image updater container security

### ISSUE THREAD

**Issue by Gianluca755** [argoproj/argo-helm#1941]
### Related helm chart

argocd-image-updater

### Describe the solution you'd like

Is it possible to add in the helm chart, the usual security stuff that is present in the other charts?
Like:
```
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
```

Thanks
