### ISSUE TITLE
ArgoWorkflow: unmatched serviceaccounts namespace & clusterrolebinding subject namespace

### ISSUE THREAD

**Issue by leewoobin789** [argoproj/argo-helm#1952]
### Describe the bug

After defining namespace of the helm chart, you have the following problem that the namespace of service accounts & configmaps (controller & server) are not explicitly set, but the subject of clusterrolebindings is configured to look for namespaced service account of ".Release.Namespace".

for instance:
***workflow-controller-crb.yaml***
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "argo-workflows.controller.fullname" . }}-cluster-template
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "argo-workflows.controller.fullname" . }}-cluster-template
subjects:
  - kind: ServiceAccount
    name: {{ template "argo-workflows.controllerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }} # namespace is configured
```

***workflow-controller-sa.yaml***
```
{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata: # Namespace will be automatically set on default
  name: {{ template "argo-workflows.controllerServiceAccountName" . }}
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
  {{- with .Values.controller.serviceAccount.labels  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml .| nindent 4 }}
  {{- end }}
{{- end }}
```

### Related helm chart

argo-workflows

### Helm chart version

0.23.0

### To Reproduce

deploy chart with namespace that is not default namespace.

### Expected behavior

namespace of belonging service accounts and configmaps must be made configurable with the ".Release.Namespace".
Also if singleNamespace is enabled, the additional roles should be explicitly namespaced.

**Comment by yu-croco** [comment]
> namespace of belonging service accounts and configmaps must be made configurable with the ".Release.Namespace".

I have the same stance as https://github.com/argoproj/argo-helm/pull/1937#issuecomment-1490126026 .
Helm Chart automatically injects namespace definition to all namespaced resources, so I think it's redundant to declare namespace. 🤔

**Comment by leewoobin789** [comment]
ok. just found out that the namespaced resources do not get any namespace assigned when I am using it with kustomize.
```
helmCharts:
  - name: argo-workflows
    includeCRDs: true
    releaseName: argo-workflow
    namespace: argoworkflow
    repo: https://argoproj.github.io/argo-helm
    version: 0.23.1
```

anyhow I support https://github.com/argoproj/argo-helm/pull/1937#issuecomment-1490126026 to be merged as you cannot rely on default setting of helm with namespaces resources.
