### ISSUE TITLE
Getting Logged Out From Argo-CD On Refresh

### ISSUE THREAD

**Issue by anthonyalayo** [argoproj/argo-helm#1971]
### Describe the bug

Hey there,

Thank you for the helm chart! It has made deploying argo much easier.

I have setup an umbrella chart with both cd and apps so that I can manage argo itself:
```
dependencies:
  - name: argo-cd
    version: 5.28.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 0.0.9
    repository: https://argoproj.github.io/argo-helm
```

In my values.yaml, I setup the argocd self management:
```
argocd-apps:
  applications:
    - name: argocd
      namespace: argocd
      project: default
      source:
        path: argo
        repoURL: https://github.com/myuser/myrepo
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

Every time I press refresh on the UI, even if nothing has changed with argocd itself, the UI logs me out with some error that my token expired.

### Related helm chart

argo-cd, argocd-apps

### Helm chart version

5.28.1 and 0.0.9

### To Reproduce

Make a helm chart with both argo-cd and argcd-apps, and specify argo-cd itself in the values.yaml:

```
dependencies:
  - name: argo-cd
    version: 5.28.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 0.0.9
    repository: https://argoproj.github.io/argo-helm
```

```
argocd-apps:
  applications:
    - name: argocd
      namespace: argocd
      project: default
      source:
        path: argo
        repoURL: https://github.com/myuser/myrepo
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```

After that, install the chart with helm, browse to the UI, and then hit refresh.

### Expected behavior

The argo UI doesn't kick you out / log you out if argo itself didn't change.

### Screenshots

![image](https://user-images.githubusercontent.com/17555572/232340093-fb92ce0b-6631-4d2b-a7fd-a8049e571cdc.png)
