### ISSUE TITLE
the field project in applicationset can't be templated

### ISSUE THREAD

**Issue by joelee2012** [argoproj/argo-helm#1978]
### Describe the bug

i try to create apps with list generator with following code:
```yaml
applicationsets:
  - name: backend-service
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    generators:
      - list:
          elements:
            - cluster: test
              name: spring-demo
              ns: spring-boot-demo
            - cluster: uat
              name: spring-demo
              ns: spring-boot-demo
    template:
      metadata:
        name: "{{name}}-{{cluster}}"
        finalizers:
          - resources-finalizer.argocd.argoproj.io
        labels: {}
      spec:
        project: "{{cluster}}"
       sources:
          - repoURL: https://helm-chart-repo/
            targetRevision: 1.0.16
            chart: backend-service
            helm:
              valueFiles:
                - $values/{{cluster}}/{{name}}.yaml

          - repoURL: https://helm-values-repo
            targetRevision: HEAD
            ref: values
        destination:
          name: "{{cluster}}"
          namespace: "{{ns}}"
        revisionHistoryLimit: 10
        syncPolicy:
          automated:
            prune: true
          retry:
            backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m0s
            limit: 5
          syncOptions:
            - CreateNamespace=true
        ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
              - /spec/replicas
        info:
          - name: url
            value: https://argoproj.github.io/
```

but it failed with error:
```
Error: Failed to render chart: exit status 1: Error: template: argocd-apps/templates/applicationsets.yaml:54:18: executing "argocd-apps/templates/applicationsets.yaml" at <tpl .project $>: error calling tpl: error during tpl function execution for "{{cluster}}": parse error at (argocd-apps/templates/applicationsets.yaml:1): function "cluster" not defined
```
if use this tip: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Template/#deploying-applicationset-resources-as-part-of-a-helm-chart,  another error happens:
```
Error: Failed to render chart: exit status 1: Error: YAML parse error on argocd-apps/templates/applicationsets.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"cluster":interface {}(nil)}
```

if change [line](https://github.com/argoproj/argo-helm/blob/main/charts/argocd-apps/templates/applicationsets.yaml#L54) to `project: {{ .project | squote }}`, everything is fine

May i know why does the project require template ? and how to fix this issue ?

### Related helm chart

argocd-apps

### Helm chart version

0.0.9

### To Reproduce

- use the above values to install argocd-apps 

### Expected behavior

the filed `project` can be templated
