### ISSUE TITLE
Specify oidc.keycloak.clientSecret securely

### ISSUE THREAD

**Issue by brsolomon-deloitte** [argoproj/argo-helm#1983]
### Is your feature request related to a problem?

There doesn't seem to be a way to specify [`oidc.keycloak.clientSecret`](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/#configuring-argocd-oidc) in a secure way as part of the Helm chart installation.

I see that you can specify it as part of [`.Values.configs.secret.extra`](https://github.com/argoproj/argo-helm/blob/00e585342a099fdc4435b816ba6b33b47424afbe/charts/argo-cd/templates/argocd-configs/argocd-secret.yaml#L45), but that requires passing the secret string as plaintext, which isn't ideal.

Other charts use the pattern of enabling the chart user to refer to an `existingSecret` containing this value.

### Related helm chart

argo-cd

### Describe the solution you'd like

Ability to specify `oidc.keycloak.clientSecret` securely.

**Comment by jdvgh** [comment]
Hi @brsolomon-deloitte,
can you try  in your values.yaml (i.e. for argocd):
```YAML
configs:
# ...
  cm:
    #...
    # OIDC configuration as an alternative to dex (optional).
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.example.com/realms/master
      clientID: $keycloak-oidc:client_id
      clientSecret: $keycloak-oidc:client_secret
      requestedScopes: ["openid", "profile", "email", "groups"]
```

With the secret:

```YAML
apiVersion: v1
data:
  client_id: Q0xJRU5USURfU0VDUkVUX1ZBTFVF
  client_secret: Q0xJRU5UX1NFQ1JFVF9WQUxVRQ==
immutable: false
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: keycloak-oidc
  namespace: argocd
type: Opaque
```
And these you can create i.e. via external secrets operator or something along the lines.
