### ISSUE TITLE
Argo-cd helm chart : Deployment strategy error during templating

### ISSUE THREAD

**Issue by IDerr** [argoproj/argo-helm#1984]
### Describe the bug

Hello,

During the installation of a new ArgoCD using helm, i encoutered this error
```
Error: template: argo-cd/templates/dex/deployment.yaml:16:11: executing "argo-cd/templates/dex/deployment.yaml" at <include "argo-cd.strategy" (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.dex.deploymentStrategy)>: error calling include: template: argo-cd/templates/_common.tpl:130:8: executing "argo-cd.strategy" at <eq $preset.type "Recreate">: error calling eq: incompatible types for comparison
```
Seems to have this error since PR #1918

Using the default values (Recreate) argo-cd can not be deployed on my side
After changing the global value to   
```
deploymentStrategy:
    type: RollingUpdate 
  ```
Argocd has been succesfully deployed 

### Related helm chart

argo-cd

### Helm chart version

5.29.1

### To Reproduce

Deploy argo-cd using the default value Recreate for Deployment strategy

### Expected behavior

Should be deploying with Recreate deployment strategy

**Comment by yu-croco** [comment]
Hi @IDerr ,
Do you use Helm Chart directly to install Argo CD? or use other tools like Terraform / Kustomize ?

There was a case that old version Terraform provider has problem, so I wonder this would help you https://github.com/argoproj/argo-helm/discussions/1973#discussioncomment-5709498 .

**Comment by IDerr** [comment]
Hello,
nope, only using the helm chart
```
global:
  podAnnotations:
    linkerd.io/inject: enabled
## Server
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: "nginx"
    hosts:
      - X
 
    # -- List of ingress paths
    paths:
      - /
    pathType: Prefix
    extraPaths:
      []
 
    # -- Ingress TLS configuration
    tls:
    - secretName: argocd-tls-certificate
      hosts:
        - X
    https: false
  config:
    url: https://X
    oidc.config: |
      name: Keycloak
      issuer: https://X/realms/master
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
```
