### ISSUE TITLE
workflow.rbac.create - Role created with unsufficient to run workflows

### ISSUE THREAD

**Issue by renzodf** [argoproj/argo-helm#2005]
### Describe the bug

Hello,

When creating the service account and role using the provided keys, it seems that the attached role doesn't have the correct right to execute workflows.

With the following values.yaml:
```
[...]
workflow:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Labels applied to created service account
    labels: {}
    # -- Annotations applied to created service account
    annotations:
      workflows.argoproj.io/rbac-rule: "'argo-users' in groups"
      workflows.argoproj.io/rbac-rule-precedence: "1"
    # -- Service account which is used to run workflows
    name: "argo-users"
  rbac:
    # -- Adds Role and RoleBinding for the above specified service account to be able to run workflows.
    # A Role and Rolebinding pair is also created for each namespace in controller.workflowNamespaces (see below)
    create: true
[...]
```

The ServiceAccount and RoleBinding are correctly created:
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows                                                          
subjects:                                                                                                               
- kind: ServiceAccount                                                                                                    
- name: argo-users 
```

However, the corresponding role doesn't have the right privileges to run workflows:

```
  name: argo-workflows
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets
  - workflowartifactgctasks
  verbs:
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtasksets/status
  - workflowartifactgctasks/status
  verbs:
  - patch
           
```

### Related helm chart

argo-workflows

### Helm chart version

0.25.1

### To Reproduce

1. Configure the helm chart with the following configuration:
```
[...]
workflow:
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Labels applied to created service account
    labels: {}
    # -- Annotations applied to created service account
    annotations:
      workflows.argoproj.io/rbac-rule: "'argo-users' in groups"
      workflows.argoproj.io/rbac-rule-precedence: "1"
    # -- Service account which is used to run workflows
    name: "argo-users"
  rbac:
    # -- Adds Role and RoleBinding for the above specified service account to be able to run workflows.
    # A Role and Rolebinding pair is also created for each namespace in controller.workflowNamespaces (see below)
    create: true
[...]
```

2. Install the chart

### Expected behavior

Created Role has sufficient privileges to run workflows as comment is the example values file suggest:
```
    # -- Adds Role and RoleBinding for the above specified service account to be able to run workflows.
    # A Role and Rolebinding pair is also created for each namespace in controller.workflowNamespaces (see below)
```

**Comment by yu-croco** [comment]
>However, the corresponding role doesn't have the right privileges to run workflows:

Hi @renzodf , thank you for opening issue.
Can you please give us the reason/logs why you think so?

**Comment by yu-croco** [comment]
Hi @renzodf , thank you for your info.

> I activated the SSO with RBAC and my user is assigned to the created service account as I can see in the logs of the argo-server as well as on the user info in the UI.
>
> But I'm not able to create a workflow with that user with the UI, I get the following error:



The ServiceAccount that is created with the [configure above](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L38-L53) is for running Workflow, not for associating with SSO rbac.
We are supposed to set the ServiceAccount like below. 🙋 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-whale
spec:
  entrypoint: whalesay
  serviceAccountName: workflow-sa # Set the SA here
  templates:
    - name: whalesay
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
```
