### ISSUE TITLE
Add application resourceTrackingMethod to Values.configs

### ISSUE THREAD

**Issue by fulcrum29** [argoproj/argo-helm#2034]
### Is your feature request related to a problem?

Currently there is no option to set resourceTrackingMethod in values file.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
kind: ConfigMap
```

### Related helm chart

argo-cd

### Describe the solution you'd like

Add _application.resourceTrackingMethod_ to _Values.configs.cm_

**Comment by yu-croco** [comment]
Hi @fulcrum29 you can apply with the following though it is not declared on values.yaml.

```yaml
configs:
  cm:
    application.resourceTrackingMethod: label # here
```
