### ISSUE TITLE
cmp configmap template

### ISSUE THREAD

**Issue by adlnc** [argoproj/argo-helm#2060]
### Describe the bug

Hi,
I noticed the current template creates as many files as plugins declared in the container's fs under /home/argocd/cmp-server/config, which in my case ended up with the following error:
```
time="2023-05-15T15:33:11Z" level=info msg="ArgoCD ConfigManagementPlugin Server is starting" built="2023-05-12T13:43:26Z" commit=cbee7e6011407ed2d1066c482db74e97e0cc6bdb version=v2.7.2+cbee7e6.dirty
time="2023-05-15T15:33:11Z" level=fatal msg="read /home/argocd/cmp-server/config/plugin.yaml: is a directory"
```
For example, having a vault and kustomize plugin creates a vault.yaml and kustomize.yaml.

I think the expected file at this path must be named plugin.yaml [as stated in the doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#register-the-plugin-sidecar).
> Make sure that plugin configuration file is present at /home/argocd/cmp-server/config/plugin.yaml. It can either be volume mapped via configmap or baked into image.

I feel like the expected file is a plugin.yaml with multiples ConfigManagementPlugin declared, which actually worked in my case. 
For a quick verification, replacing `{{ $cmp_plugin }}.yaml:` with `plugin.yaml:`
https://github.com/argoproj/argo-helm/blob/1a5ee8eb352579bd81dfc3a14ef03f6604ad0b1b/charts/argo-cd/templates/argocd-configs/argocd-cmp-cm.yaml#L17

It's also possible I just missed something out here.

Thanks for your help.

### Related helm chart

argo-cd

### Helm chart version

5.33.1

### To Reproduce

1. Helm install latest chart with latest argocd image.
2. Configure values: 
```
  configs:
    cmp:
      create: true
      plugins:
        kustomize:
          init:
            command: [sh, -c]
            args: 
              # - helm repo update
              - helm dependency build || true
          generate:
            command: [sh, -c]
            args:
              - |
                helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $ARGOCD_ENV_HELM_VALUES --post-renderer ./kustomization/kustomize.sh --api-versions $KUBE_API_VERSIONS
          discover:
            find:
              command: [sh, -c, find . -name kustomize.sh]
```
3. configure extra container for sidecar injection [as stated here](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#register-the-plugin-sidecar)
```
  repoServer:
    extraContainers:
      - name: cmp
        command: [/var/run/argocd/argocd-cmp-server]
        image: argoproj/argocd:v2.7.2
        securityContext:
          runAsUser: 999
          runAsNonRoot: 
        env:
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
            name: cmp-plugin
          - mountPath: /tmp
            name: cmp-tmp

    volumes:
      - name: cmp-plugin
        configMap:
          name: argocd-cmp-cm
      - name: cmp-tmp
        emptyDir: {}
```

### Expected behavior

Repo server should start with a argocd-cmp-server sidecar and load plugins.

### Additional context

I also can't use the init stage of my plugin because it fails while running helm dependency build: missing chart dependencies and helm repo update doesn't have helm repository configuration declared in argocd configmap, but that's a different problem :)
