### ISSUE TITLE
ConfigManagementPlugin executable not found in PATH

### ISSUE THREAD

**Issue by radirobi** [argoproj/argo-helm#2061]
### Describe the bug

Dear all,

I am using the argo-cd helm chart for my setup. I am trying to use the Argo CD Vault plugin. This plugin should be deployed as a ConfigManagementPlugin, and the plugin should be run in a sidecar container. The required binary is pulled down through the initContainer.

I have created all the customisations described [here](https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar), however when I try to create an Application, I can see the following by running `kubectl logs -f argo-cd-argocd-repo-server-11111-111111 -n argo-cd -c avp`:

`time="2023-05-17T07:38:06Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: exec: \"argocd-vault-plugin\\\"\": executable file not found in $PATH" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2023-05-17T07:38:06Z" grpc.time_ms=2.483 span.kind=server system=grpc`

What I do not understand is the following. When I enter into the sidecar by running `kubectl exec -ti argo-cd-argocd-repo-server-11111-111111 -n argo-cd -c avp -- bash` the executable is there:
```
argocd@argo-cd-argocd-repo-server-11111-11111:~$ argocd-vault-plugin version
argocd-vault-plugin v1.14.0 (98e3987befca45c9c2bdc2e915c37de7e5688b37) BuildDate: 2023-03-21T13:34:29Z
```

What am I doing wrong?  Please see the steps below and the `values.yaml` I have used to deploy my argo-cd setup.

### Related helm chart

argo-cd

### Helm chart version

5.33.3

### To Reproduce

1. Helm install chart 5.33.3 with the following values file. 
`values.yaml`:
```
global:
  image:
    tag: "v2.7.2"

configs:
  cmp:
    create: true
    plugins:
      avp:
        discover:
          find:
            command: 
              - sh
              - "-c"
              - "find . -name '*.yaml'"
        generate:
          command:
            - argocd-vault-plugin"
            - generate
            - "."

repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: cmp-plugin
      configMap:
        name: argocd-cmp-cm
  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/argocd-vault-plugin
      subPath: argocd-vault-plugin
  extraContainers:
    - name: avp
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v2.7.2
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
  initContainers:
    - name: download-tools
      image: alpine:3.8
      command: [sh, -c]
      env:
        - name: AVP_VERSION
          value: "1.14.0"
      args:
        - >-
          wget -O argocd-vault-plugin
          https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
```
2. Try to create an application with one of the following manifests. None of them working.
**Without defining plugin**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-demo
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: your-path
    repoURL: https://github.com/your/repo
    targetRevision: HEAD
```
**With defining plugin**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-demo-2
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    plugin:
      name: avp
    path: your-path
    repoURL: https://github.com/your/repo
    targetRevision: HEAD
```
3. See the error on the UI

### Expected behavior

Executable should be on the $PATH. 

### Screenshots
Plugin is visible on the UI. 
<img width="1380" alt="image" src="https://github.com/argoproj/argo-helm/assets/78905316/088f0f5e-6ea4-43a8-8060-e91de06d5bde">

**Comment by radirobi** [comment]
@crenshaw-dev @jkayani  I am tagging you guys here, based on my research you are experts on these kind of topics.

**Comment by adlnc** [comment]
Well I'm no expert, I can't easily replicate your setup but first thing that comes to my mind is that you use: `kubectl exec -ti argo-cd-argocd-repo-server-11111-111111 -n argo-cd -c avp -- bash` -> bash to test your command instead of sh. Or vice/versa, just so it's consistent.
While in your plugin declaration you only have command and no args: 
```
configs:
  cmp:
    create: true
    plugins:
      avp:
        discover:
          find:
            command: 
              - sh
              - "-c"
              - "find . -name '*.yaml'"
        generate:
          command:
            - argocd-vault-plugin"
            - generate
            - "."
```
I think it's a better practice and easier to understand, to use this kind of syntax with command and args, for example:
```
configs:
  cmp:
    create: true
    plugins:
      avp:
        discover:
          find:
            command: [sh, -c]
            args:
              - "find . -name '*.yaml'"
        generate:
          command: [sh, -c]
          args:
            - argocd-vault-plugin generate .
```
But it's just a guess, worth giving a try ? Hope this helps.
