### ISSUE TITLE
securitycontext can not be overridden

### ISSUE THREAD

**Issue by hsmade** [argoproj/argo-helm#2071]
### Describe the bug

Due to a (very long standing) [bug](https://github.com/helm/helm/issues/9027) in Helm, one can't remove a value  in a map in the values file.
Now because the values.yaml for argo-cd has this:
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L701
```yaml
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
```

and the template [argocd-server/deployment.yaml](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/deployment.yaml#L337) has:
```yaml
        securityContext:
          {{- toYaml .Values.server.containerSecurityContext | nindent 10 }}
```
It is impossible to override the security context.
This used to have an `enabled` property that was checked on in the template. Would it be possible to bring that back?

### Related helm chart

argo-cd

### Helm chart version

5.34.1

### To Reproduce

What ever value you specify (`{}` or `null`), where (on `containerSecurityContext` or anything below), it's not possible to remove the defaults.

### Expected behavior

Being able to disable the seccompProfile
