### ISSUE TITLE
error calling tpl: error during tpl function execution: function "workflow" not defined

### ISSUE THREAD

**Issue by chazapp** [argoproj/argo-helm#2073]
### Describe the bug

I'm trying to upgrade my Argo-Workflows chart from `0.25.1` to `0.28.0`.

When running `helmfile diff` to diff the currently installed chart with the updated one, i'm facing this error: 

```
STDERR:
  Error: Failed to render chart: exit status 1:  
  Error: template: <redacted>/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml:63:15: executing "<redacted>/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml"  
  at <tpl (toYaml .) $>:  
 error calling tpl: error during tpl function execution for "bucket: redacted-argo-workflows\nkeyFormat: '{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}'":   
    parse error at (<redacted>/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml:2): function "workflow" not defined
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```   
  
I'm using the available in examples of `values.yaml` key format for GCS backed artifacts registry:  
```
  artifactRepository:
    archiveLogs: true
    gcs:
      bucket: <redacted>-argo-workflows
      keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
```  
  
This is the way it's documented in the [Chart's values.yaml - L712](https://github.com/argoproj/argo-helm/blob/cd4c291e47f0e9c1184fb05e79d9f3b742195c5c/charts/argo-workflows/values.yaml#LL712C5-L712C14)   
  
  
I think [this commit](https://github.com/argoproj/argo-helm/commit/f6d44750b8ecf25e272b22dd78950e3ad43e0ffd) changed the way this configuration was templated,  

From before:  
```
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L63
gcs: {{- toYaml . | nindent 8 }}
```
to after:  

```
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L63
 gcs: {{- tpl (toYaml .) $ | nindent 8 }}
```

I think helm is trying to template my artifact's keynames `"{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"` where this was supposed to be handled by ArgoWorkflows upload code.  
  
Can we revert this templating option or provide a work-around ?

Thanks,

### Related helm chart

argo-workflows

### Helm chart version

\>0.26.6

### To Reproduce

Try to render the `gcs` artifact registry default option in `helm` templates with these values:

```
  artifactRepository:
    gcs:
      bucket: <redacted>-argo-workflows
      keyFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
```

### Expected behavior

The `keyFormat` variable should not be rendered by Helm's template but by ArgoWorkflows instead.
