### ISSUE TITLE
[argo-workflows] Allow to configure different service account for executor

### ISSUE THREAD

**Issue by NikitaGandhi** [argoproj/argo-helm#2099]
### Is your feature request related to a problem?

To disable `automountServiceAccountToken` for main containers require executor to configure serviceaccount otherwise below error occurs.

```
executor.serviceAccountName must not be empty if automountServiceAccountToken is false
```

### Related helm chart

argo-workflows

### Describe the solution you'd like

add `executor.serviceAccountName` property and update a configmap.

### Additional context

This feature improves argo-workflows hardening as explained [here](https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce)

**Comment by yu-croco** [comment]
Hi @NikitaGandhi ,
Do you mean that you want to configure  `executor.serviceAccountName` like below ?
*The sample yaml is from [here](https://blog.argoproj.io/practical-argo-workflows-hardening-dd8429acc1ce).
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    spec:
      executor:
        serviceAccountName: workflow
...
```

If so, you can configure [here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L163), then this will be rendered [here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L126-L128).
