### ISSUE TITLE
Argo Workflows - Controller links not encoded correctly

### ISSUE THREAD

**Issue by dhpollack** [argoproj/argo-helm#2114]
### Describe the bug

I am trying to add additional links to argo workflows using this [Links feature](https://argoproj.github.io/argo-workflows/links/).  Simple links appear correctly, but links with a placeholder variable such as `${metadata.name}` do not get interpreted and instead show up as the literal "${metadata.name}", which results in a broken link.  I am using argo workflows 3.4.2.  Admittedly, this could also be an issue with argo workflows itself as it does seem like the link gets sent to argo workflows as a urlencoded link.  I am not sure if this is a simple sample issue or an actual bug.

### Related helm chart

argo-workflows

### Helm chart version

0.20.5

### To Reproduce

```
controller:
  links:
    - name: Example Link
      scope: workflow
      url: http://example.com/${metadata.name}
```

### Expected behavior

In argo workflows the link above would replace ${metadata.name} with the actual name rather than literally going to "${metadata.name}"
