### ISSUE TITLE
[argo-workflows] default values.yaml generates unnecessary `artifactRepository` section in `argo-workflows-workflow-controller-configmap`

### ISSUE THREAD

**Issue by toyamagu-2021** [argoproj/argo-helm#2132]
## Problem

- `argo-workflows-workflow-controller-configmap` with default helm value contains following unnecessary section:

```yaml
data:
  config: |
    artifactRepository:
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-workflows-minio
        secretKeySecret:
          key: secretkey
          name: argo-workflows-minio
        bucket:
        endpoint:
        insecure:
```

### Related helm chart

argo-workflows

### Helm chart version

0.29.3(latest)

### To Reproduce

Template with default value.yaml in latest version.

### Expected behavior

Above section should not be appeared.

### Screenshots

N/A

### Additional context

The problem appears after v0.26.0 which deletes `useDefaultArtifactRepo` bool option.
- https://github.com/argoproj/argo-helm/pull/2002 

I think deleting the option is reasonable, but should not create the unnecessary section by default values.
