### ISSUE TITLE
Argo Workflows SSO: section is not copied in the workflow-controller-configmap

### ISSUE THREAD

**Issue by vitalyrychkov** [argoproj/argo-helm#2136]
### Describe the bug

Starting with some recent Chart version (at least 0.29.3) the SSO: section is not copied from the values.yaml to the workflow-controller-configmap. I was using SSO since long time (at least with Argo Workflows 3.1) and parameters were always copied to the  workflow-controller-configmap.

After installing the chart (0.30.0) as in the test case below , the configmap "argo-helm-argo-workflows-workflow-controller-configmap" contains only this:
```
data:
  config: |
    nodeEvents:
      enabled: true
```
The chart 0.28.0 was working properly.
With the chart 0.29.3 the configmap was also always containing the "artifactRepository:" section, but this seems to be solved in 0.30.0. (#2132)

### Related helm chart

argo-workflows

### Helm chart version

0.29.3, 0.30.0

### To Reproduce

helm repo update
helm -n argo upgrade --install -f .\values.argo-dev-debug.yaml argo-helm argo/argo-workflows

# Values file used:
``` 
images:
  # -- Common tag for Argo Workflows images. Defaults to `.Chart.AppVersion`.
  tag: "v3.4.7"

workflow:
  serviceAccount:
    create: true # Specifies whether a service account should be created
    annotations: 
      workflows.argoproj.io/rbac-rule: "'argo-admin' in groups"
      workflows.argoproj.io/rbac-rule-precedence: "1"    
    name: "argo-workflow" # Service account which is used to run workflows
  rbac:
    # -- Adds Role and RoleBinding for the above specified service account to be able to run workflows.
    create: true

controller:
  rbac:
    # -- Adds Role and RoleBinding for the controller.
    create: true
    accessAllSecrets: true

  serviceAccount:
    # -- Create a service account for the controller
    create: true
    name: ""

  name: workflow-controller

  logging:
    # -- Set the logging level (one of: `debug`, `info`, `warn`, `error`)
    level: info
    globallevel: "0"

  # -- The number of controller pods to run
  replicas: 1

 
server:
  enabled: true
  baseHref: /
  rbac:
    # -- Adds Role and RoleBinding for the server.
    create: true
  serviceAccount:
    create: true
    name: ""
  # -- The number of server pods to run
  replicas: 1
  # -- Run the argo server in "secure" mode. Configure this value instead of `--secure` in extraArgs.
  secure: true
  extraArgs: 
    - --auth-mode=sso
  #  - --auth-mode=server
  #  - --auth-mode=client

  clusterWorkflowTemplates:
    # Create a ClusterRole and CRB for the server to access ClusterWorkflowTemplates.
    enabled: true
    # Give the server permissions to edit ClusterWorkflowTemplates.
    enableEditing: true
  sso:
  ## All the values are required. SSO is activated by adding --auth-mode=sso
    issuer: https://auth-host/auth/realms/acm
    redirectUrl: https://argo-host/oauth2/callback    
    ## Secrets must be manually created in the namespace:
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    ## Scopes requested from the SSO ID provider.  The 'groups' scope requests
    ## group membership information, which is usually used for authorization
    scopes: 
      - groups
      - email
    rbac:
      enabled: true
```

### Expected behavior

Expect to see this part in the configmap "argo-helm-argo-workflows-workflow-controller-configmap":

```
  sso:
  ## All the values are required. SSO is activated by adding --auth-mode=sso
    issuer: https://auth-host/auth/realms/acm
    redirectUrl: https://argo-host/oauth2/callback    
    ## Secrets must be manually created in the namespace:
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    ## Scopes requested from the SSO ID provider.  The 'groups' scope requests
    ## group membership information, which is usually used for authorization
    scopes: 
      - groups
      - email
    rbac:
      enabled: true
```
