### ISSUE TITLE
exec permissions do not work

### ISSUE THREAD

**Issue by m00nyONE** [argoproj/argo-helm#2158]
### Describe the bug

the lines:
https://github.com/argoproj/argo-helm/blob/5ec59e90fa8f03229b8c49fe6cf50fb79572b1bf/charts/argo-cd/templates/argocd-server/role.yaml#L48-L55
and
https://github.com/argoproj/argo-helm/blob/5ec59e90fa8f03229b8c49fe6cf50fb79572b1bf/charts/argo-cd/templates/argocd-server/clusterrole.yaml#L31C3-L38C13 do not trigger when configs.cm.exec.enabled = true is set

i checked it with my argoCD installation and it does not want to apply the changes. If i patch it manually and then do an app diff, it wants to delete it again.

### Related helm chart

argo-cd

### Helm chart version

5.36.10

### To Reproduce

1. install argocd
2. let it manage itself by creating an application
3. set configs.cm.exec.enabled: "true" in the helm chart 
4. do an app diff

x. also possible to see this behavior via `helm template`

### Expected behavior

configs.cm.exec.enabled: "true" should trigger line here:
https://github.com/argoproj/argo-helm/blob/5ec59e90fa8f03229b8c49fe6cf50fb79572b1bf/charts/argo-cd/templates/argocd-server/role.yaml#L48-L55
and here:
https://github.com/argoproj/argo-helm/blob/5ec59e90fa8f03229b8c49fe6cf50fb79572b1bf/charts/argo-cd/templates/argocd-server/clusterrole.yaml#L31C3-L38C13

### Screenshots

![image](https://github.com/argoproj/argo-helm/assets/23294566/03115f42-20ef-4557-8999-a0f5279ab420)

**Comment by m00nyONE** [comment]
fixed by adding exec.enabled = true to server.config

so it needs to be activated in two parts at the same time to work

**Comment by yu-croco** [comment]
> set configs.cm.exec.enabled: "true" in the helm chart
>fixed by adding exec.enabled = true to server.config
>so it needs to be activated in two parts at the same time to work

I wonder how to pass the value would be wrong for `configs.cm` one ?
It worked with below on my local. 👀 

values.yaml
```yaml
configs:
  cm:
    exec.enabled: true
```

helm template result

```yaml
# Source: argocd-samples/charts/argo-cd/templates/argocd-server/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-argocd-server
  labels:
    helm.sh/chart: argo-cd-5.36.10
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.7.6
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - delete
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - update
      - watch
---
# Source: argocd-samples/charts/argo-cd/templates/argocd-server/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-argocd-server
  namespace: "default"
  labels:
    helm.sh/chart: argo-cd-5.36.10
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.7.6
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
 ```
