### ISSUE TITLE
helmchart inconsistency: replica vs. replicaCount

### ISSUE THREAD

**Issue by Brice187** [argoproj/argo-helm#2193]
### Describe the bug

values.yaml has inconsistent usage of the replicacount
```
controller:
  name: application-controller
  replicas: 1
...
server:
  name: server
  replicas: 1
...
repoServer:
  name: repo-server
  replicas: 1
```

vs. 

```
applicationSet:
  enabled: true
  name: applicationset-controller
  replicaCount: 1
```

### Related helm chart

argo-cd

### Helm chart version

5.41.2

### To Reproduce

not misbehaving

### Expected behavior

consistency
