### ISSUE TITLE
feature: Argo CD: pull OIDC `clientID` and `issuer` from existing secret

### ISSUE THREAD

**Issue by jessebot** [argoproj/argo-helm#2199]
### Is your feature request related to a problem?

Right now we have to specify the oidc issuer and clientID directly in plain text via the values.yaml when applying the argo-cd helm chart. It's possible to specify a clientSecret in another secret, but not the clientID or issuer. This information is still considered private, so it'd be good to have this obscured.

### Related helm chart

argo-cd

### Describe the solution you'd like

I'd like to see the issuer and clientID also optionally called from an existing secret, in the same way that we can specify a clientSecret in another secret, example currently:
```yaml
    oidc.config: |
      name: provider
      issuer: https://my.domain/realms/coolrealm
      clientID: argocd
      clientSecret: $argocd-provider:oidc.provider.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
```

Proposed update:

```yaml
    oidc.config: |
      name: provider
      issuer: $argocd-provider:oidc.provider.issuer
      clientID: $argocd-provider:oidc.provider.clientID
      clientSecret: $argocd-provider:oidc.provider.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
```

### Describe alternatives you've considered

An alternative would be to just allow for an existingSecret for OIDC credentials where issuer, clientID, and clientSecret are all defined keys.

### Additional context

This would make everything a bit more secure and allow for more open sourcing of Argo CD configurations without exposing any useful information for attackers.

**Comment by mkilchhofer** [comment]
Did you test your proposed solution already? If its not yet implemented inside the code, you have to file a feature request in the upstream project repo over there:
https://github.com/argoproj/argo-cd

**Comment by jessebot** [comment]
@michaelvl I did not! Sorry about that. Should I close this one and open this in the other repo? :)

**Comment by mkilchhofer** [comment]
> Should I close this one (..)?

We can leave it open, it doesn't matter 👍

**Comment by jessebot** [comment]
I'm still interested in this, but I'm not sure where I'd need to implement it in the codebase.

**Comment by jmeridth** [comment]
Good news @jessebot: closing this as already-supported upstream, so there's nothing to implement in the chart.

Argo CD generalized secret substitution across the **entire** `oidc.config` map (the settings manager runs `ReplaceMapSecrets` over the parsed config; present since the 3.0 line, verified in current source). That means `clientID` and `issuer` accept the same `$<secret>:<key>` references that `clientSecret` always did, and since the chart passes `configs.cm."oidc.config"` through verbatim, it works today:

```yaml
configs:
  cm:
    oidc.config: |
      name: provider
      issuer: $argocd-oidc-provider:oidc.issuer
      clientID: $argocd-oidc-provider:oidc.clientID
      clientSecret: $argocd-oidc-provider:oidc.clientSecret
```

Two requirements to know about:

1. The referenced secret (`argocd-oidc-provider` above) must live in the Argo CD namespace and carry the label `app.kubernetes.io/part-of: argocd`, or the settings manager won't see it.
2. References without a secret name (`$oidc.issuer`) resolve against `argocd-secret`, per the [sensitive-data docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets).

If you try it on a current chart (appVersion 3.5.x) and something doesn't resolve, that'd be an upstream bug worth filing on argoproj/argo-cd with the specifics.
