### ISSUE TITLE
Artifact Repository for Azure Blob - values/examples not reflecting AzureArtifiactRepository blobNameFormat

### ISSUE THREAD

**Issue by jsong336** [argoproj/argo-helm#2200]
### Describe the bug

[Values](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L753 ) and examples in the document for using Azure Blob artifact repository does not reflect [AzureArtifiactRepository](AzureArtifiactRepository). Following the document/examples leads to following error in the argo workflow controller: `Failed to register watch for controller config map: error unmarshaling JSON: while decoding JSON: json: unknown field \"blob\ in the workflow controller`

```yaml
...
artifactRepository:
  azure:
    endpoint: https://myblob.blob.core.windows.net
    container: mycontainer
    blob: myblob # this should be blobNameFormat
    accountKeySecret:
      name: my-azure-storage-credentials
      key: my-account-access-key
```
This started happening after upgrading to 0.32.1 but was in several version behind before upgrading. I am assuming this might have started complaining after https://github.com/argoproj/argo-workflows/blob/master/docs/upgrading.md#feat-fail-on-invalid-config-8295

Passing in `blobNameFormat` instead of `blob` seems to work

### Related helm chart

argo-workflows

### Helm chart version

0.32.1

### To Reproduce

Install Argo Workflow with Chart 0.32.1 and use azure artifactRepository with `blob` key

```
artifactRepository:
  azure:
    endpoint: https://myblob.blob.core.windows.net
    container: mycontainer
    blob: myblob # this should be blobNameFormat
    accountKeySecret:
      name: my-azure-storage-credentials
      key: my-account-access-key
```

### Expected behavior

This is probably expected behavior but will requires update in document
