### ISSUE TITLE
Merging of global and individual component configs is not working properly

### ISSUE THREAD

**Issue by jmeridth** [argoproj/argo-helm#2202]
### Describe the bug

Merging of global component config options and individual component config options are not working.

### Related helm chart

argo-cd

### Helm chart version

v5.42.1 (latest as of filing this issue)

### To Reproduce

Update your `values.yaml` in an umbrella chart with the following:

```yaml
## Argo CD Specific Configurations
argo-cd:
  configs:
    params:
      repoServer.log.level: debug
```

results in `argocd-cmd-params-cm.yaml` config map having the following:

```yaml
apiVersion: v1
data:
  ...
  repoServer.log.level: info # default global
  repoServer.log.level: debug #individual component config
  ...
```

bug: `repoServer.log.level` is shown twice

### Expected behavior

Update your `values.yaml` in an umbrella chart with the following:

```yaml
## Argo CD Specific Configurations
argo-cd:
  configs:
    params:
      repoServer.log.level: debug
```

should result in `argocd-cmd-params-cm.yaml` config map having the following:

```yaml
apiVersion: v1
data:
  ...
  repoServer.log.level: debug # individual component config should overwrite global
  ...
```

`repoServer.log.level` should only be there once

### Additional context

Code that needs to be investigated is the [`argo-cd.config.params`](https://github.com/argoproj/argo-helm/blob/962342fe2acef6022ac5c1a3eb352b336308b3eb/charts/argo-cd/templates/_helpers.tpl#L206-L215) helper function.  It uses the [`argo-cd.config.params.presets`](https://github.com/argoproj/argo-helm/blob/962342fe2acef6022ac5c1a3eb352b336308b3eb/charts/argo-cd/templates/_helpers.tpl#L187C13-L187C42) helper function to get global config options and then merges with overwrite.
