### ISSUE TITLE
Updating CM and Secret via helm values does not roll the Deployments

### ISSUE THREAD

**Issue by domenicbove** [argoproj/argo-helm#2221]
### Describe the bug

When I update my helm values, and upgrade my helm deployment, the `argocd-secret` secret and `argocd-cm` config map get updated as I expect. But the argo application does not have hot reloading, so I've resorted to running
```
kubectl delete pods --all -n argocd
```
Which is probably overkill, but does work in getting the new properties read in. A better solution would be to add something like this: 
```
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
To the deployment(s) that should get "rolled" when the CM/secret get updated.

See docs here: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

### Related helm chart

argo-cd

### Helm chart version

5.42.1

### To Reproduce

1. Deploy with some values
2. Update the values and run `helm upgrade`
3. Notice new values populate the CM/secret, but running apps dont honor

### Expected behavior

Only the required pods should roll
