### ISSUE TITLE
ComparisonError: Namespace "XXXX" for Deployment "XXXXX" is not managed.

### ISSUE THREAD

**Issue by surya1150** [argoproj/argo-helm#2225]
### Describe the bug

Hi Team,

We are deploying ArgoCD through helm chart into AKS cluster and it got installed successfully and able to login through admin credentials.
We are not able deploy the application into any namespace and getting below error, 
**ComparisonError
Namespace "default" for Deployment "coffee" is not managed**

We are using cluster level ArgoCD,

Below is the values.yaml I am using,

```
server:
  autoscaling:
    enabled: true
    minReplicas: 2
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  ingress:
    enabled: true
    annotations: 
       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    hosts:
      - cluster-argocd.nginx.${cluster_name}.azuredns.internal.das
    https: true     
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
```

### Related helm chart

argo-cd

### Helm chart version

"5.43.4"

### To Reproduce

Deploy ArgoCD with provided values.yaml and version - 5.43.4

### Expected behavior

Application has to be deploy without any issue
