### ISSUE TITLE
Included redis-exporter doesn't support arm64 arch

### ISSUE THREAD

**Issue by svyatoslavmo** [argoproj/argo-helm#2233]
### Describe the bug

Included redis-exporter doesn't support arm64 arch. Also when changing image repo chart renders it incorrectly. 

`image: ‘map[repository:bitnami/redis-exporter tag:1.46.0]:1.45.0’`

### Related helm chart

argo-cd

### Helm chart version

5.43.7

### To Reproduce

Change repository to bitnami/redis-exporter
Change tag to 1.46.0

### Expected behavior

You'll be able to change the repo

**Comment by yu-croco** [comment]
Hi @svyatoslavmo 

> when changing image repo chart renders it incorrectly.

It worked with the following value.yaml. Did I miss something ? 🤔 
```yaml
# first apply
redis:
  exporter:
    enabled: true

# second apply
redis:
  exporter:
    enabled: true
    image:
      repository: bitnami/redis-exporter
      tag: 1.46.0
```

My Helm version is below.
```
$ helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

**Comment by pdrastil** [comment]
The version 1.46.0 >= should support ARM64
Ref: https://hub.docker.com/r/bitnami/redis-exporter/tags?page=1&name=1.46.0

**Comment by svyatoslavmo** [comment]
@pdrastil you can check using `docker mainfest inspect public.ecr.aws/bitnami/redis-exporter:1.53.0`. Images in public ECR support only amd64. 
But same repo in Dockerhub support it `docker manifest inspect bitnami/redis-exporter:1.53.0 ` 
`{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 429,
         "digest": "sha256:eebaa52f90059b85b89f1ee6b17b1f57fc66424a75e7523425803c460d87c074",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 429,
         "digest": "sha256:4ae361307534c4edc876b5547410711f730c42a9da5d8be540f7cc5efba835c0",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}`

**Comment by pdrastil** [comment]
@svyatoslavmo It actually supports ARM but I was able to get that image only via

```
docker pull bitnami/redis-exporter@sha256:4ae361307534c4edc876b5547410711f730c42a9da5d8be540f7cc5efba835c0
```

**Comment by svyatoslavmo** [comment]
@pdrastil pls check public.ecr.aws/bitnami/redis-exporter:1.53.0 using inspect. 
Version from ECR doesn't support ARM. But version from Dockerhub do.  Is there a reason why this chart uses ECR? 

All other components of ArgoCD can be launched on ARM out of the box.

**Comment by pdrastil** [comment]
Just checked that it's really caused by AWS ECR registry that do not support ARM. The reason is probably historic when DockerHub introduced limits on the pulls from anonymous users. This caused problems in public clouds.

**Comment by svyatoslavmo** [comment]
@yu-croco I'm applying using latest stable ArgoCD( 2.8.2), helm version is the same. Just checked local `helm template . ` and 1.45.0 is there. 

My values:

 ```
  redis-ha:
    enabled: true
    replicas: 3
    exporter:
      enabled: true
      image:
        repository: bitnami/redis-exporter
        tag: 1.46.0
```

**Comment by pdrastil** [comment]
@svyatoslavmo `redis-ha` subchart uses different structure - notice that `image` is actual repository

```yaml
redis-ha:
  # -- Enables the Redis HA subchart and disables the custom Redis single node deployment
  enabled: false
  ## Prometheus redis-exporter sidecar
  exporter:
    # -- Enable Prometheus redis-exporter sidecar
    enabled: false
    # -- Repository to use for the redis-exporter
    image: public.ecr.aws/bitnami/redis-exporter
    # -- Tag to use for the redis-exporter
    tag: 1.45.0
```
