### ISSUE TITLE
monitoring.coreos.com/v1 Settable in ServiceMonitor

### ISSUE THREAD

**Issue by oisin88** [argoproj/argo-helm#2243]
### Is your feature request related to a problem?

I am using helm template on this chart before applying it to cluster.  However when I helm template I do not get the ServiceMonitor resources because this check does not pass.   

https://github.com/argoproj/argo-helm/blob/224a227fa49b00fabfb535825c9bd5648f16a30a/charts/argo-cd/templates/argocd-server/servicemonitor.yaml#L1C1-L1C1

### Related helm chart

argo-cd

### Describe the solution you'd like

Should this be settable in apiVersionOverrides?

https://github.com/argoproj/argo-helm/blob/224a227fa49b00fabfb535825c9bd5648f16a30a/charts/argo-cd/values.yaml#L14C5-L14C5

Like for these other API version? 

https://github.com/argoproj/argo-helm/blob/224a227fa49b00fabfb535825c9bd5648f16a30a/charts/argo-cd/templates/_versions.tpl

The other options is to change the conditional or add a flag to render ServiceMonitor even it when this not true.

`(.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") `

### Describe alternatives you've considered

Open to other workarounds. I could fork the chart or add all these resources sperately 

### Additional context

The full work flow is.

helm tempalte --> kustomize --> apply

It is not a helm install so it cant hit the cluster for capabilities

**Comment by oisin88** [comment]
Too Any one seeing this. I used this to resolve:

`helm template . --values values.yaml --api-versions monitoring.coreos.com/v1`

Or if you are using KustomIze HelmChartInfaltor

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  includeCRDs: false
  version: 5.41.1
  namespace: argocd-test-dev
  releaseName: argocd-test-dev
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  apiVersions:
    - monitoring.coreos.com/v1
```
