### ISSUE TITLE
argo-cd: application-controlller `Watch failed` 

### ISSUE THREAD

**Issue by yellowhat** [argoproj/argo-helm#2257]
### Describe the bug

Hi,
I am using the `argo-cd` `5.45.1` helm chart.
I have noticed that every 12 hours the `application-controller` throws the following error: 

```
 retrywatcher.go:130] "Watch failed" err="context canceled"
```

According to [this](https://github.com/argoproj/argo-cd/discussions/8494) discussion some `watch` permission are missing.

Currently the role associated the `application-controller` service account has `watch` on `secrets` and `configmaps`:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cd-application-controller
  namespace: argo-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-cd-application-controller
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argo-cd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-application-controller
  namespace: argo-cd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
```

Is there something else missing?

Thanks

### Related helm chart

argo-cd

### Helm chart version

5.45.1

### To Reproduce

kubectl logs argo-cd-application-controller-0 | grep Watch

### Expected behavior

No error
