### ISSUE TITLE
Empty dict in redis-ha affinity results in Helm rendering warnings

### ISSUE THREAD

**Issue by steadyk** [argoproj/argo-helm#2265]
### Describe the bug

Hello all,

I've tried to render the Argo CD Helm chart and encounter this warnings:
  
```
helm template --release-name argocd -n argocd --include-crds --skip-tests . > /dev/null
coalesce.go:223: warning: destination for argo-cd.argo-cd.redis-ha.haproxy.affinity is a table. Ignoring non-table value ()
coalesce.go:175: warning: skipped value for argo-cd.argo-cd.redis-ha.affinity: Not a table.
coalesce.go:223: warning: destination for argo-cd.redis-ha.haproxy.affinity is a table. Ignoring non-table value ()
coalesce.go:175: warning: skipped value for argo-cd.redis-ha.affinity: Not a table.
```

Looks like this is related to the empty dict in the affinity settings of redis-ha:

```yaml
redis-ha:
  ## Enables a HA Proxy for better LoadBalancing / Sentinel Master support. Automatically proxies to Redis master.
  haproxy:
    # -- Assign custom [affinity] rules to the haproxy pods.
    affinity: {}
  # -- Assign custom [affinity] rules to the Redis pods.
  affinity: {}
```
  
After changing this to

```yaml
redis-ha:
  ## Enables a HA Proxy for better LoadBalancing / Sentinel Master support. Automatically proxies to Redis master.
  haproxy:
    # -- Assign custom [affinity] rules to the haproxy pods.
    affinity: |
  # -- Assign custom [affinity] rules to the Redis pods.
  affinity: |
```
  
based on the redis-ha sub-chart, the warnings are gone.

Does it makes sense to change it this way?

### Related helm chart

argo-cd

### Helm chart version

5.46.2

### To Reproduce

Render Helm chart e.g. with `helm template --release-name argocd -n argocd --include-crds --skip-tests . > /dev/null`

### Expected behavior

No Helm warnings on rendering.
