### ISSUE TITLE
Failed to query provider "https://argocd-url/api/dex": 502 Bad Gateway

### ISSUE THREAD

**Issue by farouqy** [argoproj/argo-helm#2267]
### Describe the bug

I'm using **argo-cd-5.46.0** helm chart
SSO not working using dex.

![image](https://github.com/argoproj/argo-helm/assets/57801581/5a9f12ad-7aa5-4c6d-adf0-ea597be356f4)

But logs from dex server shows that the authentication was successful :

`{"level":"info","msg":"login successful: connector \"saml\", username=\"my_email\", preferred_username=\"\", email=\"my_email\"..............}`

### Related helm chart

argo-cd

### Helm chart version

5.46.0

### To Reproduce

 ```
configs:
     url: https://my-argo-cd-url
    dex.config: |
        logger:
          level: debug
          format: json
        connectors:
        - type: saml
          id: saml
          name: saml
          config:
            entityIssuer: https://my-argo-cd-url/api/dex/callback
            ssoURL: https://my-login-url (e.g. https://login.microsoftonline.com/xxxxx/a/saml2)
            caData: |
               MY-BASE64-ENCODED-CERTIFICATE-DATA
            redirectURI: https://my-argo-cd-url/api/dex/callback
            usernameAttr: email
            emailAttr: email
            groupsAttr: Group
```

**RBAC** :

```
policy.default: role:readonly
policy.csv: |
   p, role:org-admin, applications, *, */*, allow
   p, role:org-admin, clusters, get, *, allow
   p, role:org-admin, repositories, get, *, allow
   p, role:org-admin, repositories, create, *, allow
   p, role:org-admin, repositories, update, *, allow
   p, role:org-admin, repositories, delete, *, allow
   g, "84ce98d1-e359-4f3b-85af-985b458de3c6", role:org-admin # (azure group assigned to role)
```

Ingress setup : 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
    host: argocd.example.com
  tls:
  - hosts:
    - argocd.example.com
    secretName: argocd-ingress-http
```

I have also disabled TLS : _**server.insecure: "true"**_
As shown in this documentation : https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-ssl-termination-at-ingress-controller

### Expected behavior

Login to argocd dashboard

### Screenshots

![image](https://github.com/argoproj/argo-helm/assets/57801581/5a9f12ad-7aa5-4c6d-adf0-ea597be356f4)
