### ISSUE TITLE
Add commented out helm value: configs.params.application.namespaces

### ISSUE THREAD

**Issue by domenicbove** [argoproj/argo-helm#2283]
### Is your feature request related to a problem?

It's not clear how to enable this feature thru helm: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/

It seems you can just add this to your values to update the `argocd-cmd-params` configmap:
```
configs:
  params:
    application.namespaces: ns1,ns2
```

### Related helm chart

argo-cd

### Describe the solution you'd like

I'd say just add a few documentation lines in the [values.yaml](https://github.com/argoproj/argo-helm/blob/03c1be1c6d92eae55a77b4d691dcdb470f8c68c9/charts/argo-cd/values.yaml#L216-L264)

Something along the lines of:
```
    # -- Namespaces of Applications, leave commented to limit to the namespace of the ArgoCD Deployment
    # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
    # application.namespaces: this
```

### Describe alternatives you've considered

Not sure, seems like it should be commented out to work with the default behavior

**Comment by pdrastil** [comment]
Hi I believe this is documented. You have reference link on top of the section to full upstream configuration.

```yaml
# Argo CD configuration parameters
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
params:
  create: true
```
