### ISSUE TITLE
error configuring Argo to use OpenID Connect

### ISSUE THREAD

**Issue by arturmon** [argoproj/argo-helm#2286]
### Describe the bug

https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/google/#configure-argo-to-use-openid-connect
if you use the documentation at this link and use secrets that are stored in vault, then the result will be the same as in the attachment. variables do not substitute values.

### Related helm chart

argo-cd

### Helm chart version

5.34.1

### To Reproduce

helmfile.yaml
```
repositories:
- name: argo-cd
  url: https://argoproj.github.io/argo-helm

---
environments:
  default:
    values:
      - argocd:
          clientID: ref+vault://kv/k8s/staging/infra/#KUBERNETES_ARGOCD_CLIEND_ID
          clientSecret: ref+vault://kv/k8s/staging/infra/#KUBERNETES_ARGOCD_CLIEND_SECRET
---
releases:
- name: argo-cd
  namespace: argo-cd
  chart: argo-cd/argo-cd
  version: 5.34.1
  installed: true
  values:
    - values.yaml
```

values.yaml
```
configs:
  cm: 
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: {{ .Values.argocd.clientID | fetchSecretValue }}
          clientSecret: {{ .Values.argocd.clientSecret | fetchSecretValue }}
        type: oidc
        id: google
        name: Google
```

result:
```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-cm
    namespace: "argo-cd"
    labels:
      helm.sh/chart: argo-cd-5.34.1
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/component: server
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: argocd
  data:
    admin.enabled: "true"
    application.instanceLabelKey: argocd.argoproj.io/instance
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: {{ .Values.argocd.clientID | fetchSecretValue }}
          clientSecret: {{ .Values.argocd.clientSecret | fetchSecretValue }}
        type: oidc
        id: google
        name: Google
    exec.enabled: "false"
```

### Expected behavior

```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-cm
    namespace: "argo-cd"
    labels:
      helm.sh/chart: argo-cd-5.34.1
      app.kubernetes.io/name: argocd-cm
      app.kubernetes.io/instance: argo-cd
      app.kubernetes.io/component: server
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: argocd
  data:
    admin.enabled: "true"
    application.instanceLabelKey: argocd.argoproj.io/instance
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: *****6frgk8gd.apps.googleusercontent.com
          clientSecret: ****bOkVlEbDlrR02pi6j
        type: oidc
        id: google
        name: Google
    exec.enabled: "false"
```

### Screenshots

![image](https://github.com/argoproj/argo-helm/assets/7686999/0dc37355-a211-44f7-b8df-676561cdaa71)

**Comment by yu-croco** [comment]
Hi @arturmon ,
the issue is related to Argo CD's  (or vault plugin's) feature, so I think you get more help in [upstream](https://github.com/argoproj/argo-cd).
*argo-helm handles plain Helm Chart, not specific feature of Argo CD/Workflows etc.

**Comment by arturmon** [comment]
The problem here is processing the chart, not the upstream. in **ConfigMap argocd-cm** there is a line **{{- include "argo-cd.config.cm" . | trim | nindent 2 }}** which calls **{{- define "argo-cd.config.cm" -}}** and there everything becomes immediately clear, there it is processed as “I see it and I insert it”, hence the problem that variables are not processed. how I see it

```
{{/*
Merge Argo Configuration with Preset Configuration
*/}}
{{- define "argo-cd.config.cm" -}}
{{- $config := (mergeOverwrite (deepCopy (omit .Values.configs.cm "create" "annotations")) (.Values.server.config | default dict))  -}}
{{- $preset := include "argo-cd.config.cm.presets" . | fromYaml | default dict -}}
{{- range $key, $value := mergeOverwrite $preset $config }}
{{- $fmted := $value | toString }}
{{- if not (eq $fmted "") }}
{{ $key }}: {{ $fmted | toYaml }}
{{- end }}
{{- end }}
{{- end -}}
```

**Comment by yu-croco** [comment]
Thank you for the info.
*I wasn't sure what the problem was at first time.

**Comment by mkilchhofer** [comment]
Are you sure that this should work? Sorry I never used helmfile but it somehow looks like the value is not evaluated correctly before passing it down to helm.

When I use helmfile like this, it works as expected:


```yaml
# helmfile.yaml
repositories:
- name: argo-cd
  url: https://argoproj.github.io/argo-helm

---
environments:
  default:
    values:
      - argocd:
          clientID: ref+vault://cubbyhole/argo-support?proto=http#/clientID
          clientSecret: ref+vault://cubbyhole/argo-support?proto=http#/clientSecret
---
releases:
- name: argo-cd
  namespace: argo-cd
  chart: argo-cd/argo-cd
  version: 5.34.1
  installed: true
  values:
    # - values.yaml
    - configs:
        cm: 
          dex.config: |
            connectors:
            - config:
                issuer: https://accounts.google.com
                clientID: {{ .Values.argocd.clientID | fetchSecretValue }}
                clientSecret: {{ .Values.argocd.clientSecret | fetchSecretValue }}
              type: oidc
              id: google
              name: Google

```

result:

```yaml
# ...
# Source: argo-cd/templates/argocd-configs/argocd-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: "argo-cd"
  labels:
    helm.sh/chart: argo-cd-5.34.1
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: myID
        clientSecret: mySecret
      type: oidc
      id: google
      name: Google
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
# ...
```

**Comment by mkilchhofer** [comment]
Ohhh and I found your issue. If you want to use templating inside your file called `values.yaml`, you need to rename it to end in `*.gotmpl` and also add this suffix inside helmfile.yaml:

```yaml
---
releases:
- name: argo-cd
  namespace: argo-cd
  chart: argo-cd/argo-cd
  version: 5.34.1
  installed: true
  values:
    # - values.yaml
    - values.yaml.gotmpl # <--- see here
```
