### ISSUE TITLE
Some chart values should be evaluated by tpl function 

### ISSUE THREAD

**Issue by bkomraz1** [argoproj/argo-helm#2305]
### Is your feature request related to a problem?

I want some chart values will be able to reference other value:

```
  configs:
    cm:
      url: "https://argocd{{.Values.global.dnsDomain}}"
      config.yaml:
        context:
          argocdUrl: "https://argocd{{.Values.global.dnsDomain}}"
      dex.config:
        connectors:
          - type: saml
            id: saml
            name: saml
            config:
              entityIssuer: "https://argocd{{.Values.global.dnsDomain}}/api/dex/callback"
  server:
     ingress:
       hosts:
         - "argocd{{ .Values.global.dnsDomain }}"
 ```             
  

### Related helm chart

argo-cd

### Describe the solution you'd like

Some values should be evaluated by "tpl" function

```
      host: {{ tpl $host $  }}
 ```
