### ISSUE TITLE
Service workflow-controller includes image digest in app.kubernetes.io/version label

### ISSUE THREAD

**Issue by nushemto** [argoproj/argo-helm#2335]
### Describe the bug

My values:
```yaml
# tried setting the images.tag but it didn't help
#images:
#  tag: v3.5.0
controller:
  serviceLabels:
    app.kubernetes.io/version: "v3.5.0". # this is a workaround, it creates an additional same-key label and sets the "v3.5.0" without the digest. Without this, the label's value appears with the digest.
    testing: "1234"
  image:
    registry: 1234.dkr.ecr.us-west-2.amazonaws.com
    repository: third-party/argoproj/workflow-controller
    tag: v3.5.0@sha256:dda36f7a872f463a68df04d72755c086eb193fa1645e1f099f1670dd5f99a277
  metricsConfig:
    enabled: true
server:
  image:
    registry: 1234.dkr.ecr.us-west-2.amazonaws.com
    repository: third-party/argoproj/argocli
    tag: v3.5.0@sha256:608b6d532b6a1ad4ae82b1e05ee844eb2f4fffe90a8524421f95e9355a7e4be1
  secure: true
  authMode: sso
```

When rendering the chart the result is that the label  `app.kubernetes.io/version` in `workflow-controller` is using controller.image.tag instead of the Chart app version.

I am not sure why, but only the workflow-controller Service is specifying that label in this way. See [here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/templates/controller/workflow-controller-service.yaml#L9)

### Related helm chart

argo-workflows

### Helm chart version

3.5.0

### To Reproduce

1. Create a custom values file with the values I've shared above.
2. Run `helm template -f custom-values.yaml .`
3. Search for the `kind: Service` created for the workflow-controller and check its `app.kubernetes.io/version` label.

### Expected behavior

Not to include the (full) image tag+digest as part of the label, only the Chart's App version, as is the case with all other resources.

### Screenshots

![Screenshot 2023-11-07 at 17 12 15](https://github.com/argoproj/argo-helm/assets/132905558/b1f5a561-ea45-4908-85f4-647c4766bb48)
