### ISSUE TITLE
[argo-workflows] installation fails when using argocd application resource

### ISSUE THREAD

**Issue by outductor** [argoproj/argo-helm#2393]
### Describe the bug

I get this error when trying to install Argo Workflows by using ArgoCD's Application resource, but this error doesn't give me much information and not sure what's going on or how to troubleshoot. I confirmed that `cluster-wide-apps` has permissions on `argo-workflows` namespace.
<img width="688" alt="image" src="https://github.com/argoproj/argo-helm/assets/137604477/dff6b2ff-32a0-4707-b612-7e0aa459cf3f">

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.40.1
    helm:
      releaseName: argo-workflows
      # values: |

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

### Related helm chart

argo-cd, argo-workflows

### Helm chart version

0.40.1

### To Reproduce

Install Argo Workflow Helm chart with Application resource

### Expected behavior

Argo Workflows gets successfully installed.
