### ISSUE TITLE
[argo-workflows] RBAC is not working with SSO

### ISSUE THREAD

**Issue by outductor** [argoproj/argo-helm#2395]
### Describe the bug

I have the following values.yaml for server and SSO itself seems working, but I get RBAC error

```
time="2023-12-21T04:00:08.297Z" level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
time="2023-12-21T04:00:08.297Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=GetUserInfo grpc.service=info.InfoService grpc.start_time="2023-12-21T04:00:08Z" grpc.time_ms=2.002 span.kind=server system=grpc
time="2023-12-21T04:00:08.297Z" level=info duration=2.556977ms method=GET path=/api/v1/userinfo size=34 status=403
time="2023-12-21T04:00:08.300Z" level=error msg="failed to perform RBAC authorization" error="no service account rule matches"
time="2023-12-21T04:00:08.300Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = not allowed" grpc.code=PermissionDenied grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2023-12-21T04:00:08Z" grpc.time_ms=1.955 span.kind=server system=grpc
```

```yaml
server:
  secure: true
  extraArgs:
    - --auth-mode=sso
  sso:
    enabled: true
    issuer: https://argo-cd.mydomain.com/api/dex
    # sessionExpiry defines how long your login is valid for in hours. (optional, default: 10h)
    sessionExpiry: 240h
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: https://argo-workflows.mydomain.com/oauth2/callback
```

I also tried enabling `server.rbac` and `server.sso.rbac` but it didn't help. I'm sure it's already true by itself (especially when `sso.enabled` is already true).

I already checked https://github.com/argoproj/argo-helm/issues/1624 and some other related issues

What am I doing wrong?

### Related helm chart

argo-workflows

### Helm chart version

0.40.1

### To Reproduce

1. apply Helm chat with given values.yaml

### Expected behavior

SSO and RBAC works fine
