### ISSUE TITLE
Support new extensions mechanism

### ISSUE THREAD

**Issue by jcogilvie** [argoproj/argo-helm#2396]
### Is your feature request related to a problem?

Argo extensions via CRD have been [deprecated](https://github.com/argoproj-labs/argocd-extensions?tab=readme-ov-file#deprecation-notice).  Update the chart to support the new initContainer approach.

### Related helm chart

argo-cd

### Describe the solution you'd like

Retain the `server.extensions` field but use the values to inform `initContainer`s to pull down the desired extensions.  Allow for specifying 

```yaml
extensionList:
  - name:  fooBarExtension
    extensionUrl: https://foo
    extensionChecksumUrl:  https://bar # optional
```

The existing functionality for mounts and mount paths can be preserved.  

As an example, to install the rollouts extension with the new mechanism in the current helm chart, I must set:

```yaml
server:
  initContainers:
    - name: rollout-extension
      image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
      env:
        - name: EXTENSION_URL
          value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
#        - name: EXTENSION_CHECKSUM_URL
#          value: TODO
      volumeMounts:
        - name: extensions
          mountPath: /tmp/extensions
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
  volumeMounts:
    - name: extensions
      mountPath: /tmp/extensions
  volumes:
    - name: extensions
      emptyDir: {}
```

I believe with a little bit of effort this can be reduced to:

```yaml
server:
  extensions:
    enabled: true
    image: # this could/should be defaulted to the following value
      repository: "quay.io/argoprojlabs/argocd-extension-installer"
      tag: "v0.0.1"
    extensionList:
    - name: rollout-extension
      extensionUrl: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
      extensionChecksumUrl: https://github.com/foo/bar # optional 
```

### Describe alternatives you've considered

Leave it to consumers of the helm chart to specify this with initContainers.  This seems more prone to error given the volumes and volumeMounts which this helm chart already has code for.
