### ISSUE TITLE
ArgoCD: `containerSecurityContext` is not getting overwritten

### ISSUE THREAD

**Issue by eugene-marchanka** [argoproj/argo-helm#2416]
### Describe the bug

```
controller/dex/server/repoServer/etc:
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
```
Does not take any effect:
https://github.com/argoproj/argo-helm/blob/9892e505f17a24fd13e1aef8248222e141887201/charts/argo-cd/templates/argocd-server/deployment.yaml#L352-L355

### Related helm chart

argo-cd

### Helm chart version

v5.25.1

### To Reproduce

Try to generate manifests with custom `values.yaml` file:
```
controller:
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
```

### Expected behavior

Controller Deployment would look like this:
```
spec:
  template:
    spec:
      containers:
      - name: controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true

```
actual result still contains `seccompProfile`:
```
spec:
  template:
    spec:
      containers:
      - name: controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
```

**Comment by yu-croco** [comment]
Hi @engson ,
You can override with `null`, like below.
*This is because of Helm Chart's specification.

```yaml
controller:
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    seccompProfile: null
    capabilities:
      drop:
      - ALL
```

**Comment by yu-croco** [comment]
Hi @eugene-marchanka 
You can override with `null`, like below.
*This is because of Helm Chart's specification.

```yaml
controller:
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    seccompProfile: null
    capabilities:
      drop:
      - ALL
```
