### ISSUE TITLE
Infinity rollout `out of sync` when using `scaleDown` property

### ISSUE THREAD

**Issue by ozlotusflare** [argoproj/argo-helm#2418]
### Describe the bug

Hi everyone!
I faced with infinity sync loop when I tried to follow [this migration doc form deployment to rollout](https://argoproj.github.io/argo-rollouts/migrating/). Basically this `workloadRef.scaleDown` option cause this , probably because no definition in a [CRD](https://github.com/argoproj/argo-helm/blob/argo-rollouts-2.34.1/charts/argo-rollouts/templates/crds/rollout-crd.yaml#L3335-L3344) 
<img width="1224" alt="Screenshot 2024-01-10 at 6 05 53 PM" src="https://github.com/argoproj/argo-helm/assets/78478066/994fa2d3-10cd-43dd-bc2e-434b74388afc">

### Related helm chart

argo-rollouts

### Helm chart version

2.34.1

### To Reproduce

```yaml
# Not working rollout spec
...
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-ref-deployment
    scaleDown: onsuccess
...
```
```yaml
# Working rollout spec
...
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-ref-deployment
...
```

### Expected behavior

Working `scaleDown:` spec
