### ISSUE TITLE
ArgoCD extension 401 Unauthorized

### ISSUE THREAD

**Issue by Jojoooo1** [argoproj/argo-helm#2431]
### Describe the bug

Helm chart version: 5.52.2
ArgoCD extension metrics: Using kustomize with https://github.com/argoproj-labs/argocd-extension-metrics/tree/main/manifests

Configuration:
```yaml
[...]
configs:
 cm:
   extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: http://prometheus-operated.observability.svc.cluster.local:9090

  rbac:
    policy.default: role:readonly
    policy.csv: |-
      p, role:readonly, extensions, invoke, httpbin, allow
[...]
server:
  extensions:
    enabled: true
    extensionList:
      - name: extension-metrics
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension.tar.gz
          - name: EXTENSION_CHECKSUM_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension_checksums.txt
```

### Related helm chart

argo-cd

### Helm chart version

5.52.2

### To Reproduce

Use configuration in description bug

### Expected behavior

It should query the dashboard metrics

### Screenshots

![Screenshot from 2024-01-18 10-10-00](https://github.com/argoproj/argo-helm/assets/17641873/1a56ddc8-5b9b-4f4d-ada1-437201678c4e)
