### ISSUE TITLE
Add documented support for Azure DevOps webhook

### ISSUE THREAD

**Issue by MariusGrandeAndersen** [argoproj/argo-helm#2432]
### Is your feature request related to a problem?

ArgoCD has [added support](https://github.com/argoproj/argo-cd/pull/14969) for Azure DevOps webook and I think the helm chart should mention that it works and have a custom value like all the other webhooks.

Workaround you can just do this in the helm chart:
```yaml
secret:
  extra:
    webhook.azuredevops.username: argocd
    webhook.azuredevops.password: p@$$w0rd
```

### Related helm chart

argo-cd

### Describe the solution you'd like

2 new values for the helm chart configs.secret section:

* azuredevopsUsername
* azuredevopsPassword

Around the same places the chart uses for example .Values.configs.secret.gitlabSecret

### Describe alternatives you've considered

The workaround works fine, but it's not appearent for new users of the chart:
```yaml
secret:
  extra:
    webhook.azuredevops.username: argocd
    webhook.azuredevops.password: p@$$w0rd
```
