### ISSUE TITLE
ArgoWorkflows in Cluster Scope - RBACs not working properly in UI

### ISSUE THREAD

**Issue by bilyboy785** [argoproj/argo-helm#2433]
### Describe the bug

We use Argo Workflows in Cluster Scope with an external Dex for SSO. We have different teams, needs to work on WorkflowTemplates & Workflows in their namespaces. We need to allow them to see WorkflowTemplates in others Namespace too. 

When I log in with my user1, I see in the UI that I'm using the SA readonly, instead of being attached to the serviceAccount team1 in the namespace team1.

However, the user seems to have the right permissions (those of serviceAccount team1). But why do we see the serviceAccount readonly? 

![](https://media.cleanshot.cloud/media/15917/U6IyL8yKclW94gzfqj43wBCMklCPyiQMSevEc4yQ.jpeg?Expires=1705619552&Signature=lq26UV19ABuoZgc7XG3w7jrIRhvi4Y37NrosMIwjDGMKePS4RIeYawpDs1GoSkzGLKr5RFsDpoBei0lgsCb2jDYA12F1ZyBLcLFolskPyb4VRSk3krcGATstwBqMZ-gRx2gr~jefzSfwI~fjJSgloPtI4kZT-wG7pK2iGK-DKB4FNYk4BOFtODa6ZWvx~djqkFGaTcZR2g91Leil-CJzZDe30joW32dnQlPBqLQODg2PElVXO9tVulwGSkokGV6E8kmimU0SqIhhnVqTWZowYw2R3Qty-c4ZHibSqQ2lM3SE7G8Lb2ObbdITeUnNEzDQMLPcfugRBNZCwp-LSE8gNw__&Key-Pair-Id=K269JMAT9ZF4GZ) 

### Related helm chart

argo-workflows v3.5.3

### Helm chart version

0.40.5

### To Reproduce

So we configure RBACs to allow UserA working in NamespaceA and Get WorkflowTemplates in NamespaceB, NamespaceC : 

```
- apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argoworkflows-role-team1
      namespace: fifty
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argoworkflows-role-binding-team1
      namespace: team1
    subjects:
      - kind: ServiceAccount
        name: team1
    roleRef:
      kind: Role
      name: argoworkflows-role-team1
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/service-account-token
    metadata:
      namespace: team1
      name: team1.service-account-token
      annotations:
        kubernetes.io/service-account.name: team1
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: team1
      namespace: team1
      annotations:
        workflows.argoproj.io/rbac-rule: "'team1' in groups"
        workflows.argoproj.io/rbac-rule-precedence: '2'
```

We set `rbac-rule: true` to a new readonly serviceAccount : 

```
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: readonly
      namespace: argo-workflows
      annotations:
        workflows.argoproj.io/rbac-rule: 'true'
        workflows.argoproj.io/rbac-rule-precedence: '0'
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/service-account-token
    metadata:
      namespace: argo-workflows
      name: readonly.service-account-token
      annotations:
        kubernetes.io/service-account.name: readonly
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: argoworkflows-cluster-role-readonly
    rules:
      - apiGroups:
          - argoproj.io
        resources:
          - workflowstemplates
          - clusterworkflowtemplates
        verbs:
          - get
          - list
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: argoworkflows-cluster-role-binding-readonly
    subjects:
      - kind: ServiceAccount
        name: readonly
        namespace: argo-workflows
    roleRef:
      kind: ClusterRole
      name: argoworkflows-cluster-role-readonly
      apiGroup: rbac.authorization.k8s.io
```

### Expected behavior

With this configuration, we expect differents cases : 

- User1 from team1 loggin : he should be linked to serviceAccount team1 in namespace team1 with all permissions in team1 namespace
- - User2 from team2 loggin : he should be linked to serviceAccount team2 in namespace team2 with all permissions in team2 namespace
- [...]
- UserX from teamX loggin : no rule match, he should be map to the default argo-workflow-server serviceAccount, with minimal permissions (readonly).
