### ISSUE TITLE
ExternalSecret Resource not getting deleted due to foregroundDeletion finalizer

### ISSUE THREAD

**Issue by manali14** [argoproj/argo-helm#2435]
### Describe the bug

We have an external secret associated with an application. As soon as we click on sync, the secret gets deleted and externalSecret goes to a pendingDeletion state. 

We are able to successfully sync the App by force deleting the external secret.

Also, though foreground deletion through argocd is stuck in PendingDeletion state, if we delete it manually using kubectl command through jumphost, it gets deleted without adding --force.

### Related helm chart

argo-cd

### Helm chart version

v2.9.3+6eba5be

### To Reproduce

Create an application with below manifest:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: <>
  namespace: argocd
spec:
  destination:
    name: '<>'
    namespace: dev
  project: <>
  source:
    helm:
      passCredentials: true
      releaseName: <>
      valueFiles:
        - values.yaml
        - values_dev.yaml
    path: <>
    repoURL: '<>'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

### Expected behavior

The application contains below k8s resources:

1. configMap
2. svc
3. pods
4. hpa
5. deployment
6. job
7. externalSecret (reading secrets from AWS Secrets Manager)
8. ingress
9. role
10. rolebinding

Post auto-sync/manually syncing the app, the secret deletes while the corresponding secret goes to a pendingDeletion state. It has to be manually deleted through jumphost/force deleted through argocd to get the deployment done.

### Screenshots

<img width="1226" alt="Screenshot 2024-01-19 at 3 25 15 PM" src="https://github.com/argoproj/argo-helm/assets/6524146/21834f39-2cfd-4620-8eb3-2709886a151f">
<img width="1136" alt="Screenshot 2024-01-19 at 3 25 25 PM" src="https://github.com/argoproj/argo-helm/assets/6524146/b082eb8d-958b-476d-a498-5039f7109fdf">
