### ISSUE TITLE
[argo-cd] Ingress.extraHosts is broken in 6.0.0

### ISSUE THREAD

**Issue by daftping** [argoproj/argo-helm#2478]
### Describe the bug

It is not possible to define ingress extraHosts in the new chart

### Related helm chart

argo-cd

### Helm chart version

6.0.0

### To Reproduce

Define extra hosts
```yaml
server:
  ingress:
    enabled: true
    extraHosts:
      - name: argocd.example.com
        path: /
```

helm template ...
```
Error: template: argo-cd/templates/argocd-server/ingress.yaml:42:36: executing "argo-cd/templates/argocd-server/ingress.yaml" at <.Values.server.ingress.path>: nil pointer evaluating interface {}.server
helm.go:84: [debug] template: argo-cd/templates/argocd-server/ingress.yaml:42:36: executing "argo-cd/templates/argocd-server/ingress.yaml" at <.Values.server.ingress.path>: nil pointer evaluating interface {}.server
```

### Expected behavior

It is possible to define extra hosts according to documentation.

### Additional context

The error you're encountering is due to the Helm template trying to access `.Values.server.ingress.path` in a context where `.Values` does not refer to the root of your values structure, but rather to the scope of the current item in the range loop over `.Values.server.ingress.extraHosts`.

When you use range in Helm templates, the scope (or context) within the range block changes to the current item in the list you're iterating over. This means that when you try to access `.Values.server.ingress.path` inside the range block for extraHosts, it's looking for `server.ingress.path` within the current extraHost item, not at the root of your values file.

To fix this, you need to use `$` to refer to the root context. The `$` symbol is used in Go templates (and thus in Helm templates) to always refer to the root context, allowing you to access global variables even when you're inside a changed scope due to a range or with block.

Here's the corrected part of your template:

```yaml
    {{- range .Values.server.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default $.Values.server.ingress.path .path }}
            pathType: {{ default $.Values.server.ingress.pathType .pathType }}
            backend:
              service:
                name: {{ include "argo-cd.server.fullname" $ }}
                port:
                  number: {{ $servicePort }}
    {{- end }}
```
Notice the use of `$.Values.server.ingress.path` instead of `.Values.server.ingress.path` to correctly access the global values within the range block. This change ensures that you're accessing the server.ingress.path from the root of your values hierarchy, avoiding the nil pointer error you encountered.
