### ISSUE TITLE
Bug in Rendering Helm Template, Argo-Workflows Not Respecting My Values File

### ISSUE THREAD

**Issue by Richard-Barrett** [argoproj/argo-helm#2502]
### Describe the bug

So basically I put everything in this ticket on a prior repository and was directed here:

- https://github.com/argoproj/argo-workflows/issues/12649

The main thing is it seems like Helm doesn't actually respect my helm values that I have set up, when I try to render the template:

```
---
server:
  serviceType: "NodePort"
  authModes:
    - sso
  secure: true
  sso:
    enabled: true
    insecureSkipVerify: false
    clientId:
      key: "client_id"
      name: "argo-server-sso"
    clientSecret:
      key: "client_secret"
      name: "argo-server-sso"
    issuer: "<some_url>"
    redirectUrl: "<some_url>/oauth2/callback"
    sessionExpiry: "1h" #  1 Hour for Session Expiration
  ingress:
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: <some_certificate_arn>
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/wafv2-acl-arn: <some_waf_arn>
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/subnets: <some_subnets>
      alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
      alb.ingress.kubernetes.io/target-type: ip
      external-dns.alpha.kubernetes.io/hostname: <some_url>
    enabled: "true"
    ingressClassName: "alb"
    hosts:
      - <some_url>
    paths:
      - /*
    pathType: ImplementationSpecific
controller:
  logging:
    format: json
  metricsConfig:
    enabled: "true"
    serviceMonitor:
      enabled: "true"
    telemetryConfig:
      enabled: "true"
artifactRepositoryRef:
  artifact-repositories:
    annotations:
      workflows.argoproj.io/default-artifact-repository: default
    default:
      s3:
        bucket: irt-dl-us-argoworkflow-unrestricted-dev
        endpoint: s3.amazonaws.com
        region: us-east-1
        keyFormat: "workflow\
                    /{{workflow.creationTimestamp.Y}}\
                    /{{workflow.creationTimestamp.m}}\
                    /{{workflow.creationTimestamp.d}}\
                    /{{workflow.name}}\
                    /{{pod.name}}"
        useSDKCreds: true
```

When I run this, it doesn't actually give me what I would expect, especially for the sso:

```
helm template argo/argo-workflows -f terraform/irt-data-dev/values/argo.values.yaml --version "0.33.1" -n argo-workflows > manifests/dev/argo.yaml
```

### Related helm chart

argo-workflows

### Helm chart version

0.33.1

### To Reproduce

Just try to use the values file and run the template, you don't need to actually make all of the infra I am specifying in the first ticket.

### Expected behavior

I would expect the template to respect my values.
