### ISSUE TITLE
Make argocd-apps.applications a map instead of a list

### ISSUE THREAD

**Issue by anthonyalayo** [argoproj/argo-helm#2523]
### Is your feature request related to a problem?

When using the argocd-apps helm chart, I would like to have some values overwritten/changed depending on the environment. For example, let's say i'm self managing argocd. I would like for a different values.yaml to be loaded in addition to the base values.yaml.

Something like this:
```
argocd-apps:
  applications:
    - name: argocd
      ...
      ...
        helm:
          valueFiles:
            - values.dev.yaml
```

Unfortunately, helm does not support declarative overriding of values within array elements. This causes me to have to copy/paste the entire configuration into my dev/stage/test values.yaml files.

### Related helm chart

argocd-apps

### Describe the solution you'd like

Switching `argocd-apps.applications` from a list to a map, so that users can override parts of their applications depending on the environment with different value files.

### Describe alternatives you've considered

I've read far and wide on the internet about how to modify particular values within arrays in helm, and it's just not supported.
