### ISSUE TITLE
re-introduce support for path based Ingress with empty hostname

### ISSUE THREAD

**Issue by paolofacchinetti** [argoproj/argo-helm#2527]
### Is your feature request related to a problem?

Since version `6.0.0`, it is no longer possible to leave out the `server.ingress.hosts` field (now renamed to `server.ingress.hostname`) when configuring the ArgoCD ingress resource.

I deploy ArgoCD to a single-node k3s cluster with Traefik as an ingress controller. Leaving out the `hosts` field while specifying a custom argoCD path in both `configs.params.server.rootpath` and `server.ingress.paths` (now renamed to `server.ingress.path`) meant that I could reach my ArgoCD deployment on `<CLUSTER_IP>/argocd`

I've looked into the docs and tried out various configs combination, but by looking at the actual chart source code it doesn't look like my usecase is supported anymore.

Right now, leaving out the `hostname` field means that the default hostname `argocd.example.com` is used, making the ingress useless.

### Related helm chart

argo-cd

### Describe the solution you'd like

Being able to do path based routing only for ingress, while leaving out the `hosts` field

### Additional context

My values.yaml that worked with ArgoCD <  6.0.0

```yaml
configs:
  params:
    server.rootpath: "/argocd"
    server.insecure: true
server:
  ingress:
    enabled: true
    https: false
    paths:
      - "/argocd"
    annotations:
      # annotations for self-signed HTTPS ingress
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
```

**Comment by pdrastil** [comment]
Hi @paolofacchinetti your use case should be supported like this with catch-all rule. Removing this was intentional as using ingress without hostname is not really good security practice because all unmatched traffic gets routed to Argo CD server.

```yaml
configs:
  params:
    server.rootpath: "/argocd"
    server.insecure: true
server:
  ingress:
    enabled: true
    annotations:
      # annotations for self-signed HTTPS ingress
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    # Add extra rule for catch-all traffic
    extraRules:
    - http:
        path: /argocd
        backend:
          service:
            name: argocd-server
            port:
              name: http
```

**Comment by pdrastil** [comment]
One trick you might like - for using IPs with fake domain for local setup check https://nip.io/

**Comment by paolofacchinetti** [comment]
Hi @pdrastil, thank you for the very quick feedback!

I'm aware that my configuration is not exactly the best from a security standpoint, but I only deploy to on-premises private networks that aren't exposed to the public internet, so it's not a problem for me.

Regarding the extraRules example: unfortunately it has one major issue, which is that the `http.backend.service.name` field is computed at runtime and depends on the Helm Release name (`name: {{ include "argo-cd.server.fullname" . }}` ). 

To go more into details: I use ArgoCD as a Helm dependency. By doing that, I can provide default configurations for the ArgoCD chart inside my own chart's `values.yaml`. Unfortunately, I don't know beforehand the release name that will be used by the person that installs my chart, so I can't pre-compute the `"argo-cd.server.fullname"` value.

Regarding https://nip.io - it is a very useful tool, but only really works for development purposes.

I was thinking of adding a boolean field to the values.yaml (i.e. `disableHostnameRouting` ) that when set to `true`, truncates the `host`  field inside the ingress. Ofc I'd be down to develop the change myself and go through the PR review process.

**Comment by paolofacchinetti** [comment]
Also, quick nitpick on your `extraRules` example, just in case it turns out to be useful to someone else that finds this issue:

```
server:
  ingress:
    enabled: true
    annotations:
      # annotations for self-signed HTTPS ingress
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    # Add extra rule for catch-all traffic
    extraRules:
    - http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
``♠

**Comment by pdrastil** [comment]
I see - thanks for providing more details about use case. Would it help if we pass this through `tpl` function so you can also use `{{ include "argo-cd.server.fullname" . }}` in extra rules?

**Comment by paolofacchinetti** [comment]
that's a great idea! Just to be sure, will the following configuration work with your proposed change?

```yaml
server:
  ingress:
    enabled: true
    annotations:
      # annotations for self-signed HTTPS ingress
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    # Add extra rule for catch-all traffic
    extraRules:
    - http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: {{ include "argo-cd.server.fullname" . }}
                port:
                  name: {{ .Values.server.service.servicePortHttp }}
```

**Comment by pdrastil** [comment]
@paolofacchinetti This would be output with template above. The primary domain is always set as it's also passed into ConfigMaps and allows users to run with Dex out of the box. Would this work for you?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: "default"
spec:
  rules:
    - host: argocd.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: 'argocd-server'
              port:
                name: 'http'
```
