### ISSUE TITLE
Azure Templating broken between Helm Chart Version 0.26.5 and 0.26.6

### ISSUE THREAD

**Issue by HRusby-Cheyne** [argoproj/argo-helm#2528]
### Describe the bug

Previously you could use {{workflow.namespace}} style parameters to define your artifactRepository BlobName for Azure. It appears that this was broken in the commit https://github.com/argoproj/argo-helm/commit/f6d44750b8ecf25e272b22dd78950e3ad43e0ffd#diff-7c1bdf65c82164b5472073b2892bbb5d3bbe8f2ea4b2da6b600163b412fb4b90 and hasn't been fixed since

### Related helm chart

argo-workflows

### Helm chart version

>= 0.26.6

### To Reproduce

Helm install the chart with the following in your values file:
```yaml
artifactRepository:
  archiveLogs: true
  azure:
    endpoint: <SomeEndpoint>
    container: <SomeContainer>
    blobNameFormat: "{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
```

### Expected behavior

Following error message will appear:
```sh
Error: UPGRADE FAILED: template: argo-workflows/templates/controller/workflow-controller-config-map.yaml:66:17: executing "argo-workflows/templates/controller/workflow-controller-config-map.yaml" at <tpl (toYaml .) $>: error calling tpl: error during tpl function execution for "accountKeySecret:\n  key: *****\n  name: *****\nblobNameFormat: '{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}'\ncontainer: *****\nendpoint: *****": parse error at (argo-workflows/templates/controller/workflow-controller-config-map.yaml:4): function "workflow" not defined
```

### Additional context

PR in which this was introduced: https://github.com/argoproj/argo-helm/pull/2026
