### ISSUE TITLE
[Argo CD] ingressGrpc shouldn't depend on ingress' controller field

### ISSUE THREAD

**Issue by jacek-jablonski** [argoproj/argo-helm#2540]
### Describe the bug

Based on this condition (https://github.com/argoproj/argo-helm/blob/argo-cd-6.2.3/charts/argo-cd/templates/argocd-server/ingress-grpc.yaml#L1):
```
{{- if and .Values.server.ingressGrpc.enabled (eq .Values.server.ingress.controller "generic") -}}
```
GRPC ingress is only created when main ingress controller is set to `generic`. With this condition it is impossible to create GKE main ingress and GRPC ingress using nginx controller.

### Related helm chart

argo-cd

### Helm chart version

6.2.3

### To Reproduce

In `values.yaml`:
```
ingress:
  enabled: true
  controller: gke

ingressGrpc:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
```

GRPC ingress is not created.

### Expected behavior

GRPC ingress should be created with given params.
