### ISSUE TITLE
Support existing secret for ArgoCD Notification

### ISSUE THREAD

**Issue by ranrubin** [argoproj/argo-helm#2575]
### Is your feature request related to a problem?

I use a K8s operator to manage my K8s secrets  (namely [external-secrets](https://external-secrets.io/latest/)), and I would like it to create `argocd-notifications-secret` along with its content.  
However, I could not find a way to pass an existing secret to the Helm Chart, and it seems like `argocd-notifications-secret` is hard-coded. 

### Related helm chart

argo-cd

### Describe the solution you'd like

Edit the `values.yaml` with my existing secret. For example:

```
notifications:
  secret:
    # -- Whether helm chart creates notifications controller secret
    create: false

    # -- notifications controller Secret name
    name: "my-secret"

    # -- Whether to use existing secret. If true, assumes that the existing secret name is notifications.secret.name
    useExistingSecret: true
```

### Describe alternatives you've considered

What I'm currently doing is setting `notifications.secret.create` to `false`.
However, the Chart still forces me to use `argocd-notifications-secret` as my secret name.
