### ISSUE TITLE
Argo-cd deployment template volumes wrong indention

### ISSUE THREAD

**Issue by tgauweiler** [argoproj/argo-helm#259]
**Describe the bug**
When setting `Values.server.volumes` the following error is thrown:
```
Error: YAML parse error on argo-cd/templates/argocd-server/deployment.yaml: error converting YAML to JSON: yaml: line 79: did not find expected key
```
https://github.com/argoproj/argo-helm/blob/400f141dae386bea0ad6ac68a0c3ac0d6f0d3789/charts/argo-cd/templates/argocd-server/deployment.yaml#L135
uses `nindent 8` instead of the correct value of 6.

**To Reproduce**
Set inside values.yaml:
```
server:
  volumes:
  - secret:
      secretName: test
    name: test
```

**Expected behavior**
Yaml files gets generated
