### ISSUE TITLE
Allow setting resource inclusion/exclusion

### ISSUE THREAD

**Issue by aqeelat** [argoproj/argo-helm#2591]
### Is your feature request related to a problem?

Since it is part of the declarative setup, it would be useful to add it to the chart as well

https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#resource-exclusioninclusion

### Related helm chart

argo-cd

### Describe the solution you'd like

Adding an option for it in values.yaml

**Comment by yu-croco** [comment]
Hi @aqeelat , thank you for your issue.
I will make PR for this.

FYI: The following works well for now, it's just not declared in values.yaml though. :)
```yaml
configs:
  cm:
    resource.exclusions: |
      - apiGroups:
        - "*"
        kinds:
        - "*"
        clusters:
        - https://192.168.0.20
```
