### ISSUE TITLE
Change clusterCredentials type to map

### ISSUE THREAD

**Issue by nbarrientos** [argoproj/argo-helm#2592]
### Is your feature request related to a problem?

Helm [does not support merging arrays](https://github.com/helm/helm/issues/3486) so it's not possible to have for instance cluster declarations in separate "values" files (in view of encrypting them with different keys).

```yaml
configs:
  clusterCredentials:
    - name: my-cluster
      server: https://example.com:6443
      config:
        bearerToken: "foo"
        tlsClientConfig:
          insecure: false
          caData: "bar"
```

### Related helm chart

argo-cd

### Describe the solution you'd like

Declare clusters with the same syntax as `configs.repositories`:

```yaml
configs:
  clusterCredentials:
    my-cluster:
      server: https://example.com:6443
      config:
        bearerToken: "foo"
        tlsClientConfig:
          insecure: false
          caData: "bar"
```

as each cluster is represented by a key in the map `configs.clusterCredentials` it'd be possible for Helm to merge multiple clusters declared in separate values files.
