### ISSUE TITLE
Option to create OCI helm repository is not clear

### ISSUE THREAD

**Issue by chandanpjain** [argoproj/argo-helm#2601]
### Describe the bug

We are trying to add a helm repository when deploying argo-cd using helm charts. This OCI helm repository requires credentials and this is being passed as `credentialTemplates` via the helm values. But we are seeing that this repository is failing to get connected in the argo-cd repositories list and hence the application which is being deployed referencing this repository fails to sync to the cluster.

There seems to be lack of support or clear instruction to add oci helm repositories with credentials. Let us know if there is anything missing in the way we are using helm chart to set the credentials or the oci helm repo.

### Related helm chart

argo-cd

### Helm chart version

6.7.3

### To Reproduce

1. Here is our helm values

```
 credentialTemplates:
    yyy-ecr-helm-creds:
        url: xxx.dkr.ecr.us-west-2.amazonaws.com
        username: AWS
        password: password
        enableOCI: true
        type: helm
        name: rcp-ecr-helm

  repository:
      yyy-ecr-helm:
        name: yyy-ecr-helm
        type: helm
        url: xxx.dkr.ecr.us-west-2.amazonaws.com
```

Also tried with:
```
 credentialTemplates:
    yyy-ecr-helm-creds:
        url: xxx.dkr.ecr.us-west-2.amazonaws.com/yyy-chart
        username: AWS
        password: password
        enableOCI: true
        type: helm

  repository:
      yyy-ecr-helm:
        name: yyy-ecr-helm
        type: helm
        url: xxx.dkr.ecr.us-west-2.amazonaws.com/yyy-chart
```

2. We are setting the password by setting they value ` "argo-cd.configs.credentialTemplates.yyy-ecr-helm-creds.password=$ECR_PASSWORD"`.
3. In the UI, we can see credentials created, but repository is in `failed` state. 
4. The repository is getting added as `helm` as opposed to `helm oci`. We can add `helm oci` repository from the UI, but we don't seem to get instructions to set `enableOCI` flag for repository.
5. Also, we can verify that the secret is created in the `argocd` namespace with specified values in the `credentialTemplates`.
6. As a result, the application created using this repository is failing as the repository is not linked correctly.
```
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = `helm pull oci://xxx.dkr.ecr.us-west-2.amazonaws.com/yyy-chart --version 1.1.1 --destination /tmp/f3de2a7b-071d-4251-a4fb-43b0d66b2b9d` failed exit status 1: Error: pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials
```

### Expected behavior

1. Repository created successfully
2. Repository type is helm OCI
3. Credentials saved and used when application is created

### Screenshots

![image](https://github.com/argoproj/argo-helm/assets/11813513/2eef7522-f292-4210-8f81-bb7b25d8babe)

**Comment by chandanpjain** [comment]
Figured out `helm OCI` is a type of project that is accepted when adding repository in the helm values. But this does not seem to add and identify the remote repo as OCI. 

```
      yyy-ecr-helm:
        name: yyy-ecr-helm
        type: helm OCI
        url: xxx.dkr.ecr.us-west-2.amazonaws.com
```

Even though repository is added correctly as `helm OCI`, it seems with this change has converted the helm pull from `oci` to `https` as compared to previous error.

![image](https://github.com/argoproj/argo-helm/assets/11813513/1bc8bea3-1f2f-49bc-a7e1-f6c74ff8c1c1)

Below error is thrown when the application tries to pull the helm chart.
```
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = `helm registry login xxx.dkr.ecr.us-west-2.amazonaws.com --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin. time="2024-03-25T22:44:07Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="login attempt to https://xxx.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 400 Bad Request" Error: login attempt to https://xxx.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 400 Bad Request
```

It seems a correct combination of various settings is not being achieved here. Any help to set these settings right is much appreciated.

**Comment by chandanpjain** [comment]
This can be closed, the trick was to match the name of repository and credentailsTemplate.

```
 credentialTemplates:
    yyy-ecr-helm:
        url: xxx.dkr.ecr.us-west-2.amazonaws.com/yyy-chart
        username: AWS
        password: password
        enableOCI: true
        type: helm

  repository:
      yyy-ecr-helm:
        name: yyy-ecr-helm
        type: helm OCI
        url: xxx.dkr.ecr.us-west-2.amazonaws.com/yyy-chart
```

**Comment by chandanpjain** [comment]
Reopening issue.

After adding repository as detailed in last comment, especially with `type: helm OCI`, the repo is getting added. But, the connection to ECR always fails. 

More details on that is listed in another bug ticket under `argo-cd` https://github.com/argoproj/argo-cd/issues/18021. (As it is not clear either it is a bug in `argo-cd` or helm charts are not setting the required values correctly.

Also, output of `argocd repo` seems to indicate this is not an OCI repo (`OCI` column marked `false`)
![image](https://github.com/argoproj/argo-helm/assets/11813513/e65d997a-f834-4f0c-8dc8-318d0ea54736)

**Comment by pdrastil** [comment]
Hi @chandanpjain - the OCI support is poorly documented, however this is how you can get this working in values.yaml. The configuration parameters are pass-though so it should look exactly same as credentialTemplates.

```yaml
credentialTemplates:
    yyy-ecr-helm-creds:
        url: xxx.dkr.ecr.us-west-2.amazonaws.com
        username: AWS
        password: password
        enableOCI: true
        type: helm
        name: rcp-ecr-helm

  repository:
      argocd:
        name: argocd
        url: ghcr.io/argoproj/argo-helm
        type: helm
        enableOCI: true
```
