### ISSUE TITLE
Argo CD Git WebHook Secret from another secret

### ISSUE THREAD

**Issue by alex-souslik-hs** [argoproj/argo-helm#2635]
### Is your feature request related to a problem?

I've configured a Git WebHook to Argo CD but couldn't figure out how to securely add the WebHook secret to my helm values. My `values.yaml` is stored in a GitHub repo and the `argocd-secret` is defined in it. 

### Related helm chart

argo-cd

### Describe the solution you'd like

Ideally, I'd like this configuration to be handled the same way [sensitive keys can be handled in `argocd-cm`](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets).

### Describe alternatives you've considered

* Not using the WebHook secret.
* Not creating the `argocd-secret` with the Argo CD chart.

**Comment by pdrastil** [comment]
Hi @alex-souslik-hs the sensitive values in `argocd-cm` are inderctly referencing K8s secret, however webhook tokens have to be stored in Secret callled `argocd-secret`. You can achieve this with various integrations where you take full control of secret creation.

See:
- https://argo-cd.readthedocs.io/en/stable/operator-manual/security/#secrets
- https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-secret-yaml/

You can also check sample snippet bellow that uses external-secret operator if you want to provision this without hardcoding anything sensitive in `values.yaml`.

```yaml
configs:
  secret:
    createSecret: false

extraObjects:
  - apiVersion:
    kind: ExternalSecret
    metadata:
       name: argocd-secret
    spec:
      secretStoreRef:
        name: aws-secretsmanager
        kind: SecretStore
      target:
        name: argocd-secret
      data:
      - secretKey: webhook.github.secret
        remoteRef:
          key: webhook
          property: webhook.github.secret
```

**Comment by tman5** [comment]
@pdrastil I have a very similar setup. So you are saying this won't work with the helm chart?

```
  secret:
    createSecret: true
    gitlabSecret: "$otherK8sSecret:gitlabSecret"
```

**Comment by pdrastil** [comment]
@tman5 I don't think so. The substitutions are done in ConfigMap `argocd-cm` and needs to be supported by Argo CD controller. See Argo CD [docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#sensitive-data-and-sso-client-secrets). For storing / generating sensitive values outside of helm chart it's usually done by various [solutions](https://argo-cd.readthedocs.io/en/stable/operator-manual/secret-management/#secret-management) that generate and populate the secret values from external systems or require additional plugins to process encrypted values.

**Comment by yolkov** [comment]
@pdrastil so this docs [one](https://argo-cd.readthedocs.io/en/stable/operator-manual/webhook/#alternative) and [two](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Plugin/#alternative) is wrong?

**Comment by Kariton** [comment]
i'm also curious how this is supposed to work.
was unable to get those `$<k8s_secret_name>:<a_key_in_that_k8s_secret>` references to work.

**Comment by Kariton** [comment]
in the end i was able to get it working.

helm values:
```yaml
---
configs:
  secret:
    gitlabSecret: $gitlab-webhook:token
```

secret:
```yaml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitlab-webhook
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
stringData:
  token: SECRETGITLABTOKEN
```

dont know what i did wrong the first time.
