### ISSUE TITLE
sync is broken with v6.8.0

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-helm#2684]
### Describe the bug

You cannot manually sync any apps anymore with helm chart version 6.8.0.

the error message is:
`Unable to sync: error resolving repo revision: rpc error: code = Unknown desc = repository not found`

### Related helm chart

argo-cd

### Helm chart version

6.8.0

### To Reproduce

try to manual sync an argo app

### Expected behavior

the sync works without any issues with helm chart version 6.7.18

**Comment by jascsch** [comment]
example manifest of redis cache:

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: prod
sources:
  - repoURL: >-
      https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    targetRevision: '*'
    helm:
      valueFiles:
        - $valuesRepo/prod-cluster/tools/redis/values.yaml
      releaseName: redis
    chart: redis
  - repoURL: 'https://git.i.mercedes-benz.com/LES/argo.git'
    targetRevision: HEAD
    ref: valuesRepo
```
values.yaml
```
global:
  imageRegistry: registry-emea.app.corpintra.net/dockerhub
image:
  repository: bitnami/redis

architecture: standalone

auth:
  enabled: true
  existingSecret: "redis-secret"

master:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: "100Mi"
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: "50Mi"
```
