### ISSUE TITLE
argo-workflows Chart does not allow adding labels to server-service

### ISSUE THREAD

**Issue by druchoo** [argoproj/argo-helm#2697]
### Describe the bug

`.Values.server.serviceLabels` is documented in values.yaml, however the `server-service.yaml` template does not have the code to use the value and add labels.

```
server:
...
  # -- Optional labels to add to the UI Service
  serviceLabels: {}
```

### Related helm chart

argo-workflows

### Helm chart version

0.41.4

### To Reproduce

set `.Values.server.serviceLabels` and run `helm template ..`
```
server:
  serviceLabels:
    my: label
```

```
❯ helm template -n argo argo-workflows argo/argo-workflows --version=0.41.4 --set=server.serviceLabels.my-label=my-value --show-only templates/server/server-service.yaml
---
# Source: argo-workflows/templates/server/server-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-server
  namespace: "argo"
  labels:
    helm.sh/chart: argo-workflows-0.41.4
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-workflows
    app.kubernetes.io/version: "v3.5.6"
spec:
  ports:
  - port: 2746
    targetPort: 2746
  selector:
    app.kubernetes.io/name: argo-workflows-server
    app.kubernetes.io/instance: argo-workflows
  sessionAffinity: None
  type: ClusterIP
```

### Expected behavior

Setting `.Values.server.serviceLabels` should add labels to the Server Service object.
