### ISSUE TITLE
PriorityClassName is not set in redis-ha components

### ISSUE THREAD

**Issue by zoispag** [argoproj/argo-helm#2704]
### Describe the bug

When setting `global.priorityClassName` and `redis-ha.enabled: true` the redis components (`redis-ha-server`s and `redis-ha-proxy`s) do not set the same priorityClassName.

### Related helm chart

argo-cd

### Helm chart version

6.9.3

### To Reproduce

Deploy HA ArgoCD with the following values.yml:

```yml
global:
  priorityClassName: system-cluster-critical

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
```

### Expected behavior

Global priorityClassName should be also set to ha-redis components. In case of non ha-redis, redis deployment **does** get the priorityClassName as expected.

### Additional context

`redis-ha` is a dependency:

```yml
dependencies:
  - name: redis-ha
    version: 4.26.1
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
```

and has support for setting priorityClassName:

https://github.com/DandyDeveloper/charts/blob/0fe831e1c5171dd0217e1f543d40798f473a561f/charts/redis-ha/templates/redis-haproxy-deployment.yaml#L181-L183

https://github.com/DandyDeveloper/charts/blob/0fe831e1c5171dd0217e1f543d40798f473a561f/charts/redis-ha/templates/redis-ha-statefulset.yaml#L523-L525
