### ISSUE TITLE
argocd-sever ignore configured certificate

### ISSUE THREAD

**Issue by erwanval** [argoproj/argo-helm#2724]
### Describe the bug

When ```server.certificate``` is configured, a certificate resource is created as expected, and cert-manager create the secret. By default, the name of the secret created is ```argocd-server-tls``` (and can be modified in the values),  but it's never used in the deployment, so this certificate is ignored in the end.

There is however an optional secret called ```argocd-repo-server-tls``` which is mounted (with a static name written in the [deployment](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/deployment.yaml#L481)).
So I tried to name the secret like this, and I can see the right secret is mounted and my own certificate is present inside the container in the folder ```/app/config/server/tls```.
However, when checking the exposed certificate using ```openssl s_client```, my certificate is ignored and instead, it's serving a self signed certificate with ```O=Argo CD``` and 1 year validity.

I haven't tried using the ```server.certificateSecret```, but I expect the result to be the same, since it's simply another way to generate a secret named ```argocd-server-tls```.

### Related helm chart

argo-cd

### Helm chart version

6.11.1

### To Reproduce

Deploy while setting the values to create a Certificate:
```
[...]
server:
  certificate:
    enabled: true
    domain: argocd-server.argocd.svc
    secretName: argocd-repo-server-tls
    duration: 2160h # 90d
    renewBefore: 360h # 15d
    issuer:
      name: my-ca
      kind: ClusterIssuer
      group: cert-manager.io
[...]
```
Then check the exposed certificate using openssl:
```
# adapt the url and port to your env
openssl s_client -connect argocd-server.argocd.svc:443
```

### Expected behavior

Exposed certificate by argocd-server should be the one provided

### Additional context

For ```argocd-repo-server```, the chart values are a bit different. However, when a secret named ```argocd-repo-server-tls``` exists in the namespace, the exposed certificate match the one contained in this secret, so it works as expected.
The only notable difference between ```argocd-server``` and ```argocd-repo-server``` is the mountPath: ```/app/config/server/tls/``` for ```argocd-server```, and ```/app/config/reposerver/tls/``` for ```argocd-repo-server```

I tried to add the following to the ```argocd-server``` deployment, just in case, but it didn't work either:
```
volumeMounts:
- mountPath: /app/config/reposerver/tls
  name: argocd-repo-server-tls
```
