### ISSUE TITLE
ArgoCD externalRedis too many colons in address

### ISSUE THREAD

**Issue by gabriel-suela** [argoproj/argo-helm#2726]
### Describe the bug

im having a issue with externalRedis and can't login in the UI. My cfg is this:

```
externalRedis:
  host: rediss://xxx-xxx.redis.cache.windows.net
  username: ''
  password: ref+sops://secrets.enc.yaml#argocd-redis-password
  port: 6380
```

and im getting these logs from application controller
`{"level":"warning","msg":"Failed to save cluster info: dial tcp: address rediss://xxx-xxx.redis.cache.windows.net:6380: too many colons in address","time":"2024-05-29T13:47:47Z"}`

### Related helm chart

argo-cd

### Helm chart version

7.0.0

### To Reproduce

-

### Expected behavior

-
