### ISSUE TITLE
Add support to use existing secret for configuring `sshPrivateKey` in `configs.repositories.<name>`.

### ISSUE THREAD

**Issue by tanguynicolas** [argoproj/argo-helm#2727]
### Is your feature request related to a problem?

I wanted to set up a Git repository from the Helm chart, but there doesn't seem to be a secure way to pass the secret, without using things other than the chart.

### Related helm chart

argo-cd

### Describe the solution you'd like

Something like this could be really ideal:
```yaml
repositories:
  infra-repo:
    url: git@gitlab.com:awesome-org/infrastructure/helm.git
    sshPrivateKeyFromSecret:
      name: argocd-repositories
      key: infra-repo-ssh-key
```

### Describe alternatives you've considered

I tried this, which is similar to what is done for DEX configuration, but without success:
```yaml
repositories:
  infra-repo:
    url: git@gitlab.com:awesome-org/infrastructure/helm.git
    sshPrivateKey: $argocd-repositories:infra-repo-ssh-key
```

Alternatively, you can use External Secrets' Advanced Templating v2, or dataFrom (specifying the repository url in the secret). But it's not ideal.
