### ISSUE TITLE
unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.name of type string

### ISSUE THREAD

**Issue by lvijnck** [argoproj/argo-helm#2746]
### Describe the bug

Using the following TF snippet:

```
resource "helm_release" "argo_app_of_apps" {
  provider = helm
  name       = "argocd-apps"
  depends_on = [helm_release.argo]
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argocd-apps"
  namespace  = var.namespace
  # version = "1.6.2" enable to get correct output
 
  values = [
    yamlencode({
      "applications" : [
        {
          "name" : "platform",
          "namespace" : var.namespace,
          "finalizers" : ["resources-finalizer.argocd.argoproj.io"],
          "project" : "default",
          "additionalLabels" : {
            "app.kubernetes.io/part-of" : join("-", ["argo", helm_release.argo.metadata[0].revision])
          }
          "source" : {
            "repoURL" : var.repo_url,
            "path" : var.repo_path,
            "targetRevision" : var.repo_revision,
          },
          "destination" : {
            "server" : "https://kubernetes.default.svc",
            "namespace" : var.namespace
          },
          "syncPolicy" : {
            "automated" : {
              "prune" : true,
              "selfHeal" : true
            }
          }
        }
      ]
      }
    )
  ]
}
```

yields the following template, i.e., the `name` attribute is not picked up correctly.

```
"templates/applications.yaml": |
  ---
  # Source: argocd-apps/templates/applications.yaml
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    labels:
      app.kubernetes.io/part-of: argo-2
    name: 0 # mind this!
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    source:
      path: argo/
      repoURL: https://github.com/xxxx/core.git
      targetRevision: HEAD
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc/
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
```

Current fix is to fix the provider version to `1.6.2` using the TF block below:

### Related helm chart

argocd-apps

### Helm chart version

2.0.0

### To Reproduce

Add terraform snippet and check the provided template

### Expected behavior

Correct `name` attribute to be filled out
