### ISSUE TITLE
`argocd-rbac-cm` is created but with empty `policy.csv` 

### ISSUE THREAD

**Issue by iLem0n** [argoproj/argo-helm#2753]
### Describe the bug

I have local users configured by adding `"accounts.myuser"="login"` to `argocd-cm`. 
To apply some roles I configured `global.rbac` as follows (just for initial test):

```yaml
global:
  # Argo CD RBAC policy configuration
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md
  rbac:
    # -- File containing user-defined policies and role definitions.
    # @default -- `''` (See [values.yaml])
    policy.csv: |
      g, myuser, role:admin
```

The ConfigMap is created, but the attribute 'policy.csv' is empty.
```bash
$> kubectl describe  cm/argocd-rbac-cm -n argocd
Name:         argocd-rbac-cm
Namespace:    argocd
Labels:       app.kubernetes.io/component=server
              app.kubernetes.io/instance=argocd
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=argocd-rbac-cm
              app.kubernetes.io/part-of=argocd
              app.kubernetes.io/version=v2.11.2
              helm.sh/chart=argo-cd-7.1.1
Annotations:  meta.helm.sh/release-name: argocd
              meta.helm.sh/release-namespace: argocd

Data
====
policy.matchMode:
----
glob
scopes:
----
[groups]
policy.csv:
----

policy.default:
----


BinaryData
====

Events:  <none>
```

I couldn't find any code which is actually mounting this configmap to a pod so im a little bit confused where it is used at all. 

### Related helm chart

argo-cd

### Helm chart version

7.1.1

### To Reproduce

1. Configure `global.rbac.policy.csv`

### Expected behavior

- The configured policies should be written to the config-map `argocd-rbac-cm`
- The config-map should be mounted at the correct pods to enable argocd actually applying these roles 

### Additional context

actual argcd-cm
```bash
$> kubectl describe  cm/argocd-cm -n argocd
Name:         argocd-cm
Namespace:    argocd
Labels:       app.kubernetes.io/component=server
              app.kubernetes.io/instance=argocd
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=argocd-cm
              app.kubernetes.io/part-of=argocd
              app.kubernetes.io/version=v2.11.2
              helm.sh/chart=argo-cd-7.1.1
Annotations:  meta.helm.sh/release-name: argocd
              meta.helm.sh/release-namespace: argocd

Data
====
exec.enabled:
----
false
server.rbac.log.enforce.enable:
----
false
statusbadge.enabled:
----
false
timeout.hard.reconciliation:
----
0s
timeout.reconciliation:
----
180s
accounts.myuser:
----
login
admin.enabled:
----
true
application.instanceLabelKey:
----
argocd.argoproj.io/instance
url:
----
https://argocd.ilem0n.de

BinaryData
====

Events:  <none>
``
