### ISSUE TITLE
Argo-cd chart not deploy new version redis-ha

### ISSUE THREAD

**Issue by alezander86** [argoproj/argo-helm#2788]
### Describe the bug

when I am trying to deploy a new argo-helm with Redis-ha

```
Initializing config..
Copying default redis config..
  to '/data/conf/redis.conf'
Copying default sentinel config..
  to '/data/conf/sentinel.conf'
Identifying redis master (get-master-addr-by-name)..
  using sentinel (argo-cd-redis-ha), sentinel group name (argocd)
Could not connect to Redis at argo-cd-redis-ha:26379: Try again
Could not connect to Redis at argo-cd-redis-ha:26379: Try again
Could not connect to Redis at argo-cd-redis-ha:26379: Try again
  Fri Jun 21 16:11:46 UTC 2024 Did not find redis master ()
Identify announce ip for this pod..
  using (argo-cd-redis-ha-announce-0) or (argo-cd-redis-ha-server-0)
  identified announce ()
/readonly-config/init.sh: line 239: Error: Could not resolve the announce ip for this pod.: not found
```

here are my values

```
argo-cd:
  redis-ha:
    enabled: true
  redis:
    enabled: false

  server:
    replicas: 1
    env:
      - name: ARGOCD_API_SERVER_REPLICAS
        value: '1'

  controller:
    enableStatefulSet: true
  dex:
    enabled: false

  # Disabled for multitenancy env with single instance deployment
  applicationSet:
    enabled: true

  # Disable for now, since we don't have any notifications
  notifications:
    enabled: false


    params:
      server.insecure: true
      application.namespaces: >-
        env1

      applicationsetcontroller.namespaces: >-
        env1

      applicationsetcontroller.allowed.scm.providers: "https://git.example.com/,https://gitlab.example.com/"
      applicationsetcontroller.enable.scm.providers: "false"
```

### Related helm chart

argo-cd

### Helm chart version

7.2.0

### To Reproduce

1. Try to install argo-helm version 7.2.0

### Expected behavior

harbor-ha deployed without errors

### Screenshots

![image](https://github.com/argoproj/argo-helm/assets/77995538/117c8256-38cf-41e6-a2d5-e99160d63f4b)
