### ISSUE TITLE
Argo Rollouts global subscriptions can't be deployed through Helm

### ISSUE THREAD

**Issue by ajax-bychenok-y** [argoproj/argo-helm#2792]
### Describe the bug

Global subscriptions ([as in ArgoCD](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L3359-L3371)) are seems supported in Argo Rollouts:
```
data:
  service.telegram: |
    token: $telegram-token
  subscriptions: |
    - recipients:
      - telegram:-123456789|124790
      triggers:
      - on-rollout-completed
 ...
 ```
But they can't be deployed through helm.

### Related helm chart

argo-rollouts

### Helm chart version

2.36.1

### To Reproduce

Edit `argo-rollouts-notification-configmap`:
```
$ kubectl edit cm argo-rollouts-notification-configmap -n argo-rollouts
```
```
data:
  service.telegram: |
    token: $telegram-token
  subscriptions: |
    - recipients:
      - telegram:-123456789|124790
      triggers:
      - on-rollout-completed
 ...
```
And deploy something with Argo Rollouts.

### Expected behavior

I expect working global subscription configuration through helm chart.

### Additional context

I can try to provide PR if you don't mind as this seems is not documented feature.
