### ISSUE TITLE
overrideNamespace is not propagated to redis-secret

### ISSUE THREAD

**Issue by nikolaof** [argoproj/argo-helm#2817]
### Describe the bug

When creating an umbrella (wrapper) helm chart to deploy argocd and use the `overrideNamespace` attribute in values the `redis-secret` is created to the default namespace and not in the defined one. This makes all pods except the `applicationset` one unable to start. They return an error `redis-secret not found`

### Related helm chart

argo-cd

### Helm chart version

7.3.4

### To Reproduce

Create an umbrella chart like this

Chart.yaml
```
apiVersion: v2
name: argo-cd
version: 1.0.2
dependencies:
  - name: argo-cd
    version: 7.3.4
    repository: https://argoproj.github.io/argo-helm
```

values.yaml
```
argo-cd:
  namespaceOverride: argo-cd
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
```

### Expected behavior

To create the `redis-secret` in the defined namespace, so the pods can access it.

### Additional context

What I did was to change locally the following lines:

https://github.com/argoproj/argo-helm/blob/6dab5492689e9f2d389515a7059564f9d0c9fb39/charts/argo-cd/templates/redis-secret-init/job.yaml#L6

https://github.com/argoproj/argo-helm/blob/6dab5492689e9f2d389515a7059564f9d0c9fb39/charts/argo-cd/templates/redis-secret-init/role.yaml#L11

https://github.com/argoproj/argo-helm/blob/6dab5492689e9f2d389515a7059564f9d0c9fb39/charts/argo-cd/templates/redis-secret-init/rolebinding.yaml#L11

https://github.com/argoproj/argo-helm/blob/6dab5492689e9f2d389515a7059564f9d0c9fb39/charts/argo-cd/templates/redis-secret-init/serviceaccount.yaml#L7

and replace them with the following:

```
namespace: {{ include  "argo-cd.namespace" . }}
```

Then I used this modified version of argo-cd chart to build my umbrella chart and everything was deployed correctly without errors.

Shall I create a PR to commit these changes or it is not the proper way to do it?
