### ISSUE TITLE
Sync issue with argo-cd helm chart 7.4.x

### ISSUE THREAD

**Issue by jascsch** [argoproj/argo-helm#2883]
### Describe the bug

There is a sync issue with helm chart version 7.4.x so that apps are stuck in "OutOfSync" status.

### Related helm chart

argo-cd

### Helm chart version

7.4.x

### To Reproduce

use the following manifest and try to sync the dapr app.

```
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dapr
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - kind: Secret
    name: dapr-trust-bundle
    namespace: dapr
    jsonPointers:
      - /data
sources:
  - repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.11.1
    helm:
      valueFiles:
        - $values/tools/dapr/values.yaml
      releaseName: dapr
      skipCrds: true
    chart: dapr
  - repoURL: 'https://git.xxx.com/org/gitops-cluster-dev.git'
    targetRevision: HEAD
    ref: values
```

### Expected behavior

The sync status should be "Synced" instead of "OutOfSync"
The sync works perfectly fine with helm chart version 7.3.x

### Screenshots

![image](https://github.com/user-attachments/assets/34ee0514-976a-490e-8544-479c5fef4e7a)
