### ISSUE TITLE
ArgoCD stuck in `waiting for completion of hook batch/Job/argocd-redis-secret-init`

### ISSUE THREAD

**Issue by oponomarov-tu** [argoproj/argo-helm#2887]
### Describe the bug

Ref: https://github.com/argoproj/argo-helm/pull/2861

I still face the same issues even on Helm charts >= v7.4.1. My ArgoCD deployed on Fargate is managing itself after bootstrap. Tested in clean EKS (v1.30). Attaching `values.yaml` for reference.

<details><summary>Details</summary>
<p>

```yaml
controller:
  replicas: 1
  env:
    - name: ARGOCD_K8S_CLIENT_QPS
      value: "300"
    - name: ARGOCD_SYNC_WAVE_DELAY
      value: "30"
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 1
      memory: 3Gi
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      memory: "1Gi"
applicationSet:
  replicaCount: 1
dex:
  enabled: false
server:
  autoscaling:
    enabled: true
    minReplicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"
redis:
  enabled: false
redis-ha:
  enabled: true
  haproxy:
    enabled: true
    init:
      resources:
        requests:
          memory: 100Mi
          cpu: 10m
        limits:
          memory: 100Mi
    resources:
      requests:
        memory: 200Mi
        cpu: 15m
      limits:
        memory: 200Mi
  redis:
    resources:
      requests:
        memory: 500Mi
        cpu: 20m
      limits:
        memory: 1Gi
  sentinel:
    resources:
      requests:
        memory: 20Mi
        cpu: 10m
      limits:
        memory: 20Mi
  exporter:
    resources:
      requests:
        memory: 25Mi
        cpu: 5m
      limits:
        memory: 25Mi
  init:
    resources:
      requests:
        memory: 25Mi
        cpu: 25m
      limits:
        memory: 25Mi
configs:
  secret:
    githubSecret: "$github-argocd-webhook:webhook.github.secret"
  repositories:
    aws-public-ecr:
      name: aws-public-ecr
      type: helm
      url: public.ecr.aws
      enableOCI: "true"
```

</p>
</details> 

Perhaps the `ttlSecondsAfterFinished` should be configurable? 

### Related helm chart

argo-cd

### Helm chart version

7.4.1

### To Reproduce

1. Install ArgoCD.
2. Let ArgoCD manage itself.

### Expected behavior

Clean sync.

### Screenshots

N/A

### Additional context

N/A

**Comment by yu-croco** [comment]
It's related https://github.com/argoproj/argo-cd/issues/6880 ?

**Comment by oponomarov-tu** [comment]
@yu-croco 
> It's related [argoproj/argo-cd#6880](https://github.com/argoproj/argo-cd/issues/6880) ?

Yes, and it was [allegedly fixed](https://github.com/argoproj/argo-cd/issues/6880#issuecomment-2274495939) in the [following](https://github.com/argoproj/argo-helm/pull/2861) pull request. I was [advised](https://github.com/argoproj/argo-helm/pull/2861#issuecomment-2294457841) to reopen the ticket.

**Comment by speedythesnail** [comment]
I would like to also confirm that I have this issue.
![Screenshot from 2024-08-31 22-35-17](https://github.com/user-attachments/assets/313c0af2-8989-46e4-b102-db1501533adb)

**Comment by speedythesnail** [comment]
I would like to also confirm that I have this issue.

![Screenshot from 2024-08-31 22-35-17](https://github.com/user-attachments/assets/7edba397-3165-4bb4-8fbd-d68ccf06ef17)

**Comment by svianac** [comment]
Hello, I have got the same situation in an Argo of Argos architecture. The managed argos get stuck:
![image](https://github.com/user-attachments/assets/a1b90e40-1a9e-47d1-9ab4-ab0cfd2f13dd)
It tells Pending deletion. However, at cluster level I can see the Job gets created and finishes within a few seconds. But in Argo CD still shows as Running. 

I am using Helm Version 7.4.4, which has already implemented.

**Comment by DoumLaberge** [comment]
I just find the error

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}

There a missing '-' in front of the toYaml

**Comment by oponomarov-tu** [comment]
not stale, still happening

**Comment by GurayCetin** [comment]
same issue for me

**Comment by svianac** [comment]
I finally switched to use Kustomize and worked properly since...

**Comment by GurayCetin** [comment]
issue for me istio-proxy was injected to job, so i disabled it and it worked.

**Comment by ebarped** [comment]
I solved it removing the secret `argocd-redis` and triggering resync

**Comment by y13i** [comment]
> issue for me istio-proxy was injected to job, so i disabled it and it worked.

Same here, in my case added below to Helm values.

```yaml
redisSecretInit:
  podLabels:
    sidecar.istio.io/inject: "false"
```

**Comment by mate4st** [comment]
For me this happens in the latest version (7.8.0) when I set: `ignoreResourceStatusField: all`. It apparently does also ignore statuses when syncing then.

**Comment by rtomadpg** [comment]
I am seeing this issue with Helm chart v7.8.2 and ArgoCD v2.14.2+ad27246.

I am however not seeing this issue with Helm chart v7.7.23 and ArgoCD v2.13.4+102853d.

**Comment by ibauersachs** [comment]
We're still constantly seeing this with ArgoCD v3.0.12 and Helm Chart v8.2.5 (managed by Argo itself). Can this please be reopened?

**Comment by smorfs-house** [comment]
I am also experiencing this with argocd version v3.1.5 and helm chart v8.3.6

**Comment by tsubus** [comment]
this should definitely be re-opened, keeps happening also on v3.1.9 (v9.0.5 chart)

**Comment by myoung34** [comment]
Happens to me annoyingly all the time on `v3.1.9+8665140` as well.

**Comment by ibauersachs** [comment]
We're currently working around this by disabling the secret init (see https://github.com/argoproj/argo-helm/issues/2887#issuecomment-2668163782).

To still be able to bootstrap, we use a script that:
- clones a repo with argo-values.yaml containing `redisSecretInit.enabled: false`
- checks if ArgoCD is not already installed: `if ! kubectl get "deployments/argocd-server" -n argocd; then ...`
- install with `helm upgrade --install --atomic argocd argo-cd/argo-cd --version x.y.z --namespace argocd --values argo-values.yaml --set "redisSecretInit.enabled=true"`
- test if the bootstrap app is not already installed: `kubectl get application/region-bootstrap -n argocd`

The crucial parameter is the additional `--set` in the Helm command that overrides the secret init so that it runs once during bootstrap, not not later on again.

Still, I don't understand why this is necessary.

**Comment by ericblackburn** [comment]
Even if we update it to only run during bootstrap, I would like to be able to automate ArgoCD instance provisioning. So, fixing this at its core is important to me.

**Comment by mhrcm** [comment]
still happening on app version 3.1.2/chart 9.2.0

Can't even do a fresh install

If others are having this issue, you can run an install to create the secret (or create the secret manually), and set redisSecretInit.enabled=false in your values

**Comment by ibauersachs** [comment]
I'm not aware that this would have been solved meanwhile. These "stale" bots are annoying.

**Comment by lucasf-knotch-sw** [comment]
Lets make a bot to comment every single week XD

**Comment by chr0n1x** [comment]
going from helm chart v 9.4.15 --> 9.5.11, happening for me too.

not using istio. I have this in my `values.yaml` (`Chart.yaml` lists argocd 9.5.11 as a dep):

```yaml
argo-cd:
  configs:
    secret:
      createSecret: false
```

deleted the `argocd-redis` secret, terminated the stuck sync process that was waiting for the `batch/v1/Job`, started a new sync operation and things are coming up.

hope that helps anyone else.
