### ISSUE TITLE
ArgoCD Helm Chart Enforcing targetPort on all ports

### ISSUE THREAD

**Issue by azhangsg** [argoproj/argo-helm#2904]
### Describe the bug

When opening a servicePort on the argocd server, we encounter an issue where the containerPort is enforced as the targetPort for all ports opened.

Chart Config
```
containerPorts:
  server: 8080
service:
  servicePortHttpsName: mesh
  servicePortHttps: 20000
```

Resulting Kustomize
```yaml
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: mesh
    port: 20000
    protocol: TCP
    targetPort: 8080
```

### Related helm chart

argo-cd

### Helm chart version

7.1.3

### To Reproduce

1. Open a `servicePort` to a different port on the argocd server
2. Examine the new port's `targetPort` once helm chart is applied

### Expected behavior

I expected the `targetPort` for the new port to be the same as the new port.
