### ISSUE TITLE
secretTemplateAnnotations is null

### ISSUE THREAD

**Issue by eddyfussel** [argoproj/argo-helm#2908]
### Describe the bug

It seems like with helm chart version 7.2.0 onwards (latest tested iI tested is version 7.5.0, still reproducible) there was a little bug introduced when using cert-manager to use cert-manager to create certificates.

### Related helm chart

argo-cd

### Helm chart version

7.5.0

### To Reproduce

Use following `values.yaml`

```yaml
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"

  certificate:
    enabled: true
    issuer:
      kind: "ClusterIssuer"
      name: "letsencrypt-prod"
```

Template the chart with following command:

helm template test argocd/argo-cd --values values.yaml --version 7.5.0 | yq 'select(.kind == "Certificate")'`

```yaml
---
# Source: argo-cd/templates/argocd-server/certificate.yaml
kind: Certificate
metadata:
  name: argocd-server
  namespace: default
  labels:
    helm.sh/chart: argo-cd-7.5.0
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.12.3"
spec:
spec:
  secretTemplate:
  secretName: argocd-server-tls
  commonName: argocd.example.com
```

As you can see  `.secretTemplate` is `null`

### Expected behavior

`.secretTemplate` should not be specified if not needed.
