### ISSUE TITLE
global.affinity.nodeAffinity does not work

### ISSUE THREAD

**Issue by afreyermuth98** [argoproj/argo-helm#2917]
### Describe the bug

I want to deploy my argocd pods on a specific node role using nodeAffinity like this :
```
global:
  affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                  - <MY_NODE_ROLE>

 ```
But this is not replicated inside the manifests and the applications are deployed wherever they can

### Related helm chart

argo-cd

### Helm chart version

7.3.11

### To Reproduce

Deploy the helm release with this kind of helm values

### Expected behavior

argo-cd to be deployed on the good set of nodes

**Comment by yu-croco** [comment]
Hi @afreyermuth98 ,
According to the [values.yaml](https://github.com/yu-croco/argo-helm/blob/5bf013d7c7c1e4463a6bb434887a8d8b75fb1b68/charts/argo-cd/values.yaml#L124-L138), you need to define like below ?

```yaml
global:
  affinity:
    nodeAffinity:
      # -- Default node affinity rules. Either: `none`, `soft` or `hard`
      type: hard
      # -- Default match expressions for node affinity
      matchExpressions:
        - key: role
          operator: In
          values:
            - <MY_NODE_ROLE>
```

You can also read the list of types in README.
https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#global-configs
