### ISSUE TITLE
Modifying the default webhook port breaks the validatingwebhookconfiguration

### ISSUE THREAD

**Issue by nhavens** [argoproj/argo-helm#2926]
### Describe the bug

I've modified the default Argo Events webhook port (`.webhook.port` in the values.yaml) in order to resolve the following errors when using the default port 443:
```json
{"level":"error","ts":1726695996.1391778,"logger":"argo-events.webhook","caller":"webhook/webhook.go:116","msg":"ListenAndServeTLS for admission webhook errored out","error":"listen tcp :443: bind: permission denied","stacktrace":"github.com/argoproj/argo-events/webhook.(*AdmissionController).Run.func1\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:116"}
```
The port on which the `events-webhook` pod listens updates as expected, and the pod runs fine. The port in the auto-generated validatingwebhookconfiguration is also updated. However, the validatingwebhookconfiguration references the `events-webhook` Service, which has its port [hard-coded](https://github.com/argoproj/argo-helm/blob/argo-events-2.4.7/charts/argo-events/templates/argo-events-webhook/service.yaml#L11) to the default value of 443. The result is that the validating webhook does not work.

### Related helm chart

argo-events

### Helm chart version

2.4.7

### To Reproduce

1. Install Argo Events with a values.yaml including the following:
```yaml
webhook:
  enabled: true
  port: 8443
```
2. Note that the `events-webhook` Deployment uses this port:
```
❯ k get deploy events-webhook -o yaml | yq '.spec.template.spec.containers[].ports'
- containerPort: 8443
  name: webhook
  protocol: TCP
```
3. Note also that the auto-generated validatingwebhookconfiguration also uses this port:
```
❯ k get validatingwebhookconfiguration webhook.argo-events.argoproj.io -o yaml | yq '.webhooks[].clientConfig.service'
name: events-webhook
namespace: argo-events
port: 8443
```
4. But, the Service is listening on the default port 443:
```
❯ k get svc events-webhook -o yaml | yq '.spec.ports'
- port: 443
  protocol: TCP
  targetPort: webhook
```
5. As a result, I'm allowed to apply invalid config:
```yaml
# eventbus.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    exotic: {}
```
```
❯ k apply -f eventbus.yaml 
eventbus.argoproj.io/default created
```
6. Note that the EventBus does not work.
```
❯ k get eventbus default -o yaml | yq '.status'
conditions:
  - lastTransitionTime: "2024-09-18T21:57:24Z"
    message: '"spec.nats.exotic.clusterID" is missing'
    reason: InvalidSpec
    status: "False"
    type: Configured
  - lastTransitionTime: "2024-09-18T21:56:02Z"
    status: Unknown
    type: Deployed
config: {}
```

### Expected behavior

The validating webhook configuration should reject the invalid EventBus.
```
❯ k apply -f eventbus.yaml 
Error from server (BadRequest): error when creating "eventbus.yaml": admission webhook "webhook.argo-events.argoproj.io" denied the request: "spec.nats.exotic.clusterID" is missing
```
