### ISSUE TITLE
Support lifecycle hooks for Argo Workflows Server

### ISSUE THREAD

**Issue by BojanZelic** [argoproj/argo-helm#2996]
### Is your feature request related to a problem?

Whenever argo workflows server pods are rollout-restarted, evicted, ect a small blip of downtime occurs when using AWS ALB ingress resource to expose argo workflows (but probably true with any load balancer)

### Related helm chart

argo-workflows

### Describe the solution you'd like

expose configurations of `lifecycle` param to set a preStop hook, and a configuration for `terminationGracePeriodSeconds` to allow pods to persist any remaining connections

### Additional context

ex:

```
#values.yaml
  server:
   lifecycle:
     preStop: 
       exec:
         command:
           - /bin/sh
           - -c
           - |
             sleep 60;

    terminationGracePeriodSeconds: 65
```

would allow it to have enough time to remove the IP from AWS ALB, ensuring no-downtime deployments
