### ISSUE TITLE
ArgoCD Helm: Impossible to get a PDB for redis-ha

### ISSUE THREAD

**Issue by mruoss** [argoproj/argo-helm#3007]
### Describe the bug

Currently in the [ArgoCD redis/pdb helm template](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/redis/pdb.yaml#L2), there's logic that prevents the PDB to be created if redis-ha is enabled. This doesn't make sense, right? I'd even argue that PDB for HA is necessary?

### Related helm chart

argo-cd

### Helm chart version

7.6.12

### To Reproduce

use the following values when deploying:

```yaml
redis-ha:
  enabled: true
redis:
  pdb:
    enabled: true
    minAvailable: 1
```

### Expected behavior

this should create a PDB resource
