### ISSUE TITLE
argocd-apps does not fully support App in any namespace

### ISSUE THREAD

**Issue by mugioka** [argoproj/argo-helm#3033]
### Is your feature request related to a problem?

Before argocd-apps v2, it was possible to configure settings as shown below, which fully supported applications in any namespace:
```yaml
applications:
  - name: apps
    namespace: ns-1
  - name: apps
    namespace: ns-2
    # nits
```
However, since argocd-apps v2, the definition format has changed from a list to a map, making the application name the key of the map. As a result, the above configuration is no longer possible, and it no longer fully supports applications in any namespace.

### Related helm chart

argocd-apps

### Describe the solution you'd like

To resolve this issue, I believe the application name should be overridable. For example, it could be structured as follows:
```yaml
applications:
  apps-1:
    name: apps
    namespace: ns-1
  apps-2:
    name: apps
    namespace: ns-2
    # nits
```
