### ISSUE TITLE
Disabling haproxy with redis-ha results in broken deployment yaml

### ISSUE THREAD

**Issue by randori-jgross** [argoproj/argo-helm#3052]
### Describe the bug

If redis-ha is deployed with haproxy disabled, the helper for the redis sentinel secrets will be blank.

Given these values:

```yaml
redis-ha:
  enabled: true
  haproxy:
    enabled: false
```

This helper:

https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/_helpers.tpl#L57-L60

Will print nothing, leaving deployments with blank secret names:

https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L197

```bash
cannot patch "argo-argocd-repo-server" with kind Deployment:
Deployment.apps "argo-argocd-repo-server" is invalid:
[spec.template.spec.containers[0].env[17].valueFrom.secretKeyRef.name: Invalid value: ""  
[spec.template.spec.containers[0].env[18].valueFrom.secretKeyRef.name: Invalid value: ""

cannot patch "argo-argocd-server" with kind Deployment:
Deployment.apps "argo-argocd-server" is invalid: 
[spec.template.spec.containers[0].env[30].valueFrom.secretKeyRef.name: Invalid value: ""
[spec.template.spec.containers[0].env[31].valueFrom.secretKeyRef.name: Invalid value: ""
```

Is deploying redis-ha without haproxy supported?

### Related helm chart

argo-cd

### Helm chart version

7.7.5

### To Reproduce

Set the above values.yaml and template the helm chart:

```bash
helm template -f values.yaml argo/argo-cd | grep REDIS_SENTINEL -A5
```

With this output:

```yaml
          - name: REDIS_SENTINEL_USERNAME
            valueFrom:
              secretKeyRef:
                name:
                key: redis-sentinel-username
                optional: true
          - name: REDIS_SENTINEL_PASSWORD
            valueFrom:
              secretKeyRef:
                name:
                key: redis-sentinel-password
                optional: true
```

### Expected behavior

Have a check in the helpers that prohibits this configuration, or if the configuration is valid, then have an `{{- else -}}` statement that will print the correct values for redis-ha without haproxy.
