### ISSUE TITLE
Disabling redis auth - still results in "Secret argocd-redis not found" error

### ISSUE THREAD

**Issue by bhavinkotak** [argoproj/argo-helm#3057]
### Describe the bug

If redis-ha is deployed with `auth: false` and redisSecretInit also disabled - it used to work fine in our previous helm chart version of `7.3.11`; however, when we updated the helm chart to `7.7.5` - the same setup started failing with error `"Secret argocd-redis not found"` for different deployment and stateful set components of argocd.

Given these values:

```
redis-ha:
  enabled: true
  auth: false
redis:
  enabled: false
redisSecretInit:
  enabled: false
```

### Related helm chart

argo-cd

### Helm chart version

7.7.5

### To Reproduce

1. Deploy argocd helm chart v7.3.11 with below values.yaml setup for redis-ha

```
redis-ha:
  enabled: true
  auth: false
redis:
  enabled: false
redisSecretInit:
  enabled: false
```

2. It deploys perfectly fine
3. Now try to upgrade the argocd helm chart to v7.7.5 and keep same values.yaml 
4. Now argocd-app-controller, argocd-server, etc components will start failing with error "Secret argocd-redis not found"the 

### Expected behavior

Argocd upgrade from 7.3.11 to 7.7.5 should work fine with all the components being healthy.

### Additional context

Issue seems to be related to optional flag not correctly set for environment variable of REDIS_PASSWORD
For e.g., https://github.com/argoproj/argo-helm/blob/3e1b02da23a7398f5be6401bd763c7a0c5e41859/charts/argo-cd/templates/argocd-server/deployment.yaml#L252C11-L261C27

`optional: true` field should be present even when externalRedis.host is not provided

```
name: {{ default "argocd-redis" .Values.externalRedis.existingSecret }}
{{- if .Values.externalRedis.host }}
key: redis-password
optional: true
{{- else }}
key: auth
{{- end }}
```
