### ISSUE TITLE
ArgoCD installtion ingore helm values

### ISSUE THREAD

**Issue by lexdevelop** [argoproj/argo-helm#3065]
### Describe the bug

I'm trying to configure argocd during helm installation using helm values. This is my config.
```
crds:
  install: true
  keep: false
global:
  domain: argocd.mysite.com
config:
  repositories:
    - name: devops
      url: https://github.com/my-org/devops.git
      type: git
      githubApp:
        appID: xxxxxxx
        installationID: xxxxxxx
        privateKeySecret:
          name: argocd-github-app
          key: privateKey
  cm:
    create: true
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github-app:clientId
            clientSecret: $argocd-github-app:clientSecret
            orgs:
            - name: my-org
              teams:
              - dev-admin
  rbac:
    create: true
    policy.default: 'role:none'
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow
      p, role:org-admin, logs, get, *, allow
      p, role:org-admin, exec, create, */*, allow
      g, my-org:dev-admin, role:org-admin
controller:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
dex:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi
redis:
  enabled: true
  resources:
     limits:
       cpu: 50m
       memory: 128Mi
     requests:
     cpu: 10m
     memory: 32Mi
server:
  replicas: 1
  service:
    type: ClusterIP
  extraArgs:
    - "--insecure"
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
```
Sensitive values are replaced.
After installation is done dex  configuration does not exists in  config map, and rbac config map has empty value for policy.csv and policy.default, also repository defined above does not exist.
This is my installation command:
```
helm repo add argo https://argoproj.github.io/argo-helm
helm upgrade --install argocd argo/argo-cd \
  --namespace argocd \
  --create-namespace \
  --version 7.7.7 \
  --values ./path-to/values.yaml
```

### Related helm chart

argo-cd

### Helm chart version

7.7.7

### To Reproduce

1. Populate helm value  dex configuration
2. Populate helm value  rbac  policy config
3. Populate  helm value  repository

### Expected behavior

Dex config does not exist in config map.
Rbac policy is empty policy.csv and policy.default
Repository is not being created after success helm install
