### ISSUE TITLE
Cant log in after setting config.secret.argocdServerAdminPassword

### ISSUE THREAD

**Issue by zilinjak** [argoproj/argo-helm#3089]
### Describe the bug

Here are my values:

```
server:
  service:
    type: LoadBalancer
    servicePortHttp: 30000
    servicePortHttps: 30001

config:
  secret:
    argocdServerAdminPassword: '<HASH>'
    argocdServerAdminPasswordMtime: '<DATE>'
```

HASH=$(htpasswd -nbBC 10 "" admin | tr -d ':\n' | sed 's/$2y/$2a/')
DATE=$(TZ=UTC date -u +"%Y-%m-%dT%H:%M:%SZ") -> I live in UTC+1

### Related helm chart

argo-cd

### Helm chart version

7.7.11

### To Reproduce

1. Install helm with values provided above
2. Open argo-cd and enter admin/admin
3. you will be denied

### Expected behavior

Step 3 from 'To Reproduce' will be fine and process to the apps page

**Comment by yu-croco** [comment]
Hi @zilinjak , Are you sure that your values.yaml is correct ?
argo-helm don't have `config.secret` but `configs.secret`.

I could logged in with `admin` user and the `foobar` password in my local environment (kind cluster) with argo-cd v7.7.10.

password generator
```sh
$ ARGO_PWD="foobar"
$ htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'
$2a$10$ZpPYOE0VG9bVDs.2MyIzFe4neMhrCCncoAnhJ/Ul8KD/ghIgHK3v2
```

values.yaml in my umbrella chart.
```yaml
argo-cd:
  configs:
    secret:
      argocdServerAdminPassword: $2a$10$ZpPYOE0VG9bVDs.2MyIzFe4neMhrCCncoAnhJ/Ul8KD/ghIgHK3v2
      argocdServerAdminPasswordMtime: '2006-01-02T15:04:05Z' # used an example on values.yaml
```
