### ISSUE TITLE
Chart argo-events does not use controller.initContainers

### ISSUE THREAD

**Issue by guillermomolina** [argoproj/argo-helm#3094]
### Describe the bug

As stated in [README](https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/README.md), one should be able to declare an init container using the syntax similar to the other charts, but this value is not referenced in the [template](https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/templates/argo-events-controller/deployment.yaml)

### Related helm chart

argo-events

### Helm chart version

1.9.3

### To Reproduce

1. Use this values.yaml

```yaml
controller:
  initContainers:
    - name: get-ca-bundle
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
      args: 
        - cp -Lr /etc/ssl/certs/* /tmp/target/
```

2. Install chart via helm
```bash
helm -n argo-events upgrade argo-events argo/argo-events \
		--install --create-namespace --wait -v=5 --debug -f values.yaml
```

### Expected behavior

Create the init container
