### ISSUE TITLE
Notifications controller resource requests/limits not being applied

### ISSUE THREAD

**Issue by kenlasko** [argoproj/argo-helm#3102]
### Describe the bug

I've created resource requests/limits for all ArgoCD components and they are all working fine, except for the notifications controller.

### Related helm chart

argo-cd

### Helm chart version

7.7.12

### To Reproduce

1. In `values.yaml`, add the following:
```
notifications:
  resources:
    requests:
      cpu: 1m
      memory: 110Mi
    limits:
      cpu: 120m
      memory: 150Mi
```
2. Update the ArgoCD application
3. Note that the notifications controller does not have the resource requests/limits applied

### Expected behavior

The resource requests/limits should be applied to the notifications controller as it is for all other ArgoCD resources

### Screenshots

![image](https://github.com/user-attachments/assets/e2d65316-bfe5-4dba-8012-3b9afb84974c)

**Comment by yu-croco** [comment]
I ran `helm template . > foo.yaml` on my local environment with argo-cd Helm Chart v7.7.12 and it seems that `resources` are reflected? 🤔 

- values.yaml
```yaml
notifications:
  resources:
    requests:
      cpu: 1m
      memory: 110Mi
    limits:
      cpu: 120m
      memory: 150Mi
```

- result
```yaml
# Source: argo-cd/templates/argocd-notifications/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-argocd-notifications-controller
  namespace: default
  labels:
    helm.sh/chart: argo-cd-7.7.12
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v2.13.2"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: argo-cd-7.7.12
        app.kubernetes.io/name: argocd-notifications-controller
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: notifications-controller
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/version: "v2.13.2"
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: argocd-notifications-controller
      automountServiceAccountToken: true
      containers:
        - name: notifications-controller
          image: quay.io/argoproj/argocd:v2.13.2
          imagePullPolicy: IfNotPresent
          args:
            - /usr/local/bin/argocd-notifications
            - --metrics-port=9001
            - --loglevel=info
            - --logformat=text
            - --namespace=default
            - --argocd-repo-server=release-name-argocd-repo-server:8081
            - --secret-name=argocd-notifications-secret
          env:
            - name: ARGOCD_NOTIFICATIONS_CONTROLLER_LOGLEVEL
              valueFrom:
                configMapKeyRef:
                  key: notificationscontroller.log.level
                  name: argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_NOTIFICATIONS_CONTROLLER_LOGFORMAT
              valueFrom:
                configMapKeyRef:
                  key: notificationscontroller.log.format
                  name: argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_APPLICATION_NAMESPACES
              valueFrom:
                configMapKeyRef:
                  key: application.namespaces
                  name: argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_NOTIFICATION_CONTROLLER_SELF_SERVICE_NOTIFICATION_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: notificationscontroller.selfservice.enabled
                  name: argocd-cmd-params-cm
                  optional: true
            - name: ARGOCD_NOTIFICATION_CONTROLLER_REPO_SERVER_PLAINTEXT
              valueFrom:
                configMapKeyRef:
                  key: notificationscontroller.repo.server.plaintext
                  name: argocd-cmd-params-cm
                  optional: true
          ports:
          - name: metrics
            containerPort: 9001
            protocol: TCP
          resources:
            limits:
              cpu: 120m
              memory: 150Mi
            requests:
              cpu: 1m
              memory: 110Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          workingDir: /app
          volumeMounts:
            - name: tls-certs
              mountPath: /app/config/tls
            - name: argocd-repo-server-tls
              mountPath: /app/config/reposerver/tls
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-notifications-controller
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: tls-certs
          configMap:
            name: argocd-tls-certs-cm
        - name: argocd-repo-server-tls
          secret:
            secretName: argocd-repo-server-tls
            optional: true
            items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            - key: ca.crt
              path: ca.crt
      dnsPolicy: ClusterFirst
```
