### ISSUE TITLE
Chart argo-cd: ingress annotation template error

### ISSUE THREAD

**Issue by rverchere** [argoproj/argo-helm#3114]
### Describe the bug

When trying to update to argo-cd chart version 7.7.14, I get the following error:

``` 
Error: Failed to render chart: exit status 1: Error: template: argo-cd/templates/argocd-server/ingress.yaml:17:23: executing "argo-cd/templates/argocd-server/ingress.yaml" at <$value>: wrong type for value; expected string; got bool
```

It is related to the PR [#3081](https://github.com/argoproj/argo-helm/pull/3081) which enable ingress templating.

My custom values are:

```yaml
server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: true
```

Modifying the annotations by converting from bool to string corrects the issue:

```yaml
server:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
```

### Related helm chart

argo-cd

### Helm chart version

7.7.14

### To Reproduce

1. Add a custom value in server.ingress.annotations with a boolean value
2. Try to install/update

### Expected behavior

Annotation should be set as previously, maybe by converting bool to string.
