### ISSUE TITLE
Redis helm chart checksum/secret recalculation

### ISSUE THREAD

**Issue by farioas** [argoproj/argo-helm#3130]
### Describe the bug

When using Redis with Bitnami Helm charts and deploying via an idempotent templating approach (e.g., ArgoCD), the checksum/secret annotation in Redis StatefulSet gets updated on subsequent runs of helm template. This causes the StatefulSet to trigger rolling updates unnecessarily, as the secret checksum changes after the first run.

This behavior impacts temporary or short-lived environments (e.g., feature branches), where the secrets do not stabilize before the environment is destroyed.

### Related helm chart

other

### Helm chart version

20.6.3

### To Reproduce

1. Start with an empty deployment environment and the following values:
```yaml
redis:
  auth:
    enabled: true
  master:
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
    persistence:
      enabled: true
  tls:
    enabled: true
    autoGenerated: true
```
3. Run the following command to deploy Redis:
```sh
helm template my-redis bitnami/redis --values values.yaml | kubectl apply -f -
```
Redis is successfully deployed.
3. Run the following command to check for diffs:
```sh
helm template my-redis bitnami/redis --values values.yaml | kubectl diff -f -
```
Observed Diff:
```diff
- checksum/secret: dd4b1164e04884db75f070df18ce8f45027481216c93a89a3f0209f41acedea2
+ checksum/secret: ce23a18a82b6efbd5aa7104b1e0c7d8359ddce635b61678ee723a01b60371652
```
4. Apply the changes:
```sh
helm template my-redis bitnami/redis --values values.yaml | kubectl apply -f -
```
5. Run the diff again:
**No Diff:** The checksum remains stable after this step.

### Expected behavior

The `checksum/secret` annotation should not change between runs unless there is an actual change in the secret values. This would prevent unnecessary rolling updates and stabilize Redis deployments, particularly for short-lived environments.

### Additional context

This behavior appears to be linked to ArgoCD’s idempotent reconciliation strategy, where it regenerates templates on each sync.
Long-running deployment are not affected, as the checksum stabilizes over time.
Related issues in Bitnami Charts:
https://github.com/bitnami/charts/issues/29406
https://github.com/bitnami/charts/issues/24870

This issue is particularly disruptive in CI/CD pipelines for feature branch environments where consistency is critical for testing.
