### ISSUE TITLE
Add a helm template that creates the imagePullSecret

### ISSUE THREAD

**Issue by docbyte86** [argoproj/argo-helm#3140]
### Is your feature request related to a problem?

I need to create the namespace manually and add the secret to the namespace.

### Related helm chart

argo-cd, argo-events, argo-rollouts, argo-workflows, argocd-image-updater, argocd-apps

### Describe the solution you'd like

A secret for the imagePullSecrets will be created during installation of the helm chart.

Example:

https://github.com/longhorn/longhorn/blob/master/chart/templates/registry-secret.yaml

```
privateRegistry:
  # -- Setting that allows you to create a private registry secret.
  createSecret: ~
  # -- URL of a private registry. When unspecified, Longhorn uses the default system registry.
  registryUrl: ~
  # -- User account used for authenticating with a private registry.
  registryUser: ~
  # -- Password for authenticating with a private registry.
  registryPasswd: ~
  # -- Kubernetes secret that allows you to pull images from a private registry. This setting applies only when creation of private registry secrets is enabled. You must include the private registry name in the secret name.
  registrySecret: ~
```
