### ISSUE TITLE
`additionalUrls` array gets stringified

### ISSUE THREAD

**Issue by KevinMahoneyFS** [argoproj/argo-helm#3161]
### Describe the bug

The additionalUrls config parameter gets turned into a string

### Related helm chart

argo-cd

### Helm chart version

7.7.3

### To Reproduce

values.yaml:

```
configs:
  cm:
    additionalUrls:
      - a.com
      - b.com
```

creates a ConfigMap:

```
data:
  additionalUrls: '[a.com b.com]'
```

### Expected behavior

the array should be preserved in the ConfigMap

**Comment by yu-croco** [comment]
According to [the official doc](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/#argocd-cmyaml-example), you were supposed to configure like below?

```yaml
configs:
  cm:
    additionalUrls: |
      - https://argo-cd-demo2.argoproj.io
```
