### ISSUE TITLE
Define a liveness probe for the argo-workflows server

### ISSUE THREAD

**Issue by Julienlin** [argoproj/argo-helm#3174]
### Is your feature request related to a problem?

We experienced a case where the argo-workflows server died and was not responding. This could have been fixed easily by a restart from initiated by Kubernetes.

### Related helm chart

argo-workflows

### Describe the solution you'd like

We would like to have something similar to what the argo-workflows controller has: 

```yaml
          livenessProbe: {{ .Values.server.livenessProbe | toYaml | nindent 12 }}
```
values.yaml:
```yaml
  # -- Configure liveness [probe] for the server
  # @default -- See [values.yaml]
  livenessProbe:
    httpGet:
      port: 2746
      path: /
    failureThreshold: 3
    initialDelaySeconds: 90
    periodSeconds: 60
    timeoutSeconds: 30
```

### Additional context

It comes to our attention that the argo workflow server does not provide a health check endpoint (see https://github.com/argoproj/argo-workflows/discussions/7066). But we could use the same endpoint as the readiness probe to have something that can be used as a liveness probe.
