### ISSUE TITLE
Argo-server does not show any archived workflows

### ISSUE THREAD

**Issue by olevski** [argoproj/argo-helm#323]
**Describe the bug**
Argo-server does not show archived workflows in the web UI - even though they appear in the database and the workflow controller says that workflow archiving has been enabled.

**To Reproduce**
1. Create a new GKE cluster on GCP by using web UI (k8s version 1.14.10-gke27, single zone: us-west-2a, 1 node, no autoscaling, n1-standard-4, defaults for everything else)
2. Connect kubectl context
`gcloud container clusters get-credentials <cluster-name> --zone <zone-name> --project <gcp-project-name>`
3. Install postgres with default values from helm 
`helm install argo-workflows-db bitnami/postgresql`
4. Create secret with database username and password as required by argo for workflow persistence
```bash
export POSTGRES_PASSWORD=$(kubectl get secret --namespace default argo-workflows-db-postgresql -o jsonpath="{.data.postgresql-password}" )
# see additional context below for secrets k8s spec file
k apply -f db-secret.yaml
```
5. Install argo `helm install argo-test argo/argo -f values.yaml`. See [gist here](https://gist.github.com/olevski/306a3eb05abf6cb98b905b8105d6cca5) for values.yaml file. The only difference from default is the persistence section which I uncommented and properly aligned. The whole persistence section is not properly aligned btw - I will submit a PR for this.
6. Edit clusterrole so that controller can get the postgres secret. Will submit an issue for this as the helm chart currently allows only the server to get access to secrets but not the workflow controller, and the workflow controller needs access to at least the secret with the postgres username and password for persistence to work. 
    - `kubectl edit clusterrole argo-test-workflow-controller-cluster-role`
    - paste the following at the end and save
```yaml
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
```
7. Run [hello world workflow](https://github.com/argoproj/argo/blob/master/examples/README.md#hello-world) `argo submit --serviceaccount argo hello-world.yaml`

**Expected behavior**
Once the workflow completes the postgres database is populated with information of the workflow that completed and the workflow should appear in the 'Archived workflows' section of the website from argo-server. However this does not happen and the workflow information appears only in the database but not in the archived workflows section.
```
➜  ~ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default argo-workflows-db-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
➜  ~ kubectl run argo-workflows-db-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.7.0-debian-10-r82 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host argo-workflows-db-postgresql -U postgres -d postgres -p 5432
postgres=# select uid,name,phase,namespace,startedat,finishedat,clustername from argo_archived_workflows;
                 uid                  |       name        |   phase   | namespace |      startedat      |         finishedat         | clustername
--------------------------------------+-------------------+-----------+-----------+---------------------+----------------------------+-------------
 e2a768ae-8848-11ea-bf96-42010aa800a4 | hello-world-nt8cm | Succeeded | default   | 2020-04-27 05:35:20 | 2020-04-27 05:35:41.441299 | default
(1 row)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16360283/80337869-d3f29980-880f-11ea-98aa-fb223ed72363.png)

![image](https://user-images.githubusercontent.com/16360283/80337887-dce36b00-880f-11ea-8a5b-37628a7296bf.png)

**Additional context**
```yaml
# db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
type: Opaque
data:
  username: cG9zdGdyZXMK # base64 of default postgres username
  password: XXXXXXXXX # fill in with base64 encoded string, the value of POSTGRES_PASSWORD variable exported earlier
```
[workflow-controller-logs.txt](https://github.com/argoproj/argo-helm/files/4537734/workflow-controller-logs.txt)
[argo-server-logs.txt](https://github.com/argoproj/argo-helm/files/4537736/argo-server-logs.txt)

**Comment by yujingz** [comment]
@olevski its an argo issue. they will have the fix in 2.7

**Comment by olevski** [comment]
> @olevski its an argo issue. they will have the fix in 2.7

@yujingz isn't work underway already on 2.8.0? Do you know if any 2.7.x release has this fix or you mean that none of them do and a new argo release should address this?

**Comment by yujingz** [comment]
@olevski since this helm project is still on version 2.6 i thought you were on 2.6 as well. see the related PR here https://github.com/argoproj/argo/pull/2523

**Comment by paguos** [comment]
Hi @olevski I experienced the same issue. The problem was the argo server was pointing out to the wrong config map in the helm charts. You can see with fix [here](https://github.com/argoproj/argo-helm/blob/de30e84cf4a21b3c5a23d5f5105e77e56e9b99f8/charts/argo/templates/server-deployment.yaml#L33). #296 and #307 should have fix all the issues of the archive workflows in the server.

**Comment by wxmiked** [comment]
@paguos I'm working with the original poster @olevski . We finally figured out that the problem is that `persistence.archive` is missing from the Helm template and `values.yaml` file. This config option is documented here in this [rather cryptic doc](https://github.com/argoproj/argo/blob/master/docs/workflow-archive.md).

If you edit the `argo-workflow-controller-configmap` ConfigMap after installing the latest version of the Argo Helm chart (0.9.3) to add the `persistence.archive` variable set to true, the Postgres archiving works as expected.
```
apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: docker
    artifactRepository:
      archiveLogs: true
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-artifact-cred
        secretKeySecret:
          key: secretkey
          name: argo-artifact-cred
        bucket: my-bucket-refactor-argo-artifact
        endpoint: storage.googleapis.com
        insecure: true
    metricsConfig:
      enabled: true
      path: /metrics
      port: 8080
    persistence:
      archive: true
      postgresql:
        database: postgres
        host: postgres-argo-postgresql
        passwordSecret:
          key: postgresql-password
          name: postgres-argo-postgresql
        tableName: argo_workflows
        userNameSecret:
          key: username
          name: postgres-argo-config
```
![Screen Shot 2020-05-19 at 5 10 46 PM](https://user-images.githubusercontent.com/7704035/82390591-f6816800-99f3-11ea-99a3-9b4d42ded5bd.png)
