### ISSUE TITLE
Service account secret is not created but requested by agent pods

### ISSUE THREAD

**Issue by m-kay** [argoproj/argo-helm#3236]
### Describe the bug

With the flag `workflow.serviceAccount.create` a service account with the name argo-workflow is created without a corresponding service account secret. This secret however is requested when creating a workflow step with the http template. 

### Related helm chart

argo-workflows

### Helm chart version

0.45.0

### To Reproduce

1. Install argo-workflows chart with values `workflow.serviceAccount.create=true` and `workflow.rbac.agentPermissions=true`
2. create a workflow with a step using the http template
3. start the workflow

The http step is keeps stuck in a pending state.  When checking the pods which are created there is a pod in the state PodInitializing with the error "secret "argo-workflow.service-account-token" not found".

After creating this secret manually everything works fine:
```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: argo-workflow.service-account-token
  annotations:
    kubernetes.io/service-account.name: "argo-workflow"
```

### Expected behavior

I would expect the chart to create the service account secret since this is required by the agent pods.
