### ISSUE TITLE
Argo Workflows yaml parsing issue

### ISSUE THREAD

**Issue by headyj** [argoproj/argo-helm#3243]
### Describe the bug

Hello,
None of our workflows are running after going from 0.45.3 to 0.45.12. I'm seeing errors like these:

``` 
Failed: invalid spec: templates.full-pipeline.steps[0].full-pipeline templates.full-pipeline.tasks.task1 failed to resolve {{workflow.parameters.parameter1"},{"name":"upgrade-config","value":"{{tasks.task2.outputs.parameters.parameter2}}
```
I feel like it's not parsing the yaml correctly:
```
[...]
          arguments:
            parameters:
              - name: backendImages
                value: '{{`{{workflow.parameters.backendImages}}`}}'
              - name: instance
                value: '{{`{{workflow.parameters.instance}}`}}'
              - name: project
                value: '{{`{{workflow.parameters.project}}`}}'
              - name: parameter0
                value: '{{`{{workflow.parameters.parameter0}}`}}'
              - name: parameter1
                value: '{{`{{workflow.parameters.parameter1`}}'
              - name: parameter2
                value: '{{`{{tasks.task2.outputs.parameters.parameter2}}`}}'
[...]
```

This workflow is working fine in v0.45.3.

I also have these kind of errors:
```
  Failed: invalid spec: templates.full-pipeline.steps[0].full-pipeline templates.full-pipeline cannot use both 'depends' and 'dependencies' in the same DAG template
```
I do have both "depends" and "dependencies" on my template, but "dependencies" are commented out so I guess there is something wrong with the parsing?

Reverting to 0.45.3 fixed the issue

### Related helm chart

argo-workflows

### Helm chart version

0.45.12

### To Reproduce

- Create a dag pipeline with at least 2 tasks
- Configure a parameters referencing a previous task output

### Expected behavior

Workflow template should be parsed correctly
