### ISSUE TITLE
ArgoCD namespace installation - Enhance RBACs for application-controller to allow app-of-app patterns

### ISSUE THREAD

**Issue by abhijith-darshan** [argoproj/argo-helm#3285]
### Is your feature request related to a problem?

When using the argocd chart in a namespace scoped installation, the app of app pattern via `ApplicationSets` cannot be implemented.

Example:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: 'dev'
    - clusters:
        selector:
          matchLabels:
            environment: 'prod'
  template:
    metadata:
      name: '{{.name}}-app-of-apps'
      namespace: greenhouse
    spec:
      project: "default"
      source:
        repoURL: https://github.com/foo/bar
        targetRevision: 'main'
        path: helm/argo-application/template
        helm:
          valueFiles:
            - "values-{{.name}}.yaml"
      destination:
        name: ''
        namespace: namespace-argocd-is-running
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          selfHeal: true
```

This will result in an error because `argocd` will attempt to list / get every resource in the namespace it is running, indicating RBACs are missing for `argocd-application-controller`

### Related helm chart

argo-cd

### Describe the solution you'd like

Add the following rules for https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-application-controller/role.yaml

```yaml
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch
```

Since this is readOnly permissions, it should allow the usage of _app-of-app_ pattern maintained declaratively in git via `ApplicationSets`

### Describe alternatives you've considered

Currently this is being resolved via using the `extraObjects` field in `values.yaml`

```yaml
extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: app-of-apps-argocd-application-controller
      namespace: namespace-argo-is-running
    rules:
      - apiGroups:
          - argoproj.io
        resources:
          - applications
          - applicationsets
          - appprojects
        verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: app-of-apps-argocd-application-controller
      namespace: greenhouse
    subjects:
      - kind: ServiceAccount
        name: argocd-application-controller
        namespace: namespace-argo-is-running
    roleRef:
      kind: Role
      name: app-of-apps-argocd-application-controller
      apiGroup: rbac.authorization.k8s.io
```

The problem here is the namespace needs to be added to the subjects of `RoleBinding` and the values itself cannot be templated.

### Additional context

The comparison error that you would see without the role -

```
Failed to load live state: failed to get cluster info for "https://kubernetes.default.svc": error synchronizing cache 
state : failed to sync cluster https://api.gitops.k8s.com:443: failed to load initial state of resource ResourceQuota: 
resourcequotas is forbidden: User "system:serviceaccount:argo-hbgf3x:argocd-application-controller" cannot 
list resource "resourcequotas" in API group "" in the namespace "argo-hbgf3x"
```

**Comment by mike-code** [comment]
I've encountered the same problem and I've also tried another workaround to add resource inclusions to the `argocd-cm`, like so:

```yaml
  resource.inclusions: |
    - clusters: ["*"]
      apiGroups:
      - argoproj.io
      kinds:
      - Application
      - ApplicationSet
      - AppProject
    - clusters: ["*"]
      apiGroups: []
      kinds:
      - Event
      - Secret
      - ConfigMap
```

However, I still get 
```
level=error msg="Failed to sync cluster" error="failed to load initial state of resource ApplicationSet.argoproj.io: applicationsets.argoproj.io is forbidden: User \"system:serviceaccount:argocd:argocd-application-controller\" cannot list resource \"applicationsets\" in API group \"argoproj.io\"
```

which is expected because applicationsets are not listed in application-controller SA (though they are in applicationset-controller SA)
