### ISSUE TITLE
`server.extensions` installing in the wrong path

### ISSUE THREAD

**Issue by Sturgelose** [argoproj/argo-helm#3320]
### Describe the bug

When using `server.extensions` in the helm chart, extensions are being installed in the wrong path. They are expected in `/tmp/extensions` but they are instead inside `/tmp/extensions/resources`.

The CI test defined [here](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/ci/extension-values.yaml) is configured properly but it is not doing a full validation checking that the extensions are being loaded as expected in the UI, so it is not failing...

The issue seems to come from the `argocd-extension-installer` [repo](https://github.com/argoproj-labs/argocd-extension-installer/issues/6). I opened a [PR](https://github.com/argoproj-labs/argocd-extension-installer/pull/14) to fix it, but seems there is no answer yet.

Either we configure this repo to load the proper mount path of the extension installer (add `/resources` [here](https://github.com/argoproj/argo-helm/blob/d1a211b8062530afacc90e63c17648fd4863239b/charts/argo-cd/templates/argocd-server/deployment.yaml#L470)), or we merge in my PR to install the extensions in the expected path already.

Also, seems that the CI, would be nice to check that the extension is really working.

### Related helm chart

argo-cd

### Helm chart version

8.0.9

### To Reproduce

1. Install with the following values
```
server:
  extensions:
    enabled: true
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.7/extension.tar
      - name: extension-metrics
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.3/extension.tar.gz
          - name: EXTENSION_CHECKSUM_URL
            value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.3/extension_checksums.txt
```

2. open a shell to the pod, see that extensions are being loaded into `/tmp/extensions/resources` and UI extensions are not visible in the dashboard.

### Expected behavior

UI Extensions should be visible in the dashboard and they should be loaded from `/tmp/extensions/resources` or extensions-installer image to be updated with the right path.
