### ISSUE TITLE
Rename redis-ha.exporter.image

### ISSUE THREAD

**Issue by renklus** [argoproj/argo-helm#3322]
### Is your feature request related to a problem?

The argo-cd helm chart values do not use the usual naming for `redis-ha.exporter.image` and `redis-ha.exporter.tag`. This seems to trip up the renovate managers 'helm-values' and 'kubernetes'

1. The renovate manager will not detect the image version in values.yaml and will not update it: #3314 only updates line 1438 in values.yaml but missed the same image on line 1717
2. The renovate manager will not detect the image version in an argocd Helm-Application and will not update it (example see below)
3. The renovate manager tries to pin the image name in an argocd Helm-Application with a sha256 digest (see `redis-ha.exporter.image` for the value that renovate suggests)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: 'argo-cd'
    targetRevision: '8.0.10'
    helm:
      parameters:
        - name: 'server.service.type'
          value: 'LoadBalancer'        
      valuesObject:
        global:
          image:
            repository: 'quay.io/argoproj/argocd'
            tag: 'v3.0.3@sha256:95b5cf7ba6fe9b3a336de3209748475350d4fbc918c3ce508eb4cb2aa7ac2d1e'
        server:
          extensions:
            image:
              repository: 'quay.io/argoprojlabs/argocd-extension-installer'
              tag: 'v0.0.8@sha256:e7cb054207620566286fce2d809b4f298a72474e0d8779ffa8ec92c3b630f054'
        dex:
          image:
            repository: 'ghcr.io/dexidp/dex'
            tag: 'v2.43.1@sha256:0881d3c9359b436d585b2061736ce271c100331e073be9178ef405ce5bf09557'
        redis:
          exporter:
            image:
              repository: 'ghcr.io/oliver006/redis_exporter'
              tag: 'v1.73.0@sha256:1a8f5e48b2af0fb02d182be3ddd623e7e39881b6464bdb5bf843b1f6d45ed050'
          image:
            repository: 'public.ecr.aws/docker/library/redis'
            tag: '8.0.1-alpine@sha256:62b5498c91778f738f0efbf0a6fd5b434011235a3e7b5f2ed4a2c0c63bb1c786'
        redis-ha:
          exporter:
            image: 'ghcr.io/oliver006/redis_exporter@sha256:1a8f5e48b2af0fb02d182be3ddd623e7e39881b6464bdb5bf843b1f6d45ed050'
            # renovate: datasource=docker depName=ghcr.io/oliver006/redis_exporter
            tag: 'v1.73.0@sha256:1a8f5e48b2af0fb02d182be3ddd623e7e39881b6464bdb5bf843b1f6d45ed050'
          image:
            repository: 'public.ecr.aws/docker/library/redis'
            tag: '8.0.1-alpine@sha256:62b5498c91778f738f0efbf0a6fd5b434011235a3e7b5f2ed4a2c0c63bb1c786'
        configs:
          cm:
            "users.session.duration": '22h'
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

### Related helm chart

argo-cd

### Describe the solution you'd like

- rename 'redis-ha.exporter.image' to 'redis-ha.exporter.image.repository'
- rename 'redis-ha.exporter.tag' to 'redis-ha.exporter.image.tag'

### Describe alternatives you've considered

- Ensuring updates by renovate is possible by setting up a custom regex manager.
- I could not find a way to stop renovate from trying to pin the image name in 'redis-ha.exporter.image' with a sha256 digest (which would break the deployment)
