### ISSUE TITLE
[argo-rollouts] Clusterrole does not contain all required permissions for OpenShift

### ISSUE THREAD

**Issue by johnkost** [argoproj/argo-helm#340]
**Describe the bug**
After deploying Argo Rollouts via Helm in our OpenShift (3.11) cluster, I tried to perform a rollout; however, it failed due to missing permissions. I manually added the following which resolved the issue:
```
- apiGroups:
  - '*'
  attributeRestrictions: null
  resources:
  - '*/finalizers'
  verbs:
  - '*'
```

**To Reproduce**
1. Deploy the `rollout` chart on an OpenShift cluster. 
2. Apply a rollout crd

**Expected behavior**
Assuming no modifications made to the chart, the chart should rollout `rollouts` which is able to correctly handle the Rollout CRDs.

**Additional context**
