### ISSUE TITLE
email notifier doesn't work

### ISSUE THREAD

**Issue by dcommisso** [argoproj/argo-helm#394]
**Describe the bug**
In the [argocd-notifications](https://github.com/argoproj/argo-helm/tree/master/charts/argocd-notifications), setting `email` notifier in values.secret.notifier doesn't work: no email are sent and argocd-notifications-controller pod logs `Failed to process: email is not valid recipient type` error.

**To Reproduce**
1. add email configuration to chart values file, E.G.
```
secret:
  notifiers:
    email:
      host: <host>
      port: <port>
      from: <from address>
      username: <username>
      password: <password>
```

2. Apply configuration

**Expected behavior**
argocd-notifications sends the emails

**Additional context**
Email configuration is documented [here](https://argoproj-labs.github.io/argocd-notifications/services/overview/) and the code that sends email is present as well — [here](https://github.com/argoproj-labs/argocd-notifications/blob/master/notifiers/email.go). I would happy to make a PR to add missing code to helm chart.
