### ISSUE TITLE
argocd-notifications Failed to notify recipient slack:argocd-dev defined in app argocd/platform: not_in_channel

### ISSUE THREAD

**Issue by ofirshtrull** [argoproj/argo-helm#420]
**Describe the bug**
created the slack app via https://argoproj-labs.github.io/argocd-notifications/services/slack/

I have installed argo-notifications via helm with the next config (managing it via argocd)
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
spec:
  project: codebashing
  source:
    helm:
      values: |
        triggers:
          - name: on-sync-failed
            enabled: true
          - name: on-health-degraded
            enabled: true
          - name: on-sync-succeeded
            enabled: true
        secret:
          notifiers:
            slack:
              enabled: true
              token: <token>
        subscriptions:
          - recipients:
            - slack:argocd-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

after all is in place i get this errors from the argocd-notifications-controller

`│ time="2020-08-06T12:21:26Z" level=error msg="Failed to notify recipient slack:argocd-dev defined in app argocd/argocd-notifications: not_in_channel" app=argocd/argocd-notifications`
`│ time="2020-08-06T12:22:57Z" level=error msg="Failed to notify recipient slack:argocd-dev defined in app argocd/app-of-apps: not_in_channel" app=argocd/app-of-apps`

**Expected behavior**
send a slack notification
