### ISSUE TITLE
argocd-server includes argocd-darwin-amd64 and argocd-windows-amd64.exe

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo-helm#431]
**Describe the bug**

**To Reproduce**
1. install argocd into kubernetes using:
    ```
    name: argo
    apiVersion: v2
    appVersion: "1.0"
    description: Argo Workflow
    version: 0.9.8
    dependencies:
      - name: argo
        version: 0.9.8
        repository: https://argoproj.github.io/argo-helm
    ```
1.  connect to argocd-server
1. `ls /usr/local/bin/argocd*`:
    ```
    /usr/local/bin/argocd			      /usr/local/bin/argocd-darwin-amd64  /usr/local/bin/argocd-server	/usr/local/bin/argocd-windows-amd64.exe
    /usr/local/bin/argocd-application-controller  /usr/local/bin/argocd-repo-server   /usr/local/bin/argocd-util
    ```

**Expected behavior**
don't package non linux binaries into the application.

**Screenshots**

**Additional context**
