### ISSUE TITLE
Support as a subchart

### ISSUE THREAD

**Issue by filippomc** [argoproj/argo-helm#521]
When using argo as a dependency of another helm chart, the application name takes from the parent.
For example id Argo is installed as a subchart of mychart, argo-server is deployed as mychart-server. There are also references to argo-server (service account and deployment) so argo won't work in that case.

The name I can see is coming from the use in templates of the release name as in `{{ .Release.Name }}-{{ .Values.server.name}}`
Maybe it could be changed directly to  `argo-{{ .Values.server.name}}` rather than using the release name, which is not really adding anything crucial (we can install as many argos as we want in different namespaces or change server.name variable).

**Comment by mkilchhofer** [comment]
Hi @filippomc,
What chart did you try to use as a subchart? Could could you share that info with us? :)

**Comment by filippomc** [comment]
Hi @mkilchhofer the chart named **argo**.

**Comment by tgruenert** [comment]
I think this is also an issue in argo-cd chart. 

My scenario is a self managed argo-cd. I have to customize configuration with values.yaml overwrite files. But this is impossible because
a) if i use helm chart from public repo I can´t define a values file from other source
b) if i use argo-cd as subchart to use helm values overwrite system i don´t get a working deployment. Good indicator is the missing NOTES.txt output at the end of such a deployment.

It´s a kind of chicken-egg-problem.

I assume the problem is the same as @filippomc mentioned but if not, i really like to open an other issue with that.

**Comment by mkilchhofer** [comment]
> I think this is also an issue in argo-cd chart.
> 
> My scenario is a self managed argo-cd. I have to customize configuration with values.yaml overwrite files. But this is impossible because
> a) if i use helm chart from public repo I can´t define a values file from other source
> b) if i use argo-cd as subchart to use helm values overwrite system i don´t get a working deployment. Good indicator is the missing NOTES.txt output at the end of such a deployment.
> 
> It´s a kind of chicken-egg-problem.
> 
> I assume the problem is the same as @filippomc mentioned but if not, i really like to open an other issue with that.

Hmm I don't see a problem with `argo-cd` as a subchart.
regarding a): sure you can achieve this without creating an umbrella chart:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  syncPolicy: {}
  source:
    chart: chartmuseum
    repoURL: https://chartmuseum.github.io/charts/
    targetRevision: "3.0.0"
    helm:
      releaseName: chartmuseum
      version: v3
      # look at the following line:
      values: |-
        fullnameOverride: chartmuseum
        env:
          open:
            DISABLE_API: false
            STORAGE: local
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            ingress.kubernetes.io/force-ssl-redirect: "true"
            kubernetes.io/ingress.class: contour
          enabled: true
          hosts:
          - name: chartmuseum.example.com
            path: /
            tls: true
            tlsSecret: chartmuseum-ingress-cert
```
regarding b): yeah, the NOTES from the subchart are not printed - this is normal behaviour.
If there are other problems for argo-cd as a subchart, please file a separate bug 😃 

Back to the initial issue regarding the `argo` chart @filippomc :
The chart got refactored in PR #668. The new chart `argo-workflows` uses a templating function for the objects name. You can override the prefix with the common value`nameOverride`. Would you mind to test, if the problem still exists, @filippomc?
