### ISSUE TITLE
Failed to query provider - AzureAD; unsupported protocol scheme

### ISSUE THREAD

**Issue by gurjmatharu** [argoproj/argo-helm#531]
Hi, I'm trying to get SSO integrated with argocd, with our Azure AD.

I'm following the oidc tutorial [here](https://argoproj.github.io/argo-cd/operator-manual/user-management/microsoft/#azure-ad-app-registration-auth-using-oidc)

Once I have my configurations deployed I see a "Login Via" button:
<img width="292" alt="Screen Shot 2021-01-02 at 1 50 12 PM" src="https://user-images.githubusercontent.com/9407864/103467201-79480080-4d01-11eb-8ca0-f0c5f1d7ada3.png">

Once I click it I receive the following error:
`Failed to query provider "": Get "/.well-known/openid-configuration": unsupported protocol scheme ""`

My OIDC Config:
```
oidc.config: |
      name: Azure
      issuer: https://login.microsoftonline.com/<Tenant ID>/v2.0
      clientID: <Client ID>
      clientSecret: <Client Secret>
      requestedIDTokenClaims:
          groups:
              essential: true
      requestedScopes:
          - openid
          - profile
          - email
```

I'm not entirely sure how to debug this.  Any feedback is welcome!
