### ISSUE TITLE
Add env support in helm chart deployment.yaml for argocd-notifications

### ISSUE THREAD

**Issue by guanwei** [argoproj/argo-helm#571]

**Comment by 1Psy** [comment]
Hi added by https://github.com/argoproj/argo-helm/pull/580

For example add to values.yaml
```yaml
extraEnv:
  - name: HTTP_PROXY
    value: "http://proxy:3128"
```
