### ISSUE TITLE
ArgoCD helm chart could not be deployed through ArgoCD

### ISSUE THREAD

**Issue by dimitarKiryakov** [argoproj/argo-helm#585]
**Describe the bug**
We have an ArgoCD which is deploying argocd's based on the helm chart in this repository. However, the deployment fails with the following error: 
```
`helm template . --name-template argo --namespace default --set redis-ha.enabled=true --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions crd.projectcalico.org/v1 --api-versions argoproj.io/v1alpha1 --api-versions cert.gardener.cloud/v1alpha1 --api-versions dns.gardener.cloud/v1alpha1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status 1: Error: found in Chart.yaml, but missing in charts/ directory: redis-ha
```
The error is caused by the `.helmignore` file which contains the following:
```
*.tgz
output
```

The problematic part here is `*.tgz`, which is causing the above error

**To Reproduce**
1. Clone argocd helm repo locally
2. Execute `helm dependency update`
3. Execute the following template command:
```
helm template . --name-template argo --namespace default --set redis-ha.enabled=true --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions crd.projectcalico.org/v1 --api-versions argoproj.io/v1alpha1 --api-versions cert.gardener.cloud/v1alpha1 --api-versions dns.gardener.cloud/v1alpha1 --api-versions snapshot.storage.k8s.io/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds
```
4. Remove `*.tgz` from `.helmignore` and the issue will be resolved

**Expected behavior**
ArgoCD should be able to deploy argocd chart

**Comment by dimitarKiryakov** [comment]
https://github.com/argoproj/argo-helm/pull/586

**Comment by mkilchhofer** [comment]
I have the same issue when I manually run `helm template` to implement and validate #619.

**Comment by wilmardo** [comment]
I was surprised by this today too, but with an other error then above, I used this manifest:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
# Makes the delete cascade
# https://argoproj.github.io/argo-cd/user-guide/app_deletion/#about-the-deletion-finalizer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: iks-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo/argo-cd
    targetRevision: 2.17.4
    helm:
      values: |
           <values>
```
But this will result in this error:
> rpc error: code = Unknown desc = `helm pull --destination /tmp/helm847955618 --version 2.17.4 --repo https://argoproj.github.io/argo-helm argo/argo-cd` failed exit status 1: Error: chart "argo/argo-cd" version "2.17.4" not found in https://argoproj.github.io/argo-helm repository

I can reproduce this locally:
```console
# helm pull --destination /tmp/helm847955618 --version 2.17.4 --repo https://argoproj.github.io/argo-helm argo/argo-cd
Error: chart "argo/argo-cd" version "2.17.4" not found in https://argoproj.github.io/argo-helm repository
```
