### ISSUE TITLE
[argo-cd] resource name may not be empty error in chart version 2.14.6

### ISSUE THREAD

**Issue by abdennour** [argoproj/argo-helm#590]
**Describe the bug**
argocd helm chart is not functional.
Always throw the error: 
```
error: resource name may not be empty
```

**To Reproduce**
1. Prepare your values 'myvalues.yaml' with INGRESS enabled

```yaml
server:
  extraArgs:
  - --insecure
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Forwarded-Proto https;
    hosts:
      - cd.example.com

```

2. Run now `helm upgrade .... -v 2.14.6 -f myvalues.yaml`
3. Then you have to see now the issue

**Expected behavior**
The chart must be functional

**Screenshots**
N/A

**Additional context**
- helm version: v3.2.4
- argocd version: 1.8.4
- helm chart version: 2.14.6
