### ISSUE TITLE
[argo-cd] Discussion about component name customization and code simplification/dedup (esp. regarding labels)

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-helm#624]
**Is your feature request related to a problem? Please describe.**
I wanted to contribute some code optimization regarding the resource labels.
I noticed, that there is the possibility to override each component's name. Do we actually need this? This code is here since chart version `1.0.0`:
```yaml
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.server.name }} # <--- see this
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }} # <--- and see this
```
When this is not explicitly needed, we could reduce some code and use the basic helm3 skeleton for the labels:
```yaml
{{/*
Common labels
*/}}
{{- define "foo.labels" -}}
helm.sh/chart: {{ include "foo.chart" . }}
{{ include "foo.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "foo.selectorLabels" -}}
app.kubernetes.io/name: {{ include "foo.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
```

**Describe the solution you'd like**
Use a standard function for the labels and dedup code.

**Describe alternatives you've considered**
Still support this customization but use a function for code dedup.

**Additional context**
- https://github.com/argoproj/argo-helm/blob/650abd1eb1fe26a2af5a21c79d371480ea44bf8c/charts/argo-cd/templates/argocd-application-controller/deployment.yaml#L6-L13
- https://github.com/argoproj/argo-helm/blob/650abd1eb1fe26a2af5a21c79d371480ea44bf8c/charts/argo-cd/templates/argocd-configs/argocd-cm.yaml#L6-L12
- https://github.com/argoproj/argo-helm/blob/650abd1eb1fe26a2af5a21c79d371480ea44bf8c/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L6-L13
