### ISSUE TITLE
Run argo in ingress subpath(non-root)

### ISSUE THREAD

**Issue by gruppferi** [argoproj/argo-helm#655]
**Describe the bug**
I am trying to deploy argo in subpath i.e. example.com/argocd but getting 404 for UI. I used the recent helmchart and overwrite following stuff. domain name is changed to example.com for privacy matters
**To Reproduce**
1. set extra vars 
```
  extraArgs:
    - --rootpath
    - /argocd
    - --basehref
    - /argocd
 ```
2. Ingress configs
```

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"

    labels: {}
    hosts:
      - example.com
    paths:
      - /argocd(/|$)(.*)
    extraPaths:
      []
      # - path: /*
      #   backend:
      #     serviceName: ssl-redirect
      #     servicePort: use-annotation
    tls:
      - secretName: argocd-secret
        hosts:
          - example.com
    https: false

```
3. SSL terminates in cluster and certificate is deployed in ingress-controller
4. set SSO
```
  configEnabled: true
  config:
    # Argo CD's externally facing base URL (optional). Required when configuring SSO
    url: https://example.com/argocd
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance
    oidc.config: |
      name: Keycloak
      issuer: example.com/auth/realms/example
      clientID: argocd
      clientSecret: someSecrets
      requestedScopes: ["openid", "profile", "email", "groups"]
```
Cluster Info
- Kubernetes 1.19.7
- Using Nginx Ingress Controller
- Using Keycloak for SSo running on same cluster 

Expected behavior
access UI of argo

**Comment by sanzenwin** [comment]
I am facing this issues too, any solutions ?

**Comment by sanzenwin** [comment]
I have resolved it by checking [argo-cd-doc-for-ingress](https://argoproj.github.io/argo-cd/operator-manual/ingress/#argocd-server-and-ui-root-path-v153).
 `values.yaml`:
```
server:
  extraArgs:
    - --rootpath
    - /argocd
    - --basehref
    - /argocd

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/configuration-snippet: |-
        proxy_ssl_server_name on;
        proxy_ssl_name $host;
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/secure-backends: "true"
    paths:
      - /argocd(/|$)(.*)
    hosts:
      - argocd-site.com
    tls:
      - hosts:
          - argocd-site.com
        secretName: the_argocd_tls_secret
    https: true

  config:
    url: https://argocd-site.com/argocd
```
