### ISSUE TITLE
[argocd] env setting handling is broken

### ISSUE THREAD

**Issue by KlavsKlavsen** [argoproj/argo-helm#662]
**Describe the bug**

**To Reproduce**
I tried setting:
Server:
  env:
  - MYENVAR: 23

This results in 
env:
  - MYENVVAR: 23

But should have resulted in:
env:
  - name: MYENVVAR
    value: 23

as done here f.ex.
https://github.com/KongZ/charts/blob/90c5af59c56c66fb1d46f7eb8c48c0a93058d89e/charts/graylog/templates/statefulset.yaml#L72

**Comment by KlavsKlavsen** [comment]
I set this on deployemnt - and k8s rolls out pod just fine with the following:
```
env:                                                                                                                            
- name: ARGOCD_HELM_INDEX_CACHE_DURATION
  value: 300s 
```

But argocd complains:
map: map[ARGOCD_HELM_INDEX_CACHE_DURATION:300s] does not contain declared merge key: name

:(

**Comment by chgl** [comment]
The downside of splitting the args into name, value pairs instead of the `toYaml` way is that it prevents you from reading the env vars from somewhere else, such as an existing secret:

```yaml
env:
  - name: ARGOCD_SOME_SECRET_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: password
```

Where does the `map: map[ARGOCD_HELM_INDEX_CACHE_DURATION:300s] does not contain declared merge key: name` message come from? I did a quick install using the following `values.yaml` in an empty cluster and it seems to work fine:

```yaml
server:
  env:
    - name: ARGOCD_HELM_INDEX_CACHE_DURATION
      value: 300s

controller:
  env:
    - name: ARGOCD_HELM_INDEX_CACHE_DURATION
      value: 300s

repoServer:
  env:
    - name: ARGOCD_HELM_INDEX_CACHE_DURATION
      value: 300s
```
