### ISSUE TITLE
Expose Type in Server Ingress

### ISSUE THREAD

**Issue by Sherwoodwt** [argoproj/argo-helm#67]
To set up ArgoCD Server behind a Load Balancer, the service must be type LoadBalancer. The service template (argocd-server-service.yaml) doesn't include a way to set the type based on a values file.

I'd like to be able to set the type using a values file. The only workarounds I've found for this have been to either fork the repo, modify the one template file and reference the forked repo, or to call `kubectl patch` to set the type after creation as suggested here: https://argoproj.github.io/argo-cd/getting_started/#service-type-load-balancer.

Here's an example of what the fix might look like:
```
# argocd-server-service.yaml

apiVersion: v1
kind: Service
metadata:
  ...
spec:
  type: {{ .Values.server.serviceType }}
  ports:
     ...
  selector:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-server
```
