### ISSUE TITLE
[argo-cd] manifest generation bug

### ISSUE THREAD

**Issue by marcozov** [argoproj/argo-helm#723]
**Describe the bug**
Configuration generation with custom values reports an error:
```
helm template -s templates/argocd-application-controller/deployment.yaml . --values values-2.yaml
Error: YAML parse error on argo-cd/templates/argocd-application-controller/deployment.yaml: error converting YAML to JSON: yaml: line 109: did not find expected key

Use --debug flag to render out invalid YAML
```
**To Reproduce**
0. Download argo-helm and go in `charts/argo-cd/` directory.
1. Add the following values to `values-2.yaml` 
```
controller:
  volumeMounts:
    - name: ca-proxy
      mountPath: /usr/share/custom-ca-certificates
  volumes:
    - name: ca-proxy
      secret:
        secretName: ca-proxy
```
2. run `helm template -s templates/argocd-application-controller/deployment.yaml . --values values-2.yaml`

**Expected behavior**
The volumes and volumeMounts related configurations should be properly generated.

**Additional context**
The problem is that in one of the recent changes in the chart, these entries have been added in the `templates/argocd-application-controller/deployment.yaml` file:
```
        volumeMounts:
        - mountPath: /app/config/controller/tls
          name: argocd-repo-server-tls
{{- if .Values.controller.volumeMounts }}
{{- toYaml .Values.controller.volumeMounts | nindent 10}}
...
...
      volumes:
      - name: argocd-repo-server-tls
        secret:
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          - key: ca.crt
            path: ca.crt
          optional: true
          secretName: argocd-repo-server-tls
{{- if .Values.controller.volumes }}
{{- toYaml .Values.controller.volumes | nindent 8 }}
```
For volumeMounts, the indentation of the `argocd-repo-server-tls` volume is 8, not 10.
For volumes, the indentation of `argocd-repo-server-tls` is 6, not 8.
The solution is either reduce the indentation from 10 to 8 and from 8 to 6, or to move the blocks 2 spaces away.
A PR will follow with my proposal.
