### ISSUE TITLE
[argo-workflows] setting controller.extraEnv[] causes Helm install to fail

### ISSUE THREAD

**Issue by ebr** [argoproj/argo-helm#768]
Adding `controller.extraEnv` to `values.yaml` fails `helm install` with the following message:

```
Error: YAML parse error on argo-workflows/templates/controller/workflow-controller-deployment.yaml: error converting YAML to JSON: yaml: line 63: did not find expected key                                                   
Encountered a bad command exit code!
```

**To Reproduce**

Modify `values.yaml` as such:

```
controller
  extraEnv:
    - name: MAX_OPERATION_TIME
      value: 120s
```

Run `helm install .... -f values.yaml` as usual

**Expected behavior**
The release should be installed with the extra env vars applied to the controller
