### ISSUE TITLE
[argo-cd] Add note about argocdServerAdminPassword when deployed through Argo CD

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-helm#785]
Follow-up issue of #784

When deploying the `argo-cd` chart via an ArgoCD instance, we need to take care how we inject the `argocdServerAdminPassword`. If we define it like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-testing
spec:
  destination:
    namespace: testing
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.21.0
    helm:
      parameters:
      - name: configs.secret.argocdServerAdminPassword
        value: $2a$10$H1a30nMr9v2QE2nkyz0BoOD2J0I6FQFMtHS0csEg12RBWzfRuuoE6
```
It does not work because ArgoCD uses variable substitution in the parameters section.

However, if we define it in the `values` section, this works as expected:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-testing
spec:
  destination:
    namespace: testing
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.21.0
    helm:
      values: |
        configs:
          secret:
            argocdServerAdminPassword: $2a$10$H1a30nMr9v2QE2nkyz0BoOD2J0I6FQFMtHS0csEg12RBWzfRuuoE6
```
We should at least place a hint inside the Chart's README.md
