### ISSUE TITLE
[argo-workflows] SSO --auth-mode argument not set

### ISSUE THREAD

**Issue by wsams** [argoproj/argo-helm#792]
Hello, while trying to enable SSO authentication we noticed the `--auth-mode=sso` flag was not being added to the argo server command. As far as I can tell there are no other properties that can enable this behavior other than using `extraArgs`. Are we missing a setting or could this be a bug? Thanks, Weldon

**To Reproduce**
Apply the helm chart with the following sso values (with the URLs replaced with the real values):
```
server:
  secure: true
  sso:
    issuer: https://uaa.example.com
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    redirectUrl: https://argo.example.com/oauth2/callback
    scopes:
    - openid
```

**Expected behavior**
It is expected that `--auth-mode=sso` would be added to the argo server container command. Like this on the argo server deployment:
```
spec:
  containers:
  - args:
    - server
    - --configmap=argo-workflow-controller-configmap
    - --auth-mode=sso
    - --secure
```

**Additional context**
If we add,
```
extraArgs:
- "--auth-mode=sso"
```
it is added as expected. Otherwise that flag is missing.
