### ISSUE TITLE
[argo-cd] Sync podAntiAffinity for application-controller with upstream manifests

### ISSUE THREAD

**Issue by mkilchhofer** [argoproj/argo-helm#802]
**Describe the bug**
Saw this in Slack:
> **Jesper Berg Axelsen:**
> Hi guys. We are trying to make the argocd-application-controller highly available and in the helm chart I have changed the value `enableStatefulSet` to true and created 3 replicas and added `ARGOCD_CONTROLLER_REPLICAS`  to env variables. However, when Kubernetes schedules this statefulset, all my replicas are scheduled on the same node. This means that when this node fails, I completely lose my application controller. Is this intended? Is there any way to secure that these are scheduled on different nodes? Or some other way to work around it?
Ref: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1623140214208100

@jannfis  from the upstream project answered:
> **jannfis**
Hey, in the original manifests (i.e. native installation, not via Helm) there are anti affinity rules for the controller pods. You may want to address this to the Helm chart maintainers (possibly in #argo-helm-charts)

**To Reproduce**
See above

**Expected behavior**
The component `application-controller` has set an podAntiAffinity.

**Screenshots**
See above

**Additional context**
- https://github.com/argoproj/argo-cd/issues/4549
- https://github.com/argoproj/argo-cd/pull/4599

**Comment by silverraven691** [comment]
Not stale

**Comment by pdrastil** [comment]
@silverraven691 @mkilchhofer I've just checked HA deployment that we are running with 3.11.1 version of the chart and I see both application-controllers on different nodes. Is this still an issue if you have similar configuration?

```yaml
controller:
  enableStatefulSet: true
  replicas: 2
  env:
    # Must match number of replicas
    - name: ARGOCD_CONTROLLER_REPLICAS
      value: "2"
  # Add pod anti-affinity for HA deployment
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: argocd-application-controller
            topologyKey: kubernetes.io/hostname
          weight: 100
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/part-of: argocd
            topologyKey: kubernetes.io/hostname
          weight: 5
```
