### ISSUE TITLE
Any plan for releasing HA version of helm chart ?

### ISSUE THREAD

**Issue by jawlitkp** [argoproj/argo-helm#804]
Any plan for releasing the HA version of the helm chart? similar to the YAML file here 

https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml

**Comment by toneill818** [comment]
I think the README.md is a bit missleading. By default it will install the non HA version, but my modifying the values you can get the same deployment as the HA install. I was able to get an HA deployment by setting the following values

```yaml
redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2
    
repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2   
```
