### ISSUE TITLE
[argo-cd] server.config has no effect

### ISSUE THREAD

**Issue by plutino** [argoproj/argo-helm#808]
**Describe the bug**
With this simple `value.yaml`:
```yaml
  server:
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
```
argocd-cm is not updated and the two helm repos are not added.

This seems to be introduced by https://github.com/argoproj/argo-helm/pull/689
The repos are added properly with version 3.2.5, but are not added in latest 3.6.8

**To Reproduce**
1. Update values.yaml to include
```yaml
  server:
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
```
2. Run `helm upgrade`

**Expected behavior**
`argocd repo list` shows the two helm repos
