### ISSUE TITLE
Argo-Workflows: artifact-repositories configmap has to be manually created

### ISSUE THREAD

**Issue by mhaddon** [argoproj/argo-helm#814]
Setting the artifactRepository variable with the new argo-workflows breaks the new version of argo as it cannot find this key (key unsupported errors).

To fix this you need to create a configmap like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: myworkflowsnamespace
  annotations:
    workflows.argoproj.io/default-artifact-repository: gcs
data:
  gcs: |
    gcs:
      bucket: "mybucket"
```

The namespace the configmap is installed in should respect `workflow.namespace`.
