### ISSUE TITLE
ArgoCD - Add richer support for service monitor by allowing relabeling configs

### ISSUE THREAD

**Issue by AlexDHoffer** [argoproj/argo-helm#818]
**Is your feature request related to a problem? Please describe.**

One of the more unfortunate aspects of the ArgoCD exported metrics suite is that the cluster is defined as the URL of the apiserver (see the metric argocd_cluster_info and its label "server" as an example). It doesn't maintain the name of the cluster in any of its metrics, which is troublesome because I don't think that many people can identify a cluster by its apiserver unless the apiserver URL has the name of the cluster in it. 

To circumvent this, one could feasibly modify the service monitor for the ArgoCD application controller like so:

````
endpoints:
  - interval: 30s
    metricRelabelings:
      - action: replace
         regex: https://[the-url-to-ClusterA-apiserver]:443
         replacement: ClusterA
         sourceLabels:
           - server
         targetLabel: server
````

But, the Helm chart does not have any values provided for additional configs e.g. metricRelabelings, so we have to populate these ad-hoc/outside of a VCS.

**Describe the solution you'd like**

It would be nice if options like metricRelabelings were allowed for the service monitor manifest.

**Describe alternatives you've considered**

Making ad-hoc changes to the service monitor. Sucking it up and identifying a cluster by its API server.
