### ISSUE TITLE
ArgoCD: dex configuration with multiple hosts.

### ISSUE THREAD

**Issue by shivakumar12** [argoproj/argo-helm#819]
**Is your feature request related to a problem? Please describe.**
We are looking for an option to configure multiple hosts in dex configuration for high availability. Since we do not have loadbalancer URL configured. As of now we are pointing to individual LDAP host in dex, if the host is down means login will be blocked. Hence looking the solution for multiple LDAP hosts in dex config.

Can someone help on this, If this feature is present. Please provide us the example for implementation.

**Comment by pdrastil** [comment]
@shivakumar12 @mkilchhofer Maybe this might help you. There is missing sample in values.yaml but you can define multiple connectors via following section that goes into `argocd-cm` ConfigMap based on the [documentation](https://argoproj.github.io/argo-cd/operator-manual/user-management/#2-configure-argo-cd-for-sso)

```yaml
server:
  config:
    dex.config: |
      connectors:
        # GitHub example
        - type: github
          id: github
          name: GitHub
          config:
            clientID: aabbccddeeff00112233
            clientSecret: $dex.github.clientSecret
            orgs:
            - name: your-github-org
        # GitHub enterprise example
        - type: github
          id: acme-github
          name: Acme GitHub
          config:
            hostName: github.acme.com
            clientID: abcdefghijklmnopqrst
            clientSecret: $dex.acme.clientSecret
            orgs:
            - name: your-github-org
```
