### ISSUE TITLE
Webhook EventSource does not create a webhook service when the parameter is provided

### ISSUE THREAD

**Issue by DTavaszi** [argoproj/argo-helm#820]
**Describe the bug**
When I create a Webhook EventSource, and make use of the "service" parameter to automatically create a webhook-svc, the service isn't being created. 

However, when I create the same webhook event source with the quick-install instructions at: https://argoproj.github.io/argo-events/installation/, the webhook-svc is indeed created.

**To Reproduce**
To reproduce the steps, deploy the following manifest on the default installation of this argo-helm, and compare it to the installation of argo-events using the quick-install at (https://argoproj.github.io/argo-events/installation/). 

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service: 
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      port: "12000"
      endpoint: /example
      method: POST
```

**Additional context**
The quick-install adds additional services for webhooks that seems to be missing from the argo-helm install, or were missed on our end - I'm not quite sure.

**Comment by shuvozula** [comment]
For anyone having similar issues, check the Argo-events Controller-Manager logs, if the service isn't getting created, the logs will have something on it b/c that's whats creating the EventSource. I had the same problem, the service was getting created automatically before, but after fixing the errors, I was able to move forward.

In my case, I have 2 webhooks defined like so (corrected copy):
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: tc-events-webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 3000
        targetPort: 3000
        name: submit-part-mfx-proto
      - port: 3001
        targetPort: 3001
        name: submit-bom-mfx-proto
  webhook:
    submit-tc-part-events-webhook:
      port: "3000"
      endpoint: /submit_part_mfx_proto
      method: POST
    submit-tc-bom-events-webhook:
      port: "3001"
      endpoint: /submit_bom_mfx_proto
      method: POST
```
What was missing earlier was the `name` field for `spec.ports.[0].` and `spec.ports.[1]` blocks, so the error in the Controller manager was like this.
```
{"level":"error","ts":1670527400.8570108,"logger":"argo-events.eventbus-controller","caller":"eventsource/controller.go:55","msg":"reconcile error","namespace":"argo-events","eventSource":"tc-events-webhook","error":"Service \"tc-events-webhook-eventsource-svc\" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]","stacktrace":"github.com/argoproj/argo-events/controllers/eventsource.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventsource/controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```
Also had to make sure the port-names were RFC1123 compatible (use hyphens, not dashes).

Check k8s services docs here: https://kubernetes.io/docs/concepts/services-networking/service/
