### ISSUE TITLE
No support for organisation wide git credentials

### ISSUE THREAD

**Issue by arenstar** [argoproj/argo-helm#839]
**Is your feature request related to a problem? **

From Helm values i should be able to express organisation wide git credentials.

**Describe the solution you'd like**

It really should be as simple as something like this...

```
server:
  config:
    url: https://argocd.example.com
    repositories: |
      - name: config
        sshPrivateKeySecret:
          key: id_rsa
          name: argocd-repository-credentials
        type: git
        url: git@bitbucket.org:example/argocd-config.git
    credentials: |
      - name: example
        url: git@bitbucket.org:example
        sshPrivateKeySecret:
          name: argocd-repository-credentials
          key: id_rsa

configs:
  repositoryCredentials:
    id_rsa: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      etc
```
      
We should add support for credential templates

**Comment by srosell-uz** [comment]
As far as I have been able to test (and for what I understand from you question), looking on the template ([argocd-cm.yaml](https://github.com/argoproj/argo-helm/blob/6bbcd833d4398745b3bd133cea233ebda40e4c98/charts/argo-cd/templates/argocd-configs/argocd-cm.yaml#L14) all what you put under server.config it goes straight to the CM, so you just have to put the correct configuration that this CM allows on ArgoCD which from your example would be changing the _server.config.credentials_ for _server.config.repository.credentials_.

For a clear example something like:
`
server:
  config:
    url: https://argocd.example.com
    repositories: |
      - name: config
        sshPrivateKeySecret:
          key: id_rsa
          name: argocd-repository-credentials
        type: git
        url: git@bitbucket.org:example/argocd-config.git
    repository.credentials: |
      - name: example
        url: git@bitbucket.org:example
        sshPrivateKeySecret:
          name: argocd-repository-credentials
          key: id_rsa

configs:
  repositoryCredentials:
    id_rsa: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      etc
`

Hope this helps on your doubt as I think what you are requesting is already covered.

**Comment by charlrvd** [comment]
I have the same kind of issue where I am using the recommended `repository.credentials` with github app for org wide access.
But I fail to make it work via helm/declarative setup.

It work for single repo with ssh, and is visible in the UI, like so:
```
    config:
      repositories: |
        - type: git
          name: single-repo
          url: git@github.com:myorg/my-repo.git
          sshPrivateKeySecret:
            name: repository-credentials
            key: sshPrivateKey
```

But the credentials is failing:
```
    config:
      repositories.credentials: |
        - url: https://github.com/myorg
          githubAppID: "<app id>"
          githubAppInstallationID: "<install id>"
          githubAppPrivateKeySecret:
            name: repo-creds
            key: githubAppPrivateKey
```
I've tried with and without the quotes around the appid and install id numbers but that didn't change anything.
I know the github app itself works because if I add the same values via the UI I can add apps that points to private repos. But if I remove the template credentials that was created via the UI then adding apps pointing to private repo fails.

I am using argoCD  `v2.0.5+4c94d88`, let me know if I should open a separate issue or if I missed something very obvious in the doc.
