### ISSUE TITLE
Using AWS ALB with SSL results in a 404 page not found

### ISSUE THREAD

**Issue by btomasini** [argoproj/argo-helm#848]
I am running the argocd helm chart with the following spec:

```
  values:
    server:
      extraArgs:
      - --insecure
      service:
        type: NodePort
      ingress:
        paths:
        - /*
        pathType: ImplementationSpecific
        enabled: true
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/subnets: "test-ingress-a, test-ingress-b"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/ssl-redirect: '443'
        hosts:
          - argo.test.mycompany.com
        https: true
      ingressGrpc:
        enabled: true
        isAWSALB: true
```

The ALB is using an SSL cert provided by ACM, so no TLS is configured in the ingress here.  The pod and services all seem to be running, however, when I access https://argo.test.mycompany.com (actual domain name is different), I always get:

`404 page not found`

I have also run a port-forwarder directly against the pod and see the same behavior. (e.g. after port forward, http://localhost:8080 produces a 404.)

Here is the log output from the pod:

```
time="2021-07-28T14:41:42Z" level=info msg="Starting configmap/secret informers"
time="2021-07-28T14:41:42Z" level=info msg="Configmap/secret informer synced"
time="2021-07-28T14:41:42Z" level=info msg="Starting configmap/secret informers"
time="2021-07-28T14:41:42Z" level=info msg="secrets informer cancelled"
time="2021-07-28T14:41:42Z" level=info msg="configmap informer cancelled"
time="2021-07-28T14:41:42Z" level=info msg="Configmap/secret informer synced"
time="2021-07-28T14:41:42Z" level=info msg="Starting configmap/secret informers"
time="2021-07-28T14:41:42Z" level=info msg="secrets informer cancelled"
time="2021-07-28T14:41:42Z" level=info msg="configmap informer cancelled"
time="2021-07-28T14:41:42Z" level=info msg="Configmap/secret informer synced"
time="2021-07-28T14:41:42Z" level=info msg="Starting configmap/secret informers"
time="2021-07-28T14:41:42Z" level=info msg="secrets informer cancelled"
time="2021-07-28T14:41:42Z" level=info msg="configmap informer cancelled"
time="2021-07-28T14:41:42Z" level=info msg="Configmap/secret informer synced"
time="2021-07-28T14:41:42Z" level=info msg="argocd v2.0.5+4c94d88 serving on port 8080 (url: https://argocd.example.com, tls: false, namespace: kube-system, sso: false)"
time="2021-07-28T14:41:42Z" level=info msg="0xc00133c000 subscribed to settings updates"
time="2021-07-28T14:41:42Z" level=info msg="Starting rbac config informer"
time="2021-07-28T14:41:42Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
time="2021-07-28T14:42:01Z" level=info msg="Notifying 1 settings subscribers: [0xc00133c000]"
time="2021-07-28T14:42:01Z" level=info msg="Notifying 1 settings subscribers: [0xc00133c000]"

```
