### ISSUE TITLE
Can the chart support config management plugins?

### ISSUE THREAD

**Issue by perezjasonr** [argoproj/argo-helm#873]
**Describe the bug**

in the config section (which should populate the cm along with other yaml entries)
I tried to add configManagementPlugins based on the official example here:

https://github.com/argoproj/argocd-example-apps/tree/master/plugins/kustomized-helm

but it seems to break the chart. I thought at first it might be special characters, so I tried to rearrange it different ways and starting to wonder if the chart logic/templating may need, or if theres something im missing that makes this one of the configs we just can't do in the helm chart (meaning we have to go after the deploy and update the configmap manually). I say this because I have not seen any examples of this yet, i have only seen the configmap edited after deployment, or directly through a manifest deploy (not helm).

**To Reproduce**
before deploying the chart, in the server.config section add something like to values file:

```yaml
server:
   config:
      configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build"]
        generate:
          command: [sh, -c]
          args: ["helm template --release-name release-name . > all.yaml && kustomize build"]
```

try installing the helm chart, or templating it:

```
helm template argocd argo/argo-cd -f argovalues.yaml --dry-run
Error: failed to parse argovalues.yaml: error converting YAML to JSON: yaml: line 3: did not find expected key
```
note that I have tried different things, escaping characters, turning the [ ] list into a hyphen list -

without that values file its happy:

```
helm template argocd argo/argo-cd --dry-run
---
# Source: argo-cd/templates/argocd-application-controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-application-controller
  labels:

...
...
```

so does this mean, the 2 example sections (oidc, repositories) in the values.yaml are not just examples but the only 2 options it will accept?

**Expected behavior**
I would expect it to add that section like it can do with oidc conf and repositories

**Screenshots**

**Additional context**

we have used the repositories section and oidc config successfully so we know it accepts those.

this could be based on a misunderstanding, where that section simply fills out the argo cm "as is", but if it only accepts repositories and oidc.config, then I'd like to switch this to a feature request to allow configManagementPlugins to also be used to populate the cm at helm deployment.
