### ISSUE TITLE
livenessProbe failing on argo-workflow chart v0.4.2

### ISSUE THREAD

**Issue by eduardoaemunoz** [argoproj/argo-helm#893]
### Describe the bug

I've updated the chart version from 0.2.2 to 0.4.2. The liveness probe changed from

```
livenessProbe:
  httpGet:
    port: metrics
    path: {{ .Values.controller.metricsConfig.path }}
  initialDelaySeconds: 30
  periodSeconds: 30
```

to

```
# https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
livenessProbe: {{ .Values.controller.livenessProbe | toYaml | nindent 12 }}

# https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/values.yaml
livenessProbe:
  httpGet:
    port: 6060
    path: /healthz
  # Require three failures to tolerate transient errors.
  failureThreshold: 3
  initialDelaySeconds: 90
  periodSeconds: 60
  timeoutSeconds: 30
```

Port 6060 is opened as expected.

The probe fails, causing the pod to enter a `CrashLoopBackOff`.

Changing the `values.yaml` to

```
livenessProbe:
  # httpGet:
  #   port: 6060
  #   path: /healthz
  httpGet:
    port: 9090
    path: /metrics
  # Require three failures to tolerate transient errors.
  failureThreshold: 3
  initialDelaySeconds: 90
  periodSeconds: 60
  timeoutSeconds: 30
```

makes everything work as expected.

### To Reproduce

See bug report.

### Expected behavior

I expected the /healthz liveness probe to be working.
