### ISSUE TITLE
[argo-rollouts] ServiceMonitor selector doesn't match metrics Service labels

### ISSUE THREAD

**Issue by donovanmuller** [argoproj/argo-helm#911]
### Describe the bug

When enabling metrics (`controller.metrics.enabled`) and ServiceMonitor (`controller.metrics.serviceMonitor.enabled`), the ServiceMonitor `selector` label does not match the metrics Service:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/version: v1.0.2
    argocd.argoproj.io/instance: argo-rollouts
    helm.sh/chart: argo-rollouts-2.0.0
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - argo-rollouts
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/name: argo-rollouts
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
    app.kubernetes.io/version: v1.0.2
    argocd.argoproj.io/instance: argo-rollouts
    helm.sh/chart: argo-rollouts-2.0.0
  name: argo-rollouts-metrics
  namespace: argo-rollouts
spec:
  clusterIP: 172.20.27.158
  clusterIPs:
  - 172.20.27.158
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 8090
  selector:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/name: argo-rollouts
```

note the ServiceMonitor's `selector` and Service labels do not match on the `app.kubernetes.io/component` label.

### To Reproduce

1. Install Argo Rollouts via the [Helm Chart](https://artifacthub.io/packages/helm/argo/argo-rollouts)
2. Enable metrics and ServiceMonitor
3. Note that the ServiceMonitor target does not become active in Prometheus

### Expected behavior

The ServiceMonitor after being applied, is discovered and the target is active in Prometheus.

### Additional context

The reason the selector/labels don't match is that the Service uses [`app.kubernetes.io/component: {{ .Values.controller.component }}`](https://github.com/argoproj/argo-helm/blob/5c03c916be16f3228ad1745410fb82e9b75a2822/charts/argo-rollouts/templates/argo-rollouts-metrics-service.yaml#L20), whereas the ServiceMonitor uses [`app.kubernetes.io/component: server`](https://github.com/argoproj/argo-helm/blob/5c03c916be16f3228ad1745410fb82e9b75a2822/charts/argo-rollouts/templates/argo-rollouts-service-monitor.yaml#L24).
