### ISSUE TITLE
Stan instances imagePullSecret

### ISSUE THREAD

**Issue by digibank-rons** [argoproj/argo-helm#914]
### Describe the bug

Hi,

Our Stan instances keep failing due to auth issues with Dockerhub to pull the nats server image, how can we inject imagepullsecret to the Stan instances (creation invoked via eventbus controller), we tried using the eventbus specification - 
like so - 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      imagePullSecrets:
          - name: xxx-pull-secret
      replicas: 3
      auth: token
```

But it doesnt seem to do anything for the stan instances,

Thanks

### To Reproduce

install the eventbus in a system with allot of calls via single-ip to Dockerhub

### Expected behavior

a simple straight forward manner of injecting imagepullsecrets to the stan instances
