### ISSUE TITLE
[argo-cd] Okta integration failing with dex

### ISSUE THREAD

**Issue by jodybro** [argoproj/argo-helm#925]
### Describe the bug

Chart version: `3.17.5`

When enabling SSO integration with `dex` you need to pass in a few config options to `argocd-cm`.
That part I understand so I setup my config as shown below:

```yaml
  configEnabled: true
  config:
    # Argo CD's externally facing base URL (optional). Required when configuring SSO
    url: https://argocd-sandbox.$domain.com
    # Argo CD instance label key
    application.instanceLabelKey: argocd.argoproj.io/instance
    dex.config: |
      logger:
        level: debug
        format: json
      connectors:
        - type: saml
          id: okta
          name: Okta
          config:
            ssoURL: $ssoURLFromOkta
            ssoIssuer: $ssoIssuerFromOkta
            caData: |
              $base64encodedstring
            redirectURI: https://argocd-sandbox.$domain.com/api/dex/callback
            usernameAttr: email
            emailAttr: email
            groupsAttr: group
```

But `dex` keeps saying that the yaml config is invalid.
```sh
argocd-dex-server-79b8bb4dcc-jrngw dex-server time="2021-09-09T20:04:48Z" level=info msg="Starting configmap/secret informers"
argocd-dex-server-79b8bb4dcc-jrngw dex-server time="2021-09-09T20:04:48Z" level=info msg="Configmap/secret informer synced"
argocd-dex-server-79b8bb4dcc-jrngw dex-server time="2021-09-09T20:04:48Z" level=info msg="0xc0008a43c0 subscribed to settings updates"
argocd-dex-server-79b8bb4dcc-jrngw dex-server time="2021-09-09T20:04:48Z" level=warning msg="invalid dex yaml config"
argocd-dex-server-79b8bb4dcc-jrngw dex-server time="2021-09-09T20:04:48Z" level=info msg="dex is not configured"
```

Relevant log of the `argocd-server`
```sh
"argocd v2.0.5+4c94d88 serving on port 8080 (url: https://argocd-sandbox.$domain.com, tls: false, namespace: default, sso: false)"
```

### To Reproduce

1. Get values file for `3.17.5` chart
2. Get Okta integration setup and get the ca cert data into the `dex.config` key
3. Also set the `url` in the configmap to your argo instance
4. `helm install argocd argo/argo-cd -f values.yaml  --version 3.17.5`

### Expected behavior

Dex should be configured at this point and then I should be able to test out SSO integration with Okta.

**Comment by pdrastil** [comment]
Hi @jodybro - maybe unrelated but if have secrets referenced via `$` like `$ssoURLFromOkta` they have to be provided via `configs` section like so:

```yml
configs:
  secret:
    extra:
      ssoURLFromOkta: superS3cret
```

Argo CD official image uses its own utility called `argocd-dex` that typically produces this log when secret substitution fails which would explain `invalid dex yaml config` message.
