### ISSUE TITLE
server.additionalProjects doesn't create project

### ISSUE THREAD

**Issue by IvanovOleg** [argoproj/argo-helm#928]
### Describe the bug

Hello,
I've tried to install argocd helm chart 3.17.6 (2.1.2) using the next command:
`helm upgrade --install argocd argo/argo-cd -n argocd --values values.yaml`
values.yaml:
```
server:
  additionalProjects:
    - description: Common Resources
      destinations:
        - namespace: common
          server: https://kubernetes.default.svc
      name: common
      namespace: common
      sourceRepos:
        - '*'
```
List of the projects contains only default project.

### To Reproduce

**helm upgrade --install argocd argo/argo-cd -n argocd --values values.yaml**
```
server:
  additionalProjects:
    - description: Common Resources
      destinations:
        - namespace: common
          server: https://kubernetes.default.svc
      name: common
      namespace: common
      sourceRepos:
        - '*'
```

### Expected behavior

The Common project appears in the list

**Comment by IvanovOleg** [comment]
Works with:
```
server:
  additionalProjects:
    - description: Common Resources
      name: common
```

**Comment by mkilchhofer** [comment]
Did you read the docs here? https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#quick-reference
> All resources, including **Application** and **AppProject** specs, have to be installed in the Argo CD namespace (by default argocd).

Since you use `helm upgrade --install argocd argo/argo-cd -n argocd --values values.yaml` (which installs the ArgoCD control plane into namespace called `argocd`), you have to use this namespace for the App spec:

```yaml
server:
  additionalProjects:
    - description: Common Resources
      destinations:
        - namespace: common # <--- this is ok
          server: https://kubernetes.default.svc
      name: common
      namespace: common # <--- see here
      sourceRepos:
        - '*'
```
