### ISSUE TITLE
[argocd-image-updater] Automate setting up the ArgoCD API Authentication user/secret 

### ISSUE THREAD

**Issue by tuananh** [argoproj/argo-helm#932]
### Is your feature request related to a problem?

image updater still need to follow the manual step to setup argocd token as per the instruction [here](https://argocd-image-updater.readthedocs.io/en/stable/install/start/#connect-using-argo-cd-api-server)

This make it not ideal for gitops as i'm using argocd to manage argocd-image-updater too.

### Describe the solution you'd like

i'm not sure what's the best practice here but we can create an additional field in values.yaml

```yaml
secret:
  # Whether helm chart creates controller secret
  create: false
  # ArgoCD token so that image updater can talk to ArgoCD API. More information [here](https://argocd-image-updater.readthedocs.io/en/stable/install/start/#connect-using-argo-cd-api-server)
  # argocdToken: ""
```

and create it with template

```yaml
{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  labels:
    {{- include "argocd-image-updater.labels" . | nindent 4 }}
type: Opaque
stringData:
  argocd.token: {{ .Values.secret.argocdToken }}
{{- end }}
```
