### ISSUE TITLE
[argocd-image-updater] specify user and email for commit

### ISSUE THREAD

**Issue by tuananh** [argoproj/argo-helm#936]
### Is your feature request related to a problem?

right now, we only put `registries.conf` into the configmap. there's no way to specify git user and email

### Describe the solution you'd like

introduce git option in config and put that into configmap

**Comment by tuananh** [comment]
my bad, looks like i can use the `extraArgs`. lemme try that first

**Comment by tuananh** [comment]
it doesn't work as it doesn't recognize the flag 

i think we need to use `args` instead of passing all the flags in the command like that

**Comment by mkilchhofer** [comment]
How did you try it?

It seems also possible via env vars:
https://github.com/argoproj-labs/argocd-image-updater/blob/f2b1ae04cd34480ea4761207296b8a63a3584f8a/cmd/run.go#L222-L223

```yaml
extraEnv:
  - name: GIT_COMMIT_USER
    value: "argocd-image-updater"
  - name: GIT_COMMIT_EMAIL
    value: "noreply@argoproj.io"
```
