### ISSUE TITLE
Workflow controller configmap - executor imagePullPolicy

### ISSUE THREAD

**Issue by paulaylingdev** [argoproj/argo-helm#980]
### Is your feature request related to a problem?

Recently migrated to using the argo-workflows chart in this project and noticed it was not possible to set `imagePullPolicy` on the `executor` configuration within the workflow controller configmap.

Example from argoproject/argo-workflows for setting `executor.imagePullPolicy`:
- https://github.com/argoproj/argo-workflows/blob/v3.1.8/docs/workflow-controller-configmap.yaml#L166

### Related helm chart

argo-workflows

### Describe the solution you'd like

Allow the existing `values.yaml` variable `images.pullPolicy` be used in the [workflow controller configmap](https://github.com/argoproj/argo-helm/blob/master/charts/argo-workflows/templates/controller/workflow-controller-config-map.yaml#L31) to set the `imagePullPolicy`.

### Describe alternatives you've considered

Set a value which allows the configuration of `executor.imagePullPolicy`.

For example

```yaml
#values.yaml
...
executor:
  image:
    pullPolicy: Always #New
    registry: quay.io
    repository: argoproj/argoexec
...
```
