### ISSUE TITLE
[argo-cd] allow to create an extra HTTPS ingress for SSO Callback

### ISSUE THREAD

**Issue by fernandoTorresan** [argoproj/argo-helm#984]
### Is your feature request related to a problem?

The current template of the Argo-CD helm chart, only allows us to create a single HTTPS `Ingress` kind object, which for us, is a limitation when we want to have multiple ingresses (one for private traffic and another for public)

I would like to be able to create an extra ingress to be my public/external traffic, in order to integrate our [Okta](https://www.okta.com/) with the argo-cd and exposes only a specific path, but also keep the private ingress to be used through the UI.

E.g.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: argocd-public
  namespace: argocd
spec:
  ingressClassName: ingress-nginx-public
  rules:
  - host: argocd-ext.mydomain.example.com
    http:
      paths:
      - path: /api/dex/callback
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
```

### Related helm chart

argo-cd

### Describe the solution you'd like

My idea is to add a new template file to generate this ingress, something like this `ingress-external.yaml`, inside the `argocd-server` folder.

This extra `Ingress` will be optional with a default value of `server.ingressExternal.enabled` as `false`, and with that, we won't create any breaking change.

Perhaps if someone knows another way to do this Okta integration without the need to expose this public ingress and callback path, please I'll appreciate it. 

### Additional context

This is to solve my problem with Okta integration SSO Callback, but certainly, this could fill other necessities and help other use cases.

There is an example on [this documentation](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/ingress.md) called `External HTTPS SSO Callback Ingress`, which is something very similar, but instead of `Contour` Ingress, I'm using the `kubernetes/ingress-nginx`, but the situation is exactly the same.
